### ISSUE TITLE
Only the latest message receives `readBy` props

### ISSUE THREAD

**Issue by tmoran-stenoa** [GetStream/stream-chat-react#1000]
After some testing, it appears that a `Message` component only receives the correct `readBy` prop/context value if that message is the latest one in the channel.

This is problematic for us because we would like to have read indicators in the same style as WhatsApp, in which this information is available for every message that one sends, not just the latest one.

#### First Scenario
```
User A sends message 1
User A sends message 2
User B reads both messages
```
**Expected:** when logged in as user A, both messages should receive a `readBy` which includes both users A and B.
**Actual:** when logged in as user A, message 2 receives the correct `readBy`, whereas message 1 receives an empty `readBy`.

When this happens, one can hack a solution which would fetch the latest message and use its `readBy` instead, but that does not generalize because of the second scenario:

#### Second Scenario
```
User A sends message 3
User B reads message 3
User B sends message 4
```
**Expected:** when logged in as user A, message 3 should receive a `readBy` which includes both users A and B.
**Actual:** when logged in as user A, message 3 receives an empty `readBy`.

When this happens, one cannot use the hack above because all of the messages have an empty `readBy` prop when logged in as user A.

**Comment by DanC5** [comment]
@tmoran-stenoa thanks for the detailed example with steps to reproduce. I'll run this scenario with a co-worker tomorrow and get back to you.

**Comment by DanC5** [comment]
@tmoran-stenoa I believe we've figured out a way to handle this for you. I'm out of office Monday, but will polish this up Tuesday and make a patch release some time mid next week, thanks.

**Comment by DanC5** [comment]
@tmoran-stenoa we just merged a [PR](https://github.com/GetStream/stream-chat-react/pull/1014) to add support for this request. With our next release, likely within the next few days, you'll have access to the `returnAllReadData` prop on the `MessageList` component. Adding this prop will return `readBy` data for each message sent by the currently connected user, not just the most recent one.

```
<MessageList returnAllReadData />
```

I'm going to close this issue for now, but do reach back out if you need assistance in the future, thanks!

**Comment by tmoran-stenoa** [comment]
Thank you so much for the quick solution! We appreciate it a lot and will try it as soon as we can.
