### ISSUE TITLE
messageActions/MessageInput parameters support for Thread component

### ISSUE THREAD

**Issue by volodymyr-manko** [GetStream/stream-chat-react#101]
Currently, **Thread** component has no parameters like **messageActions** or **MessageInput**.
So, regardless of commands/permissions configuration on Dashboard, MessageList component (Thread -> MessageList), gets **messageActions** property as undefined, and in result the default list of actions (["edit", "delete", "mute", "flag"]) is used, which cannot be overridden for Thread.

As well there is no ability to customize MessageInput component for Thread (MessageInputSmall is used as Input prop of MessageInput instead): so the custom MessageInput in chat can differ from the one in Thread in that chat.

Could you please support these input parameters for Thread, like **messageActions**/**MessageInput**, which will be passed to MessageList and MessageInput components respectively?

```
messageActions: PropTypes.oneOfType([PropTypes.bool, PropTypes.array]),
MessageInput: PropTypes.oneOfType([PropTypes.node, PropTypes.func]),
...

<MessageList
  ...
  messageActions={this.props.messageActions}
 />
 <MessageInput
   Input={this.props.MessageInput}
   ...
 />
```

**Comment by vishalnarkhede** [comment]
Thanks @volodymyr-manko for bringing this up. We are looking into it and get back to you soon with resolution :)

**Comment by volodymyr-manko** [comment]
Thanks :)

**Comment by dmcguire81** [comment]
@tbarbugli @vishalnarkhede this could also support our use case of specializing thread-handling.

**Comment by jaapbakker88** [comment]
@volodymyr-manko the thread component now supports the following props in version `0.7.15`. This allows you to update the underlying MessageList, MessageInput and Message components, through props.
- `additionalParentMessageProps`
- `additionalMessageListProps`
- `additionalMessageInputProps`

**Comment by volodymyr-manko** [comment]
@jaapbakker88 
Cool, thanks! :)
