### ISSUE TITLE
Uploading an image not working for Team demo

### ISSUE THREAD

**Issue by wildebeast** [GetStream/stream-chat-react#1025]
It's not possible to upload an image to the Team style chatroom on this page https://getstream.io/chat/demos/team/

See gif below:

![upload-bug](https://user-images.githubusercontent.com/452074/124153935-d66f0580-da49-11eb-8928-aad218770ee3.gif)

**Comment by ambaldwin** [comment]
Hello! Thanks for bringing this to our attention. Looks like it was an issue with necessary props not being added to the 'react-file-utils' ImageDropzone component. I'm about to open a PR with these changes, and they should be reflected in the demo shortly. Thanks again, and I'm going to close this issue.
