### ISSUE TITLE
Module parse failed: Unexpected character ''  You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by fernando140alto** [GetStream/stream-chat-react#1034]
I'm having this problem while importing `stream-chat` modules to my app. 

Whenever I try to import:

```
import {
  Chat,
  Channel,
  ChannelHeader,
  ChannelList,
  MessageList,
  MessageInput,
  Thread,
  Window,
} from 'stream-chat-react';
import 'stream-chat-react/dist/css/index.css';
```

Even if I don't import the `.css` file I get these errors related to the `assets`

I'm using `next.js` but I'm not sure how specific the issue has to do with this package: https://github.com/vercel/next.js/blob/master/errors/css-npm.md

The error(s)

    > [ error ]
    > ./node_modules/stream-chat-react/dist/assets/Poweredby_100px-White_VertText.png
    > 1:0 Module parse failed: Unexpected character '�' (1:0) You may need
    > an appropriate loader to handle this file type. (Source code omitted
    > for this binary file) ModuleParseError: Module parse failed:
    > Unexpected character '�' (1:0) You may need an appropriate loader to
    > handle this file type. (Source code omitted for this binary file)
    > 
    > Module parse failed: Unexpected character '@' (4:0) You may need an
    > appropriate loader to handle this file type. | /* colors */ | /*
    > miscellaneous */
    > > @import url("https://fonts.googleapis.com/css?family=IBM+Plex+Sans:400,400i,700,700i");

And my `next.config.js`

    const { withPlugins, optional } = require('next-compose-plugins')
    const { PHASE_PRODUCTION_BUILD } = require('next-server/constants')
    const sass = require('@zeit/next-sass')
    const { requireEnvVar } = require('./lib/nodeUtils')
    
    const nextConfig = {
      publicRuntimeConfig: {
        ...
      },
    
      useFileSystemPublicRoutes: false,
    
      webpack(config, { webpack }) {
        config.plugins.push(
          new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /en/)
        )
    
        return config
      },
    }
    
    module.exports = withPlugins(
      [
        [sass],
        [
          optional(() => require('@zeit/next-bundle-analyzer')),
          {
            analyzeServer: ['server', 'both'].includes(process.env.BUNDLE_ANALYZE),
            analyzeBrowser: ['browser', 'both'].includes(
              process.env.BUNDLE_ANALYZE
            ),
            bundleAnalyzerConfig: {
              server: {
                analyzerMode: 'static',
                reportFilename: '../../bundles/server.html',
              },
              browser: {
                analyzerMode: 'static',
                reportFilename: '../bundles/client.html',
              },
            },
          },
          [PHASE_PRODUCTION_BUILD],
        ],
      ],
      nextConfig
    )

I have already tried many combinations in my `next.confg.js` file with no success at all.

Thanks as always!

**Comment by DanC5** [comment]
Hey Fernando, that's my middle name ;). You most likely need to add [`next-images`](https://www.npmjs.com/package/next-images) to your config file. This should fix the issue, but let me know if the problem persists, thanks.

**Comment by fernando140alto** [comment]
Hello Dan, nice middle name btw ;).

Tried with both `@zeit/next-css` and `next-images` as per required in the docs (https://github.com/cyrilwanner/next-compose-plugins) when using `withPlugins` method. 

```
const sass = require('@zeit/next-sass')
const css = require('@zeit/next-css')
const images = require('next-images')

nextConfig = { ... }

module.exports = withPlugins(
  [
    [sass],
    [images],
    [css],
    [
      // eslint-disable-next-line global-require,import/no-extraneous-dependencies
      optional(() => require('@zeit/next-bundle-analyzer')),
      {
        analyzeServer: ['server', 'both'].includes(process.env.BUNDLE_ANALYZE),
        analyzeBrowser: ['browser', 'both'].includes(
          process.env.BUNDLE_ANALYZE
        ),
        bundleAnalyzerConfig: {
          server: {
            analyzerMode: 'static',
            reportFilename: '../../bundles/server.html',
          },
          browser: {
            analyzerMode: 'static',
            reportFilename: '../bundles/client.html',
          },
        },
      },
      [PHASE_PRODUCTION_BUILD],
    ],
  ],
  nextConfig
)
```

```
./node_modules/stream-chat-react/dist/css/index.css
ModuleParseError: Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

Do you see something not correct?

Thanks again!

**Comment by DanC5** [comment]
@fernando140alto ok so looks like that fixed the asset import issue, but a css issue remains. I don't have a ton of experience with Next, but we do build a sample app with our library before releases and don't add those css/sass plugins. It's quite simple, but the entirety of our `next.config.js` is our sample testing app is the following...

```
const withImages = require('next-images');
module.exports = withImages();
```

It actually looks like both of those @zeit packages have been deprecated as Next now natively supports what those plugins were accomplishing. I'd make sure your Next dependency was sufficiently upgraded to handle css/sass and then hopefully adding `next-images` is all you need to do, thanks.

**Comment by fernando140alto** [comment]
Thanks @DanC5 . I'll give it a shot and play around a bit more. Thanks!

**Comment by fernando140alto** [comment]
Hey @DanC5 . I have got a very simple nextjs project where I'm trying to test the chat. However I'm still struggling with css errors.

```
./node_modules/react-file-utils/dist/styles/App.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules\react-file-utils\dist\index.js
```
from https://nextjs.org/docs/messages/css-npm:

> Importing CSS files within node_modules cannot be supported because we cannot know the correct behavior

I also tried installing `sass` a per advised here:
https://nextjs.org/blog/next-9-3#built-in-sass-support-for-global-stylesheets

The repo:
https://github.com/fernando140alto/nextjs-stream-chat-test

**Comment by DanC5** [comment]
Hey @fernando140alto we're looking into this exact issue right now as we're seeing the same thing on our Next sample app. A recent upgrade to `react-file-utils` (which we also manage) has caused the issue. We'll hopefully have a fix pushed out soon, if not today then Monday. Thanks!

**Comment by DanC5** [comment]
@fernando140alto check out this release and let me know if it fixes your problem, thanks! https://github.com/GetStream/stream-chat-react/releases/tag/v6.4.1

**Comment by fernando140alto** [comment]
Hopefully they do. I'll reach you back soon with news. Thanks!! @DanC5

**Comment by fernando140alto** [comment]
Btw got this message during `npm i`

![image](https://user-images.githubusercontent.com/86745300/125179005-cc6aa680-e1af-11eb-9195-ef59e282fce4.png)

I also tried directly with url but it gets stuck.

`npm install git+https://github.com/GetStream/stream-chat-react.git`

**Comment by DanC5** [comment]
@fernando140alto looks like you have a typo, `stream-chat-react` not `npm-stream-react` ;)

**Comment by fernando140alto** [comment]
Hey Dan, just wanted to let you know that it works. 

In the end I imported css via CDN, since I couldn't make it work via import/require.

Thanks so much for your help!
