### ISSUE TITLE
HEIC format file browser not supported

### ISSUE THREAD

**Issue by YohaanYoon** [GetStream/stream-chat-react#1039]
stram-chat-react: v5.1.6
stream-chat: v3.1.4

When users uploaded HEIC format images by android app, stream-chat-react did not displayed on browser.

![스크린샷 2021-04-16 오후 5 33 24](https://user-images.githubusercontent.com/6019966/114996532-e0b54500-9ed9-11eb-92fa-8bb8d4ed0e47.png)

**Comment by DanC5** [comment]
@YohaanYoon the error still seems to come from your app's means of serving up the image asset. I can see in your screenshot that you're serving up through Amazon S3 and the image has not been converted to a browser-friendly version. Browsers cannot render HEIC images, so your CDN needs to convert the HEIC to something supported, like a png or jpeg.

See my attached screenshot where I upload an HEIC and Imgix (Stream's default CDN) converts the image to a jpeg. It also displays properly in the message list.

<img width="491" alt="Screen Shot 2021-07-08 at 2 56 29 PM" src="https://user-images.githubusercontent.com/43552931/124990054-16f7f180-dffd-11eb-815f-a68958958f91.png">

So you have two options: either use Stream's CDN or adjust the logic within your image serving flow to convert the HEIC to a browser supported image file type.

Thanks,

**Comment by YohaanYoon** [comment]
I guess it is the simple issue and the simple answer while it takes 3 months.
I will check the issue of the app.
