### ISSUE TITLE
NextJS Support

### ISSUE THREAD

**Issue by fearless23** [GetStream/stream-chat-react#1042]
"stream-chat-react": "^6.4.0" internally uses react-file-utils
 which gives following error when building with NextJS 10.2.3

./node_modules/react-file-utils/dist/styles/App.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\react-file-utils\dist\index.js

**Comment by DanC5** [comment]
@fearless23 thanks for bringing this to our attention. We see it's due to a recent refactor of the `react-file-utils` library (which we also manage), so are looking into a fix right now.

**Comment by DanC5** [comment]
@fearless23 check out this release and let me know if it fixes your problem, thanks! https://github.com/GetStream/stream-chat-react/releases/tag/v6.4.1

**Comment by DanC5** [comment]
@fearless23 we've received reports that this release fixed the Next issue, so I'm going to close, but do reach out if you continue to have trouble. Thanks!
