### ISSUE TITLE
`MessageText` component is missing retry logic

### ISSUE THREAD

**Issue by vjdhanota** [GetStream/stream-chat-react#1046]
Hi,

We are in the process of writing a `CustomMessage` component by following this guide:

https://github.com/GetStream/stream-chat-react/wiki/How-to-Guide-for-Building-a-Custom-Message-(v.6.0.0)

It looks like the `MessageText` component is correctly rendering an error text with the message: `'Message Failed · Click to try again'` but it is missing any logic to retry sending the message.

That logic does seem available in the deprecated `MessageTeam`, though. Should we write our own `MessageText` by mirroring the logic or should that logic be expected in the exported `MessageText`?

**Comment by ambaldwin** [comment]
Hello, we're so glad you're using our examples as a guide to build your own custom message component!

Much like `MessageTeam` or our default `MessageSimple` components, you should wrap a parent element around the `MessageText` component with onClick functionality utilizing the `handleRetry` prop (available to the MessageUI Components via `MessageUIComponentProps`) within your custom message component. I hope that helps, and I'm going to close this issue, but do reach out again if there are more questions  - thanks!

**Comment by vjdhanota** [comment]
Awesome, that was really easy actually.

Still getting accustomed to the library, excuse the silly question!! Thanks!

**Comment by ambaldwin** [comment]
No problem! And for easy access, here's our [component docs](https://getstream.io/chat/docs/sdk/react/). These were recently completed and are up to date.
Thanks!
