### ISSUE TITLE
Linked articles or posts not respecting div boundaries

### ISSUE THREAD

**Issue by devluked** [GetStream/stream-chat-react#1055]
Hello,

I found an issue where when a post or an article of some sorts is pasted in and shows a preview in the chat, it extends out of the chat and does not respect the boundaries of the container. Is there a way to fix this?

![image](https://user-images.githubusercontent.com/48234476/126220954-670e07e7-5fa9-46a4-87ea-a18f8bf6666c.png)

**Comment by DanC5** [comment]
@devluked you have two options here to adjust the Card component, which is what's rendering off the screen here (https://github.com/GetStream/stream-chat-react/blob/master/src/components/Attachment/Card.tsx).

1) Adjust the CSS directly - if you inspect in the browser you'll see that some of the elements within MessageSimple (our default Message UI component) have max widths of 460 pixels, so they're growing past the width of your list container. Your first option is to grab our default classes that apply this width and change to fit the dimensions of your app. If you're using our MessageSimple component, then this is likely your easiest option. I just created a similar example on my end and was able to adjust the CSS with a couple additional selections listed below...

`.str-chat__message-simple-text-inner`
`.str-chat__message-attachment--image`

2) Create a custom Attachment component - this method would take a little bit longer, but would give you more flexibility to completely control the UI. You can create your own `Card` component with whatever dimensions you choose and pass it into a custom `Attachment` component which would be placed on `Channel`. Below is a brief example of how this would work, and while we don't have an exact example of customizing a `Card` component, this `Gallery` example walks through the same process, https://getstream.io/chat/docs/sdk/react/custom-code-examples/image_gallery/.

```
const CustomCard = (props) => {
  // do whatever custom logic you want here
};

const CustomAttachment: React.FC<AttachmentProps> = (props) => (
  <Attachment {...props} Card={CustomCard} />
);

<Channel Attachment={CustomAttachment} />
```

I'm going to close this issue as either method will solve the problem for you, but do let us know if you have additional questions about how this works, thanks!
