### ISSUE TITLE
<QuotedMessage /> contains blank <Avatar /> when needing to show initials

### ISSUE THREAD

**Issue by junminleeKS** [GetStream/stream-chat-react#1064]
The `<QuotedMessage />` component contains the following code for rendering the `<Avatar />` component:

```
<Avatar image={quoted_message.user.image} size={20} user={quoted_message.user} />
```

`<Avatar />` does not have a `user` prop and instead uses the `name` prop to show initials.

**Comment by DanC5** [comment]
@junminleeKS thanks for pointing out this issue. And just FYI, we pass the user object for people creating custom components, but we don't use it in our default version. Though we should pass the `name` field, so in our latest release, https://github.com/GetStream/stream-chat-react/releases/tag/v6.4.5, we've added the `name` field on the `Avatar` component to both the `QuotedMessage` and `QuotedMessagePreview` components. Thanks!
