### ISSUE TITLE
Need help on using Channel prop - doUpdateMessageRequest

### ISSUE THREAD

**Issue by Giddu** [GetStream/stream-chat-react#1067]
I've been trying to use doUpdateMessageRequest on Channel to include some custom attributes in the message when updated but the override is not working.

I've tried other prop such as doSendMessageRequest on Channel and clearEditingState and overrideSubmitHandler on the MessageInput and they are working as expected 

Reference:
https://getstream.io/chat/docs/sdk/react/core-components/channel/#dosendmessagerequest

Code snippet:
<Channel
  channel={activeChannel}
  doSendMessageRequest={doSendMessageRequest}
  doUpdateMessageRequest={doUpdateMessageRequest}>
  {editMode ? (
    <MessageInput
      focus={true}
      key={message.id}
      message={message}
      onChangeText={(text) => onChange(text)}
      clearEditingState={onMessageUpdate}
    />
  ) : (
    <MessageInput
      onChangeText={(text) => onChange(text)}
    />
  )}
</Channel>

Packages and versions used:
 getstream: 7.2.8
 stream-chat: 3.8.0
 stream-chat-react: 5.3.0

**Comment by ambaldwin** [comment]
Hi, thanks for reaching out and for including the versions that you're using - what error are you getting when trying to use the prop, if any? I actually don't see where in the code snippet you send that you're trying to implement that prop.

When using the handler, you should include your custom code, and then conclude with `client.updateMessage(updatedMessage)`, see code example below.

I believe this should work, so please let us know what errors you're getting and we can go from there.

const customDoUpdateMessageRequest = (cid: string, updatedMessage: UpdatedMessage) => {
    // your custom code to update the message
    client.updateMessage(yourNewlyUpdatedMessage);
 };

<Channel
  doUpdateMessageRequest={customDoUpdateMessageRequest}
>
</Channel>

**Comment by Giddu** [comment]
Hi @ambaldwin , thanks for reply.

Sorry that I missed the complete code snippet earlier. The complete code snippet is :- 

<Channel
    channel={activeChannel}
    doSendMessageRequest={customDoSendMessageRequest}
    doUpdateMessageRequest={customDoUpdateMessageRequest}>
    {editMode ? (
      <MessageInput
        focus={true}
        key={message.id}
        message={message}
        onChangeText={(text) => onChange(text)}
        clearEditingState={onMessageUpdate}
      />
    ) : (
      <MessageInput
        onChangeText={(text) => onChange(text)}
      />
    )}
  </Channel>;

And my custom update handler looks like this :-

  const customDoUpdateMessageRequest = (cid, updatedMessage) => {
    const myUpdatedMessage = {
      ...updatedMessage,
      _is_text_updated: true,
    };
    client.updateMessage(myUpdatedMessage);
  };

I don't see any console errors and the code is behaving as is the doUpdateMessageRequest property has not been passed and is doing a normal update message.

Any help would be much appreciated.

**Comment by Giddu** [comment]
@ambaldwin, not sure if it helps but I was looking through the source code of this package to see if I can spot anything which I might be doing wrong.

In my case the doSendMessageRequest works as expected for which the logic can be found here - 

https://github.com/GetStream/stream-chat-react/blob/0942cf219f4287966cf7fea69da0b53830b7d524/src/components/Channel/Channel.tsx#L594-L598

In the above code both the **channel** and **doSendMessageRequest** are passed as prop in the **Channel**

Whereas for the doUpdateMessageRequest the logic can be found here -

https://github.com/GetStream/stream-chat-react/blob/0942cf219f4287966cf7fea69da0b53830b7d524/src/components/Channel/hooks/useEditMessageHandler.ts#L41-L45

Here other than checking if the **doUpdateMessageRequest** has been passed as prop or not we are also checking if **channel** exists which we get from **useChatContext** which is different from above case.

Which leads me to believe that for some reason  we are not getting **channel** from **useChatContext** and hence the application behave as though no channel has been passed

Is there anyway I can confirm this assumption or how I can fix it?

**Comment by Giddu** [comment]
I researched a bit into the issue and the issue was as suspected. We were changing the channel but it was not updated in the context. After looking at the test cases provided in the package I made changes to update the channel and the below code worked for me. Closing this ticket.

```
  <Chat client={client}>
    <ActiveChannelSetter activeChannel={activeChannel} />
    <Channel
      channel={activeChannel}
      doUpdateMessageRequest={customDoUpdateMessageRequest}
    >
      {editMode ? (
        <MessageInput
          focus={true}
          key={message.id}
          message={message}
          onChangeText={(text) => onChange(text)}
          clearEditingState={onMessageUpdate}
        />
      ) : (
        <MessageInput
          onChangeText={(text) => onChange(text)}
          overrideSubmitHandler={onPressEnter}
        />
      )}
    </Channel>
  </Chat>
```

```
  const ActiveChannelSetter = ({ activeChannel }) => {
    const { setActiveChannel } = useContext(ChatContext);
    useEffect(() => {
      setActiveChannel(activeChannel);
    }, [activeChannel]); // eslint-disable-line
    return null;
  };
```
