### ISSUE TITLE
Pending MessageTeam.tsx deprecation - how should clients respond?

### ISSUE THREAD

**Issue by wildebeast** [GetStream/stream-chat-react#1087]
Hey GetStream, I noticed this comment in the code for MessageTeam: 

https://github.com/GetStream/stream-chat-react/blob/master/src/components/Message/MessageTeam.tsx#L301

Is there a plan to create a different team-style Message component? Should we wait for the next major release to change our UI or use/restyle a different existing component?

Thanks!

**Comment by ambaldwin** [comment]
Hello!
There are no plans to create a new team-style Message UI component; these components were intended to be used as guides for folks to use to create their own custom component. We would suggest creating a custom component here, and if you'd like, you can copy and paste the code from the MessageTeam for use in your own. Then, you'd just need to use the `Message` prop on Channel. I'm going to close this issue, but please let us know if there are other questions. Thanks!

```
const CustomMessage = (props) => {
  // custom message logic and/or MessageTeam code
  return (
    // JSX
  )
}

<Channel Message={CustomMessage} />
```
