### ISSUE TITLE
Readby data only applied to new messages?

### ISSUE THREAD

**Issue by tmoran-stenoa** [GetStream/stream-chat-react#1105]
Dear Stream developers,

After some experimentation with the React SDK, it appears that readby data is not persisted across page loads, and only updates when the current user enters a new message **while other users are viewing the chat**. Is this expected behaviour?

### Steps to Reproduce with Outcomes
1. Create chat and open it simultaneously with two different users A and B viewing it.
2. User A enters message X.
_**Outcome:** message X is marked as read by both A and B (as expected)._
3. User A reloads their page.
_**Outcome:** the read by indicator disappears -- it only says that message X was delivered. This occurs regardless of whether user B is still viewing the chat or has left._
4. User B reloads their page and enters message Y (with user A still viewing the chat).
_**Outcome:** user A still does not see that user B has read message X -- it still only says that it was delivered. User B, on the other hand, can see that user A has read message Y (as expected)._
5. User A enters message Z (with user B still viewing the chat).
_**Outcome:** now, user A can see that user B has read message Z. If `returnAllReadData` is set, then user A can also see that user B has read message X. Note that if user A enters message Z with user B **not** viewing the chat at the same time, then message X is still marked as unread._

### Expected Outcome
After step 3, user A should still see that user B has read message X, regardless of whether user B is still viewing the chat or not and whatever happens next.

### Extra Details
* This was tested with both a custom and the default message UI components.
* This was tested with both `returnAllReadData` set and unset.
* This was tested with both a custom and the default message status indicator. Therefore this doesn't seem to be a UI issue.

**Comment by DanC5** [comment]
@tmoran-stenoa I just tested this and am getting slightly different results. FYI, I'm using our default `MessageSimple` UI component.

- For step 3, after I reload the page I'm still seeing user B's avatar and they are still in the `readBy` array coming from the `MessageContext` (see screenshot 1)
- For step 4, after user B reloads and sends message Y, I'm not seeing any change to message X (see screenshot 2)

What version of the library are you on? Also, have you tested this without any customization and in a completely bare app? The jsx for the app I'm running has only this, so it's all default behavior...

```
const App = () => (
  <Chat client={chatClient}>
    <ChannelList filters={filters} sort={sort} options={options} />
    <Channel>
      <Window>
        <ChannelHeader />
        <MessageList />
        <MessageInput />
      </Window>
      <Thread />
    </Channel>
  </Chat>
);
```

![Screen Shot 2021-08-09 at 7 54 30 AM](https://user-images.githubusercontent.com/43552931/128717723-74fae4d2-08c0-4f90-978d-980a36588018.png)

![Screen Shot 2021-08-09 at 7 56 04 AM](https://user-images.githubusercontent.com/43552931/128717990-9fbd8bcf-5f29-46ed-b6dc-46795c035dd4.png)

**Comment by tmoran-stenoa** [comment]
Thanks for the quick response @DanC5 . I have tried this again on a blank app on a `messaging` channel with `returnAllReadData` set. I am on `stream-chat@3.13.1` and `stream-chat-react@6.4.11`. The Stream app was in `development` mode, if this is of any use. I used the code snippet that you provided. This is the result:

https://user-images.githubusercontent.com/84818024/128934190-2bd4ace7-12b8-43a1-9677-bdb8077dc1c4.mp4

**Comment by DanC5** [comment]
@tmoran-stenoa sorry for the delay on this, I'll check first thing tomorrow

**Comment by DanC5** [comment]
@tmoran-stenoa While I previously couldn't replicate your initial issue with or without `readAllReadData` used, now I no longer achieve the same results from my own message above, where all seemed to be working fine. Nothing around this code has changed recently in the library, so I'll do some further investigation today to see if anything has changed in the component library's received response from the chat api.

**Comment by DanC5** [comment]
@tmoran-stenoa I figured out what's going on here. The read states are only persistent for members of a channel. So if you try the same exercise in a channel where each user is a member, you should receive the expected results.

In your ChannelList filters you can return only channels in which your connected user is a member with a filter like this...

`const filters: ChannelFilters = { type: 'messaging', members: { $in: [// user ID here] } };`

Let me know if you have any more questions, thanks.

**Comment by DanC5** [comment]
@tmoran-stenoa I'm going to close this issue as all seems to be working expected for channel members. Since watchers are only temporary visitors to a channel, their read states aren't persistent on app loads. Of course reach back out if you have further issues, thanks.
