### ISSUE TITLE
Clear chat using onClick

### ISSUE THREAD

**Issue by devluked** [GetStream/stream-chat-react#1108]
Hello,

I'm trying to add a feature for admins in my application to be able to clear the chat. I am using a <MessageList/> component but not passing it a messages prop. I want to clear it using an onClick inside of a button. Could you help point me in the right direction on how to do this?

If that isn't really possible without a major refactor, is it possible to simply make messages decay and not show up anymore after x amount of time, or everytime a new user joins, they only see messages after they joined?

Thanks

**Comment by AndersDLund** [comment]
Hello and thanks for submitting an issue to our GitHub repository. We’re glad you’re getting hands on with the product. The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.
In case our understanding is incorrect and you are describing a bug, we apologize, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.
