### ISSUE TITLE
Can't get "at" user metions to appear after upgrade to latest version

### ISSUE THREAD

**Issue by wadewadewadewadewadewade** [GetStream/stream-chat-react#1110]
I just upgraded from a really old version of stream-chat and stream-chat-react, and I don't see a list of users appear when i type '@' followed by a letter or two.

I also searched through documentation as well as component code (as best I could) and didn't see how to re-enable user mentions.

Is there some switch I need to flip to get those to show up again?

Thank you!

**Comment by AndersDLund** [comment]
Hello and thanks for submitting an issue to our GitHub repository. We’re glad you’re getting hands on with the product. The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.
In case our understanding is incorrect and you are describing a bug, we apologize, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.
