### ISSUE TITLE
Updating keycodeSubmitKeys during "runtime"

### ISSUE THREAD

**Issue by gambitasto** [GetStream/stream-chat-react#1111]
Hi,

I think I have found one edge case issue with the new "keycodeSubmitKeys" property.

So in a case like this where we would have "userSpecificKeycodeSubmitKeys" that can change at any time when for example the user changes things in their settings in a modal or similar, then the updated keycodeSubmitKeys are not activated until the ReactTextareaAutocomplete (Textarea.js) component is re-mounted (full page load or similar to force componentDidMount to be called).

<MessageInput keycodeSubmitKeys={userSpecificKeycodeSubmitKeys} />

So could the UNSAFE_componentWillReceiveProps in ReactTextareaAutocomplete be modified to also take the updated keycodeSubmitKeys into account?

**Comment by ambaldwin** [comment]
Hello! Thanks for submitting an issue. We're looking into this, and I will be back with more soon.

**Comment by ambaldwin** [comment]
Hi @gambitasto thanks for your patience, and I apologize for the delay. We have plans on our roadmap to completely overhaul the Textarea.js file so it's easier to customize and use, read, and maintain. This will be a big (but, very necessary task that can include handling of the edge case you have identified), and until then we are working to complete the planned items in the near short term before we tackle this larger piece that will ultimately be a major version release. I'm sorry if this is not the answer you were looking for. As for timing of these updates here, know that it is at the very top of our high priority list. Please let me know if you have any questions. Thanks!

**Comment by gambitasto** [comment]
No worries and good to hear that improvements will be made to these components, for now we can work around this so it is ok 👍
