### ISSUE TITLE
Selecting user in ChannelList search passes undefined user to GetOrCreateChannel

### ISSUE THREAD

**Issue by tonyf** [GetStream/stream-chat-react#1125]
This seems to be a regression following the update from three days ago. Can no longer create new chats using the ChannelList component search.

Upon selecting a user in the search results for which a messaging channel doesn't exist, the following error is raised

`Unhandled Rejection (Error): StreamChat error code 4: GetOrCreateChannel failed with error: "The following users are involved in channel create operation, but don't exist: [undefined]. Please create the user objects before setting up the channel."`

It seems like the user object is not properly being passed to creation.

Here is the code:
```
const ChatPage: React.FC<Props> = ({
  user,
  chatClient,
  connect,
  disconnect,
}: Props) => {
  useEffect(() => {
    if (user) {
      connect(user);
    }
    return () => {
      disconnect();
    };
  }, [user, connect, disconnect]);

  return (
    <>
      {!chatClient ? (
        <LoadingIndicator />
      ) : (
        <>
          <Chat
            client={chatClient}
            theme="messaging light"
            customStyles={theme}
          >
            <ChannelList showChannelSearch />
            <Channel>
              <div className="flex w-full flex-col">
                <ChannelHeader />
                <MessageList />
                <MessageInput />
                <Thread />
              </div>
            </Channel>
          </Chat>
        </>
      )}
    </>
  );
};
```

**Comment by ambaldwin** [comment]
Hello! Apologize for the delay. This might be a stream-chat issue and not a React SDK issue according to the error? Please [see this repo](https://github.com/GetStream/stream-chat-js) for the change log and v4 notes. 

I'm going to close this issue, but if you think I'm closing in error, please reach back out. Thanks!

**Comment by tonyf** [comment]
It's unclear whether the issue is with the component that's calling the underlying js lib or with the js lib itself
