### ISSUE TITLE
Image/File upload

### ISSUE THREAD

**Issue by NaumanMoazzam** [GetStream/stream-chat-react#1144]
I am using client.files.upload(image.path), but it throws [Error: network error].

Any thing which I am doing wrong?

**Comment by shodgetts** [comment]
Hello and thanks for submitting an issue to our GitHub repository. We’re glad you’re getting hands on with the product. The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.
In case our understanding is incorrect and you are describing a bug, we apologise, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.

**Comment by tj-mc** [comment]
How did you resolve this? I'm also facing this issue.

**Comment by tj-mc** [comment]
If you can debug issue in the open, rather than just support chat, it will save time for all.
