### ISSUE TITLE
HEIC & SVG/XML File Types Can Not Be Previewed

### ISSUE THREAD

**Issue by nappernick** [GetStream/stream-chat-react#1154]
## Issue
Previews for HEIC & SVG files do not work, either in the upload preview, in the channel, or when clicked to view in lightbox. The file is upload-able, but not preview-able.

## Relevant Code
```typescript
import useBreakpoints from '@hooks/useBreakpoints';
import Button from '@material-ui/core/Button';
import AddFileIcon from '@ui/icons/imaterial/base/Plus in a box.svg';
import EmojiIcon from '@ui/icons/imaterial/emoticons/Emoticon.svg';
import theme from '@ui/theme';
import React from 'react';
import { FileUploadButton, ImageDropzone } from 'react-file-utils';
import { ChatAutoComplete, EmojiPicker, UploadsPreview, useChannelStateContext, useMessageInputContext } from 'stream-chat-react';

export const Input = () => {
  const { md } = useBreakpoints();
  const {
    closeEmojiPicker,
    emojiPickerIsOpen,
    handleEmojiKeyDown,
    handleSubmit,
    openEmojiPicker,
    uploadNewFiles,
    isUploadEnabled,
  } = useMessageInputContext();

  const { acceptedFiles } = useChannelStateContext();

  return (

    <ImageDropzone
      accept={acceptedFiles}
      handleFiles={uploadNewFiles}
    >
      <div style={{ padding: theme.spacing(3, 0), borderTop: '#DDDDDD 1px solid' }}>
        <div style={{ margin: theme.spacing(0, 3) }}>
          {isUploadEnabled && <UploadsPreview />}
          <div
            style={{ display: 'flex', flexDirection: 'row', alignItems: 'center' }}
          >
            <ChatAutoComplete placeholder={'Send your message...'}/>
          </div>
        </div>

        <span
          role="button"
          tabIndex={0}
          style={{ position: 'absolute', left: md ? 90 : 70, bottom: 37, cursor: 'pointer' }}
          onClick={emojiPickerIsOpen ? closeEmojiPicker : openEmojiPicker}
          onKeyDown={handleEmojiKeyDown}
        >
          <EmojiIcon style={{ height: 24, width: 24 }} />
          <EmojiPicker />
        </span>

        <div style={{ position: 'absolute', left: md ? 50 : 40, bottom: 36, width: 24 }}>
          <FileUploadButton
            accepts={acceptedFiles}
            handleFiles={uploadNewFiles}
          >
            <AddFileIcon style={{ height: 24, width: 24, fill: '#000' }} />
          </FileUploadButton>
        </div>


        <Button
          variant="contained"
          color="secondary"
          size="small"
          style={{ position: 'absolute', bottom: 36.5, right: 30 }}
          onClick={handleSubmit}
        >
          Send
        </Button>
      </div>
    </ImageDropzone>
  );
};

export default Input;

```

## Screenshots
![image](https://user-images.githubusercontent.com/67288418/131729925-67a5b3f2-a811-4231-966a-f472c5adf515.png)

![image](https://user-images.githubusercontent.com/67288418/131730819-eb7e929f-537f-4a1c-a71a-71cbcbe84bd9.png)

**Comment by ambaldwin** [comment]
Hello!
What version of 'react-file-utils' are you using? HEIC preview support was added in v1.0.4.
Also, your CDN might not processing the HEIC and turning it into a browser friendly format like jpg/png, browsers can't process HEIC formats. Let us know, thanks!

**Comment by nappernick** [comment]
We're currently using version 1.1.3 of `react-file-utils`. On the CDN front, we're not using a custom CDN, just relying on Stream to manage uploads, so I don't think that's issue. Any other possibilities I should look at or other info I could provide?

**Comment by DanC5** [comment]
Hey @nappernick we actually had a bit of an edge case in `react-file-utils` where we were only looking for `.HEIC`, so `.heic` wasn't rendering properly in the preview. It has been fixed so I'll make a release on that library shortly, and then update the React component library's dependency too.

That said, the image will only not render in the message list if the used CDN is not converting it to a browser-friendly format, which is independent of the preview thumbnail issue. See the attached screenshot from the Chrome Network tab. The uploaded HEIC image has been converted to `content-type: image/jpeg` and it renders fine. Can you inspect the upload and see that Imgix is working properly on your side?

<img width="934" alt="Screen Shot 2021-09-07 at 11 30 08 AM" src="https://user-images.githubusercontent.com/43552931/132372091-bb1da46a-3d95-432d-8820-a8bc4f232066.png">

Regarding the SVG, I have a feeling there's a similar CDN issue going on. When I add an SVG on my side, the image previews in the thumbnail and there's a successful CDN conversion to `content-type: image/svg+xml`, which renders no problem in the message list.

<img width="274" alt="Screen Shot 2021-09-07 at 11 37 11 AM" src="https://user-images.githubusercontent.com/43552931/132372960-12b8d35d-c95b-48a5-a4c4-86a7bcc5fc2e.png">

<img width="789" alt="Screen Shot 2021-09-07 at 11 37 04 AM" src="https://user-images.githubusercontent.com/43552931/132372962-bd097c39-5af5-466b-a731-8d1eaea02e74.png">

Let us know what you find in the Network tab, thanks.
