### ISSUE TITLE
Automatic Markdown formatting in ChatAutoComplete not working

### ISSUE THREAD

**Issue by dylanesque** [GetStream/stream-chat-react#1156]
I'm working on a Next.js application utilizing this library for messaging, and I'm having some trouble with fragile Markdown formatting in the `ChatAutoComplete` component. The details:

- The implementation is basically identical to the example offered in a [previous issue](https://github.com/GetStream/stream-chat-react/issues/951).

- If I *manually* add Markdown styling, or only apply bold or italic styling via the button being pressed to enable `boldState` to `true` before I start typing, no problem.

- If I click the button after I start adding text? If the last character in the wrapped text is a space? If I attempt to add text after the wrapped text (this won't work anyway, the cursor is basically glued to the end of the wrapping formatting characters)? All of these scenarios break markdown formatting. 

- If I try to click the button and apply that styling to already-typed and highlighted text? That doesn't work at all.

It would be really helpful if the example would be fleshed out some more to prevent the latter cases from happening and MD formatting from breaking so easily.

**Comment by ambaldwin** [comment]
Hello! Our default [`renderText` function](https://github.com/GetStream/stream-chat-react/blob/master/src/utils.tsx#L159) now adds bolding markdown functionality for when the message is sent (So you can type **hi** etc. and it's bolded in the MessageList). You're also able to supply your own function for this rendering as a prop on `MessageList`.  Does that help with your use case for bolding messages?

**Comment by dylanesque** [comment]
Not really, no, we are using the `renderText` function elsewhere in the codebase, but I'm talking about the MD formatting not being correctly applied/not allowing for a single unbroken string in an implementation like the above, not the Markdown being rendered in the messages (though that's broken too, I needed to fix that with some custom CSS).

**Comment by ambaldwin** [comment]
Hello! Ok, I wanted to double-check that you were aware that we do offer bolding of messages out of the box. Also, what version of the SDK are you using? If you're using our default message component, MessageSimple, our latest release hides URL link overflow there.

As far as the JavaScript you're asking about, that example for the custom onChange function was really just intended as a starting point and whatever JavaScript is within it, is up to you. Also, this Issues section of this Github repo is reserved for bug reports and feature requests and improvements. It looks like what you are asking for assistance with is a general issue and not directly related to this Stream SDK.

Although we would like to be able to provide this sort of support to all of our customers, it is unfortunately outside the support scope for our limited team. If you would like to discuss this further, our Customer Success team would be glad to hear from you and you may reach them at support@getstream.io. Thanks!
