### ISSUE TITLE
MessageSimple component has no ability to set "grow" prop for MessageInput (in message edit mode)

### ISSUE THREAD

**Issue by volodymyr-manko** [GetStream/stream-chat-react#116]
The inability to set `false` for prop `grow` for **MessageInput** component inside **MessageSimple** component (or configure anyhow **MessageInput** field size) in _message edit mode_ leads to a situation, when large text (in opened Edit message modal) automatically increases the input field, which moves Emoji picker to top and crops it, so the user can't select preferrable emoji:
```
{editing && (
          <Modal open={editing} onClose={clearEditingState}>
            <MessageInput
              Input={EditMessageForm}
              message={message}
              clearEditingState={clearEditingState}
              updateMessage={updateMessage}
            />
          </Modal>
        )}
```

So, could you please add the ability to set additional props for **MessageInput** inside **MessageSimple** component, and/or to support the fixed multirow size for **MessageInput** component (e.g. via prop `maxRows`)

**Comment by jaapbakker88** [comment]
Hi @volodymyr-manko, will have a look at this in the new year. Just to be clear, you're talking about the edit form that's being used in MessageSimple.

**Comment by volodymyr-manko** [comment]
Hi @jaapbakker88, yes I'm talking about edit form that's being used in MessageSimple. 

But as for supporting new prop `maxRows` for MessageInput - I think it'll be good to have the ability to configure it in different parts of a chat, not only in MessageSimple.

**Comment by jaapbakker88** [comment]
#119

**Comment by jaapbakker88** [comment]
@volodymyr-manko included a prop `additionalMessageInputProps` on the Message components. I also added `maxRows` to all the inputs so this is now configurable

it's live right now on `0.7.17`

**Comment by volodymyr-manko** [comment]
Sounds great, thanks! :)

**Comment by Bumboobee** [comment]
> [@volodymyr-manko](https://github.com/volodymyr-manko) included a prop `additionalMessageInputProps` on the Message components. I also added `maxRows` to all the inputs so this is now configurable
> 
> it's live right now on `0.7.17`

This worked for me! Thanks!
