### ISSUE TITLE
@Mention lists only show users you have muted

### ISSUE THREAD

**Issue by JakeLokkesmoe** [GetStream/stream-chat-react#1164]
If you have any users muted, those users become the only ones you can @ mention. I'm pretty sure this line was intended to *exclude* users you have muted, but as written, it instead excludes all users you do not have muted.

https://github.com/GetStream/stream-chat-react/blob/a7885dbc91de5ce2921fb4c4572119ede3ee2a19/src/components/MessageInput/hooks/useUserTrigger.ts#L129

This should be:
```js
return data.filter(function (suggestion) { return mutes.every(function (mute) { return mute.target.id !== suggestion.id; }); });
```

**Comment by ambaldwin** [comment]
Hello! I apologize for the delay and thanks for the note. We've just opened at PR to address this and we expect to have a patch release out later today. I'm going to close this issue - thanks!

**Comment by JakeLokkesmoe** [comment]
Thanks for your help! I think there might still be an issue with the change in that PR though.

https://github.com/GetStream/stream-chat-react/pull/1170/commits/179f9f080fd70c34f4dc742a8f627b3f533bc13a#r708648345
