### ISSUE TITLE
allowNewMessagesFromUnfilteredChannels does not respect new channels for some reason

### ISSUE THREAD

**Issue by PWKad** [GetStream/stream-chat-react#1165]
`ChanneList.allowNewMessagesFromUnfilteredChannels` appears to work well except for when a new channel is created during the session and the user is added while they have the channel list open.  If a new channel is created while the chat is open it will force it's way to the top, regardless of filters.

**Comment by DanC5** [comment]
@PWKad I'm going to close this since we're chatting on zendesk
