### ISSUE TITLE
You can't use a channel after client.disconnect() was called

### ISSUE THREAD

**Issue by lyvecom** [GetStream/stream-chat-react#1188]
When you switch from a guest to a user using the disconnect method to try to run connectUser with new credentials, we get a crash and error: You can't use a channel after client.disconnect() was called. Any way to resolve this? 

We need users to be able to view chat, but can only write in chat once they add a user name.

**Comment by shodgetts** [comment]
This is a tough one and isn't really supported. Essentially you need to perform an entire teardown of the guest client and re-render all of the components with the new WebSocket connection ID and using the updated client. You're going to continue getting errors and crashes if the components try to use the client from the guest user with the React components. I'd encourage you to write logic to ensure the entire component structure is re-rendered with the new client if possible.

**Comment by shodgetts** [comment]
As this is not really an issue related to the React SDK, I'm going to close it and ask you to please reach out to support@getstream.io if you have any more questions. We like to reserve this issues space for actual bugs/feature improvements for the SDK.
