### ISSUE TITLE
Avatar uses charAt, renders broken text when used with emoji name

### ISSUE THREAD

**Issue by legastero** [GetStream/stream-chat-react#1195]
There are several spots using `charAt` instead of the code point methods, which can lead to broken surrogate pairs being rendered.

Specifically, at https://github.com/GetStream/stream-chat-react/blob/master/src/components/Avatar/Avatar.tsx#L51, if a user name starts with an emoji.

That one stayed a bit hidden because the split pair was in an alt attribute and not readily visible.

**Comment by DanC5** [comment]
Hello @legastero, I just opened a PR that addresses this issue and adds support to the fallback logic of the Avatar component. In my testing it now renders emojis properly as the fallback initials. I've been conversing with Juan on Slack, so I'm going to close the GH issue. Thanks!

https://github.com/GetStream/stream-chat-react/pull/1197/files
