### ISSUE TITLE
Issue when importing SCSS style index

### ISSUE THREAD

**Issue by tonyjaimep** [GetStream/stream-chat-react#1199]
Our project cannot use CSS files because of compatibility issues with loaders. I was trying to import the SCSS version of the stylesheet (`stream-chat-react/dist/scss/index.scss`) and when I did it, I got the following error:

```
./node_modules/stream-chat-react/dist/scss/index.scss
@import '../../node_modules/mml-react/src/styles/index.scss';
^
      File to import not found or unreadable: ../../node_modules/mml-react/src/styles/index.scss.
      in /<project_dir>/node_modules/stream-chat-react/dist/scss/index.scss (line 7, column 1)
```

Looks like `mml-react` should be added to the bundle too, right?

**Comment by ambaldwin** [comment]
Hello! What version of the SDK are you using?

**Comment by tonyjaimep** [comment]
```
"stream-chat": "^3.12.1",
"stream-chat-react": "^6.4.2",
```

**Comment by DanC5** [comment]
@tonyjaimep in version 6.4.4 we refactored our import logic for the external dependencies (such as `mml-react`) and no longer draw from node modules, as other clients had similar issues with path resolution. If you upgrade to at least that version you should be fine, but do let us know, thanks.

**Comment by tonyjaimep** [comment]
Thank you :)
