### ISSUE TITLE
MessageText & renderText for stream-chat-react?

### ISSUE THREAD

**Issue by lr-mjaouen** [GetStream/stream-chat-react#121]
Hello,

Is there something like `MessageText` & `renderText` https://github.com/GetStream/stream-chat-react-native/issues/62 in stream-chat-react in order to parse custom text and keep the defaults one (links for instance)?
And actually anything for custom commands or an example for https://getstream.github.io/stream-chat-react/#chatautocomplete?
Thank you!

**Comment by jaapbakker88** [comment]
Hi @lr-mjaouen right now we don't support this. We're working on v2 of the library and I'll make sure to put this on the list. The easiest way to do this right now is to built your own message component.

**Comment by lr-mjaouen** [comment]
@jaapbakker88 thank you. In order to pass a custom prop in a message and display it in a CustomMessage component what's the best way for the input? Right now I use a custom handleSubmit function but I can't reset the state on the message sent.
```
    const handleSubmit = async (event: any) => {
        event.preventDefault();
        const response = await props.channel.sendMessage({
            text: event.target.innerHTML,
            annotation: currentTime,
        });
    };
```
Should I use something else?

**Comment by lr-mjaouen** [comment]
(I extended the `MessageInput` component, I didn't find an other way to do it)

**Comment by jaapbakker88** [comment]
@lr-mjaouen yeah right now that's probably the best way, this might also be someone we want to think about for v2

**Comment by lr-mjaouen** [comment]
https://github.com/GetStream/stream-chat-react/blob/master/src/utils.js
