### ISSUE TITLE
Add `value` to `SuggestionItemProps`

### ISSUE THREAD

**Issue by dannyphillips** [GetStream/stream-chat-react#1210]
I'm using `AutocompleteSuggestionHeader` and `AutocompleteSuggestionItem` props to customize the autocomplete. In my custom components, I'm reusing the types `SuggestionItemProps` & `SuggestionListHeaderProps`.

`SuggestionListHeaderProps` has a `value` key, which can easily be used to build a case statement for the various autocomplete triggers:
```javascript
  const { value } = props
  const initialCharacter = value[0]

  switch (initialCharacter) {
    case '@':
      return (
        <div className="suggestion-header">
          Only team members assigned to or on the distribution list for this
          item will appear below.
        </div>
      )
    case '/':
      return <div className="suggestion-header">Available commands...</div>
    case ':':
      return <div className="suggestion-header">Choose an emoji...</div>
    default:
      return null
  }
```

It would be great to have `value` added to `SuggestionItemProps` so we can build a similar case statement to render the appropriate component.

**Comment by yetieaterxb1** [comment]
Hi @dannyphillips,

Thanks for reaching out to us. We have added the `value` prop to the `SuggestionItemProps` as well and will release this change tomorrow. 

Here is the PR if you would like to look at the change: https://github.com/GetStream/stream-chat-react/pull/1213

Best Regards,
Grant
