### ISSUE TITLE
Convert  AutoCompleteTextarea component to typescript

### ISSUE THREAD

**Issue by akasuv** [GetStream/stream-chat-react#1215]
Hi, Team! We're using Steam as part of our app infrastructure, and it's awesome! I'm noticing AutoCompleteTextarea is still a JS component, I would love to convert it to TS, let me know if you guys need some help.

**Comment by DanC5** [comment]
Hello @akasuv, we very much appreciate the offer to help and are glad you're enjoying the component library!

Just this morning we talked about our plan for the underlying textarea and it's autocomplete functionality. Next week we are going to start work on refactoring these components with plans to publish them as a standalone autocomplete dependency that can be used by developers outside of this SDK. Of course the code will all be modernized and converted to TypeScript, with some helpful new features likely added as well.

Keep an eye out for new library releases as we'll probably have something in a month or so, and will also promote it through the standard dev channels.

I'm going to close this issue as we're starting to make moves on the conversion, thanks!

**Comment by chinesehemp** [comment]
It looks like this component is still using jsx. Any updates?
