### ISSUE TITLE
Edition of a message with a uri attachement duplicates the attachement

### ISSUE THREAD

**Issue by lr-mjaouen** [GetStream/stream-chat-react#122]
![image](https://user-images.githubusercontent.com/56837954/71938600-f471e780-317d-11ea-8b86-9b87373d874a.png)
Editing a message with uri attachement will duplicate the attachement

**Comment by jaapbakker88** [comment]
Hi @lr-mjaouen, thanks for reporting this issue,  this is definitely a bug and we're investigating the source of it. We will report back here once we know more

**Comment by jaapbakker88** [comment]
hi @lr-mjaouen I fixed this issue in version `0.7.19`. Can you confirm it's working correctly now?

**Comment by lr-mjaouen** [comment]
All good!Thanks

**Comment by lr-mjaouen** [comment]
Actually it works for link images but duplicates custom attachements.
![image](https://user-images.githubusercontent.com/56837954/72172224-a12cae80-33a2-11ea-9783-7fff8c139fb6.png)

**Comment by lr-mjaouen** [comment]
could fix it? 
```
       let attachments = [...this.state.attachments];

        if (this.props.message && this.props.message.attachments) {
            // attachments.push(...this.props.message.attachments);
            attachments = this.props.message.attachments;
        }
```

**Comment by jaapbakker88** [comment]
Looking into this again. Seems above fixes some cases but not all.

**Comment by jaapbakker88** [comment]
Going to close this ticket. This should be resolved.

**Comment by Matti93GL** [comment]
This error continues to occur in the `version: "3.5.0"` , i attached image of the problem
<img width="770" alt="Captura de Pantalla 2021-01-25 a la(s) 14 03 22" src="https://user-images.githubusercontent.com/62907714/105738725-1b7c9200-5f16-11eb-87a4-b054d862c764.png">
