### ISSUE TITLE
[Send a message] The same attachment can't be selected if it was deleted from preview

### ISSUE THREAD

**Issue by volodymyr-manko** [GetStream/stream-chat-react#123]
Steps to reproduce:

1. Click "attachment" icon
2. Select attachment in the window
3. Click "delete" the attachment on the preview
4. Try to select the same attachment again

**Expected result:**
The same attachment is selected

**Actual result:**
The same attachment can't be selected.

**Comment by jaapbakker88** [comment]
Can you share a bit more information on this? What MessageInput are you using? What kind of attachment are you selecting?

**Comment by volodymyr-manko** [comment]
Sure, you can reproduce it in any message input field (e.g. in a field with placeholder "Type your message", here: https://getstream.github.io/stream-chat-react/#!/Chat/1).
Attachment means any picture, e.g, in .png format.

It seems it's not related to #122 issue.

**Comment by jaapbakker88** [comment]
I'm not able to reproduce, I just released a fix for the #122 issue. Could you upgrade to version `0.7.19` and try again?

**Comment by volodymyr-manko** [comment]
I'll try to present you the steps to introduce the issue. :)

Steps 1-2:

![step1](https://user-images.githubusercontent.com/55987896/72157944-c11f9a80-33c1-11ea-8866-03248d9f270b.png)

Step 3:

![step2](https://user-images.githubusercontent.com/55987896/72157945-c11f9a80-33c1-11ea-8ae6-6604a2a25717.png)

Step 4: same as steps 1-2 (try to attach the same image, that was previously removed from preview).

Result (nothing is attached):

![step4](https://user-images.githubusercontent.com/55987896/72157948-c11f9a80-33c1-11ea-8159-9daca0d66ca0.png)

**Comment by jaapbakker88** [comment]
I can see the image failed to upload the first time, do you see any errors in the console?

**Comment by volodymyr-manko** [comment]
You are right, that image really failed to upload, and now I see the error in a console (bad image example from my side). 
Nevertheless the same steps are also reproduced for valid images which are uploaded successfully. Try please again.

**Comment by jaapbakker88** [comment]
I am able to reproduce this now, will look in to this.

**Comment by vishalnarkhede** [comment]
Fix will be ready soon - https://github.com/GetStream/react-file-utils/commit/474a17a7a49cba867f9d28bbc970610e6012d3b5

**Comment by vishalnarkhede** [comment]
Hey @volodymyr-manko this issue was fixed and released. Please use the latest version of stream-chat-react and let us know if its still not working for you

**Comment by volodymyr-manko** [comment]
> Hey @volodymyr-manko this issue was fixed and released. Please use the latest version of stream-chat-react and let us know if its still not working for you

Thanks!
