### ISSUE TITLE
Channel mark read fails silently if no initialized channels when first loaded

### ISSUE THREAD

**Issue by kainosnoema** [GetStream/stream-chat-react#1231]
Took us awhile to figure out what was going on here (`stream-chat-react@6.9.1`). We're seeing intermittent cases where a channel does not get marked as read at all. Turns out it happens when the `Channel` component is mounted before any channels are initialized.

1. The component grabs the config on first update here: https://github.com/GetStream/stream-chat-react/blob/fb32750de2dab89fe39bb833ab571ecca03a6ce3/src/components/Channel/Channel.tsx#L320
2. If no channels of this type have been initialized yet, this value is `undefined`.
3. The `channelConfig` value is never updated, even after channel initialization.
4. On new messages, the `markRead` function checks `channelConfig` and skips if it's undefined: https://github.com/GetStream/stream-chat-react/blob/fb32750de2dab89fe39bb833ab571ecca03a6ce3/src/components/Channel/Channel.tsx#L338-L339

The next time the component is forced to update this is fixed, but there's a window where read events just don't work at all.

**Update:** Further, anything that uses `channelConfig` in the `ChannelStateContext` will also fail unexpectedly even after the channel is initialized. Might be a good idea to use state there and update it once it's available and anytime the config is updated.

**Comment by yetieaterxb1** [comment]
Hi @kainosnoema,

Thanks for reaching out and bringing this to our attention. Out of curiosity has this been happening recently after a recent update or has it always been an issue? 

Best,
Grant

**Comment by yetieaterxb1** [comment]
Hey @kainosnoema I was doing some testing while leaving the `channelConfig` `undefined` while `Channel` is mounted. I couldn't get the marked as read issues you are having. 

I appreciate the detailed info you shared already, but is there anything else you could share about the setup of your app just to help me recreate this.

**Comment by kainosnoema** [comment]
@yetieaterxb1 not sure what more to add here, as you can see from the code I linked to (in latest release), the `markRead()` function returns early when `channelConfig` is undefined.

Some helpful context might be that we're not using `ChannelList`, but instead managing that part ourselves so the `Channel` component is mounted before any channels are queried or initialized—but this should be a valid way to use the component based on everything I've seen.

Here I've simply breakpointed it and it happens every time to me when I first load the Channel component prior to initializing any channels:
<img width="914" alt="Screen Shot 2021-10-08 at 10 51 14 AM" src="https://user-images.githubusercontent.com/145951/136601127-22fe1227-6d67-48a2-9977-9a8a7e8bd968.png">
