### ISSUE TITLE
Missing 'ChannelListTeamProps' in stream-chat-react

### ISSUE THREAD

**Issue by gozanohesron** [GetStream/stream-chat-react#1266]
In typescript, I am getting this error '"stream-chat-react"' has no exported member named 'ChannelListTeamProps'. Did you mean 'ChannelSearchProps'?

**Comment by DanC5** [comment]
Hello @gozanohesron, `ChannelListTeam` is a deprecated and removed component, therefore its props type no longer exists. Feel free to use `ChannelListMessengerProps` instead, as this pertains to the default `List` prop on the `ChannelList` component.

**Comment by DanC5** [comment]
I'm going to close as this should fix your problem, but I'll continue to receive notifications on this issue if you have further questions, thanks!

**Comment by gozanohesron** [comment]
@DanC5 can you update the demo code as it is still using said code? I am trying to study the demo code but I am having problem with that specific line. After putting the component you mentioned, I got new error pertaining to the children property

**Comment by DanC5** [comment]
Which demo are you referring to?

**Comment by gozanohesron** [comment]
@DanC5 this one

https://github.com/GetStream/website-react-examples/tree/master/social-messenger

**Comment by DanC5** [comment]
Oh I see, `social-messaging-ts` in the website examples repo. I'll push that change up right now

**Comment by gozanohesron** [comment]
@DanC5 yes yes, the TS version of that app. I am getting errors for that

**Comment by DanC5** [comment]
Just updated, https://github.com/GetStream/website-react-examples/blob/master/social-messenger-ts/src/components/MessagingChannelList/MessagingChannelList.tsx#L22.

Are you wrapping the type in React.FC like in the example? https://github.com/GetStream/website-react-examples/blob/master/social-messenger-ts/src/components/MessagingChannelList/MessagingChannelList.tsx#L26

You need this so TypeScript knows the component will render children. If you're not using React.FC then you can wrap the type in `PropsWithChildren`, imported from React.

`PropsWithChildren<ChannelListMessengerProps>`

**Comment by gozanohesron** [comment]
@DanC5  I am just following the demo code as it is. I'm just studying it how to implement on our own app

**Comment by gozanohesron** [comment]
Hi @DanC5 would you mind helping me, I am getting last two errors with the ff files
![image](https://user-images.githubusercontent.com/8002580/140122412-d0ef4c4d-b19f-4cb7-9ae9-ed18e541a04d.png)
![image](https://user-images.githubusercontent.com/8002580/140122839-795fffd8-dbbf-4e43-bcdc-ca5841960977.png)

**Comment by gozanohesron** [comment]
or perhaps should I report this on the example repository?

**Comment by gozanohesron** [comment]
@DanC5 it did fix the issue for the second one

**Comment by gozanohesron** [comment]
@DanC5 thank you very much for the assistance
