### ISSUE TITLE
Search Function and Search Input Implementation

### ISSUE THREAD

**Issue by gozanohesron** [GetStream/stream-chat-react#1268]
Hi. Is there anyone who can assist or direct me to a sample how to use this? 

https://getstream.io/chat/docs/sdk/react/utility-components/channel_search/#searchfunction
https://getstream.io/chat/docs/sdk/react/utility-components/channel_search/#searchinput

I am trying to do it this way.

```
 searchFunction: (params: ChannelSearchFunctionParams, event: React.BaseSyntheticEvent) => {
            const search = async () => {
                params.setSearching(true);
                await chatClient?.queryChannels({ type: 'messaging', members: { $in: [header.userId!] }, 'member.user.name': { $autocomplete: event.target.value } }).then(channel => {
                    params.setResults(channel);
                    params.setSearching(false);
                    params.setResultsOpen(true);
                })
            }

            search();
        }

```
Or how can I get the value of the search field so I can set it here

```
searchQueryParams: {
            channelFilters: {
                filters: { type: 'messaging', members: { $in: [header.userId!] }, 'member.user.name': { $autocomplete: [I WANT TO PUT THE SEARCH VALUE HERE] } }
            }
        },
```

**Comment by zacheryconverse** [comment]
Hello and thanks for getting in touch, we’re excited you’re getting hands on with our product. 

However, the Issues section of this Github repo is reserved for bug reports and feature requests and improvements. It looks like what you are asking for assistance with is a general issue.

Although we would like to be able to provide this sort of support to all of our customers, it is unfortunately outside the support scope for our limited team. If you would like to discuss this further, our Customer Success team would be glad to hear from you and you may reach them at support@getstream.io.

In case our understanding is incorrect and you are describing a bug, we apologize, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly. In the meantime, we are going to mark this issue as closed.
