### ISSUE TITLE
Channel Query using Channel Name

### ISSUE THREAD

**Issue by gozanohesron** [GetStream/stream-chat-react#1271]
Is there any way to filter using channel name? I think that will be a good filter. I would like to filter the name 'My Sample Channel'

![image](https://user-images.githubusercontent.com/8002580/140489737-dd157999-83ac-4ed1-a16a-ccb5275e4327.png)

**Comment by DanC5** [comment]
Hey @gozanohesron glad you figured this one out. Just for future reference though, please direct these kinds of inquiries to support. We have a dedicated support team that operates in all time zones that are equipped to handle these kinds of questions. GitHub issues should be reserved for potential bugs/fixes on the library, whereas integration help should go to support. Thanks!
