### ISSUE TITLE
Add formatDate prop to MessageSimple component

### ISSUE THREAD

**Issue by volodymyr-manko** [GetStream/stream-chat-react#128]
Currently **MessageSimple** component doesn't allow to change default formatting of message timestamp:

```
const when = moment(message.created_at).calendar();
```

Could you please support `formatDate` prop for **MessageSimple** component, like in **DateSeparator** case?

```
/** Override the default formatting of the date. This is a function that has access to the original date object. Returns a string or Node  */
    formatDate: PropTypes.func,
```

**Comment by jaapbakker88** [comment]
Hi @volodymyr-manko I will take a look at resolving this as soon as possible

**Comment by jaapbakker88** [comment]
@volodymyr-manko we've started work on this feature. Will update you here if we have more to report.

**Comment by volodymyr-manko** [comment]
Thanks :)
