### ISSUE TITLE
Incompatibility with Next.js 11 due to static import of images

### ISSUE THREAD

**Issue by rafaelalmeidatk** [GetStream/stream-chat-react#1285]
The library assumes that every app that consumes it has a loader configurated for images imports, which isn't always the case. The `Attachment/Card` component is importing an image here:

https://github.com/GetStream/stream-chat-react/blob/9f7be762a36b765c6afcef1fe749cbcf4f620bf5/src/components/Attachment/Card.tsx#L5

And this throws an error when using Next.js:

> error - ./node_modules/stream-chat-react/dist/assets/Poweredby_100px-White_VertText.png
> Module parse failed: Unexpected character '�' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> (Source code omitted for this binary file)

The proposed solution in #1034 isn't ideal because the `next-images` library is incompatible with Next.js's built-in support for static images imports (that you can use with the `next/image` component). [Reference](https://nextjs.org/docs/upgrading#nextconfigjs-customization-to-import-images)

It would be better if `stream-chat-react` replaced the static image imports with inline SVG components, so there is no need for custom loaders in the users apps.

**Comment by petyosi** [comment]
Thank you @rafaelalmeidatk - indeed, this is a problem. We will research for a proper solution, perhaps there's a way to eliminate the import entirely.

**Comment by rafaelalmeidatk** [comment]
Yeah it is possible to remove the import, my suggestion is to use SVG components. So instead of importing an image file, you can write a component like this (either in another file or in the file it's used):
```js
export const PoweredByGiphy = (props) => (
  <svg aria-labelledby="pbgiphy" role="img" {...props}>
    <title id="pbgiphy">Powered By Giphy</title>
    <path ... />
  </svg>
)
```

And use it in the other components like a normal component:
```js
const Example = () => (
  <PoweredByGiphy className="..."  />
)

**Comment by petyosi** [comment]
@rafaelalmeidatk we are going to just move the image to CSS, eliminating the need for image imports or SVG. I'm also examining few other things that don't seem to work with next@12.

**Comment by petyosi** [comment]
@rafaelalmeidatk we are working on this here: https://github.com/GetStream/stream-chat-react/pull/1315

**Comment by petyosi** [comment]
@rafaelalmeidatk this has been released recently, please let us know if the issue persists.

**Comment by petyosi** [comment]
That is the right version - give it a try.

**Comment by rafaelalmeidatk** [comment]
@petyosi sorry for the delay, I upgraded the dependencies and the issue is fixed. Thank you!
