### ISSUE TITLE
`openMentionsList` does not exist on `useMessageInputContext`

### ISSUE THREAD

**Issue by dannyphillips** [GetStream/stream-chat-react#1286]
I'm trying to use `openMentionsList` per this PR: https://github.com/GetStream/stream-chat-react/pull/1261, but getting 
`
Property 'openMentionsList' does not exist on type 'MessageInputContextValue<MessengerType, DefaultChannelType, LiteralStringForUnion, UnknownType, DefaultMessageType, UnknownType, DefaultUserType<...>, CustomTrigger>'`

**Comment by dannyphillips** [comment]
Related: https://github.com/GetStream/stream-chat-react/issues/1256

**Comment by yetieaterxb1** [comment]
Hey @dannyphillips we are waiting for another change to the library and will be making a release after that. 
Aologize for the delay. 

Best,
Grant

**Comment by dannyphillips** [comment]
okay. thanks for letting me know

**Comment by ambaldwin** [comment]
Hi @dannyphillips this is now released in v6.12.0. Thanks!
