### ISSUE TITLE
Provide global custom MessageInput/handleSubmit for both, message sending and message edition

### ISSUE THREAD

**Issue by lr-mjaouen** [GetStream/stream-chat-react#129]
Provide global custom MessageInput/handleSubmit for both, message sending and message edition in order to use the same extended `handleSubmit` function. 

Right now the only possible way to extend it is to extend the `MessageInput` component if so it's not the same component use in `Message***` (ex `MessageSimple`) component.

**Comment by jaapbakker88** [comment]
@lr-mjaouen i'm not a 100% sure what you mean. Could you elaborate on this?

**Comment by lr-mjaouen** [comment]
The question is, how can I send an extended message (a custom attachment) using the chat input?
So extending the `MessageInput` component and change the `handleSubmit` function. Ok.
The problem is when I edit a message, it use the default one and not the extended one, so I have to extend `MessageSimple `.
To be able to provide a custom `handleSubmit` or a custom attachment shouldn't be a default option?

**Comment by jaapbakker88** [comment]
How would you like to extend it. We have a prop called `overrideSubmitHandler`, this will completely override it, so you can technically implement your own custom attachments etc.

Is that what your looking for

**Comment by lr-mjaouen** [comment]
https://github.com/GetStream/stream-chat-react/commit/3478f2e334824356f95d166cb4e9efa0fae07d23 thx

**Comment by jaapbakker88** [comment]
That's definitely an option. Will investigate a way to make this more useful.

**Comment by lr-mjaouen** [comment]
Thanks, a line line could be enougth
```
       this.props.overrideSubmitHandler(
                {
                    text,
                    attachments,
                    mentioned_users: uniq(this.state.mentioned_users),
                    parent: this.props.parent,
                },
                this.props.channel.cid,
                this.props
            );
```

**Comment by lr-mjaouen** [comment]
(Providing a possible global hook before delete, update & create (send) could be nice I think maybe)

**Comment by jaapbakker88** [comment]
@lr-mjaouen we now export a useMessageInput hook that lets you use all of the functionality of the MessageInput yourself, more information on that here: https://github.com/GetStream/stream-chat-react/blob/master/src/docs/MessageInputHooks.md

**Comment by WebPro9369** [comment]
@jaapbakker88 Is `useMessageInput` still available to use? I'm not sure if I can use it.

**Comment by ambaldwin** [comment]
Hi @WebPro9369 yes, we still provide this hook: https://github.com/GetStream/stream-chat-react/blob/master/src/docs/useMessageInput.md. Are you getting an error when you're implementing?

**Comment by WebPro9369** [comment]
@ambaldwin Thanks for your response.
I think it doesn't get exported in TS version.

**Comment by ambaldwin** [comment]
Hi @WebPro9369 , I believe we are exporting it. Check out:
https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageInput/hooks/messageInput.ts

A good example of implementation of this hook is from our example repo and the Team TypeScript app. We are using v.5.2.1 in this app.
https://github.com/GetStream/website-react-examples/blob/master/team-ts/src/components/TeamMessageInput/TeamMessageInput.tsx

Am I missing something? Are you getting an error when trying to implement?

**Comment by wallawe** [comment]
For anyone else arriving here from google like I have wondering what happened to `useMessageInput`, it's now `useMessageInputContext`
