### ISSUE TITLE
Adding transparency (opacity) to top comments in chat

### ISSUE THREAD

**Issue by lyvecom** [GetStream/stream-chat-react#1298]
We're currently using your React library and are using chat as an overlay on a video. 

We can not figure out how to add transparency (opacity) to the top comments. You have this in your React Native library, but nothing with React. Can this be done?

**Comment by petyosi** [comment]
Hey, 

I assume that you want to achieve something [like this](https://codesandbox.io/s/modern-surf-dce3e?file=/src/styles.css:233-265). You can use your browser inspector to see the CSS classes of the message elements and set their background.

Let us know if this is what you had in mind.

**Comment by lyvecom** [comment]
That is exactly it, thank you!
