### ISSUE TITLE
Feature request: MessageInputFlat with custom UploadsPreview

### ISSUE THREAD

**Issue by robrechtme** [GetStream/stream-chat-react#1299]
Hi 👋

I want to use a custom `UploadsPreview` in my message input. 

Unfortunately, it is baked into [`MessageInputFlat`](https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageInput/MessageInputFlat.tsx#L90), so I have to copy-paste the entire component just to change the `UploadsPreview`. It would be nice if this could be changed in a prop and passed into the `componentContext`, just like `FileUploadIcon` and `SendButton` already are. 

Just a suggestion 😁. Let me know if you would like me to submit a PR.

**Comment by petyosi** [comment]
Thank you for the suggestion @robrechtme - if you feel like submitting a PR, we would gladly accept that. 

Regards,

**Comment by robrechtme** [comment]
I can look into it if I find the time 😁

**Comment by MartinCupela** [comment]
It is possible to customize uploads preview with `AttachmentPreviewList` component now. Passing it as a prop to `Channel` component.
