### ISSUE TITLE
Long link in message does not get truncated properly

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#1302]
When sending a message that includes a long link, it's not truncating it and breaks the UI

Tested it in https://getstream.io/chat/demos/messaging/ and can be replicated with any long link like this one https://www.google.com/search?q=funny+cat+pictures&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjtouebhdb0AhXQUWwGHQ0MBNUQ_AUoAXoECAEQAw&biw=3050&bih=1253&dpr=1
![image](https://user-images.githubusercontent.com/1654135/145343334-b83a13f7-146d-42e5-9d65-cf5cd28788b7.png)

**Comment by ambaldwin** [comment]
Hi! What version of the React library do you see this in?
We did have a fix in [v6.6.0](https://github.com/GetStream/stream-chat-react/blob/develop/CHANGELOG.md#660-2021-08-30) that addressed this, so please let us know what version you're using. Thanks!

**Comment by ambaldwin** [comment]
I just noticed that this is in our demo app on our website - we are a couple versions behind in our demo app currently, but this is on our radar to get completed.

I'm going to close this issue. Thank you!

**Comment by alexlopezit** [comment]
We are using version 6.11.0 and had fixed it overwriting the link css by adding white-space pre-wrap and works fine for us now.
