### ISSUE TITLE
How can I fix the error of "Uncaught ChunkLoadError: Loading chunk 0 failed."?

### ISSUE THREAD

**Issue by SatoshiKawabata** [GetStream/stream-chat-react#1308]
I got this error on open EmojiPicker... How can I fix it?
```
Uncaught ChunkLoadError: Loading chunk 0 failed.
(error: http://localhost:3000/test1/test2/0.index.js)
    at Function.requireEnsure [as e] (bootstrap:105)
    at EmojiContext.js:55
    at step (EmojiContext.js:43)
    at Object.next (EmojiContext.js:24)
    at EmojiContext.js:18
    at new Promise (<anonymous>)
    at ./node_modules/stream-chat-react/dist/context/EmojiContext.js.__awaiter (EmojiContext.js:14)
    at EmojiContext.js:51
    at initializeLazyComponentType (react-dom.development.js:1432)
    at readLazyComponentType (react-dom.development.js:11862)
```

I use react-router. The MessageInput component is used in the page of `/test1/test2`. When I click the emoji button and open EmojiPicker, I got above error.

I use webpack bundle. EmojiContext uses `React.lazy` and EmojiPicker component uses `Suspense`. I guess the `0.index.js` file exists on `/0.index.js` but the page of `/test1/test2` is opened so get from the relative path `/test1/test2/0.index.js`. The file path does not exist...

## Version
I use this version.
```
    "stream-chat": "^4.4.2",
    "stream-chat-react": "^6.11.0",
```

**Comment by ambaldwin** [comment]
@SatoshiKawabata thanks for this. Are you using NextJS? We are working on related errors [in #1315 PR](https://github.com/GetStream/stream-chat-react/pull/1315). Please let us know, thanks!

**Comment by SatoshiKawabata** [comment]
@ambaldwin Thanks! I'm waiting for shipping it on production.
