### ISSUE TITLE
`channel.updated` event results in an override of the `own_capabilities` on stream-chat-react version `6.12.2`

### ISSUE THREAD

**Issue by BrianLi101** [GetStream/stream-chat-react#1310]
In the latest version of the library (`6.12.2`), I've noticed an issue where the firing of the `channel.updated` event results in the disappearance of a number of fields on the active `channel` of `useChatContext()`. Most notably, the `own_capabilities` field ends up disappearing and resulting in the inability to perform a number of actions on the `MessageSimple`.

Below is a screenshot from a wrapper component we wrote (`ChatMessageList`) for `MessageList` that does not customize the behavior of the original component. It has a hook initialized on the `channel` value from `useChatContext()` that listens for all of the events and logs out the `own_capabilities` of the `channel`. As you can see, the `channel.updated` event firing results in an overwriting of `own_capabilities` which causes message-level features like ['react', 'reply', ...] to disappear.

<img width="932" alt="Screen Shot 2021-12-12 at 11 15 02 PM" src="https://user-images.githubusercontent.com/17527579/146053337-e22dee6e-1b27-4b40-ae99-b8c89db83dac.png">

**Comment by yetieaterxb1** [comment]
Hi @BrianLi101,

Thanks for reaching out and bringing this to our attention. Could you please provide a code snippet to help me reproduce this on my end? Currently I cant reproduce this issue.

Best,
Grant

**Comment by BrianLi101** [comment]
Hi Grant,

When using the latest version of `stream-chat-react`, I've been able to get the issue any time there is a backend update to the channel and show it using the code below:

```
import React from 'react';
import {
	MessageList,
	MessageListProps,
	useChatContext,
} from 'stream-chat-react';

const ChatMessageList: React.FC<MessageListProps> = (props) => {
	// TODO: use this to debug the own_capabilities issue in stream-chat-react version 6.10.0 or later
	const { channel } = useChatContext();
	React.useEffect(() => {
		if (channel) {
			console.log('configuring listening for channel events');
			channel.on((event) => {
				console.log('event', event);
				console.log('channel.state', channel.state);
				console.log(channel.data?.own_capabilities);
			});
		}
	}, [channel]);
	return <MessageList {...props} />;
};

export default ChatMessageList;
```

**Comment by yetieaterxb1** [comment]
Hey Brian,

Thanks for such a detailed response. We have narrowed down what causes this issue and will let you know when we have a fix for it. 

Best,
Grant
