### ISSUE TITLE
Get unread count for different channel types

### ISSUE THREAD

**Issue by sergeyzhukov** [GetStream/stream-chat-react#1316]
What is the most efficient way to get an unread count for each group of channels grouped by type? 

For example, we have some channels with `type = 'sms'` and some channels with `type = 'team'`. And we want to display both of these unread count badges on the same screen.  (example attached)
<img width="440" alt="Screenshot 2021-12-23 at 19 35 44" src="https://user-images.githubusercontent.com/1446268/147263573-47265b3f-b2d9-4a2f-8116-8e937dfc1144.png">

<img width="446" alt="Screenshot 2021-12-23 at 19 35 54" src="https://user-images.githubusercontent.com/1446268/147263589-6f2c54c6-1dfd-40e4-bc3c-476ea51c8f22.png">

In a typical case with only one type of channel, we used `total_unread_count` from events, but this is impossible if we need to compute the unread count for each type of channel on the fly. 

Maybe you have some example of how to implement this?

**Comment by zacheryconverse** [comment]
Hello, and thanks for submitting an issue to our GithHub repository. We’re glad you’re getting hands on with the product!

Channel **Types** are only meant for channels with differing permissions. Perhaps you are able to create sms and team channels with the same channel type?

The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.
