### ISSUE TITLE
"Quotes" (aka replies) still available in message options when quotes disabled in configuration

### ISSUE THREAD

**Issue by jmckenney** [GetStream/stream-chat-react#1320]
As an admin, I would like to be able to disable  the "reply" option from message options so that I can maintain parity with previous chat experience while migrating.

With threads/replies and quotes disabled:
<img width="1312" alt="Stream___Channel_Type" src="https://user-images.githubusercontent.com/3220205/148309236-b7eec4d6-d2f2-4a4c-b768-f0fb052df8ed.png">

Reply option is still available for a message:
<img width="408" alt="reply" src="https://user-images.githubusercontent.com/3220205/148309371-9df580e6-65b0-49aa-8c1b-dc9d7d7cde74.png">

If I try to reply to the message and attempt to send, I am given this error:
```
StatusCode: 400
code: 19
duration: "0.00ms"
message: "SendMessage failed with error: \"SendMessage failed with error: \"SendMessage failed with error: \"SendMessage failed with error: \"SendMessage failed with error: \"quotes are not enabled for this channel\"\"\"\"\""
more_info: "https://getstream.io/chat/docs/api_errors_response"
```

**Comment by jmckenney** [comment]
Dug a bit deeper and it does look like the component is getting the correct channel configuration to provide as context:
<img width="767" alt="channelConfig-settings" src="https://user-images.githubusercontent.com/3220205/148420013-3c3cfecf-0ceb-45e1-97eb-abe6c5733fbd.png">

But the message itself isn't getting that setting:
<img width="765" alt="disableQuotedMessagesBoolean" src="https://user-images.githubusercontent.com/3220205/148420061-33fb019f-51e6-41c3-ab5d-72ed0fe99544.png">

FYI, current version: `resolution: "stream-chat-react@npm:6.12.2"`

**Comment by petyosi** [comment]
This seems like a bug on our side indeed. We'll take a look.

**Comment by yetieaterxb1** [comment]
To fix this issue you can use ` const { channelConfig } = useChannelStateContext();` and then pass this prop to the `MessageList` to get your desired outcome like this ` <MessageList disableQuotedMessages={!channelConfig?.quotes} />`

**Comment by jmckenney** [comment]
> To fix this issue you can use ` const { channelConfig } = useChannelStateContext();` and then pass this prop to the `MessageList` to get your desired outcome like this ` <MessageList disableQuotedMessages={!channelConfig?.quotes} />`

This worked, thanks very kindly for the quick reply. 

![1_JmdR9_AyUCgvvBYDV6PTDw](https://user-images.githubusercontent.com/3220205/148623164-6e76bbe9-2de2-42d0-89b8-1112ed23070a.jpeg)

**Comment by yetieaterxb1** [comment]
No problem at all!

**Comment by jmckenney** [comment]
I see this is now fixed in newest upgrade. Thanks kindly!
