### ISSUE TITLE
Error: expected string for field "message.mentioned_users[0]" but got object

### ISSUE THREAD

**Issue by joefatora** [GetStream/stream-chat-react#1322]
We had been sending the user objects as the values of the mentioned_users array without issue, but all of a sudden it broke and appears to require the user ID instead. The documentation still seems to indicate that the user object should be passed. We are using the built-in Autocomplete component to handle mentions. Does something need to be updated?

stream-chat-react version: 6.0.4
stream-chat version: 3.10.0

**Comment by ambaldwin** [comment]
Hi @joefatora the value should still be users. Did you upgrade stream-chat-react or stream-chat right before getting this error? Your stream-chat version is a couple major versions behind, we're now at 5.1.1. Are you using any custom components involving the input or wherever you're adding mentioned users? Thanks!

**Comment by petyosi** [comment]
@joefatora please let us know if we can help further. Thanks!
