### ISSUE TITLE
A way to call function scrollToBottom from a VirtualizedMessageList

### ISSUE THREAD

**Issue by ivanros** [GetStream/stream-chat-react#1328]
We need to render a custom button whenever the scroll is not at the bottom limit so it goes there when pressed.

Is there a way to call `VirtualizedMessageList`'s `scrollToBottom` function?

**Comment by petyosi** [comment]
@ivanros you can use the `Channel` MessageListNotifications property for that purpose: https://getstream.io/chat/docs/sdk/react/core-components/channel/#messagelistnotifications
