### ISSUE TITLE
firstOfGroup not working on first message

### ISSUE THREAD

**Issue by ivanros** [GetStream/stream-chat-react#1337]
The `VirtualizedMessageList` prop `firstOfGroup` is not working with the first message in a chat as it doesn't have any message previous to itself.

https://github.com/GetStream/stream-chat-react/blob/9f7be762a36b765c6afcef1fe749cbcf4f620bf5/src/components/MessageList/VirtualizedMessageList.tsx#L239-L242

Maybe if there is not previous message it should be `true`.

**Comment by zacheryconverse** [comment]
Thanks for reaching out about this issue. We have a fix for this and you can expect to see it in our next release. I'll go ahead and close this issue, but feel free to contact us anytime. Have a beautiful day.

Cheers
