### ISSUE TITLE
Update ChatAutoComplete proposition: adding onBlur props

### ISSUE THREAD

**Issue by SFromentarius** [GetStream/stream-chat-react#1345]
In case we want to access `onBlur` of the `textarea` behind `ChatAutoComplete` component we could create the onBlur props here and pass it to `AutoCompleteTextarea` which already has `onBlur` as props.

https://github.com/GetStream/stream-chat-react/blob/2b26d54a2981aa42abd81c8bb743f0a70b4e0df8/src/components/ChatAutoComplete/ChatAutoComplete.tsx

What do you think? Thanks

**Comment by petyosi** [comment]
Thank you for the suggestion @SFromentarius - we are in the middle of updating the input implementation, so we will take that into account.

**Comment by SFromentarius** [comment]
Thanks for the feedback @petyosi ✨
