### ISSUE TITLE
UploadsPreview for MessageInputSmall displays the send button of MessageInputFlat

### ISSUE THREAD

**Issue by eindride** [GetStream/stream-chat-react#1349]
`MessageInputFlat` and `MessageInputSmall` use the same `UploadsPreview` component. `UploadsPreview`, when deciding if it should show the `str-chat__send-button`, does a `getElementsByClassName` and uses the first element returned. Which is always the send button of the `MessageInputFlat` component.

So if in a thread you try to upload a file the send button will appear in the main chat's input and not in the thread's input

**Comment by petyosi** [comment]
Thanks for the report, we will look into it.

**Comment by zacheryconverse** [comment]
Hi @eindride. A fix for this has been made and will be in our next release. Cheers
