### ISSUE TITLE
Modal component is also not exported nor typed

### ISSUE THREAD

**Issue by damianprzygodzki** [GetStream/stream-chat-react#135]
I can't use Modal i.e. when i want to customize editing of message...

Guys, this "UI-kit" is pretty useless when you want to use it with typescript. You are using doubled declarations of propTypes (one in components, second in ts files). Maybe its good to make refactor of these or make awareness that ts here is not supported?

**Comment by vishalnarkhede** [comment]
Hey @damianprzygodzki  we will soon update this repo by exporting all the components with their types. 

Our next major refactor will publish all the components in typescript itself instead of maintaining separate typescript declaration file.
