### ISSUE TITLE
Preview for channel with unread message isn't rendered as bold  .... after connection recovered.

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-react#1351]
Say I have Channel A and B. I am on Channel A. If I receive a message from Channel B, the Preview in ChannelList would display the new message snippet and become bolded to indicate that there is a new unread message. This works perfectly realtime when the websocket is well and alive.

Now I turn off Wifi. Someone sends some messages in Channel B. I turn Wifi back on ....
The Preview for Channel B would actually pick up the new message and render the snippet, BUT .... the Preview isn't bolded somehow (as if there is no unread message). If I switch to other unrelated Channel (or reload the page), Channel B's Preview would be rendered as bold correctly.

**Comment by linhewinner** [comment]
Any update here? Thread list also isn't reordered FWIW

**Comment by MartinCupela** [comment]
@linhewinner did you use the default components with default setup or are there some customizations on your side? If so, could you please share more details in order we can reproduce the issue on our side?

**Comment by MartinCupela** [comment]
@linhewinner this issue is fixed by #1458

**Comment by linhewinner** [comment]
Cool, thanks!

Is it possible for you to comment here when this is out in a release? I'll update my dependency then.
