### ISSUE TITLE
Sream-chat-app Dependency is not installing / (Shwoing error)

### ISSUE THREAD

**Issue by vansh12345341** [GetStream/stream-chat-react#1357]
Whenever I try to install stream-chat-react dependency it shows a error unable to resolve the dependency tree and a long line of errors whereas when I tried to install stream-chat using npm it got installed and even showed in the package.json folder.I would like to get this issue resolved.

**Comment by petyosi** [comment]
Hey, 
Which version of node/npm you're using? Can you paste the error you get?

**Comment by vansh12345341** [comment]
node version -> v16.13.2
npm version -> 7.12.0
![image](https://user-images.githubusercontent.com/57994031/151931227-06a82764-f311-45aa-b8a1-6046fab56744.jpg)

Here is a Image link of the error You can open it in the browser

**Comment by petyosi** [comment]
Did you try the suggestion provided?
```
retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by vansh12345341** [comment]
okay it worked thanks
