### ISSUE TITLE
EmptyStateIndicator appears during channels loading

### ISSUE THREAD

**Issue by alex-dolbik** [GetStream/stream-chat-react#1361]
According this code https://github.com/GetStream/stream-chat-react/blob/master/src/components/ChannelList/ChannelList.tsx `EmptyStateIndicator` doesn't check loading status and appears during channels loading.

Can we improve that or at least prop `isLoading` to be able to control component rendering logic?

**Comment by ambaldwin** [comment]
Hi @alex-dolbik , the `List` UI component checks the loading status via the values that are sent via the `loading` prop and if channels are being loaded then just the `LoadingIndicator` component is rendered, not the children components which includes the paginator/empty state indicator. See this in action [here](https://github.com/GetStream/stream-chat-react/blob/develop/src/components/ChannelList/ChannelListMessenger.tsx#L68) in the SDK's default channel list UI component. Perhaps you're not accounting for this in a custom ui component? Or, please let me know if you think I'm missing something.

**Comment by petyosi** [comment]
@alex-dolbik let us know if you need further assistance here. Thank you!
