### ISSUE TITLE
About Vite compiler

### ISSUE THREAD

**Issue by ivanros** [GetStream/stream-chat-react#1375]
We are testing to compile our project, which has `stream-chat-react` as a dependency, with Vite. After several tests it seems that there is no compatibility with the Vite build since there is a dependency called `custom-events` in this repository that needs `global` variable support. 

We have tested with the following configuration that you use as an example here...
https://github.com/GetStream/stream-chat-react/blob/develop/examples/vite/vite.config.ts#L6
...but other libraries start to fail after the definition of `global` in the configuration.

Is there any way to compile your project with Vite without `global` giving problems?

**Comment by ambaldwin** [comment]
Hi @ivanros instead of putting global in the define section of the vite config file, try adding the following snippet at the bottom of the body and let us know how that goes. Thanks!

```
<script>
      var global = globalThis;
      global.ICAL = global.ICAL || {};
    </script>
```

**Comment by ivanros** [comment]
Hello, thank you very much for your quick response. 

It is indeed a solution that works for us, but we are not very convinced to assign the `global` variable in the `index.html` in this way. 
From what we have investigated it is your `custom-events` dependency that causes this `global` to fail, do you know if there will be an update in which you remove this dependency or adapt it for all browsers?

**Comment by ambaldwin** [comment]
Hi @ivanros we have created a task in our backlog to remove this ancient dependency. Timing TBD. Thanks!
