### ISSUE TITLE
In threads, MessageActions appears when no actions are available

### ISSUE THREAD

**Issue by MelodyCheng99** [GetStream/stream-chat-react#1376]
When no actions are available for a message, and I hover over this message, I'd like the 3 dots to **not** appear, as clicking on these 3 dots doesn't do anything. This appears to only be an issue in threads.

In a thread:
<img width="388" alt="Screen Shot 2022-02-16 at 4 42 40 PM" src="https://user-images.githubusercontent.com/31972980/154382026-31178ac7-b8f7-4020-a799-30912a105d65.png">

Clicking on the 3 dots doesn't do anything (because all actions have been disabled).

**Comment by jmckenney** [comment]
upvote.

**Comment by zacheryconverse** [comment]
Thanks for this report. We will look into this and get back to you soon. Feel free to fill us in with any updates in the meantime.

**Comment by zacheryconverse** [comment]
We've made [updates ](https://github.com/GetStream/stream-chat-react/pull/1380) to fix this issue. The patch will be in our next release. Thanks again for this report 🙏

**Comment by MartinCupela** [comment]
Fixed by #1380
