### ISSUE TITLE
Rollup externals are not being added to peerDependencies

### ISSUE THREAD

**Issue by jchild3rs** [GetStream/stream-chat-react#138]
I use react-dropzone outside of StreamChat. However, StreamChat sneaks in a version of react-dropzone that is old. This is causing me a lot of problems. It seems I have to downgrade to whatever StreamChat uses. Hard to know what version to use when it is not even included as a dep in your package.json.

**Comment by jchild3rs** [comment]
Found it as a dependency to `react-file-utils`. Now time to revert all my nice hook based code to render props because of this. Fun!

**Comment by jchild3rs** [comment]
For anyone running into this, a (not so great) workaround would be to use npm aliasing:
`"my-react-dropzone": "npm:react-dropzone@^10.2.1",`

**Comment by tbarbugli** [comment]
@jchild3rs thank you for reporting this!
