### ISSUE TITLE
problem whit modules

### ISSUE THREAD

**Issue by Darkyxz** [GetStream/stream-chat-react#1386]
Compiled with problems:X

ERROR in ./node_modules/stream-chat-react/dist/assets/str-chat__connection-error.svg

Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at getHashDigest (I:\chat\client\node_modules\loader-utils\lib\getHashDigest.js:46:34)
    at I:\chat\client\node_modules\loader-utils\lib\interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (I:\chat\client\node_modules\loader-utils\lib\interpolateName.js:110:8)
    at Object.loader (I:\chat\client\node_modules\file-loader\dist\index.js:29:48)

WARNING in ./node_modules/stream-chat-react/dist/css/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/stream-chat-react/dist/css/index.css) 
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'I:\chat\client\node_modules\stream-chat-react\dist\css\index.css.map' file: Error: ENOENT: no such file or directory, open 'I:\chat\client\node_modules\stream-chat-react\dist\css\index.css.map'
 @ ./node_modules/stream-chat-react/dist/css/index.css 8:6-241 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-211 83:0-211 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ./src/App.jsx 11:0-46
 @ ./src/index.js 6:0-24 8:38-41

WARNING in src\components\TeamMessage.jsx
  Line 5:13:  'handleOpenThread' is assigned a value but never used  no-unused-vars

src\components\UserList.jsx
  Line 75:8:  React Hook useEffect has missing dependencies: 'client' and 'loading'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/stream-chat-react/dist/assets/str-chat__connection-error.svg
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at getHashDigest (I:\chat\client\node_modules\loader-utils\lib\getHashDigest.js:46:34)
    at I:\chat\client\node_modules\loader-utils\lib\interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (I:\chat\client\node_modules\loader-utils\lib\interpolateName.js:110:8)
    at Object.loader (I:\chat\client\node_modules\file-loader\dist\index.js:29:48)
 @ ./node_modules/stream-chat-react/dist/components/ChatDown/ChatDown.js 3:0-70 19:18-29
 @ ./node_modules/stream-chat-react/dist/components/index.js 11:0-36 11:0-36
 @ ./node_modules/stream-chat-react/dist/index.js 1:0-29 1:0-29
 @ ./src/App.jsx 8:0-41 43:35-39
 @ ./src/index.js 6:0-24 8:38-41

webpack 5.69.1 compiled with 1 error and 2 warnings in 19249 ms

i dont know what happen

**Comment by petyosi** [comment]
Hey, 

It looks like you're [facing this issue](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported). It's not specific to our library from what I see, so I'm going to close this.
