### ISSUE TITLE
`DefaultAttachmentType` does not match the type of `Attachment`

### ISSUE THREAD

**Issue by bryanjswift** [GetStream/stream-chat-react#1387]
Released in `stream-chat` 5.6.0 was a change to the type of `Attachment`, see https://github.com/GetStream/stream-chat-js/commit/e911e020f0c6c20d57b17fab6db14ac6165caf3f#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aR1436, that added `file_size` with a type of `string | undefined | number`.

This type can not be reconciled with the `DefaultAttachmentType` in https://github.com/GetStream/stream-chat-react/blob/57472bed12197b26eb96f2b6b989838f113999e6/src/types/types.ts#L14

Until these types match custom message implementations will fail to build with TypeScript.

Refs https://github.com/GetStream/stream-chat-js/pull/893

**Comment by MartinCupela** [comment]
The custom generics for attachment type can be overridden as so:

```ts
type LocalAttachmentType = { x: 'y' } & Record<string, unknown>;
```
