### ISSUE TITLE
Make it easier to append additional autocomplete triggers while keeping the default ones

### ISSUE THREAD

**Issue by calvinwyoung** [GetStream/stream-chat-react#1403]
In order to customize `autocompleteTriggers`, the Stream docs advise us to implement a custom `TriggerProvider`:
https://getstream.io/chat/docs/sdk/react/custom-code-examples/suggestion_list/

Implementing a custom `TriggerProvider` requires, at a minimum, supporting the `/`, `:`, and `@` triggers, whose implementations are provided by `useCommandTrigger`, `useEmojiTrigger`, and `useUserTrigger`.

Unfortunately those hooks are *not* currently exported publicly:
https://github.com/GetStream/stream-chat-react/blob/develop/src/components/MessageInput/hooks/index.ts

As a result, we're forced to copy/paste the implementation of those triggers into our own codebase. We'd prefer to simply import the hooks directly from `stream-chat-react`.

Is there a reason to keep those hooks private to this package? If not, can you please export them? I'd happily open a PR if this is okay with your team.

Thank you!

**Comment by calvinwyoung** [comment]
I went ahead and opened #1406 to address this issue. Thank you for your consideration!

**Comment by ambaldwin** [comment]
Hi @calvinwyoung I believe you're thinking that after creating a custom `TriggerProvider`, [you'd then pass it in as a prop into `Channel`](https://getstream.io/chat/docs/sdk/react/customization/input_ui/#custom-triggers)? Just want to make sure you've seen that documentation page, too. Also, if you're implementing a custom trigger provider, you have the option to remove or add triggers as you wish. At a minimum, you don't necessarily have to use the 3 default triggers.

And, thanks for submitting that PR. I'm not sure of the history of not exposing those hooks, though I know that has come up before in the context of a custom trigger provider, I'm just not sure of the outcome. We will take a look and will update this issue accordingly.

**Comment by calvinwyoung** [comment]
@ambaldwin Yes, I'm thinking about creating a custom `TriggerProvider` that I'd then pass into a `Channel`.

The implementation of `DefaultTriggerProvider` involves initializing a `TriggerSettings` object that maps a string character to one of the trigger hooks:
https://github.com/GetStream/stream-chat-react/blob/0651fe693ef8752bf5453b05d7fb9e033cf17d01/src/components/MessageInput/DefaultTriggerProvider.tsx#L77-L87

`TriggerSettings` is implemented as a union type that requires the `/`, `:`, and `@` triggers to be defined:
https://github.com/GetStream/stream-chat-react/blob/0651fe693ef8752bf5453b05d7fb9e033cf17d01/src/components/MessageInput/DefaultTriggerProvider.tsx#L56-L67

Omitting one of the default triggers results in a type error:
![image](https://user-images.githubusercontent.com/1173768/156271403-721eb5de-9614-449b-a4e2-d00cf2669e07.png)

I don't see how we can implement a custom `TriggerProvider` *without* defining the 3 default triggers.

Please let me know if your team is aware of another workaround. Otherwise I suspect that exporting these hooks will make life simpler for anyone else who's trying to implement a custom `TriggerProvider`.

**Comment by ambaldwin** [comment]
Hi @calvinwyoung thanks for those details. I don't know of a workaround; I wrote the above without looking at that type. At one point the intention was that be more flexible for customization of the defaults. We can look at that too. Thanks!

**Comment by petyosi** [comment]
@calvinwyoung thanks for opening this. The use case you have is valid, but I am conservative over the proposed solution. It increases our public API surface and can prevent us from refactoring the component in the future. It's also a "chatty" API - those hooks make sense only within the context of extending the existing trigger provider and have no other use.

I will close your PR for now and we will discuss a more robust solution with the team.

**Comment by calvinwyoung** [comment]
@petyosi Thanks for the quick response. Yes this makes sense — I certainly wouldn't to increase your public API surface by too much.

But as a compromise, what if we *only* exported the hooks that are strictly required for implementing custom trigger providers? This includes:

- `useCommandTrigger`
- `useEmojiTrigger`
- `useUserTrigger`

Does that keep the public API surface sufficiently manageable? We're stuck in a difficult situation because we *need* a custom `TriggerProvider` (as is recommended by your docs), but by copying the implementation into our codebase, we risk something breaking if your team updates some of the underlying trigger behavior.

Thanks again for your consideration!

**Comment by petyosi** [comment]
Of course. But we rarely change that part of the code. I would say that you can copy those for now and replace them as soon as we implement the solution.

**Comment by calvinwyoung** [comment]
@petyosi Okay we'll do that for now. Thank you!
