### ISSUE TITLE
When can `ChatContext`'s `activeChannel` value be `null`?

### ISSUE THREAD

**Issue by tomvalorsa** [GetStream/stream-chat-react#1410]
Hi, I'm trying to display some basic UI when the connected user has zero available channels, e.g. "You have no chats, create one". The use case here is to show a prompt for new users who haven't created any channels yet.

I'm wondering if I can use the `Channel` component's `EmptyPlaceholder` as a mechanism for this. However, I'm not sure if I can safely assume that `activeChannel` having a value of `null` will always mean that a user has no channels.

Is there a legitimate scenario where the `ChatContext`'s `activeChannel` value is `null`? Or does this just occur when there are no channels available to the currently connected user? Thanks

**Comment by zacheryconverse** [comment]
Hello @tomvalorsa and thanks for submitting an issue to our Github repository. A more reliable check for channels may be by using your `queryChannels` `filter` - [Docs](https://getstream.io/chat/docs/javascript/query_channels/?language=javascript). If your permissions are set to only allow read access to channel members, a filter starting point may be: 
`const filter = { type: 'messaging', members: { $in: ['tomvalorsa'] } }; `

FYI - `setActiveChannelOnMount` defaults to true, and sets the most recent channel received from the query as active on component mount, so the value of `activeChannel` will depend on your implementation. 

We’re glad you’re getting your hands on the product. The Issue section of this Github repo is now reserved only for bug reports, feature improvements, and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at [support@getstream.io](mailto:support@getstream.io) with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed. In case our understanding is incorrect and you are describing a bug, we apologize and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.
