### ISSUE TITLE
Start of a new thread badge

### ISSUE THREAD

**Issue by arnautov-anton** [GetStream/stream-chat-react#1424]
Hide “Start of a new thread” once the first reply landed in the thread.

![image.png](https://images.zenhubusercontent.com/621f96cdc790c77df1453e5b/7821e664-fef6-4f36-8a61-bdb0226e735b)

**Comment by alexlopezit** [comment]
@arnautov-anton you could do that with a custom component and pass it to the `Channel` as prop

```
import React from 'react'
import { useChannelStateContext } from 'stream-chat-react'

export const ThreadStart = () => {
    const { thread } = useChannelStateContext()

    if (thread?.reply_count && thread?.reply_count !== 0) {
        return null
    }

    return <div>Start of a new thread</div>
}
```

The use it like

```
<Channel ThreadStart={ThreadStart}>
```

**Comment by MartinCupela** [comment]
With the release of v10.0.0 the "Start of new thread" badge was removed
