### ISSUE TITLE
Fix build warnings

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-react#1432]
**Motivation**
Running the usual build results in a bunch of warnings, most likely related to our umd bundles. 

**Acceptance Criteria**
Build should pass with no warnings.

**Comment by ivanrosvimi** [comment]
I don't know if it happens to you but when compiling with Vite I get the following warning since the beginning of time when compiling stream-chat-react styles
![image](https://user-images.githubusercontent.com/101631558/189291806-6b1e39ef-0f4f-4e23-93ee-065a5a8d88c8.png)

**Comment by ivanrosvimi** [comment]
Any update?

**Comment by petyosi** [comment]
@ivanrosvimi this is not a known problem. The task in question is related to the build warnings themselves. Can you reproduce this somewhere? We have a few vite test cases, but none of them causes that.

**Comment by petyosi** [comment]
Isn't this solving your problem? https://github.com/vitejs/vite/discussions/5079

**Comment by petyosi** [comment]
@ivanrosvimi I tested the setup in [this stackblitz](https://stackblitz.com/edit/vitejs-vite-dgx6zx?file=package.json,src%2FApp.tsx,tsconfig.json&terminal=dev). I can't see any warnings in the terminal there. What am I missing?

**Comment by ivanrosvimi** [comment]
Yes, you are right. I have been testing your StackBlitz and seeing what could happen with our code as it is quite similar. 
Investigating in the Vite issues and looking at their changelogs it is something that they fixed from 2.9.2 by hoisting to the chatset of the styles: https://github.com/vitejs/vite/blob/v2.9.15/packages/vite/CHANGELOG.md#292-2022-04-13.

Thank you very much for your time and sorry for not having seen it on our own.

**Comment by MartinCupela** [comment]
The warnings have been fixed
