### ISSUE TITLE
Have default reaction emojis match between iOS/Android and Web sdks. 

### ISSUE THREAD

**Issue by jmckenney** [GetStream/stream-chat-react#1437]
**Motivation**
Clarity in communication between consumers/applications.

**Proposed solution**
Change the web sdk options to better match iOS/Android or vice versa. 

**Acceptance Criteria**
GIVEN I click reactions to choose for a message
WHEN I am in either iOS/Android/Web
THEN I see the same number of emojis and they match as close as possible

GIVEN I click reactions to choose
WHEN I am on WEB
THEN I do not see the angry emoji since that is not on the iOS/Android list of reactions

👎  on iOS is 😢  on web
❗❓ on iOS is 😮  on web
😠 on web is not seen on iOS/Android

**Comment by jmckenney** [comment]
When attempting to follow instructions here: https://getstream.io/chat/docs/sdk/react/custom-code-examples/reactions/
I'm finding it very difficult to get objects that end up showing the emojis that I want that also match correctly to iOS and show the correct numbers relative to those already chosen via iOS.

**Comment by zacheryconverse** [comment]
Hi @jmckenney,

Thanks for your feature request. We'll discuss this and get back to you soon.
