### ISSUE TITLE
Vulnerability in dependent package

### ISSUE THREAD

**Issue by bhdryrdm** [GetStream/stream-chat-react#1441]
**Motivation**
An XSS vulnerability has been discovered in a dependent package. I hope you fix it quickly.

**Proposed solution**
Please follow the instructions in this solution.
https://security.snyk.io/vuln/SNYK-JS-BRAINTREESANITIZEURL-2339882

**Comment by zacheryconverse** [comment]
Thanks for the report! We will look into this and get back to you soon.

**Comment by bhdryrdm** [comment]
Any update on this? @petyosi @zacheryconverse

**Comment by petyosi** [comment]
@bhdryrdm we have not gotten to this yet.

**Comment by bhdryrdm** [comment]
Hi @petyosi @zacheryconverse,

https://github.com/GetStream/stream-chat-react/commit/f541b27fa9d8855a279b87611aee2476571d24d6

This issue has been fixed by the depandabot. You can close.
