### ISSUE TITLE
Narrow gifs break the Giphy logo

### ISSUE THREAD

**Issue by santhoshvai** [GetStream/stream-chat-react#1445]
Refer to the screenshot below taken from the typescript example app,

![Screenshot 2022-03-11 at 09 57 48](https://user-images.githubusercontent.com/3846977/157839493-732f3825-1967-4992-9656-0f63ce40af4a.png)

This is mostly due to the recent giphy size customisability. Relevant changes: https://github.com/GetStream/stream-chat-react/pull/1374 https://github.com/GetStream/stream-chat-react/pull/1440

**Comment by ambaldwin** [comment]
Hi @santhoshvai thanks for submitting for for including related PRs. We have an issue in our backlog to look into this. Thanks!

**Comment by MartinCupela** [comment]
Outdated
