### ISSUE TITLE
Package huge size and dynamic imports

### ISSUE THREAD

**Issue by ivanrosvimi** [GetStream/stream-chat-react#1455]
**Motivation**
We are trying to find a way to import the generic CSS from `stream-chat-react` into our application without having to import the entire `index.scss`. Also the compilation is importing us emoji or mml vendor libraries, which makes the weight of the packages much higher. 

Something similar happens with the library itself, because even if we import the components separately at the end the whole library is compiled (more than 1Mb in size).

We are aware that we can import the styles for each component we use separately, but wouldn't it be better to have them imported dynamically into each React component?

**Proposed solution**
Dynamically export each component or stylesheet when needed, on demand.

**Acceptance Criteria**
- Package compiled size to be less than 1Mb.

**Comment by petyosi** [comment]
Hey @ivanrosvimi, 

Thank you for your feedback. the bundle size is indeed large and this is something that we would like to tackle in the long run. I would take your issue as a general rather than a concrete feature request as to do so might have to do some fundamental architectural changes.
