### ISSUE TITLE
Quoted message doesn't have the correct word-wrapping 

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-react#1457]
See attached screenshot. The quoted message doesn't have the right word-wrapping in composer or messageList

<img width="1301" alt="Screen Shot 2022-03-17 at 4 10 20 PM" src="https://user-images.githubusercontent.com/97132583/158908844-6df55a8c-6cf8-4509-a109-aea7ab778864.png">

**Comment by zacheryconverse** [comment]
Thanks so much for the report.

**Comment by MartinCupela** [comment]
Addressed in: https://github.com/GetStream/stream-chat-css/issues/67
