### ISSUE TITLE
refactor: Merge MessageInputSmall and MessageInputFlat into one component

### ISSUE THREAD

**Issue by MartinCupela** [GetStream/stream-chat-react#1462]
## Motivation

Maintenance of two separate components supporting the same interface requires double work to keep them in sync and opens door to the bugs.

## Proposal

Deprecate the `MessageInputSmall` and replace it by `MessageInputFlat` as a default input for both the main channel view as well as message thread view.

**Comment by arnautov-anton** [comment]
Added deprecation notice to MessageInputSmall, closing.
