### ISSUE TITLE
Support `flag-message` channel capability

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-react#1476]
**Motivation**
The UI should respect the server configuration when it comes to flagging messages. The capability is passed in `flag-message`.

**Proposed solution**
Take the flag into account in [the message actions logic](https://github.com/GetStream/stream-chat-react/blob/baaf2cbae7c2415d60451bfb05b98d4173bb5dda/src/components/Message/Message.tsx#L95-L108). 

Also, check if the rest of the `can`s don't need the same treatment. Consult [the capabilities table](https://getstream.io/chat/docs/react/channel_capabilities/?language=javascript&q=Capabil#channel-capabilities).

**Acceptance Criteria**
Disabling the flag from the server should prevent the flag message action from being displayed.

**Comment by MartinCupela** [comment]
resolved with #1807
