### ISSUE TITLE
chore: refactor classname construction with `classnames`

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-react#1477]
**Motivation**
We [have long walls of conditional class construction](https://github.com/GetStream/stream-chat-react/blob/baaf2cbae7c2415d60451bfb05b98d4173bb5dda/src/components/Message/MessageSimple.tsx#L98-L109).

**Proposed solution**
[classnames solves that](https://www.npmjs.com/package/classnames).

**Acceptance Criteria**
Have all className concatenations replaced with classnames.

**Comment by arnautov-anton** [comment]
Ongoing process but most has been rewritten using [`clsx`](https://github.com/lukeed/clsx), smaller/faster equivalent of `classnames`, closing.
