### ISSUE TITLE
How to set users?

### ISSUE THREAD

**Issue by ApurvaDani** [GetStream/stream-chat-react#148]
ror: {"code":43,"message":"JWTAuth error: signature is not valid. Make sure the token is created using the secret for API key \"xxxxxxxxxxxx"","StatusCode":401,"duration":""}

**Comment by tbarbugli** [comment]
During development you can disable auth checks from the Dashboard and use development tokens

```js
await client.setUser(
    {
        id: 'john',
        name: 'John Doe',
        image: 'https://getstream.io/random_svg/?name=John',
    },
   client.devToken('john'),
);
```

before going live you need to generate user tokens on your backend and use that instead dev tokens

Here's how you do it with Node

```js
const client = new StreamChat('', '{{ chat_api_secret }}');
const token = client.createToken('john');
```

More on this topic: https://getstream.io/chat/docs/init_and_users/?language=js

**Comment by itwaze** [comment]
@tbarbugli 
When i testing with example API KEY - all is good
But when i try to create a new user with my own API KEY - i see an error

```
{
"code":2,
"StatusCode":401,
"message":"WS failed with code 2 and reason - Connect failed with error: \"Chat is not enabled for organization with id 48174 and name itwaze\"",
"isWSFailure":false
}
```


```
const client = new StreamChat("qk4nn7rpcn75"); // cyxdn88hbvbx - my own API KEY, created for testing

client.setUser(
  {
    id: "john",
    name: "John Doe",
    image: "https://getstream.io/random_svg/?name=John",
  },
  client.devToken("john")
);
```
