### ISSUE TITLE
Read receipts for all messages

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#1481]
**Motivation**
At the moment it seems the read receipts are only available for the user that has sent the message, for example:
- Channel has 3 users, A, B, and C
- User A sends a message
- All users have seen the message
- Only user A can see the message status showing who has seen the message.

We would like to know if this is a limitation or is it possible to show the message status to all users, so in the scenario above, users A, B and C can see who has read the message.

**Proposed solution**
Perhaps provide some configuration where we can either use the message status as is or show to all users.

**Comment by petyosi** [comment]
@alexlopezit I am moving this to the stream-chat-js repository. Strictly speaking, your question refers to Stream's platform capabilities, so our backend team is better equipped to help you. You can reach out to them through our support email.

**Comment by petyosi** [comment]
Issue moved to [GetStream/stream-chat-js #936](https://github.com/GetStream/stream-chat-js/issues/936) via [**ZenHub**](https://www.zenhub.com/)
