### ISSUE TITLE
chore: Upgrade react version to v18

### ISSUE THREAD

**Issue by MartinCupela** [GetStream/stream-chat-react#1489]
For reference:

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

**Comment by petyosi** [comment]
Note, we should still support v16 and v17.

**Comment by cenacrharsh** [comment]
I am unable to use stream-chat with the current version of React i.e v18, what should I do?

**Comment by petyosi** [comment]
@cenacrharsh we are working over this issue in https://github.com/GetStream/stream-chat-react/pull/1534. You can check if the problems you encounter are mentioned there. If you have discovered something additional, please share it with us. Thank you!

**Comment by MartinCupela** [comment]
resolved by #1595
