### ISSUE TITLE
Size of package

### ISSUE THREAD

**Issue by luq10** [GetStream/stream-chat-react#149]
This package is realy huge - 1.6mB. On bundlephobia - https://bundlephobia.com/result?p=stream-chat-react@0.7.13 - I see that:

24.6% of size is `emoji-mart`
15.2% of size is `moment`

Maybe, you can change this subpackages to something lightwight one, for example `dayjs` or `date-fns` instead `moment`, or maybe you can do something else to decrease size of package

**Comment by vishalnarkhede** [comment]
HEY @luq10 thanks for reporting this. We will look into it soon :)

**Comment by kovacsmarcellcodinglab** [comment]
Yes, please decrease the package size. What is the current status?

**Comment by tbarbugli** [comment]
the 0.9.0 release uses day.js instead of moment.js that's a ~20% reduction in bundle size. The next big win is to optimize emoji-mart

**Comment by bignoggins** [comment]
any update on this? Would love to see an option to asynchronously load the emoji-mart JSON file as well aka

**Comment by jaapbakker88** [comment]
@bignoggins it's in our backlog currently, we've taken some time to explore some options but no resolution yet.

**Comment by bignoggins** [comment]
Ok thanks

**Comment by amardeepranu** [comment]
Any prioritization here? Stream chat and emoji-mart take up around 29% of our total bundle size - it would be nice to get this down

**Comment by bignoggins** [comment]
Yeah hard to claim that Stream Chat is performant but have such a
needlessly large bundle. Bundle size is a huge factor in web performance.

**Comment by osdiab** [comment]
also this currently relies on a transitive dependency, version 0.2.0 of your library `react-file-icon`, which pinned the react version and therefore makes my bundle end up with two copies of react.  echoing the others, this is pretty egregious. will make some PRs to rectify the specific issue i noticed.

**Comment by JGrishey** [comment]
Hey guys, we're also feeling the size of this package in our project. Right now it's ~44% of our bundle size, which is tempting us to potentially create our own UI for this.

Any update on the status of bringing the size down would be awesome. Thanks for the great work!

**Comment by DanC5** [comment]
All here, we just merged our emoji-mart refactor to master and will make a release within the coming days.

Check out these PR notes for information on the change and bundle size decrease: https://github.com/GetStream/stream-chat-react/pull/530

Check out the last comment in this GH issue for some of the new customization features: https://github.com/GetStream/stream-chat-react/issues/522

The high points...

- reduced the size of the compressed emoji data JSON from ~597KB to ~183KB
- by default now only use emoji-mart's Nimble components from their dist/modern bundle
- provided ability to customize data set and UI components via Channel props
- injected `emojiConfig` object into `ChannelContext` to gain access to custom bits anywhere in your app

Let me know if you have any questions on this performance improvement, thanks for your patience here!

**Comment by DanC5** [comment]
Closing this issue as we addressed the moment and emoji-mart pieces, but of course let us know if we can help further, thanks!

PS - we're planning our next release for next Wednesday the 10th, which will include all the emoji-mart changes
