### ISSUE TITLE
#BUG <MessageList /> Component works, but not <VirtualizedMessageList />

### ISSUE THREAD

**Issue by CloudMunk** [GetStream/stream-chat-react#1504]
Having issues implementing VirtualizedMessageList component.

At the moment I am using the MessageList  component and it works fine, but when I try to switch it out with the VirtualizedMessageList  component nothing renders(no messages render).

As in the docs, it is a child of the Channel component and I get no errors in the console for either component.

        Parent with channel component: 
        <Channel
            EmptyStateIndicator={EmptyState}
            EmptyPlaceholder={OpenThreadMessage()}
            channel={channel}
            Message={(messageProps, i) => <TeamMessage key={i} {...messageProps} />}
        >
          <ChatContainer profile={profile} token={token} />
        </Channel>

     Child with <MessageList /> & <VirtualizedMessageList />:

       <GiphyContext.Provider value={{ giphyState, setGiphyState }}>
      <div style={{ width: "100%" }}>
        <Window>
          <div className="h-screen overflow-auto flex flex-col justify-between">
            <div className="sticky inset-x-0 top-0">
              <TeamChannelHeader />
            </div>
            <div className="mt-20">
              <VirtualizedMessageList
                stickToBottomScrollBehavior="auto"
                /* message={MessageSimple} */
                defaultItemHeight={60}
                additionalVirtuosoProps={{
                  increaseViewportBy: { top: 0, bottom: 200 },
                  itemSize: (el: any) => el.getBoundingClientRect().height
                }}
              />
              {/* <MessageList />
              <div ref={messagesEndRef} /> */}
            </div>
            {loaded ? (
              <div className="sticky inset-x-0 bottom-0">
                <ViewedProfileContext.Provider value={{ profile: otherProfile, paid }}>
                  <MessageInput
                    Input={CustomMessageInput}
                    overrideSubmitHandler={overrideSubmitHandler}
                  />
                </ViewedProfileContext.Provider>
              </div>
            ) : (
              <LoadingSpinner isLoading={true} />
            )}
          </div>
        </Window>
        <Thread />
      </div>
    </GiphyContext.Provider>

    
    I've tried moving them up and into the parent, works fine for MessageList but not for VirtualMessageList.

**Comment by petyosi** [comment]
@CloudMunk most likely, the problem is related to the custom styling of the nested elements in your structure. Can you replicate the problem by starting from this [working sandbox](https://codesandbox.io/s/high-throughput-stream-vml-forked-x15f66?file=/src/App.js)? I will re-open the ticket once we have more to work with. Thank you in advance!
