### ISSUE TITLE
MessageList component throws 'duplicated key' error when provided an array of messages

### ISSUE THREAD

**Issue by arquadrado** [GetStream/stream-chat-react#1510]
I'm using the `MessageList` component with the prop `messages` to which I pass an array of filtered messages but it always throws the 'duplicated key' warning in the console. I made sure that there are no repeated messages in the array that is passed but it always causes the error. If the `messages` prop is not passed everything works as expected. Any clue on what I might be missing?

Here's how I am using the component:

```
 <MessageList
        onlySenderCanEdit
        closeReactionSelectorOnClick
        formatDate={formatDate}
        hideDeletedMessages
        hideNewMessageSeparator
        Message={MyMessage}
        messageActions={[]}
        {...messageListProps}
      />
```

In which `messageListProps` is just an object which has the `messages` array or is otherwise empty.

EDIT:

I was digging deeper and it seems that when I pass the array `[{id: 'some-message-id', text: 'Some message'}]` as the `messages` prop when I check the prop `enrichedMessages` inside the library's `useMessageListElements` hook it always has an added element like `{
    "customType": "message.date",
    "date": "2022-04-11T16:07:04.444474Z",
    "id": "some-message-id"
}`. 

For some reason this custom type message is added with the same id as the first element of the passed `messages` array.

EDIT2: 

I believe the problem is [here](https://github.com/GetStream/stream-chat-react/blob/0a812b4e494ceae5505465bd856e66f5d3155918/src/components/MessageList/utils.ts#L95) because although this message should have been filtered [here](https://github.com/GetStream/stream-chat-react/blob/0a812b4e494ceae5505465bd856e66f5d3155918/src/components/MessageList/hooks/useMessageListElements.tsx#L79) it's ending up the in the final array.

**Comment by petyosi** [comment]
Thanks, this seems like a legit bug in our enrichMessages implementation. We will look into it.
