### ISSUE TITLE
bug: `keycodeSubmitKeys` has bugs when using "cmd + enter" as override

### ISSUE THREAD

**Issue by joshkaplan** [GetStream/stream-chat-react#1530]
**Describe the bug**

When `MessageInput`'s `keycodeSubmitKeys` is set to a modifier + enter, it gets into a weird state. after sending the first message, the modifier by itself sends messages until enter is hit by itself.

**To Reproduce**

1. Use a `MessageInput` component
2. Set `keycodeSbumitKeys` to `[[91, 13]]` (on a mac)
3. Send a message (type something, hit cmd/ctrl + enter)
4. Type out another message
5. Hit the modifer (cmd) by itself -- the message sends
6. This^ behavior continues until enter is pressed again by itself

Interestingly, i **cannot** reproduce this exact behavior with ctrl (``[[17,13]]``). It seems to have something to do specifically with cmd + enter. Something about cmd + enter seems to make the enter key "stuck", and you have to press enter again in order to release it. 

**Expected behavior**
* cmd + enter sends the message
* cmd by itself does not

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: mac os
- Browser: chrome 
- Version: latest

**Comment by joshkaplan** [comment]
Okay I found the root cause (I think): the `keyup` event does not fire for a key while cmd is pressed. This is apparently known behavior on Macs.

I can think of 2 ways to fix this:
1. Don't require a keyup event to be fired for non-modifer key. (perhaps make this an edge case just for when cmd is pressed)
2. Don't use `keyup` at all, and instead implement modifers using `e.metaKey`, `e.shiftKey` etc. (This seems easier to me, but it would be a breaking change, since you wouldn't be able to support arbitrary key codes.)

**Comment by joshkaplan** [comment]
In the meantime, I think the immediate solution for me is to just register my own event handlers and use them to fire `sendMessage` ? (Let me know if this is a bad idea or if you have better ideas!)

**Comment by petyosi** [comment]
Hey @joshkaplan - thanks for reaching out and for the research you've shared. The scenario you illustrate is a valid one - we should look into supporting it reliably. I agree that we should use modifiers rather than relying on `keyUp`. 

Registering your own event handlers should work fine. In the meantime, we will try to get to that issue as soon as possible (I can't give an ETA yet).

I apologize for the inconvenience,
