### ISSUE TITLE
Allow quote reply on a message which is already a quote reply

### ISSUE THREAD

**Issue by vishalnarkhede** [GetStream/stream-chat-react#1535]
**Motivation**

Currently react chat SDK doesn't allow quote replying to a message which is already a quote reply to some previous message. There is no such behaviour on any other chat SDK. So to keep behavioural consistency, it should be allowed ideally.

**Proposed solution**

Drop the `!message.quoted_message` check for rendering of message actions. - https://github.com/GetStream/stream-chat-react/commit/8f4525bbb9541142c87f3b8c6af5faf2bf183a2d#diff-41b84369fa0c06695be04b04193a33e80cd02c64086165790fdbfacf07037339

**Comment by arnautov-anton** [comment]
Resolved in #1662.
