### ISSUE TITLE
An ability to show initials with two letters.

### ISSUE THREAD

**Issue by 1pinkmann** [GetStream/stream-chat-react#1536]
**Motivation**
Right now it is possible to show only one letter as initials. And this is strictly defined in Avatar.js component.

**Proposed solution**
**Change:**
`var initials = getWholeChar(nameStr, 0);`

**To:**
`var nameToArray = nameStr.split(' ')`
`var initials = nameToArray.length > 0 ? nameToArray[0][0] + nameToArray[1][0] : getWholeChar(nameStr, 0); `

**Acceptance Criteria**
Avatar should contain one **OR** two letters in initials.

**Comment by petyosi** [comment]
Hi @1pinkmann , 

The Avatar component is meant to be a simple, non-configurable default implementation, which should be overridden based on your requirements. You can override it by passing a custom component prop to [the channel component](https://getstream.io/chat/docs/sdk/react/core-components/channel/#avatar). You can also override the avatars in the channel list [from the respective prop](https://getstream.io/chat/docs/sdk/react/core-components/channel_list/#avatar).

Hope this helps, let me know if you need further assistance.
