### ISSUE TITLE
New messages

### ISSUE THREAD

**Issue by DobritoiuBogdan747** [GetStream/stream-chat-react#154]
Is it possible to show new messages DateSeparator and have a flag on each new message that is new? 

Example: I have a new message on a channel which i didn't open. When I open it I want to see the 'New messages' DateSeparator and those new messages to have a red background. (Similar to Slack's new messages separator + a flag for each message that is considered new)

**Comment by vishalnarkhede** [comment]
Hey @DobritoiuBogdan747 , it should be possible with some tweaks. I will try to setup some example app to check in next few days and get back to you :)
