### ISSUE TITLE
bug: defaultValue in MessageInput not getting rendered

### ISSUE THREAD

**Issue by tomSidebar** [GetStream/stream-chat-react#1541]
**Describe the bug**

Providing a defaultValue in the additionalTextareaProps of a MessageInput doesn't render in the UI.

**To Reproduce**

1. Create a MessageInput with additionalTextareaProps that contain some defaultValue
2. Observe that the rendered MessageInput doesn't display the defaultValue (although when inspecting the element I can see the defaultValue populated in the textArea element)

**Expected behavior**

I expect the defaultValue to be rendered on load, and that it can be altered within the MessageInput.

**Screenshots**

**Package version**
- stream-chat-react: 8.1.1
- stream-chat-css: 2.8.0

**Desktop (please complete the following information):**

- OS: MacOS 12.3.1
- Browser: Chrome
- Version 100.0.4896.127

**Comment by tomSidebar** [comment]
What I'm ultimately trying to accomplish is to save a draft of somebody's unsent message, so if they switch channels and come back to the original channel then their message draft is still there. If there's already an existing way of doing that then please let me know.

**Comment by MartinCupela** [comment]
@tomSidebar thank you for bringing this up. Your use case is valid. I would like to clarify one thing:

Do I understand it well, that you are not to implement the above described desired behavior, because the input is cleared on focus?

Thank you

**Comment by tomSidebar** [comment]
@MartinCupela The input is not populated at all with the defaultValue provided, no matter whether it's focused or not. When I inspect the element in Chrome I can see the defaultValue in the resulting textarea (looks like this: `<textarea data-testid="message-input" ...>MY_DEFAULT_VALUE</textarea>`), but it just doesn't show up in the UI.

I'm invoking the input via `<MessageInput additionalTextareaProps={{ placeholder, defaultValue }} />`, where placeholder and defaultValue are both const strings.

**Comment by MartinCupela** [comment]
@tomSidebar I have found the source of the problem. But I have a question regarding the acceptance criteria.

I understand the following:
1. You want a `defaultValue` string to be displayed on the first render of the `MessageInput` component

What should happen in the `MessageList` when:
a) user presses Enter without typing anything into the input (thus trying to submit the default value)
b) user erases part of the `defaultValue` string and presses Enter
c) user erases the whole `defaultValue` string and presses Enter

What should happen in the `MessageInput` when:
a) user presses Enter without typing anything into the input (thus trying to submit the default value)
b) user erases part of the `defaultValue` string and presses Enter
c) user erases the whole `defaultValue` string and presses Enter

If something else comes to your mind, regarding the behavior, could you please share your thoughts?

**Comment by tomSidebar** [comment]
@MartinCupela 

> What should happen in the MessageInput when:
a) user presses Enter without typing anything into the input (thus trying to submit the default value)
b) user erases part of the defaultValue string and presses Enter
c) user erases the whole defaultValue string and presses Enter

a) This should submit the defaultValue and clear the input.
b) This should submit the updated content and clear the input.
c) This shouldn't submit anything (unless there's also a file or other attachment), and the input remains cleared.

The only other behavior I can think of is that the user adds more content to the defaultValue which should follow b).

**Comment by tomSidebar** [comment]
Thank you!!
