### ISSUE TITLE
bug: editing a message with url adds a bogus attachment (image)

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-react#1546]
**Describe the bug**

editing a message with url adds a bogus attachment (image).

**To Reproduce**

1. start the examples/typescript app (not relevant, any vanilla setup works)
2. send `https://youtube.com/` message
3. edit the message. Change the protocol from `https` to `http`.
4. Submit
5. Two attachments appear - a plain image and an URL preview. 

**Expected behavior**

Only the URL attachment should remain.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/13347/165251927-2ba7cb00-38fe-4f62-a0be-6e96c646b669.png">

**Package version**
- stream-chat-react: 8.1.1
- stream-chat-css: 6.5.0

**Comment by arnautov-anton** [comment]
Fixed in #1598.
