### ISSUE TITLE
Improve display order of attached images.

### ISSUE THREAD

**Issue by YohaanYoon** [GetStream/stream-chat-react#1556]
**Motivation**
A clear and concise description of what the problem/opportunity is. Ex. I'm always frustrated when [...]
As shown following attached image, the display order of attached images in the red rectangle looks weired.
How about change the display order of attached images?

<img src='https://user-images.githubusercontent.com/74169602/165870970-64903d74-a11f-4076-9e58-ff19e53e302f.png'>

**Proposed solution**
I proposed as following:
As is
1 2
[] 3

To be
1 2
3 []

**Acceptance Criteria**
A set of predefined requirements that must be met to mark a user story complete.

**Comment by petyosi** [comment]
@MartinCupela - can you please check this? Not sure if we can't tweak that through some `display: grid` CSS.

**Comment by YohaanYoon** [comment]
Do you have any plan to fix this issue?
Please let me know when will fix it.

**Comment by petyosi** [comment]
Hey, 

the suggestion is in our backlog, but I am afraid we don't have an ETA for it yet.

**Comment by YohaanYoon** [comment]
I understand it. When you have a plan it, please let me know. Thanks.

**Comment by MartinCupela** [comment]
this issue has been solved with the release of theming v2 in v10.0.0
