### ISSUE TITLE
bug: virtualized thread styling is broken. 

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-react#1557]
**Describe the bug**

Looks like a flexbox gone wrong. 

**To Reproduce**

1. Go to [this sandbox](https://codesandbox.io/s/stream-chat-react-tutorial-forked-l3pzqp?file=/src/App.tsx)
2. Click on some of the threaded replies

**Screenshots**
<img width="542" alt="image" src="https://user-images.githubusercontent.com/13347/165917918-6d069e7a-0381-496c-88e0-601aa97e2960.png">

**Comment by arnautov-anton** [comment]
Fixed in the v10.0.0, closing.
