### ISSUE TITLE
There is an issue with the mute

### ISSUE THREAD

**Issue by kovacsmarcellcodinglab** [GetStream/stream-chat-react#157]
1. "notification.mutes_updated" successfully called when I mute the user, but "unmute" is not working,
    API not call this event. I use command to unmute user. 
    Is there any config for contextmenu to show "unmute" option?
2. How to hide messages from muted user, but other user need to get muted user messages in channel?

**Comment by kovacsmarcellcodinglab** [comment]
Solved other way

**Comment by Jarchisamira** [comment]
@kovacsmarcellcodinglab  How did you solve it?
