### ISSUE TITLE
feat: Marking messages as read does not correctly update the unread count in Preview

### ISSUE THREAD

**Issue by jpsierens88** [GetStream/stream-chat-react#1573]
**Describe the bug**

calling `mark_read(user_id, { message_id: message_id })` (ruby) in the BE marks the whole channel as read, even if there's other new messages that havent been read. reconnecting the chat shows the correct unread count

**To Reproduce**

- have a ChannelList component, with a Preview component that shows the unread count
- send a couple of messages to the channel, the unread counter should update
- in the BE, mark one of the messages as read

**Expected behavior**

The Preview should show the correct unread message count

**Screenshots**
sending new messages
![image](https://user-images.githubusercontent.com/64793862/167930948-31c647f4-5c1f-4b6d-8230-8ce398c97cbe.png)
marking 1 of the messages as read in the BE with `mark_read(user_id, { message_id: message_id })` will mark all the channel as read
![image](https://user-images.githubusercontent.com/64793862/167931489-0df2574d-a9c5-4b94-9f3d-482c50ed72e4.png)
reconnecting to chat will bring in the correct unread count
![image](https://user-images.githubusercontent.com/64793862/167931577-0c726548-fa44-4e5a-acb9-8ac06e519d52.png)

**Package version**
- stream-chat-react: 8.0.0
- stream-chat-css: n/a
- stream-chat-js: 6.5.1 (stream-chat)

**Comment by MartinCupela** [comment]
@jpsierens88 Thank you for reporting this problem. I was able to reproduce it and will fix it. At the moment I do not have ETA.

**Comment by MartinCupela** [comment]
@jpsierens88 as there are few customizations including the unread counter and red dot indicator, could you please add the following info:

1. where unread count is taken in you channel preview component?
2. what flag does your red dot use to be conditionally rendered?

Thank you

**Comment by jpsierens88** [comment]
hi @MartinCupela, our custom channel preview component just uses the `unread` prop which comes from stream-chat-reacts `ChannelPreview` ([source](https://github.com/GetStream/stream-chat-react/blob/HEAD/src/components/ChannelPreview/ChannelPreview.tsx#L144))

both unread count and flag use a `unread >= 1` condition to show

I think the main problem comes from the stream-chat-react `ChannelPreview`. [It's resetting the unread count](https://github.com/GetStream/stream-chat-react/blob/HEAD/src/components/ChannelPreview/ChannelPreview.tsx#L79) whenever a `notification.mark_read` event fires

**Comment by MartinCupela** [comment]
This issue is actually a new feature not yet supported by the SDK.

**Comment by MartinCupela** [comment]
Currently only a whole channel can be marked read. The issue describes possibility to mark read a specific message.
