### ISSUE TITLE
LoadMorePaginator not displayed

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#1574]
We are currently experimenting an issue where the `Load more` button is not being displayed when we use the `options.limit` to 30 which is the max number of channels we can query.

The code below will set the `hasNextPage` to false when the number of channels returned is less than the limit, but it seems the API is not consistently returning 30 which is causing this bug of the button not being loaded and users can't see more channels.

https://github.com/GetStream/stream-chat-react/blob/3376e4ca736c0ac722bf7f71a2345e59aedf0fe0/src/components/ChannelList/hooks/usePaginatedChannels.ts#L55

**Comment by petyosi** [comment]
Based on what you say, I would consider this a problem in our backend, as there's no real action in the React code. I will point our backend team towards that problem, but notice that we will likely have to investigate the details in your app instance - you can contact us through support@getstream.io for that.

**Comment by alexlopezit** [comment]
Thank @petyosi , email sent.
