### ISSUE TITLE
Update code examples and tutorial for theming-v2

### ISSUE THREAD

**Issue by szuperaz** [GetStream/stream-chat-react#1575]
**Motivation**
When themeing-v2 is implemented we should make sure our documentation is aligned with the changes

**Proposed solution**
- Update existing code examples in the docs that use theme variables (if any)
- Update tutorial: to use theme-v2
- Update screenshots in docs (if any)
- Update theming guide with examples and screenshots -> https://github.com/GetStream/stream-chat-css/blob/theming2/docs/theming/introduction.mdx

**Acceptance Criteria**
A set of predefined requirements that must be met to mark a user story complete.

**Comment by MartinCupela** [comment]
Accomplished with the release of v10.1.1
