### ISSUE TITLE
Add visual regression testing for sample app

### ISSUE THREAD

**Issue by szuperaz** [GetStream/stream-chat-react#1576]
**Motivation**
Setting up [visual regressions ](https://playwright.dev/docs/screenshots#element-screenshot)[through playwright](https://playwright.dev/docs/screenshots#element-screenshot) seems fairly easy. A new theme would be the right moment to introduce such testing. Visual tests could also help us making sure that we don't break the old theme.

**Proposed solution**
[A clear and concise description of what you want to happen.](https://www.notion.so/stream-wiki/Theming-2-0-b3f8f48514fe49c3997198e08874b5e4#868b88b952e941918596d52082ec94ff)
We could use regression for the current theme and for the new theme as well

**Acceptance Criteria**
A set of predefined requirements that must be met to mark a user story complete.

**Comment by oliverlaz** [comment]
Ongoing effort. We are closing this issue.
