### ISSUE TITLE
Apply theme-v2 to channel list and preview

### ISSUE THREAD

**Issue by szuperaz** [GetStream/stream-chat-react#1579]
**Motivation**
A clear and concise description of what the problem/opportunity is. Ex. I'm always frustrated when [...]

**Proposed solution**

**Acceptance Criteria**
- [ ] Layout
- [ ] Theme
- [ ] RTL support
- [ ] Component layer variable docs

Angular implementation: https://github.com/GetStream/stream-chat-angular/pull/292

**Comment by MartinCupela** [comment]
fixed by #1603
