### ISSUE TITLE
Apply theme-v2 to channel and channel header components

### ISSUE THREAD

**Issue by szuperaz** [GetStream/stream-chat-react#1581]
**Motivation**
A clear and concise description of what the problem/opportunity is. Ex. I'm always frustrated when [...]

**Proposed solution**

Screenshots: https://github.com/GetStream/stream-chat-css/pull/101

**Acceptance Criteria**
- [ ] Layout
- [ ] Theme
- [ ] RTL support
- [ ] Component layer variable docs
- [ ] Implement responsive layout for channel-list and channel in sample app

**Comment by MartinCupela** [comment]
closed by #1644
