### ISSUE TITLE
bug: Type 'DefaultStreamChatGenerics' is not assignable to type 'StreamChatGenerics'

### ISSUE THREAD

**Issue by lukasspettel** [GetStream/stream-chat-react#1592]
**Describe the bug**

I tried to use the newest stream-chat-react (8.1.3-beta.1-because of react 18) with the social-messenger-ts demo-app and I'm getting the following typescript error:

**Screenshots**

![grafik](https://user-images.githubusercontent.com/70133373/168662128-55c4e6ca-aca9-486d-8170-9db57c73058c.png)
...
![grafik](https://user-images.githubusercontent.com/70133373/168662230-89e02d40-9bc4-4d7d-ae1e-c6154f781baf.png)

Can someone help me with that error?

**Package version**
- stream-chat-react: 8.1.3-beta.1
- stream-chat-js: 6.5.1

**Comment by MartinCupela** [comment]
@lukasspettel thank you for bringing this up. The issue was resolved by #1595 .
