### ISSUE TITLE
bug: all the app examples are using StreamChat.getInstance() to initiate the client

### ISSUE THREAD

**Issue by MartinCupela** [GetStream/stream-chat-react#1616]
**Describe the bug**

Client initiation with `StreamChat.getInstance` method is not reliable and leads to multiple / no client instances in the application state. We have already updated the documentation demonstrating alternative approach, but everywhere else the old instantiation approach is used.

**Acceptance criteria**
All code snippets converted:

[ ] [API Tour](https://getstream.io/chat/get_started/)
[ ] [stream-chat-react/examples](https://github.com/GetStream/stream-chat-react/tree/develop/examples)
[ ] Watercooler
[ ] [website-react-examples](https://github.com/GetStream/website-react-examples)

**Comment by tplk** [comment]
Hi! Can you clarify why is it advised the other way around in the docs right now?

https://getstream.io/chat/docs/javascript/?language=javascript#chat-client

> Please also note here the usage of `StreamChat.getInstance()` available since `stream-chat-js@2.12.0`. This new Singleton pattern allows you to instantiate a unique `StreamChat` client, i.e create a `StreamChat` instance and retrieve it wherever you need it on your app to perform API calls. After calling it once, any following `getInstance()` call will return the initial `StreamChat` instance. This should prevent from accidentally creating multiple `StreamChat` instances.
> 
> This new Chat client version is backward compatible. That means users can continue using `new StreamChat()` if they use an older version of the library or for any other reason.
