### ISSUE TITLE
bug: jumpToMessage() causes <Message> components to mount and unmount twice every time

### ISSUE THREAD

**Issue by joshkaplan** [GetStream/stream-chat-react#1622]
**Describe the bug**

`jumpToMessage()` causes `<Message>` components to mount and unmount twice every time.

**To Reproduce**

1. Create a channel with 1 or more messages, and the ability to call `jumpToMessage()`
2. Call `jumpToMessage()`
3. See that the `<Message>` components all mount and unmount. 
```javascript
// put this inside <Message>
useEffect(() => {
  console.log(message.id);
}, [message.id]);
```

**Expected behavior**

When it actually loads new messages, I'd expect to see some new messages load. When the messages are already loaded (e.g. I've already clicked the button once, or there are <25 messages total in the channel), I'd expect to see the messages at _most_ re-render, definitely not a full un-mount and mount. (The above `console.log` would not fire.)

**Screenshots**

n/a

**Package version**
- stream-chat-react: 9.1
- stream-chat-css: n/a
- stream-chat-js: 6.3

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: Latest

**Additional context**

* Note that this behavior does **not** occur for `jumpToLatestMessage()`. (Although this function only works after `jumpToMessage()` has been clicked, which is perhaps another bug... if I scroll up, I'd like to be able to still use this function.)
* **Potential root cause**: I looked through the source code but couldn't pinpoint exactly why this is happening... in theory I would have thought that the `key` set in `useMessageListElements` would prevent this, I'm not sure why it's not.
* **Potential immediate cause**: I think this is triggered because this function is fetching new messages every time. Could potentially mitigate by simply not fetching new messages if it's not needed (e.g. the second time I trigger the function with the same input, it doesn't need to fetch new messages, it can just scroll.)
* This bug is particularly noticeable for me, since I am lazily loading some custom attachment info on Message mount... which is perhaps not the best design. Let me know if there's a better way to fetch the custom attachment data!

Thanks!

**Comment by MartinCupela** [comment]
@joshkaplan thank you for raisin the issue. What message list component do you use? Could you try to upgrade to v9.1.1. I believe the fix could help.

**Comment by joshkaplan** [comment]
Wow you guys are fast, beat me to it! 🎉
