### ISSUE TITLE
bug: window not found during NextJS compilation. happens in index.cjs.js

### ISSUE THREAD

**Issue by kdsbatra** [GetStream/stream-chat-react#1623]
**Describe the bug**

When using latest version with NextJS. it complains window not found during compilation. Happens on 9.1 and after

**To Reproduce**

1. `npm install stream-chat-react@latest`
2. Start NextJS server
3. Go to any page that loads/compiles stream-chat-react in your app
4. See error in browser and nextjs console (happens in dist/index.cjs.js around line 8770)

**Expected behavior**

There shouldn't be a error

**Screenshots**

**Package version**
- stream-chat-react: 9.1.0+
- stream-chat-css: ~
- stream-chat-js: 6.6.0

**Desktop (please complete the following information):**

- OS: [e.g. iOS]  MacOS
- Browser [e.g. chrome, safari]    Chrome
- Version [e.g. 22]     102.0.5005.61

**Additional context**

**Comment by MartinCupela** [comment]
@kdsbatra please upgrade to v9.1.2 which contains the fix. Thank you
