### ISSUE TITLE
bug: messageActionsHandler in Message should include messageActions as part of the dependency array

### ISSUE THREAD

**Issue by jpsierens88** [GetStream/stream-chat-react#1627]
**Describe the bug**

Currently, you have a [useCallback](https://github.com/GetStream/stream-chat-react/blob/HEAD/src/components/Message/Message.tsx#L95-L109) `messageActionsHandler` that handles the actions a user can make in a message, like `['delete', 'react']`. This useCallback has several dependencies, but its missing 1: `messageActions`. `messageActions` is the prop us users can pass through the `MessageList` to tell you what actions we want a user to have.

Currently, our `messageActions` is the result of a condition:
```
<MessageList messageActions={isMemberOfChannel && [MESSAGE_ACTIONS.edit, MESSAGE_ACTIONS.delete, MESSAGE_ACTIONS.react]} />
```

if the current user is a member of the channel, we allow some actions, if he's not, he cant do anything. 

What happens now is that when one of our users leaves the channel, he's still able to do the actions above, because your `messageActionsHandler` isnt being updated by a change in `messageActions`. Same thing the other way, when a user enters a chat, he cant take any defined action.

As a work around for now, I have this set up in our own custom message ui component:
```
const messageActionsHandler = useCallback(
    () =>
      getMessageActions(allowedActions, {
        canDelete,
        canEdit,
        canFlag,
        canMute,
        canPin: false,
        canQuote,
        canReact,
        canReply,
      }),
    [allowedActions, canDelete, canEdit, canFlag, canMute, canQuote, canReact, canReply]
  )
```
note that `allowedActions` is in the dependency array

**To Reproduce**

Add a `MessageList` component with a `messageActions` prop. Try conditionally passing actions to `messageActions`, the `messageActionsHandler` wont update itself because `messageActions` is not part of the dependencies

**Expected behavior**
`messageActionsHandler` should udpdate on changes of `messageActions` so that the UI can be properly updated

**Package version**
- stream-chat-react: 8.0.0
- stream-chat-css: n/a
- stream-chat-js: 6.5.1

**Comment by petyosi** [comment]
Thanks for the report - we will look into that.

**Comment by MartinCupela** [comment]
@jpsierens88 Could you please provide some more details regarding the following?

1. Do we understand well that you are trying to handle user permissions via `messageActions` enum?
2. Why have you decided to manage permissions via `messageActions` instead of interaction with the API?
3. How do you grant / remove user permissions on the API side?

Thank you

**Comment by jpsierens88** [comment]
1) We have our permissions set up through the stream dashboard. `messageActions` is being used as a way to let us show the actions if a user is in the channel, if hes not in the channel, we dont show the actions. 

2) It seemed like a good option to handle message actions UI for our case, [as per your API docs](https://getstream.io/chat/docs/sdk/react/core-components/message_list/#messageactions). In case we switch to only the API, how could we handle the real time effect of permissions on a user joining/leaving a channel? Is it possible to update a users permission to not be allowed to make message actions if he's not part of the channel, but able to view it?
Right now, `messageActions` works well for this because some user roles are able to see a channel without being a member of it, but they are not allowed to act on messages (like react) unless they join. so we can use a flag like `isMemberOfChannel` to conditionally set the allowed message actions through `messageActions`. However, this doesnt update on real time, when the user enters or leaves, hence why I created this bug.

3) we are using permissions v2 so we have access to the dashboard to grant/remove permissions
