### ISSUE TITLE
Message reactions consolidation

### ISSUE THREAD

**Issue by szuperaz** [GetStream/stream-chat-react#1637]
**Motivation**
The message reactions don't match on mobile and web SDKs
Details: Based on: https://getstream.slack.com/archives/C012FGW0XJS/p1655454447938709 

**Proposed solution**
Not yet

**Acceptance Criteria**
A set of predefined requirements that must be met to mark a user story complete.

**Comment by NiftyGift** [comment]
Current differences web/mobile differences:
- `sad:` reaction has a thumb down icon on mobile
- `angry:` reaction is missing on mobile

Suggested changes for web (see pic for details):
- replace sad emoji with a thumbs down
- remove the angry emoji
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/16894776/174268964-a7e64589-bf1d-4ba1-896b-f5d3818a3fd8.png">

**Comment by jmckenney** [comment]
Very thankful that you are considering tackling this.

**Comment by seanrossvida** [comment]
Great news! I believe the ideal implementation would be to allow for a set of custom icons and meanings to be used universally in the chat application, so as to allow clients to define their own branded reactions. It's easy to misinterpret the reactions without consistency or text equivalents for accessibility. "Thumbs down" is often construed as dislike, not sad. 

Thanks for your consideration and work in this area. Cheers!
