### ISSUE TITLE
bug: VirtualizedMessageList breaks "position: fixed" element inside the scroller

### ISSUE THREAD

**Issue by arzamax** [GetStream/stream-chat-react#1649]
**Describe the bug**

[react-virtuoso commit](https://github.com/petyosi/react-virtuoso/commit/c2a2919f0859f72ce03a2bfaf2102f26745d0422) added "will-change: transform" style property to the list scroller and created new stack context for inner elements ([MDN](https://developer.mozilla.org/ru/docs/Web/CSS/will-change)). Attachment gallery modal has "position: absolute" behavior and renders regarding the list now.

<img width="1227" src="https://user-images.githubusercontent.com/27233636/175923204-b4cf0223-3d32-4a92-8635-652e867e8a5c.png">

**Screenshots**

<img width="1227" src="https://user-images.githubusercontent.com/27233636/175923204-b4cf0223-3d32-4a92-8635-652e867e8a5c.png">

**Package version**
- stream-chat-react:

**Comment by petyosi** [comment]
@arzamax thanks for reporting that. The `will-change` combats a problem introduced in Chrome 102, but it indeed leads to the unintended consequences of the gallery not working as expected.

**Comment by petyosi** [comment]
@arzamax as a temporary measure, you can remove the will-change setting:
```tsx
<VirtualizedMessageList additionalVirtuosoProps={{ style: { willChange: 'unset' }, increaseViewportBy: { top: 400, bottom: 200 } }} />
```

Unfortunately, I am still unable to reproduce (and, potentially, find alternative cures) for this problem: https://github.com/petyosi/react-virtuoso/issues/675.
