### ISSUE TITLE
Integrate react-virtuoso autoscrollToBottom to handle image loading

### ISSUE THREAD

**Issue by petyosi** [GetStream/stream-chat-react#1650]
**Motivation**
In a timeline with loading images without a specified size, the virtualized message list does not account for the increased space, causing the list to stop "following" the conversation. 

We will solve that eventually with explicit image sizes coming from our backend. But for now, [I've exposed this method](https://github.com/petyosi/react-virtuoso/commit/6a6a7316a11cbc89c6a812665509d718e11c54ca) that allows the list to "catch up" on increased sizes.

**Acceptance Criteria**
A timeline with images without fixed sizes should load correctly at the bottom and should scroll to the bottom if a message with an image attachment is received.

**Comment by MartinCupela** [comment]
fixed with release[ v9.2.0](https://github.com/GetStream/stream-chat-react/compare/v9.1.5...v9.2.0)
