### ISSUE TITLE
bug: Edit Message Modal Background Flashes When Focus Changes

### ISSUE THREAD

**Issue by gimurpe** [GetStream/stream-chat-react#1653]
**Describe the bug**

Hello, I was wondering if you have any ideas on why this happens. Everytime you type something in the edit modal form, or more specific the focused element changes, the background flashes and you can see what it seems a box-shadow behind the modal window. I am not modifying the styles generated by stream chat by any means.

**To Reproduce**

1. Open a chat
2. Click on the three dots menu next to any of your own messages
3. Select 'Edit Message'
5. Click inside the text input , type something, click on the modal
6. Background flickers

**Expected behavior**

The background remains the same

**Screenshots**

![StreamChat](https://user-images.githubusercontent.com/7089148/176309221-da5e47f9-cb37-43d3-aea0-4fba3abf699b.gif)

**Package version**
    - stream-chat: "3.13.1",
    - stream-chat-react: "6.4.9",

**Desktop (please complete the following information):**

- OS: [iOS]
- Browser [chrome]
- Version [101.0.4951.64 ]

**Comment by petyosi** [comment]
@gimurpe I can confirm that this is a bug with the versions you have specified, which has been addressed in subsequent releases. You can upgrade to the latest versions of both `stream-chat` and `stream-chat-react`.
