### ISSUE TITLE
bug: Users reporting seeing connection issues error when no internet issues

### ISSUE THREAD

**Issue by jmckenney** [GetStream/stream-chat-react#1657]
**Describe the bug**

When testing we have seen a number of times when this shows up:

<img width="375" alt="Screen Shot 2022-06-30 at 8 22 29 AM" src="https://user-images.githubusercontent.com/3220205/176715380-967ddb74-1950-43c7-895e-2813bef62cf0.png">

- Internet connection does not appear to be an issue.
- Messages can still be sent while this is intermittently showing/blinking.
- speed tests show no issues / latency seems fine
- stream chat status shows no issue during these times

We've also had a number of our users report seeing this. Is the threshold for showing it too low? Is there something else that could be causing it to show?

**To Reproduce**

Steps to reproduce the behavior (this is not perfect, but will at least show how to get the error to show):
1. in chrome inspector, throttle network to 'offline'

**Expected behavior**

This message should only show if there is truly an issue with network.

N/A

**Package version**
- stream-chat-react:
```
"stream-chat-react@npm:^7.0.0":
  version: 7.0.0
  resolution: "stream-chat-react@npm:7.0.0"
```
- stream-chat-css:
- stream-chat-js:
```
"stream-chat@npm:^6.0.0":
  version: 6.3.0
  resolution: "stream-chat@npm:6.3.0"
```

**Desktop (please complete the following information):**

- OS: mac 12.4
- Browser: Chrome latest
- Version: multiple and `103.0.5060.53`

**Smartphone (please complete the following information):**
N/A

**Additional context**

N/A

**Comment by shodgetts** [comment]
Hello @jmckenney , thanks for getting in touch. This does not appear to be an issue with the React SDK and will be better handled with our support team. Can you please email support@getstream.io with your app_id and a link to this issue and we'll take it from there. 

Thanks!
