### ISSUE TITLE
bug: SuggestionList prop types are unused and outdated

### ISSUE THREAD

**Issue by rvanlaarhoven** [GetStream/stream-chat-react#1659]
**Describe the bug**

The [SuggestionItemProps](SuggestionItemProps) and [SuggestionListProps](https://github.com/GetStream/stream-chat-react/blob/39cedcb8d0821e4bb6e8061349ae52132aa32c45/src/components/ChatAutoComplete/ChatAutoComplete.tsx#L43) are both outdated and unused in their components. This makes it difficult to extend the functionality with our own implementation and ensure they still align on future releases.

The `SuggestionList` ([defined here](https://github.com/GetStream/stream-chat-react/blob/39cedcb8d0821e4bb6e8061349ae52132aa32c45/src/components/AutoCompleteTextarea/List.jsx)) does not use the `SuggestionListProps`. The props in this component also don't match that type completely. E.g. Several props like `currentTrigger` and `selectionEnd` are used in the component, but not defined in the type.

The `SuggestionItem` ([defined here](https://github.com/GetStream/stream-chat-react/blob/39cedcb8d0821e4bb6e8061349ae52132aa32c45/src/components/AutoCompleteTextarea/Item.jsx)) has the same problem.

**Expected behavior**

The types should match their components and be used in those components to the ensure stability in future releases and allow users to safely extend this functionality.

**Package version**

- stream-chat-react: 9.1.4

**Comment by petyosi** [comment]
Agreed, these are not perfect. The autocomplete textarea has not been migrated to typescript (it's, in fact, a fork of a semi-dormant project) - we've been looking into this for a while. 

In the meantime, I updated the types we export.
