### ISSUE TITLE
The editMessage inside the submit handler is missing the 'customMessageData'

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#1693]
https://github.com/GetStream/stream-chat-react/blob/bb7442cbf4bb709ac477fc59f0ee35afb60888d5/src/components/MessageInput/hooks/useSubmitHandler.ts#L152-L155

We know we could use the current provided Channel prop `doUpdateMessageRequest` but it would be easier if the `handleSubmit` called from `useMessageInputContext` supports `customMessageData` as it indicated in it's type definition.

The problem is that by using `doUpdateMessageRequest` is too complex to try and add any custom properties to the message while editing.

**Comment by alexlopezit** [comment]
Just to add a bit more context, we are currently using a custom `EditMessageForm` where we had to add a new custom context to handle custom message data, then when saving we would like to use the method `handleSubmit` directly.

**Comment by MartinCupela** [comment]
fixed by #1696

**Comment by MartinCupela** [comment]
@alexlopezit thank you for opening this request. I have created a PR to be reviewed. Please let us know, if anything else needed.

**Comment by alexlopezit** [comment]
Awesome news, thanks @MartinCupela

**Comment by alexlopezit** [comment]
This was released in 9.4.0
