### ISSUE TITLE
DefaultStreamChatGenerics is not exported

### ISSUE THREAD

**Issue by gajus** [GetStream/stream-chat-react#1704]
I am trying to type `ChannelList` `Preview` property.

```ts
import { type ComponentType } from 'react';
import { DefaultStreamChatGenerics } from 'stream-chat';
import { type ChannelPreviewUIComponentProps } from 'stream-chat-react';
import { isContraTipsChannel } from '../../utils/contraTips.js';
import { getPaidProjectIdFromChannelData } from '../../utils/getPaidProjectIdFromChannelData.js';
import { StreamContraTipsChannelCard } from './StreamContraTipsChannelCard.js';
import { StreamPaidProjectChannelCard } from './StreamPaidProjectChannelCard.js';

export const StreamChannelCard: ComponentType<
  ChannelPreviewUIComponentProps<DefaultStreamChatGenerics>
> = (props) => {
  const paidProjectId = getPaidProjectIdFromChannelData(props.channel?.data);
  if (paidProjectId) {
    return <StreamPaidProjectChannelCard {...props} />;
  } else if (isContraTipsChannel(props.channel.id)) {
    return <StreamContraTipsChannelCard {...props} />;
  } else {
    return null;
  }
};

```

However, in this example, `DefaultStreamChatGenerics` is not exported from `stream-chat` or from `stream-chat-react`.

Not clear how type this component without it.

**Comment by gajus** [comment]
In general, I am a bit confused about the types here.

It seems like we need to explicitly provide `DefaultStreamChatGenerics` to `ChannelList` as well, e.g.

```ts
<ChannelList<DefaultStreamChatGenerics>
  Preview={StreamChannelCard}
/>
```

**Comment by petyosi** [comment]
In general, you don't need to access the `DefaultStreamChatGenerics` explicitly - this is an internal interface. There are two possible scenarios - you want to customize the data types, in which case you should [use this approach](https://github.com/getstream/stream-chat-js#-getting-started). If you do so, you should, indeed, further specify the custom generic at the JSX level.

If you don't need that, you don't need to pass a generic - [like this](https://codesandbox.io/s/generics-usage-ivcbed?file=/src/App.tsx:1048-1176).
