### ISSUE TITLE
lightweight version of stream-chat-react

### ISSUE THREAD

**Issue by gajus** [GetStream/stream-chat-react#1705]
Has anyone implemented a lightweight version of [stream-chat-react](https://github.com/GetStream/stream-chat-react)?

`stream-chat-react` with all of its dependencies accounts for almost 4MB, which is 50%+ of our total vendor bundle.

We require pretty basic chat functionality and this appears a total overkill.

**Comment by petyosi** [comment]
To answer your question directly, we are not aware of such version. 

On our side, we are looking at moving a lot of the bulit-in dependencies into dynamic imports (or some sort of a tree-shakeable architecture), that would allow integrations who don't need the full feature set to strip it down as much as possible.

A similar conversation has been held in https://github.com/GetStream/stream-chat-react/issues/1455.
