### ISSUE TITLE
bug: Channel Filter isn't working for a newly received channel

### ISSUE THREAD

**Issue by vinaygregoryjohn183** [GetStream/stream-chat-react#1710]
**Describe the bug**

I have set the filter:
const filters: ChannelFilters = {
        members: { $in: [`${userId}`] },
        $or: [
          { channelType: { $exists: false } },
          { channelType: ChannelType.WHATSAPP }
        ],
        isHidden: false
 };
When the channel list loads initially, the channels are filtered as expected. But when a new message is received that channel which isn't satisfying the filter condition (it's channel type is Instagram) also appears in the list. This isn't expected as we are filtering only Whatsapp channels.
But upon refreshing the list the filter works fine and this channel (Instagram channel) isn't appearing (as per the expectation).

**Expected behavior**

The filter should work at all times not only when the Channel List is rendered the first time.

**Package version**
- stream-chat-react: 8.0.0

**Comment by luisgereda** [comment]
Hi,

Thank you for reaching out.

We have reserved GH issues for bug reports on the UI SDKs. 
This issue seems to be a wrong filtering issue. 

To give you support please contact support@getstream.io detailing your App ID and we will take it from there.

Regards,
Luis
