### ISSUE TITLE
Provide the ability to show unread counts filtered at team level

### ISSUE THREAD

**Issue by kyleosborn** [GetStream/stream-chat-react#1712]
**Motivation**

Currently, unread counts are at a user level. Since the introduction of multi tenancy/teams, we can't seem to find a way to show how many unread messages you have for channels in a 'team' without filtering, querying, paging and manually counting unread props at a channel level.

In our use case, we have one user who is a member of multiple teams. We filter the channel list by team, which is determined by what area of the platform they are on. The unread counts that come back are therefore misleading in this instance as they reflect that of other teams outside of the users current context.

**Proposed solution**

1. Introduce a method to get unread channel and message counts, that accepts a team id as a parameter.
2. Provide the ability to 'watch' unread counts filtered to a team level to ensure the socket events include the correct values.

**Comment by luisgereda** [comment]
Hi,

Thank you for reaching out.

We have reserved GH issues for bug reports on the UI SDKs.
Your question is related to the Chat API and has nothing to do with our React UI SDK.

To give you support please contact support@getstream.io detailing your App ID and we will take it from there.

Regards,
Luis
