### ISSUE TITLE
Make `emoji-mart` modular/optional

### ISSUE THREAD

**Issue by arnautov-anton** [GetStream/stream-chat-react#1715]
**Motivation**
Current implementation uses hardcoded `emoji-mart` features which makes it hard to upgrade and maintain and also unnecessarily increases SDK's package size.

**Proposed solution**
Remove from the SDK, make `emoji-mart` optional, introduce simpler API which could be used with different emoji pickers.

TODO:
- [x] remove from Reactions (ReactionSelector, ReactionsList) - #1947 
- [x] remove EmojiPicker component - #2117 
- [x] remove from MessageInput suggestion list

**Comment by marcojacobsNL** [comment]
Is there any update on this? Because we're trying to upgrade to React 18 and NPM is always throwing errors related to this specific emoji-mart version not being compatible.

**Comment by arnautov-anton** [comment]
Hey, @marcojacobsNL, we're currently working on resolving this issue. The plan is to release this fix by the end of this month if everything goes according to plan. We'll be releasing an alpha version with `emoji-mart` completely gone from the SDK sometime the week after next (16.10. - 20.10.). You should be able to move to React v18 without any major hiccups though, you might be greeted with warnigns but those should not affect the functionality of your application even with the current state of the SDK.

**Comment by arnautov-anton** [comment]
Hey, everyone! Last week on Friday we released [`11.0.0-rc.2`](https://github.com/GetStream/stream-chat-react/releases/tag/v11.0.0-rc.2) ([on NPM](https://www.npmjs.com/package/stream-chat-react/v/11.0.0-rc.2)) which now allows you to completely override (and remove) built-in `EmojiPicker` component and makes it slightly easier to implement your own `emojiSearchIndex` mechanism for our emoji autocomplete as it's no longer type-fixed to the one provided by the `emoji-mart`. We still need to decouple `emoji-mart` styling supplied with our CSS package to tackle issue #2116 - we'll be releasing that fix alongside with the update to our documentation in the RC3. We're still considering re-exporting some necessary `emoji-mart` parts for our default `EmojiPicker` component to make re-instating default behaviour slightly easier for our integrators, we'll be releasing that in RC4 for you to try out. I'll be updating this thread with new updates as we continue working on resolving this cluster of issues. We'll be grateful for any feedback/suggestions you'd have.

**Comment by arnautov-anton** [comment]
Another update for y'all - [`11.0.0-rc.3`](https://github.com/GetStream/stream-chat-react/releases/tag/v11.0.0-rc.3) ([on NPM](https://www.npmjs.com/package/stream-chat-react/v/11.0.0-rc.3)) has been released with the major change to the styling bundles. Our custom `emoji-mart` styling and `emoji-replacement` (used in combination with `Chat.useImageFlagEmojisOnWindows`) styling are now distributed separately from the main CSS bundle making final bundle of the integrators who do not use these features slightly smaller. Again, we'll be grateful for any feedback/suggestions you'd have.

**Comment by cuvant** [comment]
Hi @arnautov-anton I've upgraded to [11.0.0-rc.3](https://github.com/GetStream/stream-chat-react/releases/tag/v11.0.0-rc.3), and now the default emojis aren't showing anymore (theme V2). The "emoji-mart" package got updated to "^5.4.0", can't find any docs on how to get them back.

**Comment by arnautov-anton** [comment]
Hey, @cuvant, we've mentioned release guides in our [`11.0.0-rc.2`](https://github.com/GetStream/stream-chat-react/releases/tag/v11.0.0-rc.2) release which shipped with this change, here's the ["reinstate previous behavior" segment](https://github.com/GetStream/stream-chat-react/blob/e98cb6cfe08e0e040ff1945f9af274c904631a0f/docusaurus/docs/React/release-guides/emoji-picker-v11.mdx#L22-L41) in the release guide you're looking for. When installing release candidate versions make sure to install with `@rc` tag (`yarn add stream-chat-react@rc`) to get the latest version. Please follow the release notes across the RC releases - planned breaking changes are marked and come with transition guides. Once `v11` is out, make sure to switch to the `@latest` distribution channel so you can keep taking advantage of patches and new features.

**Comment by arnautov-anton** [comment]
Hey, everyone! We've officially released [`11.0.0`](https://github.com/GetStream/stream-chat-react/releases/tag/v11.0.0) on the `latest` distribution channel. Features/fixes mentioned in this thread (and released in on our `rc`) have not changed much (if at all) so if you started transitioning earlier the switch to `latest` should be as easy as running `yarn add stream-chat-react`. Closing this issue with this comment, feel free to submit new-found issues related to our latest release. 🙂
