### ISSUE TITLE
bug: the separateGiphyPreview flag among VirtualizedMessageList props has no effect

### ISSUE THREAD

**Issue by MartinCupela** [GetStream/stream-chat-react#1729]
**Describe the bug**

The giphy preview is always rendered outside the message list even though the value of `separateGiphyPreview` prop is set to `false`. The preview is always rendered inside the `<div>` element with class `giphy-preview-message` below the message notifications elements.

This is caused by the use of `processMessages` function inside the `VirtualizedMessageList`. This function always sets the giphy preview:
 
https://github.com/GetStream/stream-chat-react/blob/f23a3766e9b750f9c11e8bbd8bbfb5b9b8112a4a/src/components/MessageList/utils.ts#L76

**To Reproduce**

Toggle the value of `separateGiphyPreview` on `VirtualizedMessageList`.

**Expected behavior**

Probably render the preview inside the message list. Can this prop be deprecated as there are no complaints about the current behavior?

**Package version**
- stream-chat-react: 9.5.0

**Comment by lr-mjaouen** [comment]
Hello, is there any update on this?
Could you add a line in the doc too I spent some time wondering why it was not working?
Also it would be actually good to render the component where we want (just link it to a context so we could render it where we want).
Also I have an other bug, the GiphyPreview component does not show up directly (I need to send a second message to have it, it seems the event listening is not working properly?)

Thank you!
