### ISSUE TITLE
bug: Code doesn't compile when I import stream-chat-react

### ISSUE THREAD

**Issue by hawkesie** [GetStream/stream-chat-react#1734]
My code will not compile when I import stream-chat-react.
I ran 
npm install react react-dom stream-chat stream-chat-react

In my application I import as follows:

```
import React, { useEffect, useState } from 'react';
import { StreamChat } from 'stream-chat';
import { Chat, Channel, ChannelHeader, MessageInput, MessageInputSmall, VirtualizedMessageList, Window } from 'stream-chat-react';
```

And in the console I get the error 
Failed to compile.
```

./node_modules/html-to-react/node_modules/htmlparser2/lib/esm/index.js 67:9
Module parse failed: Unexpected token (67:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   return getFeed(parseDOM(feed, options));
| }
> export * as DomUtils from "domutils"; // Old name for DomHandler
|
| export { DomHandler as DefaultHandler };
```

If I remove the stream-chat-react import,
`import { Chat, Channel, ChannelHeader, MessageInput, MessageInputSmall, VirtualizedMessageList, Window } from 'stream-chat-react';`
, the application compiles fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/19408350/188698324-17fd1b59-4786-45de-86cf-1dc808180db4.png)
![image](https://user-images.githubusercontent.com/19408350/188698399-1dc5d63f-52da-431a-8326-564abe9cc603.png)

**Package version**
- stream-chat-react:
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**
Windows 11

I have tried running npm install and on different versions of stream-chat-react but haven't had any luck. Please help

**Comment by petyosi** [comment]
@hawkesie we are looking into fixing this, but it will require an un-entangling of several dependencies (which apparently have made questionable decisions with their versioning). The gist is that your project is likely using an older version of webpack. Here's a similar thread with a  few recommendations on how to work around it: https://github.com/GetStream/stream-chat-react/issues/1675.

**Comment by shindeajinkya** [comment]
@hawkesie @petyosi have you guys found any solution to this? facing same issue

**Comment by oliverlaz** [comment]
hi @shindeajinkya,

This third-party dependency of `stream-chat-react` uses modern syntax for their exports which isn't always supported by default on all bundlers.
Usually, these bundlers (webpack, rollup, etc...) might use Babel for transpiling the modern Javascript into browser-understandable Javascript flavor.

In this case, you need to enable/install: https://babeljs.io/docs/en/babel-plugin-proposal-export-namespace-from
Once this plugin is activated, the conflicting line would compile just fine.

**Comment by shindeajinkya** [comment]
This worked @oliverlaz, thanks
