### ISSUE TITLE
bug:load-more-channels

### ISSUE THREAD

**Issue by leticiafontoura** [GetStream/stream-chat-react#1735]
**Describe the bug**

Not sure if it's a bug.
I'm using the custom components provided by you for List and Preview on the Channel List component (MessagingChannelList.js and MessagingChannelPreview.js).
My channel list is scrollable.
However, when I click on the "load more" button, the scroll goes back up. Same happens if I've scrolled a bit and click on a channel preview, the scroll goes up again.
I think that the props that are passed to render the list/previews are not incremented but updated as a whole, so the whole component gets rebuild, something like that.

But I'd really like to know if there's any way I can prevent this from happening. In the "native" components for both List and Preview, this behavior doesn't happen.

**To Reproduce**

ChannelList component:

`<ChannelList
              filters={filters}
              sort={sort}
              options={options}
              List={(props) => (
                <MessagingChannelList
                  {...props}
                  onCreateChannel={() => setIsCreating(true)}
                />
              )}
              Preview={(props) => <MessagingChannelPreview {...props} {...{ setIsCreating }} />}
            />`

**Expected behavior**

**Screenshots**

**Package version**
- stream-chat: "^6.6.0",
- stream-chat-react: "^9.1.3"

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] chrome (any)

**Comment by petyosi** [comment]
@leticiafontoura I am not 100% certain about the origin of the files you refer to (MessagingChannelList.js), but I recall having such a problem in the past with one of our demos. 

However, we resolved that in the typescript version of the demo, at least. 

I suggest you contact us with further details at support@getstream.io - we will help you from there.
