### ISSUE TITLE
bug: Pinning a message changes the last updated message in Channel List Preview

### ISSUE THREAD

**Issue by chinesehemp** [GetStream/stream-chat-react#1736]
**Describe the bug**

When a user pin a message, this fires off a message update event. Which the channel list preview has event listeners listening to last message update. So this changes the last message preview in the channel preview list to the pinned message and not the last new message recieved.

[Offending file `src/components/ChannelPreview/ChannelPreview.tsx`](https://github.com/GetStream/stream-chat-react/blob/f23a3766e9b750f9c11e8bbd8bbfb5b9b8112a4a/src/components/ChannelPreview/ChannelPreview.tsx#L103)

**To Reproduce**

1. Go to 'any channel and find a message that is not the last message recieved.'
2. Click on 'click on pinned message'
3. See channel list preview to 'see the last message preview and time/date has been set to the pinned message instead of showing the last message received.'

**Expected behaviour**

The Channel list preview should show the last message received, not the last message updated.

**Screenshots**

**Package version**
- stream-chat-react: 9.5.0

**Comment by petyosi** [comment]
Thank you for the report, we will investigate this further.

**Comment by NwaforAugustine321** [comment]
@petyosi I want to work on this task. Please assign the task to me to work on it.

**Comment by MartinCupela** [comment]
The bug is not present in the SDK anymore.
