### ISSUE TITLE
bug:ChannelList duplicating channels in view

### ISSUE THREAD

**Issue by leticiafontoura** [GetStream/stream-chat-react#1755]
**Describe the bug**

_I'm using [this demo](https://github.com/GetStream/website-react-examples/tree/master/social-messenger-ts/src) as my foundation_

My Channel List component renders channels from 9 to 9 - so my "limit" is always 9 and my offset varies on each click on my "load more" button.

This works perfectly. Except when I have the following scenario:

- i have 9 channels rendered on screen
- i dont need to load more channels (i have more, i just dont need to talk to them at this moment)
- channel number 13 sends me a message: well, it wasn't rendered at first, but then if a new message is received, it gets to the top of my channel list, which is expected
- now i have 10 channels rendered on screen
- when i click the load more button, what happens is: the last rendered channel is duplicated when the other 9 channels are loaded. no idea why. really. 

**Expected behavior**

I thought it should not duplicate the last channel.

**Screenshots**

I'm not sure if I can provide the demo video for you, but if I do, I'll share it later.

stream-chat: "^6.6.0",
stream-chat-react: "^9.1.3"

**Desktop (please complete the following information):**

OS: [e.g. iOS] macOS
Browser [e.g. chrome, safari] chrome (any)

**Comment by arnautov-anton** [comment]
Hey, @leticiafontoura, thank you for submitting this issue and sorry for the prolonged delay - I added "confirmed" as I thought it would be beacuse of the filters missing `cid: $nin` rule but then I tested it and can't seem to be able to reproduce the issue. Do you think you could fork [this sandbox](https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv), try to recreate the behaviour and then share it with us? It would really help us speed up the process of fixing this. Thanks again!
