### ISSUE TITLE
bug: empty new line is ignored by markdown parser in Message text

### ISSUE THREAD

**Issue by MartinCupela** [GetStream/stream-chat-react#1756]
**Describe the bug**

Empty lines are ignored in the message text.

**To Reproduce**

1. In message input type text, then add 1+ empty lines with Shift + Enter, type more text
2. Send message
3. Observe the message text ignoring the empty lines

![image](https://user-images.githubusercontent.com/32706194/190629277-64c24099-9206-4854-91f8-09281489ebe4.png)

**Expected behavior**

Empty lines are kept:

![image](https://user-images.githubusercontent.com/32706194/190628892-98200cf8-d5c8-47f5-9b72-cedbbd29f407.png)

**Package version**
- stream-chat-react: 10.0.2

**Comment by arnautov-anton** [comment]
Blocked by https://github.com/GetStream/stream-chat-react/issues/1560.

**Comment by barrelmaker** [comment]
@MartinCupela Found a solution...don't think you're going to like it but it worked for me :) In the `MessageText` [component](https://github.com/GetStream/stream-chat-react/blob/master/src/components/Message/MessageText.tsx) you can add a step after the `messageTextToRender` and add this:

```tsx
messageTextToRender = messageTextToRender?.replaceAll("\n\n", "\n  ‎  \n").replaceAll("\n", "\n  \n")
```

Where the first `replaceAll("\n\n", "\n  ‎  \n")` has a unicode empty character "`U+200E`" between the two `\n`. If you copy that exactly it will unfortunately work. For some reason, this is the only solution I've found to work.

Here is the `MessageText` component with a little more context:

```tsx
const { t, userLanguage } = useTranslationContext("MessageText")
const message = propMessage || contextMessage
const hasAttachment = messageHasAttachments(message)

let messageTextToRender =
  message.i18n?.[`${userLanguage}_text` as `${TranslationLanguages}_text`] || message.text

messageTextToRender = messageTextToRender
  ?.replaceAll("\n\n", "\n  ‎  \n")
  .replaceAll("\n", "\n  \n")

const messageText = useMemo(
  () => renderText(messageTextToRender, message.mentioned_users),
  [message.mentioned_users, messageTextToRender]
)

const wrapperClass = customWrapperClass || "str-chat__message-text"
const innerClass =
  customInnerClass || `str-chat__message-text-inner str-chat__message-${theme}-text-inner`

if (!messageTextToRender && !message.quoted_message) return null
```

Don't ask me how or why this works, but if you're in a pinch it'll do the job.
