### ISSUE TITLE
Where is channels in the chatContext?

### ISSUE THREAD

**Issue by leogoesger** [GetStream/stream-chat-react#176]
In the doc it says channels are in the chatContext, but it seems like it isn't supported it. 

channel, client, and setActiveChannel are the only objects.

**Comment by vishalnarkhede** [comment]
Hey @leogoesger , thanks for bringing it up. It looks like a mistake in docs, we will update the docs.

**Comment by leogoesger** [comment]
@vishalnarkhede I could raise other issues, but `EmptyStateIndicator` is missing in ChannelList's prop types.

And if may, what is the strategy to add user to a chat when the user has not been created?

Use case:
We are migrating from Chatkit, so lots of current users have never called `setUser` yet. We need a way for us to initiate the convo with those un-initialized users, and does the initialization at the same time. 

In Chatkit, we did it on the server level, we send the error message to the server and have it create those users, and then create the channel. 

Is that still the correct approach here? Or there is something built in?

**Comment by thesyncim** [comment]
@leogoesger,
yes, users need to be created before added to a channel.

(I'm aware that pusher is working on an export tool that will make this process easier, but it's not ready yet)

for now, you can either use server-side auth or alternatively you could generate an [import file](https://getstream.io/chat/docs/import/?language=js&q=import).

Best,
Marcelo Pires

**Comment by leogoesger** [comment]
@thesyncim what doe server side auth mean? creating the user on server side once error? or using the `updateUsers` methods creating all the users beforehand?

**Comment by tbarbugli** [comment]
@leogoesger yes, you can use updateUsers to sync users in bulk from your backend (apologies for the misnomer, it actually does an upsert)

**Comment by leogoesger** [comment]
And current it seems like all the users can see all the channels, is this caused by the "upsert"?

**Comment by vishalnarkhede** [comment]
> Hey @leogoesger , thanks for bringing it up. It looks like a mistake in docs, we will update the docs.
@leogoesger we have updated the docs. Closing this for now ... If you have any more followup questions, please feel free to reopen.
