### ISSUE TITLE
bug: migration to React 18 leads to unmet peer dependency for emoji-mart

### ISSUE THREAD

**Issue by ArthurGoupil** [GetStream/stream-chat-react#1772]
**Describe the bug**

Migration to React 18 causes an unmet peer dependency for emoji-mart 3.0.1, which supports React 15/16/17 (latest version of emoji-mart is currently 5.2.2 and does support React 18)

**To Reproduce**

Update to latest React + stream-chat-react version and install dependencies.

**Screenshots**

<img width="696" alt="Capture d’écran 2022-09-21 à 11 14 40" src="https://user-images.githubusercontent.com/50388474/191465566-4f5ff3b6-c5ff-4ac6-b224-8b87d7fac220.png">

**Package version**
- stream-chat-react: 10.1.1

**Additional context**

Could be - temporarily - fixed by [this other open issue](https://github.com/GetStream/stream-chat-react/issues/1715) suggesting making `emoji-mart` optional.

**Comment by oliverlaz** [comment]
hi @ArthurGoupil, thanks for submitting this bug report.

This is a known issue to us. We plan to do some improvements in how emojis are handled across the whole SDK (#1715).
With that effort, we'll have this problem fixed too. I'll be closing this issue for now and you can track the other one.

**Comment by ArthurGoupil** [comment]
Alright thanks @oliverlaz !
