### ISSUE TITLE
bug: edit message form does not display video and audio attachments

### ISSUE THREAD

**Issue by MartinCupela** [GetStream/stream-chat-react#1782]
**Describe the bug**

Uploaded video and audio attachments are not displayed in `EditMessageForm`.

**To Reproduce**

1. Send a message with video / audio file attachment
2. Edit the message and observe that the edit form does not show the attachment

**Expected behavior**

Show attachments similar to uploaded images and other files.

**Screenshots**

[video_and_audio_attachment_hidden_in_edit_form.webm](https://user-images.githubusercontent.com/32706194/191615373-a6e97904-a9e5-4fa7-acfe-11865509a9b5.webm)

**Package version**
- stream-chat-react: 10.1.1
- stream-chat-css: 3.1.1

**Comment by Mandeepmunde** [comment]
@MartinCupela It seems that only input type='file' and images are displayed on **Edit Message** button. Video and audio attachments can displayed by adding audio and video type in `src/components/MessageInput/hooks/useMessageInputState.ts`. But, we need to check the impact on other places as well to display audio and video uploaded attachments.

![Screenshot 2022-11-15 at 2 44 38 PM](https://user-images.githubusercontent.com/47518932/201879226-ffc9eddc-db48-44e0-8d43-b1fd0b1fd463.png)

**Comment by MartinCupela** [comment]
fixed by v11.15.0
