### ISSUE TITLE
bug: Overlapping message author name

### ISSUE THREAD

**Issue by tkrevh** [GetStream/stream-chat-react#1788]
**Describe the bug**

stream-chat-react@5.4.0 release is the last one properly displaying the author names when there are a lot of messages posted from different chat users.

All later versions cause the overlap.

**To Reproduce**

3 users should join the chat.
1 user only observes, while the other two users post messages.
Soon you will observe that the author name will be overlapped/hidden behind the next message.

**Expected behavior**

It should properly display the name of the message author.

Post v5.4.0 (bug)
![image](https://user-images.githubusercontent.com/5480798/192575702-65b9b337-484e-4ac8-bbd7-6582388d0a4f.png)

v5.4.0 (still working properly):
![image](https://user-images.githubusercontent.com/5480798/192575796-6203e894-aee7-4e88-8d13-8775f9ef0c31.png)

**Package version**
- stream-chat-react: latest
- stream-chat-css: latest
- stream-chat-js: latest

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 105 (latest update)

**Additional context**

The problem is resolved if I include the cdn.jsdelivr.net/npm/stream-chat-react@5.4.0/dist/css/index.css instead of cdn.jsdelivr.net/npm/stream-chat-react/dist/css/index.css or any other release from 6.0.0. onwards.

**Comment by petyosi** [comment]
@tkrevh I can't seem to replicate the problem you describe with the current library version. Take a [look at this sandbox](https://codesandbox.io/s/third-user-with-long-message-list-t253my?file=/src/App.tsx) for what I've tried. Is there anything additional that needs to be taken into account?

**Comment by tkrevh** [comment]
@petyosi ahh, that's great that you've prepared such sandbox, this makes it so much easier to collaborate.
If you change the theme to "livestream light", the problem becomes immediately visible.
![image](https://user-images.githubusercontent.com/5480798/192739957-6e5ca9c6-1266-4368-a6b4-0de192575612.png)

**Comment by petyosi** [comment]
I see what you mean. With v10, the use-case-specific theming has been deprecated and will not be maintained moving forward - it's hard and inefficient on our side to keep those variations up-to-date as the API surface becomes huge. 

If you're actively developing your app, I recommend you consider moving to [theming v2](https://getstream.io/chat/docs/sdk/react/theming/themingv2/#using-theme-v2). If this, however, is not feasible for you at the moment, [this CSS override](https://codesandbox.io/s/third-user-with-long-message-list-t253my?file=/src/styles.css:102-192) fixes the problem in the setup.

**Comment by tkrevh** [comment]
Awesome, thank you!
We'll apply the CSS override for now, and look into theming v2.
