### ISSUE TITLE
Can't resolve 'i18next'

### ISSUE THREAD

**Issue by khanilov** [GetStream/stream-chat-react#179]
Going through [tutorial](https://getstream.io/chat/react-chat/tutorial/), I received following error in console:

> Failed to compile.
> 
> ./node_modules/stream-chat-react/dist/index.es.js
> Module not found: Can't resolve 'i18next' in '<path>/node_modules/stream-chat-react/dist'

I have `"stream-chat-react": "^0.10.0"`

Installing `i18next` package manually solves the issue. Also this issue can't be reproduced in `0.9.0`. Maybe you forgot to add `i18next` to `package.json` during last release?

If it was intendant, what should I do to avoid this issue?

Thanks in advance.

**Comment by vishalnarkhede** [comment]
Hey @khanilov , unfortunately that dependency was missing in package.json. We have it fixed it in `0.10.1`!
