### ISSUE TITLE
bug: Pining messages no longer persist to the channel backend

### ISSUE THREAD

**Issue by zencephalon** [GetStream/stream-chat-react#1809]
**Describe the bug**

When using `client.pinMessage` to pin messages they don't show up as pinned under either

`channel.getPinnedMessages`

or

`stream.channel('livestream', channel.id).query({})`

**To Reproduce**

Pin a message using `client.pinMessage`. Elsewhere try to fetch the pinned messages.

**Expected behavior**

Pinned messages should show up when queried.

**Package version**
- stream-chat-react:

10.2.0

- stream-chat-js:

7.1.0

**Desktop (please complete the following information):**

MacOS

Chrome

Chromium Engine Version 106.0.5249.103

**Additional context**

This was working before we updated so maybe https://github.com/GetStream/stream-chat-react/pull/1784 had something to do with this?

**Comment by arnautov-anton** [comment]
Hey, @zencephalon, this is a BE issue which is currently getting fixed. We expect the release of the fix in the upcoming days. I'll keep this open and close it once the fix is out. 👍

**Comment by zencephalon** [comment]
@arnautov-anton Sorry to bother! Any update on this? We have a launch deadline coming up in a few weeks so if this doesn't look like it'll get resolved I'll write my own backend to implement pinned messages.

**Comment by arnautov-anton** [comment]
Hey, @zencephalon, no bother at all, thank you for reminding! I talked to the BE team and the issue is still being worked on, @ferhatelmas will post an update once there's a progress.

**Comment by shrugs** [comment]
bumping for an update 🙏

**Comment by arnautov-anton** [comment]
Hey, @zencephalon, sorry for the prolonged delay - I see that you use `livestream` type of the channel - did you update user permissions for that scope in [the dashboard](https://dashboard.getstream.io/app/1183261/chat/rolespermissions/roles)? Check by selecting the scope `livestream` and then edit user role, see if the right column has "Pin message" grant.

I did test it myself and without it obviously does not work but after adding the grant - everything works as expected. There's one issue that we know of but that's related to truncating of the channel and shouldn't affect you in any way. If the issue still persists I'd ask you to fork [this sandbox](https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv) and replicate the issue for us so we can proceed with the investigation.

**Comment by zencephalon** [comment]
Yeah, we have the pin message grant enabled. If it looks like it works on your end, then I wager it does. I don’t have a motivation to test it anymore because we implemented our own pin message API using Redis due to the original issue not resolving in time for us to meet our deadline.
