### ISSUE TITLE
stream-chat-react 10.3.0 incorrect dependency resolution with stream-chat 8.0.0

### ISSUE THREAD

**Issue by chinesehemp** [GetStream/stream-chat-react#1813]
**Describe the bug**

I've upgraded  `stream-chat-react` to version 10.3.0 and also upgraded `stream-chat` to version 8.0.0, but when I try to deploy my app, I get npm dependency tree error.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: stream-chat@8.0.0
npm ERR! node_modules/stream-chat
npm ERR!   stream-chat@"^8.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer stream-chat@"^7.1.0" from stream-chat-react@10.3.0
npm ERR! node_modules/stream-chat-react
npm ERR!   stream-chat-react@"^10.3.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**To Reproduce**

Steps to reproduce the behaviour:
1. Install `stream-chat` version 8.0.0
2. Install `stream-chat-react` version 10.3.0
3. Run npm install
**Expected behavior**

No dependency tree error.

**Screenshots**

<img width="670" alt="Screenshot 2022-10-13 at 11 11 43" src="https://user-images.githubusercontent.com/58605231/195569662-66c63d91-8ce4-456e-8b84-a253e2da4b01.png">

**Package version**
- stream-chat-react: 10.3.0
- stream-chat: 8.0.0

**Comment by oliverlaz** [comment]
Hi @chinesehemp, `stream-chat-react@10.3.0` requires `stream-chat@^7.1.0`. From semver perspective, `stream-chat@8.0.0` doesn't fulfill the `stream-chat-react` requirements hence the error you see.

We'll soon release a new React SDK version compatible with the `stream-chat@^8.0.0`.
Until then, we suggest you downgrade to `stream-chat@7.2.0`.

**Comment by MartinCupela** [comment]
@chinesehemp new version 10.3.1 of stream-chat-react is available. You should be now able to install stream-chat@8.0.0 with it.

**Comment by chinesehemp** [comment]
Thank you.
