### ISSUE TITLE
bug: Special characters +/- not shown and ">" cannot be sent

### ISSUE THREAD

**Issue by dmitry-yudakov** [GetStream/stream-chat-react#1816]
**Describe the bug**

When trying to send a single character in the chat that is "+" or "-", it is successfully sent but is not visualised correctly with default Message UI.

If trying to send ">" character, then it would not be sent at all.

It works when these characters are part of longer string.

**To Reproduce**

1. Go to https://getstream.io/chat/demos/messaging/ or default Starter app
2. Type + or - and send
3. The typed character is not shown correctly in the sent message bubble.
4. Type > in the input and try to send
5. The message is not sent and the cursor in the input is moved at the beginning

**Expected behavior**

I would expect the characters +, -, > to be sent and shown without issues.

**Package version**
- stream-chat-react: 10.3.1
- stream-chat-css: 3.6.0
- stream-chat-js: 8.0.0

Same was with:
- stream-chat-react: 10.2.0
- stream-chat-css: 3.5.4
- stream-chat-js: 7.1.0

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: Version 106.0.5249.103 (Official Build) (x86_64)

I can open a separate issue for the ">" symbol if you like as it's a bit different problem.

**Comment by petyosi** [comment]
@dmitry-yudakov by default, the package parses messages as markdown. The symbols you have listed are considered bullet lists markers. If you're interested in disabling that behavior, you can turn off that by overriding the [`renderText` prop](https://getstream.io/chat/docs/sdk/react/core-components/message_list/#rendertext).
