### ISSUE TITLE
bug: The issue of MessageList height

### ISSUE THREAD

**Issue by YohaanYoon** [GetStream/stream-chat-react#1819]
**Describe the bug**

**To Reproduce**

1. Go to Channel List
2. Click on Channel
3. The height of the MesageList is increased by messages, and Message Input will not be shown.

**Expected behavior**

The height of the MesageList will be fixed, and Message Input will be shown.
It works normally in version 9.3.0.
However, when I applied the 10.2.0 of the stream-chat-react to the chat service, the height of the MesageList is increased by messages, and Message Input will not be shown. (It works normally in https://getstream.io/chat/demos/messaging/. I guess the version of the stream-chat-react is same with me.)

The code is as follows:

```
    return (
      <div>
        <S.AppBar />
        <Chat client={chatClient} theme="messaging light" i18nInstance={i18n}>
          <Channel channel={channel}>
            <Window>
              <MessageList
                messageActions={MESSAGE_ACTIONS_CLASSTALK}
              />
              <MessageInput
                doFileUploadRequest={doFileUploadRequest}
                doImageUploadRequest={doFileUploadRequest}
              />
            </Window>
            <Thread />
          </Channel>
        </Chat>
      </div>
    );
```

![chrome-capture-2022-9-14](https://user-images.githubusercontent.com/6019966/195793025-682a9733-2cc7-451a-a3f8-794cb5ac7286.gif)

Please let me know how to fix it.

**Package version**
- stream-chat-react: 10.2.0
- stream-chat-css: 3.6.0
- stream-chat-js: 7.1.0

**Desktop (please complete the following information):**

- OS: OSX
- Browser: chrome
- Version: 106

**Smartphone (please complete the following information):**

**Additional context**

**Comment by petyosi** [comment]
@YohaanYoon I am not sure what's the problem with the setup - can you replicate it [by forking this sandbox](https://codesandbox.io/s/interesting-maxwell-oojunq?file=/src/App.tsx:1099-1100)?

**Comment by YohaanYoon** [comment]
@petyosi 

I find the reason of the issue.
I have troubled when I run react script build, so, I am imported css from `import "stream-chat-react/dist/css/v2/index.css";` instead of `import "stream-chat-react/dist/css/index.css";`.
Do I use `import "stream-chat-react/dist/css/index.css";`?
You can see as following link: https://codesandbox.io/s/sweet-tree-2qk8wv

**Comment by petyosi** [comment]
@YohaanYoon the v2 theming mechanism leaves the layout to the integrator - you can check the additional styling that needs to be applied here: https://codesandbox.io/s/suspicious-architecture-q7lyr3?file=/src/styles.css

**Comment by YohaanYoon** [comment]
Thank you!
