### ISSUE TITLE
bug: Can't start after updating latest version

### ISSUE THREAD

**Issue by sonsosad** [GetStream/stream-chat-react#1829]
**Describe the bug**
- After I updated the latest version, I  encounter this issue and can't start the project

**To Reproduce**
- Update version from 9.5.2 to 10.3.1

**Package version**
- stream-chat-react:10.3.1
- stream-chat-css:^3.7.0
- stream-chat-js:7.1.0

**Additional context**
This is the error message: 
```
./node_modules/stream-chat-react/dist/css/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/stream-chat-react/dist/css/index.css)
ParserError: Syntax Error at line: 1, column 18
```

**Comment by arnautov-anton** [comment]
Hey, @sonsosad, could you please provide us more information about this issue? This is all surface-level and does not give us a lot to work with. What tools do you use to build your application (Next/Vite/CRA...)?

**Comment by sonsosad** [comment]
> 

I'm using React SDK. Please help me!

**Comment by arnautov-anton** [comment]
I'll suggest you to contact [support@getstream.io](mailto:support@getstream.io), our support engineers will assist you accordingly.
