### ISSUE TITLE
bug: MessageInput spreads props to React.Fragment. This is invalid

### ISSUE THREAD

**Issue by joelpierre** [GetStream/stream-chat-react#1830]
**Describe the bug**

If `dragAndDropWindow` is true, currently instead of using the `MessageInputProvider` you use `React.Fragment` you then spread `props` on to a fragment which is invalid. You get an error in your console.

**To Reproduce**

1. Set `dragAndDropWindow` to true on a Channel
2. Use MessageInput with any props.
3. Error is shown in console

**Expected behavior**

You should only spread props to the provider.

**Screenshots**
![199036368-4e48ed2e-35f0-483a-918d-a643ba4bd304](https://user-images.githubusercontent.com/8969851/199268526-1840571e-1666-4db4-b400-85432190197b.png)

**Package version**
- stream-chat-react: 10.1.1

**Comment by oliverlaz** [comment]
Hi @joelpierre, many thanks for reporting this issue.
We'll have a look at it and we'll get back to you once we have this problem fixed.

**Comment by joelpierre** [comment]
Amazing. Thanks @oliverlaz
