### ISSUE TITLE
Custom List in ChannelList, always scroll up when click channel

### ISSUE THREAD

**Issue by wisnuvb** [GetStream/stream-chat-react#1832]
I made a component for the `List` and when I click on a channel it always scrolls up. 

Here's my code snippet:

```
<ChannelList
    setActiveChannelOnMount={false}
    filters={{
        members: { $in: [chatClient.user.id || chatClient.userID || ''] },
    }}
    List={props => <MessagingChannelList {...props} />}
    Preview={props => <MessagingChannelPreview {...props} />}
    Paginator={props => <InfiniteScroll threshold={300} {...props} />}
/>
```

If in the `MessagingChannelList` I add CSS (using tailwind) `overflow-y: scroll` it will automatically scroll up when the channel is clicked. But if I don't add it, infinite scroll doesn't work. Here's the `MessagingChannelList` code screenshot:

<img width="809" alt="Screen Shot 2022-11-03 at 11 31 50" src="https://user-images.githubusercontent.com/3140168/199648145-f137f827-47d5-4444-a16b-c3fe1f61904e.png">

What should I fix? Thank you

**Comment by MartinCupela** [comment]
@wisnuvb there may be few reasons that lead to a container not to be scrollable. Could you please share a minimal reproduction with [codesandbox.io](https://codesandbox.io/), please?

**Comment by wisnuvb** [comment]
Thank you @MartinCupela for responding. Last night I found a solution to my problem. The problem is not in getStream, but in the custom component that I made.

Looks like we can close my question 🙏

**Comment by MartinCupela** [comment]
@wisnuvb thank you for the update. Would you mind to add your solution to your StackOverflow question in case somebody else would run into a same situation?
