### ISSUE TITLE
I'm trying to understand 

### ISSUE THREAD

**Issue by Arodlives** [GetStream/stream-chat-react#1846]
how getstream works with a user when you already have an oauth  provider .
would i be able to use the token already generated from the oauth for the client side authentication?
I'm not sure if im approaching it right .
but basically trying to use the 

await client.connectUser that has the data from the oauth provider in my database
-like if i already have existing users in my database *

I'm using nextjs with next auth,prisma,and planetscale .
 Thank you for taking your time to read this :)

**Comment by luisgereda** [comment]
Hi,

We have reserved the issues reports on GH for bug reports only.
Please send us your questions to support@getstream.io, and someone from our support team will be happy to help you.

Regards,
Luis
