### ISSUE TITLE
bug: ChannelList not always up to date

### ISSUE THREAD

**Issue by leticiafontoura** [GetStream/stream-chat-react#1853]
**Describe the bug**

I'm getting same issue [described here](https://github.com/GetStream/stream-chat-react-native/issues/145) but I'm with React SDK. 
A lot of my users have to refresh the chat page after some time so they can see new messages on top of the channel list. 

I saw it happening once (they're sharing screen with me so I could see it), but I can't reproduce it in our development environment.

"stream-chat": "^6.6.0",
"stream-chat-react": "^9.1.3"

**Comment by AndersDLund** [comment]
Hi,

We have reserved issue reports on GH for bug reports only.

Please fill out a support request here https://getstream.io/contact/support/, and someone from our support team will be happy to help you.
