### ISSUE TITLE
bug: dragAndDropWindow prop removes MessageInput props

### ISSUE THREAD

**Issue by joelpierre** [GetStream/stream-chat-react#1856]
**Describe the bug**

Setting the `dragAndDropWindow` prop on the Channel component  to true removes any props I pass to the message input

**Expected behavior**

I expect my props to be passed accordingly and not removed. Things like `overrideSubmitHandler` are extremely important.

**Package version**
- stream-chat-react: 10.4.1

**Additional context**

Not sure why the dropZone feature would remove every prop without documentation explaining why?

**Comment by petyosi** [comment]
Hi, 

the behavior you encounter is actually due to the dropzone needing access to those properties as well. To pass props to the message input while having `dragAndDropWindow` set to true, you can use the `optionalMessageInputProps` [prop like this](https://codesandbox.io/s/recursing-lederberg-nufp8g?file=/src/App.tsx:1345-1512).

**Comment by joelpierre** [comment]
@petyosi 

This doesn't work the moment I want to do anything more like using the channel action context for example as I am declaring this outside of the context. 

We have a situation in which I need to ensure messages are manipulated before sending to your servers previously the implementation used the sendMessage function from useChannelActionContext but obviously that won't work with this approach. 

How then can I override the submit handler to send a message in the way I wish? 

Also your docs should really explain the fact that this behaviour is wiped the moment one prop is changed.

**Comment by petyosi** [comment]
I agree that the behavior change should be described better. There's a [reference to that in the API reference](https://getstream.io/chat/docs/sdk/react/components/core-components/channel/#optionalmessageinputprops), but it's far from intuitive. 

Up to your next question, you can lift a reference to what you need from the context using a ref - [take a look at that approach](https://codesandbox.io/s/recursing-lederberg-nufp8g?file=/src/App.tsx:692-965).
