### ISSUE TITLE
bug: Unable to use custom sorting for MessageInput 

### ISSUE THREAD

**Issue by Zellotath** [GetStream/stream-chat-react#1862]
**Describe the bug**

`MessageInput` has a `mentionQueryParams` property that is not being handled correctly. Specifically, this property allows you to supply a `{ filters?: UserFilters, options?: UserOptions, sort?: UserSort }` value. Any value provided for `sort` will have issues:

1. If you provide a single value (e.g., `{ name: -1 }`), this gets combined with the default mention query ([here](https://github.com/GetStream/stream-chat-react/blob/develop/src/components/MessageInput/hooks/useUserTrigger.ts#L108)) to produce `{ id: 1, name: -1 }`.  This produces a warning from `normalizeQuerySort` ([here](https://github.com/GetStream/stream-chat-js/blob/3a5f6f65876fa6f53d404e8af23266d712b0d270/src/utils.ts#L112)) and may not actually produce the expected results.
2. If you provide an array of values (e.g., `[{ name: -1}, { last_active: 1 }]`), this gets combined incorrectly in the default mention query, producing a 400 error from the server and no results. `"StreamChat error code 4: QueryUsers failed with error: \"expected number for field \"sort[0].direction\" but got number '0'\""`
3. If you don't want to sort on `id`, you are out of luck.

**To Reproduce**

Steps to reproduce the behavior indicated as **point 1** above:
1. Use the `<MessageInput>` component and supply the following `mentionQueryParams` value:
```TypeScript
const customSort: UserSort = { name: 1 };
const customQuery = {
  sort: customSort,
};
// ...
<MessageInput mentionAllAppUsers mentionQueryParams={customQuery} />
```
2. Attempt to @mention a user in a channel using the above message input.
3. Check the console log to notice the warning about object field order.

Steps to reproduce the behavior indicated as **point 2** above:
1. Use the `<MessageInput>` component and supply the following `mentionQueryParams` value:
```TypeScript
const customSort: UserSort = [ { team: 1 }, { name: 1 } ];
const customQuery = {
  sort: customSort,
};
// ...
<MessageInput mentionAllAppUsers mentionQueryParams={customQuery} />
```
2. Attempt to @mention a user in a channel using the above message input.
3. Check the network tab to see that the query request failed with a 400 error, and no results are produced or shown by the component.

**Expected behavior**

If a `sort` value is provided, that value should be used instead of being incorrectly combined with the default `sort` value.
1. If I provide `{ name: 1 }`, results should come back only sorted by `name`.
2. If I provide `[{ team: 1 }, { name: 1 }]`, results should come back sorted by team, then by name.

**Screenshots**

N/A

**Package version**
- stream-chat-react: 9.5.0
- stream-chat-css: 2.11.0
- stream-chat-js: 7.0.0

**Desktop (please complete the following information):**

- OS: Mac OS 12.6.1
- Browser: Chrome
- Version: 108

**Additional context**

**Comment by MartinCupela** [comment]
@Zellotath thank you for reporting this. There is indeed incorrect merging of sort configuration objects taking place. Morover you are not able to override the `TriggerProvider` that wraps the `MessageInput` children. The fix we will provide will besides allow to provide a custom `TriggerProvider` besides fixing the merge.

**Comment by MartinCupela** [comment]
@Zellotath you can actually provide your own `TriggerProvider` component that should provide `autocompleteTriggers` to its children. You may want to change it, if you do not agree with having the `id` field always present. You can take inspiration from our [default provider component](https://github.com/GetStream/stream-chat-react/blob/develop/src/components/MessageInput/DefaultTriggerProvider.tsx).

**Comment by Zellotath** [comment]
@MartinCupela thanks for both the suggestion and for fixing the array merging issue!
