### ISSUE TITLE
bug: Dependency emoji-mart@3.0.1 has outdated peer dependency for React 18

### ISSUE THREAD

**Issue by jmagner** [GetStream/stream-chat-react#1866]
Peer dependency requirement for  React in emoji-mart@3.0.1 is "react": "^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0".

Unable to install  using React 18 .

**To Reproduce**

Install in a project using React 18.

**Expected behavior**

Expecting emoji-mart to support React 18

**Package version**
- stream-chat-react: 10.4.1
- stream-chat-css:
- stream-chat-js: 8.1.2

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jmagner** [comment]
I suppose this isn't an issue for Stream Chat React, and must be fixed by the emoji library.

**Comment by marcojacobsNL** [comment]
Is there any update on this? Because we're trying to upgrade to React 18 and NPM is always throwing errors related to this specific emoji-mart version not being compatible.
