### ISSUE TITLE
bug: update channels list

### ISSUE THREAD

**Issue by shivani805** [GetStream/stream-chat-react#1870]
i m facing issues on update ChannelsList by updating filter props state

we implemented search feature and want the search results should  apply on the channelsList itself , do not want popup or separately render in dropdown .

And to achieve this i m trying with filter props in channelList like i m changing the filter state(before and after search) but the chat channel is not rendering so it is the issue. 

or can you suggest other solution

**Package version**
- stream-chat-react: 9.5.2
- stream-chat: 7.1.0

**Comment by petyosi** [comment]
Hi @shivani805,

Thanks for contacting us and for choosing Stream! The issues section of this repository is preserved for bug reports only. To get help with your integration, contact us through our Help Center, so our support team can review your case:
https://getstream.io/contact/support/

Furthermore, it would be helpful if you can demonstrate the problem you're facing by creating a minimal reproduction by forking this sandbox: https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv.
