### ISSUE TITLE
Update to theme v2 breaks down the Chat layout

### ISSUE THREAD

**Issue by Ksuzi** [GetStream/stream-chat-react#1871]
Hello! 
My team and I use the get-stream to implement the chat with different channels. We decided to bump to the latest theme version, but there is an issue with the layout. To be clear - this issue can be fixed by a developer (just by adding a `grid` and `flex` display and parent container). But in the version below, we haven't faced such an issue with the layout. Everything already has worked out of the box, without some additional CSS code.
We wanna be sure, that it's a known issue or a new approach to the Chat layout, and my team and I will know what to do with the new Chat layout - fix it by ourselves, or wait for a new patch with a fix.

Attached are the screenshots that represent how Chat looks after migrating to the new theme v2.
Also added the code sample.

Thank you!

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/53110264/207025923-4a13364d-0bf1-4675-aa2b-8452416d11bd.png">
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/53110264/207026676-451232c7-dc3b-40d3-a376-3157b08f1929.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/53110264/207026068-a700213a-60a6-4e91-8118-0a6249649edc.png">

**Comment by arnautov-anton** [comment]
Hey, @Ksuzi! In the theming v2 we decided to leave the basic layouting to the integrators as the previous approach caused more troubles than necessary - you can read more about this in our [tutorial](https://getstream.io/chat/react-chat/tutorial/). Hope this helps, closing for now, let me know if you have any other questions.
