### ISSUE TITLE
bug: Stream chat cannot parse message with mentions with @ as last character

### ISSUE THREAD

**Issue by michalvankodev** [GetStream/stream-chat-react#1872]
**Describe the bug**

Stream chat is not able to parse a message correctly if it contains mentions and the last element in the message is `@`. `utils.tsx` throws an error which is not recoverable

**To Reproduce**

1. Simple stream-chat-react app implementation without custom elements used
2. Create a group chat.
3. Write a message mentioning someone from the group and leaving an alone `@` character at the end of the message. eg: "Hi @mentioned user, this will crash the app. @"
5. See error in `utils.tsx` [at line 200](https://github.com/GetStream/stream-chat-react/blob/develop/src/utils.tsx#L200) (currently as of version 10.4.1)
"
**Expected behavior**

Parser should be able to handle this kind of message.

**Package version**
- stream-chat-react: 10.4.1
- stream-chat-css:
- stream-chat-js: 7.2.0

**Desktop (please complete the following information):**

- OS: Fedora 37
- Browser Firefox
- Version 107.0

**Comment by arnautov-anton** [comment]
Hey, @michalvankodev, thank you for submitting this issue! I managed to reproduce it myself and the fix should be fairly easy so we should be able to release it later this week.
