### ISSUE TITLE
bug: no translation key for "Maximum number of files reached"

### ISSUE THREAD

**Issue by YohaanYoon** [GetStream/stream-chat-react#1876]
**Describe the bug**

No translation key for "Maximum number of files reached"

**To Reproduce**

1. Go to channel at mobile (iPhone)
2. Click on file input button to attached images
3. Select 11 images
4. See error with "Maximum number of files reached"

**Expected behavior**

The stream-chat-react will be provided translation key. 

**Screenshots**
![Screenshot_20221212_132836_Classting-stg](https://user-images.githubusercontent.com/6019966/207552274-21ac2217-9df4-4c12-9cca-b83e01522d1e.png)

**Package version**
- stream-chat-react: 10.4.1
- stream-chat-css: 3.6.0
- stream-chat-js: 7.2.0

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: iphone
- Browser safari

**Additional context**

**Comment by petyosi** [comment]
@YohaanYoon this string is not discoverable in the codebase, so I am not sure what's the reason for that. We have this translation here: https://github.com/GetStream/stream-chat-react/blob/eb444b0364cbc45813fc297812a6cb45e6167efd/src/i18n/en.json#L63 - is there any chance that you're using your own custom input? I will reopen the issue once we get more details on your side.

**Comment by YohaanYoon** [comment]
@petyosi 

I already added the translation as follows:

`  "You've reached the maximum number of files": "최대 첨부파일 초과하였습니다.",`

**Comment by petyosi** [comment]
@YohaanYoon the string from your screenshot is not present in the SDK codebase - so this might be due to something else, like a custom input. Can you reproduce the problem [in a codesandbox](https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv)? This will help us trace it down and assist you better.

**Comment by YohaanYoon** [comment]
@petyosi  You're right. I misunderstood QA engineer's reports. I am sorry for confusing.
