### ISSUE TITLE
question: overriding default chat reactions does not work as documented in official getstream guide

### ISSUE THREAD

**Issue by sumeetpareek** [GetStream/stream-chat-react#1880]
**Describe the bug**

On web client UI, overriding the default set of chat reactions does not work as documented in the [official getstream guide](https://getstream.io/chat/docs/sdk/react/guides/theming/reactions/#override-the-default-set). After much debugging I was able to figure out the correct steps to customize chat reactions, so this issue is fix the official documentation with those steps.

**To Reproduce**

1. Have a working local setup of stream chat.
2. Follow steps in the guide to override default chat reactions.

**Expected behavior**

Expected behavior is that chat now has your custom reactions and custom reaction icons.

**Screenshots**

TODO adding soon

**Package version**
- stream-chat-react: 10.4.1
- stream-chat-css: 3.7.0
- stream-chat-js: n/a

**Desktop (please complete the following information):**

**Additional context**

**Comment by petyosi** [comment]
@sumeetpareek - you've mentioned that you've discovered the necessary changes for the setup to work for you. Can you please share those? Thank you in advance!

**Comment by MartinCupela** [comment]
@sumeetpareek the documentation states, that `ReactionSelector` should be passed `reactionOptions` prop in order display custom reactions. That is still valid. If you are passing the a custom `ReactionSelector` component as a prop into the `Channel` component, then you have to wrap our `ReactionSelector` into a component as so:

```
const CustomReactionSelector = React.forwardRef(
  (
    props: ReactionSelectorProps<StreamChatGenerics>,
    ref: React.ForwardedRef<HTMLDivElement | null>,
  ) => {
    return <ReactionSelector {...props} reactionOptions={customReactions} ref={ref}/>;
  });
```

If you are building a custom `Message` component, then you do not have to do that. I do not believe this is a flaw of the documentation as the above pattern is already documented.
