### ISSUE TITLE
bug: Channel is not directly filtered out of the `ChannelList` when a member leaves the channel.

### ISSUE THREAD

**Issue by GuidovdRiet** [GetStream/stream-chat-react#1881]
**Describe the bug**

Channels are not directly filtered out of the `ChannelList` when a member leaves the channel.

**To Reproduce**

- Remove member from channel including a message (when there is no message added, the functionality works as expected)

```jsx
await channel.removeMembers([user_id], {
   text: 'User is removed from channel',
})
```

```jsx
<ChannelList
  filters={{
    type: channelType,
    members: { $in: [accountId] },
    last_message_at: { $gte: '2020-01-01T00:00:00.00Z' },
  }}
  sort={[{ last_message_at: -1 }]}
  options={{ watch: true, state: true }}
/>
```

**Expected behavior**

Filter out channel from `ChannelList` directly after the user leaves the channel. On refresh the filters actually work. You would expect that the channel is filtered out directly after you leave the channel. Since the user is not part of the channel anymore the filter `members: { $in: [accountId] },` should be applied.

**Screenshots**

**Package version**
- stream-chat-react: 10.4.1
- stream-chat-js: 8.1.3

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Google Chrome
- Version: 107.0.5304.121 (Official Build) (x86_64)

**Additional context**

**Comment by petyosi** [comment]
@GuidovdRiet this is one unfortunate limitation of the current platform implementation - the channel list does not automatically live handle most of the updates that can affect its context. It's a fairly complex implementation, that needs support on our backend. 

As a practical solution for the moment, we recommend handling the updates manually - [here's a guide in our docs that shows something similar](https://getstream.io/chat/docs/sdk/react/components/core-components/channel_list/#customizing-event-handlers).

**Comment by GuidovdRiet** [comment]
@petyosi Thank you for the suggestion. I will give it a try 👍

**Comment by GuidovdRiet** [comment]
Solved. For my specific use case, this is the solution:

```jsx
/**
 * Removes the channel from the ChannelList when a user leaves the channel
 * problem default event: when a user leaves -> the channel is not automatically removed from the ChannelList
 */
async function customOnChannelUpdated(
  setChannels: React.Dispatch<
    React.SetStateAction<Array<Channel<StreamChatGenerics>>>
  >,
  event: Event<StreamChatGenerics>
) {
  const channel = event.channel;

  // Filter out the deleted channel
  setChannels((channels) => {
    return channels.filter((c) => c.cid !== channel?.cid);
  });
}
```

```jsx
<ChannelList 
  onChannelUpdated={customOnChannelUpdated}
 />
```
