### ISSUE TITLE
bug: Message list loads all messages and goes scroll crazy

### ISSUE THREAD

**Issue by joelpierre** [GetStream/stream-chat-react#1883]
**Describe the bug**

As soon as I open a channel with a lot of messages in it, your `MessageList` component fetches ALL messages. Please see video below (for privacy I have not shown all the messages but just the scroll bar going crazy and my mouse static). I know you have the `VirtualisedMessageList` component however these do not marry with regards to props entirely especially with things like `formattedDate`. Is the advice just to use `VirtualisedMessageList` if you are expecting channels with a ton of messages?

**To Reproduce**

1. Have a lot of messages in a chat
2. Scroll up a little 

**Expected behavior**

It should smoothly scroll up as I assume there is still pagination happening in this component as you fetch a max of 100 at a time?

**Screenshots**

[If applicable, add screenshots to help explain your problem.](https://user-images.githubusercontent.com/8969851/208174147-de7a64e2-7755-4ef6-ba25-d672eda41715.mov)

**Package version**
- stream-chat-react: `10.4.1`
- stream-chat-js: `8.1.3`

**Desktop (please complete the following information):**

- OS: [e.g. iOS] : macOS Monterey 12.6.1
- Browser [e.g. chrome, safari] chrome 108

**Comment by petyosi** [comment]
@joelpierre this seems weird, certainly not an expected behavior. Can you replicate the problem by modifying the standard tutorial in [this sandbox](https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv)?

**Comment by joelpierre** [comment]
@petyosi - Just edited it, but cannot reproduce will investigate my end to see if there are any styles being overridden potentially causing this issue

**Comment by MartinCupela** [comment]
@joelpierre I was able to reproduce the behavior. I will not take a look at it and may come back to you with additional questions.

**Comment by MartinCupela** [comment]
@joelpierre can you please share the code snippet / sandbox, where we will be able to see, what props are you passing to `MessageList` component? This may be related to `scrolledUpThreshold` value.

**Comment by joelpierre** [comment]
Hey @MartinCupela, I scrolled a minute amount and the rest was just the component scroll jacking and going haywire. The only props we passed were `messageActions`  and `formatDate`. We were modifying some styles but I removed those and still got the error so not CSS related.

**Comment by MartinCupela** [comment]
@joelpierre do you observe this only on Chrome or any other browser?

**Comment by MartinCupela** [comment]
@joelpierre could you please provide a reproduction of your scenario in [this sandbox](https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv)? We would like to make sure, we have the best possible overview of all the intervening variables.

**Comment by joelpierre** [comment]
@MartinCupela hopefully this should do: https://codesandbox.io/s/crimson-hooks-h25fqd?file=/src/App.tsx as you can see one scroll up and it jumps very high up the message list and also loads many pages it shouldn't hit yet.
