### ISSUE TITLE
bug: is it support nextjs

### ISSUE THREAD

**Issue by AnujSsStw** [GetStream/stream-chat-react#1884]
**Describe the bug**
I was getting the error ```ReferenceError: getComputedStyle is not defined``` when I tired to copy and paste the example on the website for react.

**To Reproduce**

use it in nextjs

**Expected behavior**
nothing like ```ReferenceError: getComputedStyle is not defined``` should appear

**Screenshots**
I have to do this wired way to get it working
![Screenshot from 2022-12-17 22-03-12](https://user-images.githubusercontent.com/92370865/208252023-96a6973f-2acf-4c0f-a216-c77e0cdcdab1.png)

this is when directly copy pasting the code
![Screenshot from 2022-12-17 22-09-49](https://user-images.githubusercontent.com/92370865/208252134-297d1dc8-af3c-42f9-b43d-40c06981185b.png)

![Screenshot from 2022-12-17 22-10-02](https://user-images.githubusercontent.com/92370865/208252196-d2807519-611b-4ebc-b0b8-a7ac53c2b69a.png)

**Package version**
latest

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Brave, chrome

**Comment by petyosi** [comment]
@AnujSsStw can you try following the nextjs example [from here](https://github.com/GetStream/stream-chat-react/tree/develop/examples/nextjs)? Let us know if it does not work for you.
