### ISSUE TITLE
bug: Build css syntax error

### ISSUE THREAD

**Issue by Praful-cs** [GetStream/stream-chat-react#1886]
**Describe the bug**

In react getting this error from node modules.

```
Creating an optimized production build...
Failed to compile.

./node_modules/@stream-io/stream-chat-css/dist/css/index.css
ParserError: Syntax Error at line: 1, column 18
```

I have imported the CSS file in Component. I have tried both the css files but getting the same error
`@stream-io/stream-chat-css/dist/css/index.css`
`stream-chat-react/dist/css/index.css`

**To Reproduce**

Create react app with this package and functionally then create a build - 
1. npm run build

**Package version**
- stream-chat-react: 10.4.2

**Comment by MartinCupela** [comment]
@Praful-cs thank you for your report. We will be taking a look into this issue. Meanwhile, if you are just starting with the SDK, we would recommend you to use the latest stylesheet that you can import with `stream-chat-react/dist/css/v2/index.css`

**Comment by MartinCupela** [comment]
fixed by : https://github.com/GetStream/stream-chat-css/pull/212
