### ISSUE TITLE
feat: Add pluralization to image gallery '{{ imageCount }} more'

### ISSUE THREAD

**Issue by tedderple** [GetStream/stream-chat-react#1899]
**Motivation**
As a translator, we need to be able to pluralize properly into several languages that have different pluralization for 0, 1, 2, 3, 4 , 5+

https://lingohub.com/blog/2019/02/pluralization 

**Proposed solution**
The proposed solution is to handle it similarly to the replyCount for a minimum pluralization criteria

 "imageCount_one": "1 reply",
"imageCount_few": "{{ count }} replies",
"imageCount_many": "{{ count }} replies",
"imageCount_other": "{{ count }} replies"

**Acceptance Criteria**
Minimum Acceptance Criteria: Translation should account for singular and plural translation

Goal Acceptance Criteria: Be able to account for a wide variety of languages 
Code Sample from https://github.com/GetStream/stream-chat-react/blob/a641515e424c824680df4d051dc216ff16674381/src/i18n/ru.json

  "replyCount_few": "{{ count }} ответов",
  "replyCount_many": "{{ count }} ответов",
  "replyCount_one": "1 ответ",
  "replyCount_other": "{{ count }} ответов",
  "searchResultsCount_few": "{{ count }} результата",
  "searchResultsCount_many": "{{ count }} результатов",
  "searchResultsCount_one": "1 результат",
  "searchResultsCount_other": "{{ count }} результатов",

**Comment by MartinCupela** [comment]
Hello @tedderple, thank you for your request. What you are asking for is the change of meaning of the translation. The current implementation says how many more images are there, that are not immediately shown to a user. You are asking to change it into the (total?) number of images. Somebody else may have a different need. We may reconsider this request in the future, but not in the near term.

**Comment by tedderple** [comment]
@MartinCupela 

Hi,

Thank you for your reply. I'm not requesting the count to be the total number of images. We're requesting if we can have pluralization similar to how reply count is pluralized. 

Singular, few, many.

Different languages have different pluralization needs as outlined in the blog I've linked.

**Comment by MartinCupela** [comment]
@tedderple introducing the pluralization as you propose it would be a breaking change for other users of the component. And many may not be happy about that. We are not planning to introduce this breaking change in the near future. Feel free to open a PR, that will not break other users of the SDK and will meet your needs.

**Comment by tedderple** [comment]
Gotcha, thank you for looking into it.
