### ISSUE TITLE
Hide reactions in messages

### ISSUE THREAD

**Issue by aniciom** [GetStream/stream-chat-react#19]
One question, is there any way to hide the reactions in the list of messages displayed in a channel? 

Thanks

**Comment by tschellenbach** [comment]
Makes sense to me. Jaap what do you think?

**Comment by jaapbakker88** [comment]
Yeah makes sense to me as well. Would you just like to be able to deactivate reactions completely @aniciom?

**Comment by aniciom** [comment]
Yah would be nice, anyways it seems they don't show if i disable them from the dashboard, anyways would be a nice a feature as well as some kind of customizable internationalization for some parts of the components, example: Is Typing function ( user/s is/are typing), dates below the message, thanks for the effort and keep going the good work

**Comment by jaapbakker88** [comment]
@aniciom so that's a different thing right? I think the way to go for reactions is you disable them on the dashboard and then they won't show. Let me know if that's working. Could you open another issue for the internationalization and I will look for the best way to implement that.

**Comment by aniciom** [comment]
Sure, thanks
