### ISSUE TITLE
Add scss source files to package files

### ISSUE THREAD

**Issue by khanilov** [GetStream/stream-chat-react#190]
Hello,

I have a proposal how to enhance styles theming process.

Based on your answer on [How to customize styles?](https://github.com/GetStream/stream-chat-react/issues/29) thread.

> Hey @codekiln 
> 
> There are two ways to customize the styles:
> 
> 1. You can override the css classes (of stream-chat-react) in your project, and they will take precedence over the default classes. You can check this codepen example where I have changed the background color of chat screen and font-weight of text: https://codepen.io/vishtree/pen/rXNyep
> 
> 2. You can clone the repository on your end and manually edit the styles in repository. This is the way mentioned in readme file: https://github.com/GetStream/stream-chat-react#customizing-styles
>
> _Originally posted by @vishalnarkhede in https://github.com/GetStream/stream-chat-react/issues/29#issuecomment-512725815_

I see that each of this two approaches has unpleasant downside:

1. Extra css and possible future specificity issues.

2. Manual syncing stream-chat-react styles updates with local ones, via building source code and copying files.

My proposal is to add scss source files to npm package. It should drastically improve theming experience without downsides above.

As a reference: bootstrap have such [feature](https://getbootstrap.com/docs/4.4/getting-started/theming/) and it super convenient.

What do you think?

**Comment by vishalnarkhede** [comment]
Hey @khanilov ,

Thanks for bringing this up. We will look into it and get back to you on this one soon :)

**Comment by alexlopezit** [comment]
Would also love this, so we could also use any font we choose
