### ISSUE TITLE
bug: `notification.mark_read` resets all channels `unreadCount`

### ISSUE THREAD

**Issue by alessandroliveri** [GetStream/stream-chat-react#1903]
**Describe the bug**

When using 2 chats (channels) in the same app with 2 separated unread messages counters, it seems that when the SDK is calling `markRead` on one opened channel , we received a `message.read` event but also a `notification.mark_read` that contains `unread_channels: 0` even if the other channel was never opened and all counter are set to 0 because of [this code ] (https://github.com/GetStream/stream-chat-js/blob/b6d14aba0b64686ed719946c9c212bebf7157b01/src/client.ts#L1245) in the js lib.

if I understood how it should work the problem is in the event payload, that container a wrong `unread_channels: 0` field, so server side but maybe I'm wrong.

**To Reproduce**

1. Go to a page with 2 separated embedded channels and unread counters
2. Send a message to both chats you will seen unread counters updated to 1
3. Open 1 channel 
4. Both unread counter are set to 0 even if the other one still contains an unread message

**Expected behavior**

Only the concerned unread counter is updated

**Package version**
- stream-chat-react: 10.4.3
- stream-chat: 8.2.1

**Desktop (please complete the following information):**

- OS: MacOS 13.1
- Browser Chrome
- Version 108.0.5359.124

**Comment by MartinCupela** [comment]
Hey @alessandroliveri , thank you for filing the issue. I tried to reproduce it following the steps you described. I used the `examples/typescript` app to do that. However the result is that, only the active channel is marked read. The other is still displaying unread count. You can see it for yourself in the video below. Have you somehow customized listening to the mentioned events?

[mark-unread.webm](https://user-images.githubusercontent.com/32706194/213154082-6fbcbdce-a2e9-4152-869b-aa7730e2dc11.webm)

**Comment by MartinCupela** [comment]
Closing, now response received
