### ISSUE TITLE
Select multiple message and callback

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-react#1907]
**Motivation**
Hello,
Im using all your components. I wonder how can i implement following feature:
- select one, two or three message
- Have a global menu to make a batch actio 

**Proposed solution**
Best solution would be to have a prop to select message, and a callback to manage max number if selected message, and one to display a button

**Comment by arnautov-anton** [comment]
Hey, @Abacaxi-Nelson, you can achieve this by creating and utilising your own [custom message component](https://getstream.io/chat/docs/sdk/react/components/message-components/message_ui/), here's a [sandbox sample](https://codesandbox.io/s/custom-message-forked-j8f6uo) of how you'd achieve this. It uses RxJS for state management, but it's easy to swap for something like regular React context - the main concept is there. If you have any other questions regarding your integration, please direct your questions to [Stream support](https://getstream.io/contact/support/) as GH issues are reserved for bugs and feature requests.
