### ISSUE TITLE
question:setActiveChannelOnMount

### ISSUE THREAD

**Issue by leticiafontoura** [GetStream/stream-chat-react#1909]
**Describe the bug**

We've uploaded our sdk from 
"stream-chat": "^6.6.0",
    "stream-chat-react": "^9.1.3",

to 

"stream-chat": "^8.2.1",
    "stream-chat-react": "^10.4.3",

And on the ChannelList component I set `setActiveChannelOnMount={false}`

Although it works and doesn't set an active channel right away -- instead it displays the initial screen we've developed, the <Channel /> component div is still being rendered, causing the layout to break.

To avoid it from displaying when it shouldn't, I wrote something like this ` {!displayInitialScreen &&  <Channel etc /> } `

But I don't think this is the proper way for it to work, is it? Because on the previous version, I didn't need to have this validation - if no active channel was set, the` <Channel />` component simply wasn't rendered.

**To Reproduce**

**Expected behavior**

If the setActiveChannelOnMount prop is set to false, I don't expect it to render the channel component.

**Screenshots**

On the updated version of the SDK:

![screenshot-localhost_3000-2023 01 17-15_54_32](https://user-images.githubusercontent.com/47862337/212987537-45259720-55cf-47fa-852f-df75b1c2e16d.png)
<img width="1105" alt="Captura de Tela 2023-01-17 às 15 55 39" src="https://user-images.githubusercontent.com/47862337/212988262-892781c6-34b7-48a4-87a2-f7011f85410d.png">

On the old version I was using:

<img width="1100" alt="Captura de Tela 2023-01-17 às 16 08 36" src="https://user-images.githubusercontent.com/47862337/212989481-9be64cbd-5e83-47c0-9b92-95720f5200d2.png">

**Package version**
- stream-chat-react:  "^10.4.3"
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
Hey @leticiafontoura if the channel is not set, the `ChannelComponent` renders `EmptyPlaceholder` component that is passed to `Channel` via `ChannelProps`. The `EmptyPlaceholder` is set by default to `null` => blank space is rendered instead of a message list. Are you setting this prop somehow?

**Comment by leticiafontoura** [comment]
@MartinCupela I wasn't aware of that prop! Thank you so much for your help :) it makes things way easier now.

**Comment by MartinCupela** [comment]
Happy to help! 👍
