### ISSUE TITLE
question: `overrideSubmitHandler` doesn't pass quoted_message_id to message object

### ISSUE THREAD

**Issue by joelpierre** [GetStream/stream-chat-react#1910]
**Describe the bug**

When using `optionalMessageInputProps={{ overrideSubmitHandler: () => {...} }}` on the `Channel` component the `overrideSubmitHandler` doesn't pass quoted_message_id to message object and therefore does not allow someone to reply to the message.

**To Reproduce**

Video shows steps below:
- Add overrideSubmitHandler to Channel component
- Reply to a message

**Expected behavior**

I expect the quoted message to be attached and the message input to reset.

**Screenshots**

https://user-images.githubusercontent.com/8969851/213281428-4b739ed4-b426-4eec-86e5-26692cfc09ce.mov

**Package version**
- stream-chat-react: 10.4.3
- stream-chat-js: 8.2.1

**Desktop (please complete the following information):**

- OS: macOs
- Browser: Chrome
- Version latest

**Comment by MartinCupela** [comment]
@joelpierre thank you for reporting this. We will try to reproduce the issue.

**Comment by MartinCupela** [comment]
@joelpierre your implementation of `overrideSubmitHandler` should take the `quotedMessage` value from the `ChannelStateContext` (`useChannelStateContext`). This is how the SDK implements the addition of the quoted message by default:

https://github.com/GetStream/stream-chat-react/blob/2202c63e9d21daf047d65ba940d466dab8610079/src/components/Channel/Channel.tsx#L659

So you should not expect to receive `quotedMessage` among the `overrideSubmiteHandler`'s arguments.

**Comment by joelpierre** [comment]
Thanks @MartinCupela - The docs really need to expand on this, as we now have to basically override everything you do in your submit? It would be great if the **final** message object was passed to overrideSubmitHandler as the location I have to put it in in order for it to work is actually outside of the channel context too. So a lot of "refs" or "state" setting has to be done in order for me to get "channel" data.

Also from your link it would seem I also need to setQuotedMessage(undefined) to avoid permanently setting a quoted message?

**Comment by joelpierre** [comment]
@MartinCupela - Your suggestion doesn't seem to work

![Screenshot 2023-01-20 at 21 18 00](https://user-images.githubusercontent.com/8969851/213807104-ebd7746b-f785-4e12-ad9d-4dcd70e7d13b.png)

**Comment by joelpierre** [comment]
> @MartinCupela - Your suggestion doesn't seem to work
> 
> ![Screenshot 2023-01-20 at 21 18 00](https://user-images.githubusercontent.com/8969851/213807104-ebd7746b-f785-4e12-ad9d-4dcd70e7d13b.png)

Ahh I put it here instead...

![Screenshot 2023-01-20 at 21 20 29](https://user-images.githubusercontent.com/8969851/213807348-3b115542-e83a-4bfa-972b-681c19aa2b01.png)

**Comment by MartinCupela** [comment]
@joelpierre can I close this ticket, please?

**Comment by joelpierre** [comment]
All good 👍🏽
