### ISSUE TITLE
question: Seamless auth from backend server

### ISSUE THREAD

**Issue by KrunchMuffin** [GetStream/stream-chat-react#1913]
Has anyone ever done an integration whereby you have an auth'd user in a backend app like Java and want to log them into the React frontend chat without them having to login in again to chat? It is a closed system, so we don't have guests/anon. I hired some devs to do it, but I don't know if it is the best way, or if there is a best way.

**Comment by arnautov-anton** [comment]
Hey, @KrunchMuffin - the general idea is that you create your own token endpoint which accepts application token (or valid session) to generate a token for the chat application so you should only authenticate once per application. 
The flow would look something like this:

sign in and generate session or token for your web application -> with that token (or session) hit your /generate-stream-token and return valid chat token -> store it locally and pass the token to the Chat component 

You can take it further with `tokenProvider` function which expects a promise and will be called each time the SDK makes the request to the Stream servers making it perfect for short lived chat tokens.

Here's how would such `tokenProvider` look:
```ts
const tokenProvider = async () => {
	let localStreamToken = localStorage.getItem("stream:token");

	if (isTokenExpired(localStreamToken)) {
		localStreamToken = await myApp.getNewToken();
		localStorage.setItem("stream:token", localStreamToken);
	}

    return localStreamToken;
};
// ...
chatClient.connectUser(<userData>, tokenProvider)
```
Hope this helps, let me know if you have any other questions.

**Comment by KrunchMuffin** [comment]
Thanks for the info.

So there wouldn't be too much to change in the React chat SDK to get it to work?

**Comment by arnautov-anton** [comment]
No change at all, there's everything you need to make it work. 👍

**Comment by KrunchMuffin** [comment]
Where is a good place to get help with this? I am not a React, or any JS framework, dev. I have gone through the tutorial hoping it would come out like the examples online, but it doesn't. I don't mind paying for help.

**Comment by arnautov-anton** [comment]
Oh, I see, you should definitely contact our [support engineers](https://getstream.io/contact/support/) then I'm sure they'll be able to help you with your integration. 🙂 

@GetStream/customer-support

Closing this for now.
