### ISSUE TITLE
bug: Window prop tread is supposed to manually trigger opening a thread

### ISSUE THREAD

**Issue by michalvankodev** [GetStream/stream-chat-react#1917]
**Describe the bug**

According to documentation and code comments there is a prop on a `Window` component that is supposed to manually open a thread. 

I want to use this feature but I've noticed that this prop `thread` is not used in the `Window` component. It's just documented as an optional prop but the value is not passed into any context or component.

The code that I'm referring to can be found here: https://github.com/GetStream/stream-chat-react/blob/ede059f3372601882d0551fe5a8f10c19768c4c7/src/components/Window/Window.tsx#L27

I've also taken a look into the history of the component and the functionality is missing since the history is tracked for this file.

I'd like to know if there is any way how could I trigger manually opening a thread/

**Comment by MartinCupela** [comment]
@michalvankodev thank you for reporting this bug. Indeed this is a bug of `thread` prop not being used.  The comments are also misleading, because this prop was probably intended for hiding the `Window` component using CSS and not to open a thread. We will fix this bug and report the progress here.

**Comment by michalvankodev** [comment]
I've found a solution with `openThread` and `dispatch` from `useChannelActionContext()`.
Actually, I haven't been able to use `openThread` because it requires a DOM event that would be `preventDefault` in the implementation. As I want to trigger this from the `useEffect` on mount of the component I had opted to use the `dispatch` method:

```typescript
dispatch({ channel, message: threadMessage, type: 'openThread' });
```

**Comment by MartinCupela** [comment]
Yes, this was not very wise decision to couple the function with the event object to produce a side effect like that. As this would be a breaking change, I have created a new issue #1921 .

Thank you for reporting this.

**Comment by michalvankodev** [comment]
Just to let you know, I checked the implementation :point_up: and it makes sense when you want to display the thread in a controlled fashion. What I actually wanted was to trigger opening a thread. Best described with `const { openThread } = useChannelActionContext`.

That one still requires an actual DOM event to be used otherwise it will throw an error.

**Comment by MartinCupela** [comment]
True, one definition in `ChannelActionsContext` have slipped. I will fix it.
