### ISSUE TITLE
Possibility of adding aria-hidden for MessageActionIcon

### ISSUE THREAD

**Issue by tedderple** [GetStream/stream-chat-react#1922]
**Motivation**
We went through an accessibility audit and would like to ask if it would be possible to add the option to add aria-hidden label on this decorative SVG:
https://github.com/GetStream/stream-chat-react/blob/03fbe2b5ab1f71d82880586bada6ed2cba156db4/src/components/MessageActions/MessageActions.tsx#L137

**Proposed solution**
add option to have aria-hidden property to this decorative icon

**Acceptance Criteria**
MessageActionsProps can have an option to add aria-hidden to the ActionsIcon

**Comment by MartinCupela** [comment]
Hello @tedderple ,

thank you for the interest in the SDK. At the moment, we do not have immediate plan to review the accessibility of the components. You can easily achieve the desired effect by overriding `MessageOptions` and `ActionsIcon` components as follows:

```tsx
const ActionsIcon = ({ className = '' }: IconProps) => (
  <svg
    aria-hidden={false}
    className={className}
    height='4'
    viewBox='0 0 11 4'
    width='11'
    xmlns='http://www.w3.org/2000/svg'
  >
    <path
      d='M1.5 3a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm4 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm4 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z'
      fillRule='nonzero'
    />
  </svg>
);

...

const CustomMessageOptions = (props: MessageOptionsProps) => <MessageOptions {...props} ActionsIcon={ActionsIcon}/>

...

const App = () => (
  <Chat client={chatClient}>
    <ChannelList filters={filters} sort={sort} options={options} showChannelSearch />
    <Channel MessageOptions={CustomMessageOptions}>
      <Window>
        <ChannelHeader />
        <MessageList />
        <MessageInput focus />
      </Window>
      <Thread />
    </Channel>
  </Chat>
);

```
