### ISSUE TITLE
bug: Deleting a channel when using the Channel component without ChannelList outputs errors.

### ISSUE THREAD

**Issue by DannyBiezen** [GetStream/stream-chat-react#1939]
**Describe the bug**

In my application I am rendering a `Channel` without a `ChannelList`

```
<Chat client={client}>
        <ChannelView channel={existingChannel}>
            <Window>
                <VirtualizedMessageList  />
                <MessageInput />
            </Window>
        </ChannelView>
</Chat>
```

From my Backend I then delete my channel.
`await _channelClient.DeleteAsync(type, id);`

This successfully deletes the channel, however I get the following error.
![image](https://user-images.githubusercontent.com/94181463/219104975-d348357d-eff1-40c7-9c6b-62054f6a4d54.png)

**To Reproduce**

I can reproduce this in the typescript example app by making a few tweaks.

1. Go to the typescript example app
2. Replace the App component with the following code, make sure to replace the channel id with the id of an existing channel:
```
const App = () => {
  const [channel, setChannel] = useState<Channel | null>();

  useEffect(() => {
    async function getChannel() {
      const channels = await chatClient.queryChannels({
        id: '<id>',
      });
      setChannel(channels[0]);
    }
    getChannel();
  }, []);

  return (
    <Chat client={chatClient}>
      <ChannelView channel={channel!}>
        <Window>
          <ChannelHeader />
          <MessageList />
          <MessageInput focus />
        </Window>
        <Thread />
      </ChannelView>
    </Chat>
  );
};
```
4. Delete the channel from the BE
5. See error
![image](https://user-images.githubusercontent.com/94181463/219106085-43f7d95c-4ff1-4994-87b3-635c587a328b.png)

**Expected behavior**

To not get an exception.

**Package version**
- stream-chat-react: 10.6.0
- stream-chat-css: 3.9.0
- stream-chat-js: 8.3.0

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 109

**Comment by MartinCupela** [comment]
@DannyBiezen I see few problems in your approach:

1. You cannot assert that the `channel` value will always be defined (in your example `<ChannelView channel={channel!}>`)
2. You are not handling an edge case when `chatClient.queryChannels()` returns an empty array of channels
3. You are not checking that the `channel.disconnected === true` - this happens, when the channel is deleted (when event `channel.deleted` arrives, the client marks that channel as `disconnected`.

Based on these, you can show different views,
