### ISSUE TITLE
bug: No default TypingIndicator provided when using VirtualizedMessageList

### ISSUE THREAD

**Issue by DannyBiezen** [GetStream/stream-chat-react#1941]
**Describe the bug**

The `VirtualizedMessageList` does not have a default implementation for the `TypingIndicator`:
https://github.com/GetStream/stream-chat-react/blob/34b8e71771566551180af412f3c13d0740ccc725/src/components/MessageList/VirtualizedMessageList.tsx#L149

The `MessageList` does have a default implementation: https://github.com/GetStream/stream-chat-react/blob/34b8e71771566551180af412f3c13d0740ccc725/src/components/MessageList/MessageList.tsx#L81

**Expected behavior**

I can get the expected behavior by passing the `TypingIndicator` to the `Channel` component
`<Channel TypingIndicator={TypingIndicator} />`.

However, I would've expected this to work out of the box. Are there any specific reasons to not have this as the default? 
I'm also wondering if there are any docs about the differences between `MessageList` and `VirtualizedMessageList` as I've been running into other issues due to slight differences in behaviour between the two.

**Package version**
- stream-chat-react: 10.6.0
- stream-chat-css: 3.9.0
- stream-chat-js: 8.3.0

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 109

**Comment by MartinCupela** [comment]
Hello @DannyBiezen , I am not aware of the reason why default `TypingIndicator`. We would like to deprecate the `MessageList` eventually, but we keep that epic in the backlog for now. That is also the reason we do not have a list of the differences.

Please pass your TypingIndicator component to corresponding Channel prop to work around this.

**Comment by dannyBies** [comment]
If I pass the `TypingIndicator` to the `Channel` component I quickly run into https://github.com/GetStream/stream-chat-react/issues/1951 which is making it unusable for my situation so I've disabled it for now.

**Comment by MartinCupela** [comment]
@dannyBies the issue #1951 will be partially fixed with https://github.com/GetStream/stream-chat-css/pull/221. The only thing we cannot introduce in a minor version / patch is change of markdown (moving TypingIndicator outside the message list's scroll container).
