### ISSUE TITLE
bug: React same key warning in messageList component.

### ISSUE THREAD

**Issue by Sanjuhub** [GetStream/stream-chat-react#1942]
**Describe the bug**
I have created some user_created_group and any user edit/update the group name or group image, with the update I am adding a system message something like:
<img width="706" alt="Screenshot 2023-02-16 at 5 22 57 PM" src="https://user-images.githubusercontent.com/20820156/219358032-69d7a9ba-164b-4acf-954b-badfbf96abb0.png">

But when two system messages are added at the same time then I am getting react warning: _Encountered two children with the same key, `Tue Feb 14 2023 11:59:07 GMT+0530 (India Standard Time)`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version._

I am using the `messageList` component for rendering messages.
`<MessageList
                    key={uuidGenerator()}
                    Message={CustomMessage}
                    customMessageActions={customActions}
                    messageActions={actions}
                    messageLimit={constantOptions?.STREAM_MESSAGE_LIMIT}
                    internalInfiniteScrollProps={{
                        threshold: 750,
                    }}></MessageList>`

Any idea how can I fix it?

**Screenshots**

<img width="279" alt="Screenshot 2023-02-16 at 5 12 16 PM" src="https://user-images.githubusercontent.com/20820156/219355811-dfc29879-da17-4d60-aab0-8b74cc427e4e.png">

**Package version**
"stream-chat": "^8.2.0",
"stream-chat-react": "^10.6.0",
"@stream-io/stream-chat-css": "^3.7.1",

**Comment by Sanjuhub** [comment]
When this fix will be released? @arnautov-anton

**Comment by arnautov-anton** [comment]
Hey, @Sanjuhub! Thank you for your contribution and sorry for not replying earlier. We usually plan our releases on Fridays - so this one should be out tomorrow. :)
