### ISSUE TITLE
bug: Image gallery swipe buttons look incorrect on small images

### ISSUE THREAD

**Issue by DannyBiezen** [GetStream/stream-chat-react#1943]
**Describe the bug**

Uploading multiple images of which one or more are small results in styling issues. 
![image](https://user-images.githubusercontent.com/94181463/219370838-d1ff6d5f-4a38-4c59-bd15-07bbe48231ac.png)

**To Reproduce**

1. Go to https://getstream.io/chat/demos/messaging/
2. Go to https://picsum.photos/100.jpg to get 2+ random images of 100w/100h
3. Download these images
4. Upload these images to the demo app.
5. Click on the image to open the `GalleryModal`
6. Notice the styling issues

**Expected behavior**
The GalleryModal to be useable by users when they try to view small images.

**Package version**
- stream-chat-react: 10.6.0
- stream-chat-css: 3.9.0
- stream-chat-js: 8.3.0

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 109

**Comment by MartinCupela** [comment]
@DannyBiezen thank you for reporting this. Feel free to apply your own CSS to make those buttons smaller or otherwise styled.

I am closing this issue in favor of: https://github.com/GetStream/stream-chat-css/issues/222
