### ISSUE TITLE
bug: useImageFlagEmojisOnWindows does not work with v2 theme

### ISSUE THREAD

**Issue by DannyBiezen** [GetStream/stream-chat-react#1944]
**Describe the bug**

The setting `useImageFlagEmojisOnWindows` does not work when using v2 theme.
Using the v1 theme does correctly show the flag emoji.

**To Reproduce**

1. Enable `useImageFlagEmojisOnWindows`: `<Chat useImageFlagEmojisOnWindows />`
2. Make sure you're importing the correct css (v2) `import "stream-chat-react/dist/css/v2/index.css";`
3. Send a flag emoji
4. Notice that no flag appears
![image](https://user-images.githubusercontent.com/94181463/219431891-78302526-678f-4c4c-9487-13b2482c94b6.png)

If I change the css import to `import "stream-chat-react/dist/css/index.css`
I get the expected emoji:
![image](https://user-images.githubusercontent.com/94181463/219431792-84e9cc86-476f-4536-8184-3a1f460bfa3e.png)

**Expected behavior**

To get a flag instead of a country code.

**Package version**
- stream-chat-react: 10.6.0
- stream-chat-css: 3.9.0
- stream-chat-js: 8.3.0

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 109

**Comment by shodgetts** [comment]
Hi @DannyBiezen 👋 Stephen here from the Stream CS team. I've noticed a few different bug reports you've opened. What's the Stream Org ID you're using? Feel free to drop me a note at stephen@getstream.io

**Comment by MartinCupela** [comment]
@DannyBiezen This bug is being solved with the following PR:

https://github.com/GetStream/stream-chat-css/pull/220
