### ISSUE TITLE
Add option to align items at the bottom when using MessageList

### ISSUE THREAD

**Issue by DannyBiezen** [GetStream/stream-chat-react#1945]
**Motivation**

When using the `VirtualizedMessageList` I can pass in a prop to align my messages to the bottom:
```
<VirtualizedMessageList additionalVirtuosoProps={{ alignToBottom: true}}  />
```
`alignToBottom: false`:
![image](https://user-images.githubusercontent.com/94181463/219447359-33d223e9-50b9-4bec-86b7-27f093f99843.png)

`alignToBottom: true`:
![image](https://user-images.githubusercontent.com/94181463/219447812-5eeb611e-68be-4007-8468-07cf2f4408db.png)

I would like to align my messages to the bottom when using `MessageList`. As far as I can tell this is currently not possible.

**Proposed solution**
Add an `alignToBottom` prop to the `MessageList` component.

**Acceptance Criteria**
- New messages appear on the bottom instead of the top of the screen.

**Comment by arnautov-anton** [comment]
Hey, @DannyBiezen, sorry for the delay and thank you for this feature submission. Unfortunately we won't be adding this feature to our `MessageList` anytime soon as the long-term plan is to move away from this component, deprecate it and focus on maintaining only the `VirtualizedMessageList` as both lists have its own set of problems and it's not easy to focus on fixing both.

If you're set on using `MessageList` then the easiest way to implement this feature in your integration is by applying these custom style-sheet rules (you might have to tinker with it slightly, but this soluton should work as expected):

```css
.str-chat__list {
  display: flex;
  align-items: flex-end;
}

.str-chat__message-list-scroll {
  max-height: 100%;
  width: 100%;
}
```

Closing this for now, let us know if you have any other questions. :)

**Comment by DannyBiezen** [comment]
Ah okay! Are you planning on eventually adding some of the features from `MessageList` such as a default `TypingIndicator` and the `DateSeparator`,  into the `VirtualizedMessageList`?

The CSS seems to mostly work which is great! I wasn't aware that the plan was to remove the `MessageList` at some point so I will try to get everything working with the `VirtualizedMessageList` instead!
