### ISSUE TITLE
bug: channel.state.pinnedMessages will not update if trying to unpin message from not loaded page yet

### ISSUE THREAD

**Issue by sergeyzhukov** [GetStream/stream-chat-react#1946]
**Describe the bug**

When client tries to do `client.unpinMessage(message)` and message that user trying to unpin is on the second page of `MessageList` - `channel.state.pinnedMessages` will still contain that message that should be unpinned. After reloading the page - `channel.state.pinnedMessages` will have the correct data.

**To Reproduce**

1. Create several messages inside the channel that do not fit into one pagination page.
2. On fresh page after loading, try to unpin some specific message that was 100% on second page
3. Check `channel.state.pinnedMessages`.
4. Should still contain this message. 

**Expected behavior

channel.state.pinnedMessages should no longer contain the message.

**Package version
- stream-chat-react: 10.5.0
- stream-chat-js: 8.3.0

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS Ventura
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 109.0.5414 arm64

**Comment by MartinCupela** [comment]
@sergeyzhukov could you please confirm, from where the mentioned `channel` object  (`channel.state.pinnedMessages`) is taken from in your code? It should be accessed by `useChannelStateContext` in that case the UI is updated correctly in my reproduction.

**Comment by sergeyzhukov** [comment]
@MartinCupela yes, I'm using `pinnedMessages` from `useChannelStateContext`

like this

`const { channel: stateChannel, pinnedMessages } = useChannelStateContext()`

**Comment by MartinCupela** [comment]
@sergeyzhukov would you be so kind, and provide a minimum reproduction by forking this [codesandbox](https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv), please? I am not able to reproduce the behavior based on the description. Thank you

**Comment by MartinCupela** [comment]
closing the issue for inactivity
