### ISSUE TITLE
bug: full re-render of the Channel wrapper on ChannelList filter update (without changing the active channel)

### ISSUE THREAD

**Issue by lr-mjaouen** [GetStream/stream-chat-react#1948]
**Describe the bug**

_A clear and concise description of what the bug is._

When filtering on the ChannelList, everything under `<Channel></Channel>` is completely (hard) re-rendered (unmounted before being mounted again), which will make it disappear for a sec (even for a basic text component).
The current active channel does not change so the Channel component should not be remounted/rerendered this way.

**To Reproduce**

```

const [ searchFilter, setSearchFilter ] = useState();
<>
	<ChannelsSearchInput setSearchFilter={setSearchFilter} />
    <ChannelList<ChatGenerics>
        channelRenderFilterFn={dmsChannelFilterFunction}
        setActiveChannelOnMount={false}
        filters={dmsFilters}
        sort={ChannelDefaultSort}
        Preview={ChannelPreview}
        LoadingIndicator={LoadingChannels}
        EmptyStateIndicator={isFiltering ? () => <NoResultsState /> : () => <EmptyChannelsState />}
        LoadingErrorIndicator={ErrorChannelsState}
        List={ChannelListMessenger}
        options={{ limit: DirectMessageChannelLimit }}
        lockChannelOrder={false}
        allowNewMessagesFromUnfilteredChannels={true} // allows to add not yet watched channels (unlisted) to the list
        renderChannels={renderDmsChannels}
    />
</>
```
Then on filtering, everything under <Channel> will flick even if the active channelId does not change.
```
import { Channel } from 'stream-chat-react';


          <Channel>
              <Text>This text component will be unmounted/mounted when filtering</Text>
          </Channel>
```

**Expected behavior**
_A clear and concise description of what you expected to happen._

Do not re-render Channel if the active channel id does not change.

Would it be possible that on filtering/fetching you reset the list & with it the current active channel which makes it to be unmounted/mounted again?

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Before filtering,
![image](https://user-images.githubusercontent.com/56837954/220192259-ef7f6f4b-1ab7-49ad-89cb-ffb78a3a6f40.png)
Filtering, the message list under <Channel> disapear (glitch for a sec),
![image](https://user-images.githubusercontent.com/56837954/220191988-bf3d7c4f-27fe-4675-aec5-c8edc25e22a7.png)
Then re-rendered again,
![image](https://user-images.githubusercontent.com/56837954/220193317-b3999e56-aedf-4d0f-b833-4ebfd26a3d56.png)

**Package version**
"stream-chat": "^8.1.3",
"stream-chat-react": "10.4.1",

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOs BigSure
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] Version 110.0.5481.100 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] MacBookPro 

**Additional context**

Please let me know if it's not clear enough or if I did a mistake. Thank you!

**Comment by MartinCupela** [comment]
@lr-mjaouen could you please provide a minimum reproduction of the scenario? I am not able to reproduce the complete re-render on typing the search query.

We have created a template for an easier reproduction in codesandbox:

https://codesandbox.io/s/stream-chat-react-tutorial-vq5ntv

Thank you

**Comment by lr-mjaouen** [comment]
Thank you I'll try to soon.

**Comment by lr-mjaouen** [comment]
I did it quickly, I could have make a mistake but here for instance it re-renders (unmount/mount) everything
https://codesandbox.io/s/exciting-christian-c4kxyv?file=/src/App.tsx

**Comment by lr-mjaouen** [comment]
I want indeed to search from the API, since all channels are not listed I don't want to search only client side.
(But I just don't want that it reinitialize the current active channel when I change the filters?)

**Comment by lr-mjaouen** [comment]
Here is the UI,
![image](https://user-images.githubusercontent.com/56837954/224805326-43157658-7ce0-4836-aec5-b5f618a3ca44.png)
I think what you are saying is to keep the initial list (I have 2, one on top of the other but it does not change much) and display hover other ones only when we filter so we keep the initial list & keep the watch for it too.
But would not be easier to just keep the current active channel until we set it?

**Comment by tao-qian** [comment]
We are a bit confused by this behavior as well. It is odd that <Channel /> would re-render, when the prop change happens on <ChannelList />.

Our setup is similar:
```
<ChannelList filters={filters}/>
<Channel channel={activeChannel}/>         
```

We are modifying the filters on ChannelList based on user Input and displaying the result to the user. And we are seeing <Channel /> being re-rendered, causing flickering, when activeChannel is changed.

**Comment by tao-qian** [comment]
> change in filters leads to a new channels query what leads to a new state for <Channel/>

Yeah this is the part which I felt might not be necessary from a product perspective. Intuitively, `<Channel/>` should just be dependent on a a single Channel, not all the Channels returned by the `<ChannelList />`. That said, I understand that there are probably technical reasons why this was implemented the way it is, and it might not be easy to change this current behavior.

> The ChannelList provides search functionality. Please, share more details about why you try to implement your custom search this way?

We tried the search functionality initially but didn't like the UI treatment of showing two separate lists to the user:
- one list from the ChannelList (which are the Channels the user is in)
- one list for the search result

So we thought that we can just `filter` to search/filter on the existing ChannelList directly, that works especially with the `autocomplete` query you guys already support, but yeah the re-rendering is causing some issue.

**Comment by MartinCupela** [comment]
I understand. Unfortunately, the `ChannelList` is a monolith of search + list. The `ChannelList` sets active channel, so after a new query a new channel instance is set to the state from which the `Channel` component takes the data. We have thoughts on providing separate list and search components rather than refactor of the existing `ChannelList`. But, unfortunately, at the moment it is not at the top of the list.

**Comment by tao-qian** [comment]
Yeah no worries! Thanks for the additional context on the technical constraint. We understand all the problems you mentioned about existing design and prioritization as well :slightly_smiling_face: 

We will just explore a workaround on our end. Fortunately this is not something that's too hard for us customize.
