### ISSUE TITLE
bug: TypingIndicator in a VirtualizedMessageList shows the indicator at an incorrect location when scrollbar is visible

### ISSUE THREAD

**Issue by DannyBiezen** [GetStream/stream-chat-react#1951]
**Describe the bug**

The TypingIndicator for the VirtualizedMessageList does not stay at the bottom when a scrollbar appears.

**To Reproduce**

1. Open the TypeScript example app
2. Add the TypingIndicator to the `Channel` as this is set to `null` by default.
```
import { TypingIndicator } from 'stream-chat-react';
<Channel TypingIndicator={TypingIndicator}>`
```
3. Remove `if (!isTypingActive) return null;` from `TypingIndicator.tsx` to make the indicator always visible to make it easier to test
4. Add enough messages in a channel for a scrollbar to appear
5. Notice that the Indicator will keep moving up with every new message

![image](https://user-images.githubusercontent.com/94181463/220696046-ed525467-b487-4c1e-a326-8d238ab04a19.png)

**Expected behavior**
The indicator to always be visible and stick to the bottom of the chat.

**Package version**
- stream-chat-react: 10.6.0
- stream-chat-css: 3.9.0
- stream-chat-js: 8.3.0

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 109

**Comment by MartinCupela** [comment]
@DannyBiezen you can apply the following css to keep the indicator at the bottom:

```
.str-chat__virtual-list .str-chat__typing-indicator {
  position: static;
}
```

Moving the indicator at another location in the DOM would mean a breaking change which we would like to avoid for now.
