### ISSUE TITLE
bug: VirtualizedMessageList re-renders all messages (on new message), cut playing videos, gifs etc

### ISSUE THREAD

**Issue by lr-mjaouen** [GetStream/stream-chat-react#1955]
**Describe the bug**

_A clear and concise description of what the bug is._

If you send a YouTube video for instance on the demo one, the only one using a VirtualizedMessageList (virtuoso?),
https://getstream.io/chat/demos/livestream/
And if you send a new text message, the list is re-rendered, making videos gifs or any other integrationto be cut and mounted again.
It's making the virtualized list difficult to use since on every messages all integrations will be stopped, rerendered etc (it really slows down the performances & the user experience).

**To Reproduce**

1. Go to https://getstream.io/chat/demos/livestream/
2. Send a new message with a youtube video
3. Play the video in the chat
4. Send a new classic text message
5. Everything is rerendered, the youtube video is stopped & rerendered

**Expected behavior**

Don't re-render the list and existing messages just add the last one to the list without an extra mount.
_If possible keep the last current message mounted (just hidden when necessary) (like Slack does since a few months) in order to keep this message mounted even while (far) scrolling._

**Screenshots**
![image](https://user-images.githubusercontent.com/56837954/221227052-3db743cc-09cd-480b-a27d-19ebd4b99123.png)

**Package version**
"stream-chat": "^8.1.3",
"stream-chat-react": "10.4.1",

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macos
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] 110.0.5481.100 (Official Build) (x86_64)

**Additional context**

(It's working ok for the MessageList component since it's not mounted again)

**Comment by MartinCupela** [comment]
@lr-mjaouen this limitation is known to us and is related to the virtuoso dependency. We do not have an ETA to tackle this problem so we keep this issue in our backlog.

**Comment by lr-mjaouen** [comment]
Ok thank you.

**Comment by lr-mjaouen** [comment]
What is an ETA? Thank you.

**Comment by MartinCupela** [comment]
@lr-mjaouen we do not have ETA for this at the moment.

**Comment by lr-mjaouen** [comment]
estimated time of arrival

**Comment by MartinCupela** [comment]
This issues has been fixed by https://github.com/GetStream/stream-chat-react/pull/2067
