### ISSUE TITLE
Allow to add a spinner or placeholder when image is loading in the MessageList

### ISSUE THREAD

**Issue by neopit** [GetStream/stream-chat-react#1958]
**Motivation**
It could be great to allow to add of a spinner or placeholder when the image is loading in the MessageList.

**Proposed solution**
Currently, it is possible to create a custom Image component based on the GetStream Image component.
It is great but the update cannot be propagated everywhere.

For example, we can create a custom Image component and pass it to the <Attachment> component. It works but only when the message displays a single image.
If the user sends several images then the component used by Stream is the Gallery. In this case, it is not possible to pass props for indicating we would like to use a custom Image component. It seems possible to customize the Gallery component it means too much work.

So here are a couple of solutions:

1. Able to provide a spinner or a placeholder to the existing Image Stream component  and this would be reflected on single and gallery image
2. Be able to provide a custom Image component used for a single image but also for multi-image (Gallery)

**Comment by MartinCupela** [comment]
@neopit thank you for the suggestion on a new feature. We will keep it in our backlog for now.

**Comment by MartinCupela** [comment]
It is possible to provide custom `BaseImage` component to `Channel` component to override the default underlying component for rendering the images in both `Gallery` and `Image`. This is possible as of v11.1.0. Fixed by #2200.
