### ISSUE TITLE
Getting unread count even I am present on that channel

### ISSUE THREAD

**Issue by siddharthJadhav** [GetStream/stream-chat-react#197]
Hello,

I am implementing PWA web-chat with react js.

I customize a channel list as mention in https://getstream.io/chat/react-chat/tutorial/  this link.

I fetching message count using below code
`const unreadCount = channel.countUnread();`

To fetch real-time unread count I fetch from the channel when I received a new message.
` 
channel.on('message.new', (event) => { 
const unreadCount = channel.countUnread();
}`

I am present on channel still I got an unread count for that channel.

The expected behavior is I will get the unread count only if I am not present on that channel.

**Comment by vishalnarkhede** [comment]
Hey @siddharthJadhav, when you receive message.new event, channel doesn't know yet if you have read the message or not. If you are currently active on channel, then we mark it as read manually - https://github.com/GetStream/stream-chat-react/blob/master/src/components/Channel.js#L493

**Comment by siddharthJadhav** [comment]
When I read that message I also manually doing the same using
`channel.markRead(); `

There is any way so I can get an active channel in MyChannelPreview.

**Comment by vishalnarkhede** [comment]
@siddharthJadhav `activeChannel` is already present in preview component - https://github.com/GetStream/stream-chat-react/blob/master/types/index.d.ts#L205

**Comment by siddharthJadhav** [comment]
Ok got it thank you.

**Comment by siddharthJadhav** [comment]
@vishalnarkhede  I am trying to read `activeChannel` inside `MyChannelPreview`  component.
`props.activeChannel`

But I get `{}`.

**Comment by siddharthJadhav** [comment]
any update?

**Comment by vishalnarkhede** [comment]
Hey @siddharthJadhav can you please share your code of ChannelList?

**Comment by siddharthJadhav** [comment]
@vishalnarkhede  Bellow is my channel preview component

import React, { Component } from 'react';
import "./MyChannelPreview.css";
export class MyChannelPreview extends Component { 

   constructor(props){
      super(props);

      this.state = {
        name: this.props.channel.data.name,
        lastMeaasge: this.props.latestMessage,
        unreadCount: unreadCount,
        activeChannel: props.activeChannel
      }
      this.listenToChanges();
    }

    listenToChanges() {
      const {channel} = this.props;

      channel.on('message.new', (event) => {
        console.log('message event : ' , event);
          this.setState({
            lastMeaasge: event.message.text,
            unreadCount: channel.countUnread()
          });
        });

        channel.on('message.read', (event) => {
          console.log('message event read : ' , event);
            this.setState({
              unreadCount: channel.countUnread();
            });
          });
    }


    render() {
        return (
        <div >
          <button className="str-chat__channel-preview-messenger str-chat__channel-preview-messenger--unread">
            <div className="str-chat__channel-preview-messenger--left">
                <div className="img-placeholder">
                </div>
             </div>
            <div className="str-chat__channel-preview-messenger--right username-lable">
              <div className="str-chat__channel-preview-messenger--name">
                <span className="wrap-text">{this.state.name}</span> 
                <span className="dot">{this.state.unreadCount}</span>;
              </div>
              <div className="str-chat__channel-preview-messenger--last-message">{this.state.lastMeaasge}</div>
            </div>
          </button>
        </div>
      );
    }
  }



For initializing particular chat I am using
`<Channel channel={Channel}>`

**Comment by vishalnarkhede** [comment]
@siddharthJadhav can you please also add <ChannelList> component code?

**Comment by siddharthJadhav** [comment]
@vishalnarkhede  Which component code you want?

**Comment by vishalnarkhede** [comment]
@siddharthJadhav pardon me. `ChannelList`* component code!!

**Comment by siddharthJadhav** [comment]
@vishalnarkhede  I am using the default code for the channels list. I am only customizing the channel preview.

**Comment by jaapbakker88** [comment]
@siddharthJadhav is this still an issue?

**Comment by siddharthJadhav** [comment]
@jaapbakker88  Sorry for the late reply.

I have fixed this with some custom workaround.
