### ISSUE TITLE
TypeScript typedefs for mobile nav add additional required props to `<Channel>` component

### ISSUE THREAD

**Issue by DamonOehlman** [GetStream/stream-chat-react#198]
I've dropped a comment to the commit line the introduces the change (which I think is an issue):

https://github.com/GetStream/stream-chat-react/commit/dbab78b78219a9a42dc5ca2bef20c2c793751a8e#r38333039

Copy of error reported by TS:

```
Overload 1 of 2, '(props: Readonly<ChannelProps>): Channel', gave the following error.
  Type '{ children: Element[]; channel: Channel; Message: FC<MessageUIComponentProps>; }' is missing the following properties from type 'Readonly<ChannelProp
s>': openNav, openMobileNav, closeMobileNav
Overload 2 of 2, '(props: ChannelProps, context?: any): Channel', gave the following error.
  Type '{ children: Element[]; channel: Channel; Message: FC<MessageUIComponentProps>; }' is missing the following properties from type 'Readonly<ChannelProp
s>': openNav, openMobileNav, closeMobileNav
```

As mentioned in the inline comment on the commit, I believe this is due to the introduction of these additional required attributes / methods on the `ChatContextValue` interface.

**Comment by jaapbakker88** [comment]
@DamonOehlman this issue should be fixed in version 0.11.7, let me know if that works for you.

**Comment by DamonOehlman** [comment]
@jaapbakker88 Yep, that fixed that issue.  There is one more that I just noticed as well (apologies that I missed it the first time around), but the `additionalTextareaProps` on the `<MessageInput>` is also marked as required from a typedef perspective.  Not sure if this is by design or not.  That's an easy one for me to work around though by passing an empty object and I've done that and we are now on the latest version.

**Comment by jaapbakker88** [comment]
@DamonOehlman Thanks, I'll look into that. We're currently converting our whole library to TS so that should make it easier for us to catch these types of issues, but please point them out whenever you see them!
