### ISSUE TITLE
Initial scroll message list to first unread message

### ISSUE THREAD

**Issue by DmitriyNikolenko** [GetStream/stream-chat-react#1980]
**Motivation**
React Native library has this useful functionality which is improving UX. But I have not managed to find it in React library.

**Proposed solution**
Add 'initialScrollToFirstUnreadMessage' property to 'Channel' component the same as it is in React Native library

**Acceptance Criteria**
When 'initialScrollToFirstUnreadMessage' property is set a user sees a list of messages starting from the first unread when opens a chat channel.

**Comment by therajumandapati** [comment]
Hi @MartinCupela Dmitriy and I work on the same team. Were you able to pick this issue up?

**Comment by therajumandapati** [comment]
@MartinCupela We're happy to make a PR to support this if you could point us in the right direction.

**Comment by MartinCupela** [comment]
This is in progress

**Comment by therajumandapati** [comment]
Appreciate the update @MartinCupela

**Comment by MartinCupela** [comment]
It is possible to jump to the first unread message using [jumpToFirstUnreadMessage function](https://getstream.io/chat/docs/sdk/react/components/contexts/channel_action_context/#jumptofirstunreadmessage).
