### ISSUE TITLE
bug: Events not triggering on client side after soft deleting a user from the stream

### ISSUE THREAD

**Issue by Sanjuhub** [GetStream/stream-chat-react#1983]
**Describe the bug**
After soft deleting a user from the stream, the user is successfully removed from all channels including one-to-one chat and group chat. However, the expected events such as channel.updated or member.removed are not triggering on the client side after the member_count is updated in the channel data. This issue prevents the client from receiving the necessary updates related to the deleted user's removal from the channels, which may cause issues in the functionality of the chat application.

**To Reproduce**
1. Soft delete a user from the stream.
2. Observe the channel data and confirm that the member_count has been updated.
3. Check if the expected events such as channel.updated or member.removed are triggered on the client side.

**Expected behavior**
The expected events channel.updated or member.removed should trigger on the client side after soft deleting a user from the stream, allowing the client to receive the necessary updates related to the deleted user's removal from the channels

**Package version**
- stream-chat-react: ^10.4.2
- stream-chat-css: ^3.7.1
- stream-chat-js: ^8.2.0

**Comment by MartinCupela** [comment]
@Sanjuhub thank you for reporting this. We are fixing the issue.
