### ISSUE TITLE
bug: A mobile app receives a push notification despite the "skip_push: true" option.

### ISSUE THREAD

**Issue by deugene** [GetStream/stream-chat-react#1984]
**Describe the bug**

A mobile app based on stream-chat-react-native receives push notifications even though we send messages with the "skip_push: true" option.

**To Reproduce**

```
      const messageText = 'Test skip_push option'
      await channel?.sendMessage(
        {type: 'system', text: messageText, silent: true},
        {skip_push: true},
      );
```

**Expected behavior**

A mobile app does not receive a push notification if we send a message with the "skip_push: true" option.

**Package version**
- stream-chat-react: 10.5.0
- stream-chat-react-native: 5.9.1

**Comment by MartinCupela** [comment]
Hello @deugene , thank you for reporting this. The described behavior occurs only when the type of the message is `system`. This is a bug on the API side, that will be fixed. We will follow up with updates.

**Comment by MartinCupela** [comment]
@deugene the fix has been deployed. A push notification is not sent for system message if `skip_push` is enabled.
