### ISSUE TITLE
bug: Unable to remove the quoted message if the text area already contains a value

### ISSUE THREAD

**Issue by alessandroliveri** [GetStream/stream-chat-react#1988]
**Describe the bug**
When using `setQuotedMessage(undefined)` the quoted message is sent anyway if the textarea already contains a text

**To Reproduce**

1. Add a quoted message via `setQuotedMessage(message)`
2. Start typing something in the `ChatAutoComplete`
3. Delete the quoted message via `setQuotedMessage(undefined)`
4. Send the message

**Expected behavior**

The message sent shouldn't contains the quoted message but only the text

**Package version**
- stream-chat-react: 10.7.4
- stream-chat-js: 8.5.0

**Desktop (please complete the following information):**

- OS: MacOS 13.3
- Browser chrome, safari
- Version 112.0.5615.49

**Additional context**

if, after using `setQuotedMessage`, I force the textarea cleaning via `setText('')` the message quoted is removed as well

**Comment by arnautov-anton** [comment]
Hey, @alessandroliveri, thank you for submitting this issue - I was able to reproduce it and drafted a fix accordingly, we should be able to release it later this week.

**Comment by alessandroliveri** [comment]
Thank you so much for the quick checking 🙏
