### ISSUE TITLE
setGuestUser not working

### ISSUE THREAD

**Issue by talha-abdullah-990** [GetStream/stream-chat-react#1998]
CreateGuest failed with error: "JWTAuth error: token contains an invalid number of segments getting this error on creating guest user what's the issue this was working perfect berfore
` this.chatClient = new StreamChat(streamChatKey,{ timeout: 10000 })

```
  // https://getstream.io/blog/chat-edge-infrastructure/
  this.chatClient.setBaseURL('https://chat.stream-io-api.com')
  const { me: guestUser } = await this.chatClient.setGuestUser({
    id: userId,
    name: userName
  })`
```

**Comment by MartinCupela** [comment]
Hello @talha-abdullah-990, thanks for submitting an issue to our GitHub repository. We’re glad you’re getting hands on with the product. The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at [support@getstream.io](mailto:support@getstream.io) with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.
In case our understanding is incorrect and you are describing a bug, we apologise, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.

**Comment by ssshah** [comment]
we have updated the version of stream-chat package and it was working. Thanks
