### ISSUE TITLE
i18n feature

### ISSUE THREAD

**Issue by aniciom** [GetStream/stream-chat-react#20]
Hello i was wondering if its possible in the next releases, add some kind of customizations for locales in the components

Example #1: Typing text
Example #2: Online state text
Example #3: Dates (Like today, yesterday, months, etc)
Example #4: Message input placeholder
Example #5: Message deleted (I know its coming from backend)

And other places where it might be possible to add some kind of locale customizations, i know its a bit too much, i didn't dig enough in the components so i put what i saw, but please consider this feature, i think it might be a good enhancement and for the react native components too.

Thanks in advance!
Keep the good work going on.

**Comment by jaapbakker88** [comment]
Thanks for your request, i'll look into it for a future release.

**Comment by cbedoy** [comment]
@aniciom that could be fixed if they exposed strings.xml to can be overwritten from our side

**Comment by fredfgb** [comment]
> Thanks for your request, i'll look into it for a future release.

hi, how can I address this at this moment?

**Comment by tbarbugli** [comment]
@fredfgb we are going to add i18n next week to all React SDKs

**Comment by fredfgb** [comment]
> @fredfgb we are going to add i18n next week to all React SDKs

very nice! I wonder that documentation will be updated too rt ?

**Comment by vishalnarkhede** [comment]
@fredfgb docs for i18n - https://github.com/GetStream/stream-chat-react#internationalisation
