### ISSUE TITLE
bug:ChannelList not updating correctly in all cases

### ISSUE THREAD

**Issue by ayushidianapps** [GetStream/stream-chat-react#2001]
**Describe the bug**

We have a message forwarding feature in our application. We can forward to at the max 10 users.
In some cases the ChannelList does not update correctly.

Suppose I have logged in from an account of user A from MacBook Pro and Windows laptops.
Now from one of the devices I forward a message to 10 users.
Sometimes the ChannelList does not update correctly and just shows maybe 7 or 8 out of 10 channels on which we've forwarded the message.
When we reload the page, then the data is displayed correctly.

**To Reproduce**

1. Using backend forward a message to many channels from one user's account (consider more of those channels that would not be visible in the first set of channels being shown on the ChannelList)
2. Check on the front end if all the channels under different network speeds are visible

**Expected behavior**

The ChannelList must always be updated an in sync, and all the devices logged in from that account must see the updated list.

**Video of the issue**

https://drive.google.com/file/d/1EyPiSIUGQra2v55-03GDcxGMvgZ5TdVb/view?usp=sharing

**Package version**
- stream-chat-react: 10.4.2
- stream-chat-css: 3.7.2

**Desktop (please complete the following information):**

Device 1:
- OS: iOS
- Browser: chrome
- Version: 112.0.5615.137

Device 2:
- OS: Windows
- Browser: chrome
- Version: 112.0.5615.138

**Comment by MartinCupela** [comment]
@ayushidianapps thank you for filing this issue. There is one important intervening variable and that is the implementation of your forwarding service on the server. We unfortunately cannot reproduce that. Do you have some hypothesis, why the described behavior may occur? Do you have logs of sending those forwarded messages to stream API, which then were not delivered to other users?

**Comment by ayushidianapps** [comment]
Hi, I understand that it's difficult to replicate this on your end. But the
thing is that the messages were delivered successfully to all the users,
it's just that the list did not update correctly.

Please refer to this:
https://drive.google.com/file/d/1EyPiSIUGQra2v55-03GDcxGMvgZ5TdVb/view

**Comment by MartinCupela** [comment]
@ayushidianapps could you please provide a reproduction with this sandbox? I would need to know how does your implementation look like. Thank you

https://codesandbox.io/s/support-to-fork-template-g64slj?file=/src/App.tsx

**Comment by MartinCupela** [comment]
@ayushidianapps without seeing the amount of customization done on your side, I cannot help you debugging the code.

**Comment by ayushidianapps** [comment]
Can we get on a call for this?

**Comment by MartinCupela** [comment]
@ayushidianapps regarding the integration issues, I would ask you to [contact our support team](https://getstream.io/contact/support/). They will be able to help you the best. The GitHub issues is rather reserved for reporting bugs and file feature requests. Thank you
