### ISSUE TITLE
Custom fields should be returned in the ChannelList component

### ISSUE THREAD

**Issue by pomSense** [GetStream/stream-chat-react#2011]
**Motivation**
Custom fields returned in the `ChannelList` can allow for a lot of different use cases. For example, in our use-case, we need to display some of the custom fields on the `ChannelList` that allows the user to distinguish between the different channel types present in our application.

Currently, we're setting custom channel fields when creating the channel but are not able to leverage them on the `ChannelList` component as those fields are not returned.

**Proposed solution**
Return a channel's custom fields when using the `ChannelList`. 

**Acceptance Criteria**
When the `ChannelList` component is used, it should include custom fields that were set when the channel was created/updated.

**Comment by MartinCupela** [comment]
@pomSense thank you for the input. Could you please provide more clarification?:

1. what do you mean by including custom fields by `ChannelList` component? Did you mean props? 
2. Could you provide an example of the interface and how it should used? 
3. Where are you trying to access custom fields - could you attach a code snippet? The custom fields are not returned with the query channel request?

**Comment by pomSense** [comment]
Hi @MartinCupela 
Apologies for not clarifying. We are creating the stream channel as below where we pass in additional details of the channel in  `channel_detail`. 

```ts
import { Channel, DefaultGenerics, StreamChat } from 'stream-chat'

  /**
   * Creates a new chat channel
   */
 async function createChannel(
    id: string,
    type: string,
    name: string,
    createdBy?: UUID,
    channelMetadata?: IChatMetadata
  ): Promise<void> {
    const channel = this.client.channel(type, id, {
      name,
      created_by_id: createdBy || config.STREAM_CHAT.DEFAULT_USER,
      channel_detail: { ...channelMetadata }
    })

    await channel.create()
}
```

On the client, we are using the ChannelList as such (with some extraneous code removed):

```tsx
import { Channel as ChannelInstance } from 'stream-chat'
import { ChannelList, useChatContext } from 'stream-chat-react'
import type { DefaultStreamChatGenerics } from 'stream-chat-react/dist/types/types'

/**
 * Renders the list of chats, allowing you to select the chat you want to open
 */
export const ChatList = React.memo((props: IChatListProps) => {
const { chatListFilter } = useChatList()
...
 const handleChannelFilter = useCallback(
    (channels: ChannelInstance[]) => {
      // returns the unread channels
      if (filterType === 'Unread')
        return channels.filter((chatChannel) => channel?.id === chatChannel.id || chatChannel.countUnread() > 0)
      // returns the shipment chat channels
      else if (chatTypeFilter === 'team') return channels.filter((chatChannel) => chatChannel.type === 'team')
      // returns the direct message chats
      else if (chatTypeFilter === 'messaging') return channels.filter((chatChannel) => chatChannel.type === 'messaging')
      // returns all channels
      else return channels
    },
    [filterType, chatTypeFilter, channel]
  )
...
return (
          <ChannelList
            filters={chatListFilter}
            sort={{ last_message_at: -1 }}
            options={{}}
            List={CustomChatList}
            Preview={ChatPreview}
            Paginator={ChatListPaginator}
            EmptyStateIndicator={ChatListEmptyState}
            setActiveChannelOnMount={isAnyChatActive ? false : !isMobile}
            channelRenderFilterFn={handleChannelFilter}
          />
}
```

What we are trying to accomplish is to filter the ChannelList with any of the details we provided in the `channel_detail`. For example, if we created a channel with 
```
channel_detail: {
customerID: '123',
ticketNumber: 'abc,
type: 'Tickets',
status: 'In transit'
}
```

Then on the client, we want to be able to filter the list of Channels shown based on one of these fields. i.e.:
- A button to toggle between the `type` property
- Filter channels for a specific customer using `customerID`
- Display the ticketNumber on each Channel card when we render the `ChannelList`
- Display the status on the channel card

Here is a design to show an example of how we want our users to be able to toggle between the filters, and how the channel list can display.

<img width="1313" alt="image" src="https://github.com/GetStream/stream-chat-react/assets/35952778/d3e6e766-80d1-486d-b5eb-97d11fd9cade">


Please let me know if this makes sense

**Comment by pomSense** [comment]
Hi @MartinCupela As per my colleagues, it looks like we can just pass the filters in the ChannelList and should be able to accomplish what I was asking. 

I will close the issue for now. Thanks for the help!
