### ISSUE TITLE
bug: Error: call connectUser or connectAnonymousUser before creating a channel

### ISSUE THREAD

**Issue by hclanka** [GetStream/stream-chat-react#2017]
I don't really know why this is happening

![image](https://github.com/GetStream/stream-chat-android/assets/110328123/9a3d0ac3-8540-42de-baa4-85ebe96db241)

here is the code that im doing with react and useEffect
```js
  const [chatClient, setChatClient] = useState(null);
  const [channel, setChannel] = useState(null);
  const [data, setData] = useState({});

  useEffect(() => {
    async function initStream() {
      await axios
        .get(
          "http://localhost:3000/user/get-user?authUid=7se0WJ6NhYVJQOKsZOpXxMStcW92"
        )
        .then((res) => {
          const data: object = res["data"]["record"][0];
          setData(data);
        })
        .catch((err) => console.error(err));

      const client = StreamChat.getInstance("6myfguk8dbpp");

      setChatClient(client);

      const channel = client.channel("messaging", "general", {
        name: "Chat",
      });
      setChannel(channel);
    }
    initStream();
  }, [data]);

```

**Comment by MartinCupela** [comment]
Hello @hclanka , you have omitted the effect cleanup in you snippet. That may be the reason for the error. You are not disconnection on re-render. Please, take a look at this[ introductory guide](https://getstream.io/chat/docs/sdk/react/basics/getting_started/#summary) on which demonstrates the connection setup in the effect.

**Comment by hclanka** [comment]
hey thanks for the help! This should work <3 I didnt know there were these docs i was using this one this whole time https://getstream.io/chat/docs/node/tokens_and_authentication/?language=javascript
