### ISSUE TITLE
bug: hideOnThread is missing the CSS to actually hide the component in v2 CSS/SCSS

### ISSUE THREAD

**Issue by autumnwoodberry** [GetStream/stream-chat-react#2024]
**Describe the bug**

When setting the `hideOnThread` prop to `true` on the `<Window/>` component, the classname is correctly added to the element when a thread is opened, but the CSS necessary to actually hide the <Window/> is not there, so it is not hidden.

**To Reproduce**

1. Setup a basic project and use `<Window hideOnThread>`
2. Observe that when you open a thread, the window is not hidden.

**Expected behavior**

The CSS for hiding the window is present, and the window is not displayed on the screen.

**Package version**
- stream-chat-react: 10.8.1

**Desktop (please complete the following information):**

- OS: Mac OSX
- Browser: Chrome

**Additional context**

This bug happens when importing the v2 css directly, or when importing the scss file.

**Comment by MartinCupela** [comment]
Hello @autumnwoodberry , the v2 stylesheet does not list rule for `str-chat__main-panel--hideOnThread` class. Thank you for reporting this. We will add it. In the meantime, you can add that rule to your local stylesheet and everything should work.
