### ISSUE TITLE
Your example doesn't properly work

### ISSUE THREAD

**Issue by Darapsas** [GetStream/stream-chat-react#204]
Using typescript and "stream-chat-react": "0.11.10". Getting this error when trying to start your example code: 

![20200410_111109](https://user-images.githubusercontent.com/20926795/78975075-0451ec80-7b1c-11ea-8eb6-e154bed53155.png)

For now I have just changed your index.d.ts 906th line to this:
![image](https://user-images.githubusercontent.com/20926795/78975265-6b6fa100-7b1c-11ea-8368-35a4f81d3eeb.png)

**Comment by vishalnarkhede** [comment]
Thanks for bringing it up @Darapsas . We will fix it in next release :)

**Comment by vishalnarkhede** [comment]
@Darapsas I have published a patch for this - `v0.11.12`.
