### ISSUE TITLE
Flag and Mute command is not working

### ISSUE THREAD

**Issue by siddharthJadhav** [GetStream/stream-chat-react#205]
Hello,

I am creating React js PWA using Getstream.

When I try to mute particulate  user by typing in the text input
`/mute @username`

it throws an error "invalid mute cmd. please specify a valid user"

And when I try to add a particular flag by typing in the text input
`/flag @username`

It's not working.

Can you tell me how do I solve this issue?

**Comment by siddharthJadhav** [comment]
any update?

**Comment by vishalnarkhede** [comment]
Hey @siddharthJadhav this is a bug. I will look into it today. Thanks for brining this up :)

**Comment by mksglu** [comment]
> Hey @siddharthJadhav this is a bug. I will look into it today. Thanks for brining this up :)

I created a fresh CRA application and tried to reproduce this issue. Then yes! I have the same issue. I did not notice an issue on the front-end side. 500 error codes are returned from a URI.

* URI:
```
https://chat-us-east-1.stream-io-api.com/channels/channelType/1/message?user_id=1&api_key=kfheymkdn9e7&connection_id=baf46017-d195-4259-b722-bea3bcd5495b
```
* Request Payload:
```
{
    "message": {
        "text": "/unmute @Misty cell ",
        "attachments": [],
        "mentioned_users": ["1"],
        "id": "1-65537be2-7298-4c3f-917c-164ca120fdae"
    }
}
```
* Payload:
```
{
    "code": -1,
    "message": "SendMessage failed with error: \"\"",
    "StatusCode": 500,
    "duration": "0.00ms"
}
```

**Comment by vishalnarkhede** [comment]
We are currently working on fixing issue with flag/mute commands. The problem is that api expects `/flag @user_id` or `/flag user_id`, but our UI sdk currently sends `/flag username` or `/flag @username`. 

We are working on fixing it so that following format will work.- `/flag @username`

**Comment by jaapbakker88** [comment]
@siddharthJadhav this issue should be fix. Remember that the flag actions works on messages not users. /mute and /ban should work.
