### ISSUE TITLE
bug: User is not able to delete giphy message

### ISSUE THREAD

**Issue by habrahamyanmabbly** [GetStream/stream-chat-react#2053]
**Describe the bug**

User is not able to delete giphy message

**To Reproduce**

1. Create giphy message
2. Click on ellipsis menu on the giphy message
3. Click Delete message
4. Refresh the page or re-open chat

**Expected behavior**
- Message is with GIF applied to it deleted

**Screenshots**

**Package version**
- "stream-chat": "^8.1.0",
- "stream-chat-react": "^10.4.0",
- "getstream": "^8.1.0",

**Desktop (please complete the following information):**

- All Browsers

**Additional context**
[Download link of the video](https://api.media.atlassian.com/file/3c7fdeb3-dc39-4697-80b5-9db8d88d44ea/artifact/video_1280.mp4/binary?client=62e0d669-2bde-4345-90b3-25ead5d8251f&collection=&max-age=2592000&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI2MmUwZDY2OS0yYmRlLTQzNDUtOTBiMy0yNWVhZDVkODI1MWYiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjNjN2ZkZWIzLWRjMzktNDY5Ny04MGI1LTlkYjhkODhkNDRlYSI6WyJyZWFkIl19LCJleHAiOjE2ODkwODYxNDQsIm5iZiI6MTY4OTA4NTI0NH0.0BTANgFb9pD4zf36NcBmCRWrCMIupCKq7edYWBe8mFg)

## The request works fine when delete gif is triggered
<img width="1511" alt="image" src="https://github.com/GetStream/stream-chat-react/assets/105516141/8c86af13-7b9f-4fb3-a94e-45c0f06d477c">

Here is the preview object
```
{
    "message": {
        "id": "<message_id>",
        "text": "",
        "command": "giphy",
        "html": "",
        "type": "deleted",
        "user": {
            "id": "<user_id>",
            "role": "user",
            "created_at": "2022-08-24T22:16:23.777485Z",
            "updated_at": "2023-06-26T08:56:06.588814Z",
            "last_active": "2023-07-11T14:17:33.912744314Z",
            "banned": false,
            "online": true,
            "backend": true,
            "profileIri": "/api/profile_members/122c151d-54c1-4253-8edc-9c963fcf8a1f",
            "profileType": "ProfileMember",
            "roles": [
                "ROLE_MEMBER",
                "ROLE_INVESTOR",
                "ROLE_USER"
            ],
            "profileId": "122c151d-54c1-4253-8edc-9c963fcf8a1f",
            "avatar": "https://dev.assets.tiger21.com/all-uploads/2022-07-31/62e693f2ddc59076948519.png?Expires=1980713661&Signature=Xclq~TpDYCIYUXsnc8VEVvGBMUInZEvCgAlu4wuG63SAihvqhwW1-gKJCZ4QZpy4S-wR~X2eml1rpH19kHurvtaZIzYymSQFJzUDnuHqQYqsnVPtCv8gGGS~NIZsBBmTwOskueSTTKpR3PvaL~7v2DWmqOmcojm0eHNo2mOkJhRQ3OgprTmZeC09~V0CoYbbbO1P5Hn3v~0wdzhP2hJuKOsMmxW89YRtWjYF2fTBxAOpEz0MSf5czuprSa8T~1nkxP-geiGDjQ8NDe8C-xlIKuXHixUyFsvRV33lYLkZlDsGrYUpr83FcUHtb22CUfHNQvlbdEpEa1Bs8AcnHZZxLg__&Key-Pair-Id=KUO0XOOETMAH0",
            "name": "Hrant Abrahamyan",
            "userId": "d384b792-6b1e-4fce-9294-477001032481",
            "userIri": "/api/users/d384b792-6b1e-4fce-9294-477001032481"
        },
        "attachments": [
            {
                "type": "giphy",
                "title": "test",
                "title_link": "https://giphy.com/gifs/school-test-yeah-8RczH5vL2k7Ju",
                "thumb_url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/giphy.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=giphy.gif&ct=g",
                "giphy": {
                    "original": {
                        "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/giphy.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=giphy.gif&ct=g",
                        "width": "245",
                        "height": "153",
                        "size": "996473",
                        "frames": "35"
                    },
                    "fixed_height": {
                        "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200.gif&ct=g",
                        "width": "320",
                        "height": "200",
                        "size": "1509264",
                        "frames": ""
                    },
                    "fixed_height_still": {
                        "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200_s.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200_s.gif&ct=g",
                        "width": "320",
                        "height": "200",
                        "size": "37183",
                        "frames": ""
                    },
                    "fixed_height_downsampled": {
                        "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200_d.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200_d.gif&ct=g",
                        "width": "320",
                        "height": "200",
                        "size": "268421",
                        "frames": ""
                    },
                    "fixed_width": {
                        "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200w.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200w.gif&ct=g",
                        "width": "200",
                        "height": "125",
                        "size": "629565",
                        "frames": ""
                    },
                    "fixed_width_still": {
                        "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200w_s.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200w_s.gif&ct=g",
                        "width": "200",
                        "height": "125",
                        "size": "18138",
                        "frames": ""
                    },
                    "fixed_width_downsampled": {
                        "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200w_d.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200w_d.gif&ct=g",
                        "width": "200",
                        "height": "125",
                        "size": "116207",
                        "frames": ""
                    }
                }
            }
        ],
        "latest_reactions": [],
        "own_reactions": [],
        "reaction_counts": {},
        "reaction_scores": {},
        "reply_count": 0,
        "cid": "messaging:1688677863716",
        "created_at": "2023-07-11T14:30:40.270128Z",
        "updated_at": "2023-07-11T14:30:40.27015Z",
        "deleted_at": "2023-07-11T14:30:44.252543481Z",
        "shadowed": false,
        "mentioned_users": [],
        "silent": false,
        "pinned": false,
        "pinned_at": null,
        "pinned_by": null,
        "pin_expires": null,
        "command_info": {
            "name": "Giphy"
        },
        "args": "test"
    },
    "duration": "15.06ms"
}
```

**Comment by habrahamyanmabbly** [comment]
> **Describe the bug**
> 
> User is not able to delete giphy message
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Create giphy message
> 2. Click on ellipsis menu on the giphy message
> 3. Click Delete message
> 4. Refresh the page or re-open chat
> 
> **Expected behavior**
> 
> * Message is with GIF applied to it deleted
> 
> **Screenshots**
> 
> If applicable, add screenshots to help explain your problem.
> 
> **Package version**
> 
> * "stream-chat": "^8.1.0",
> * "stream-chat-react": "^10.4.0",
> * "getstream": "^8.1.0",
> 
> **Desktop (please complete the following information):**
> 
> * All Browsers
> 
> **Additional context** [Download link of the video](https://api.media.atlassian.com/file/3c7fdeb3-dc39-4697-80b5-9db8d88d44ea/artifact/video_1280.mp4/binary?client=62e0d669-2bde-4345-90b3-25ead5d8251f&collection=&max-age=2592000&token=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI2MmUwZDY2OS0yYmRlLTQzNDUtOTBiMy0yNWVhZDVkODI1MWYiLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjNjN2ZkZWIzLWRjMzktNDY5Ny04MGI1LTlkYjhkODhkNDRlYSI6WyJyZWFkIl19LCJleHAiOjE2ODkwODYxNDQsIm5iZiI6MTY4OTA4NTI0NH0.0BTANgFb9pD4zf36NcBmCRWrCMIupCKq7edYWBe8mFg)
> 
> ## The request works fine when delete gif is triggered
> <img alt="image" width="1511" src="https://user-images.githubusercontent.com/105516141/252696956-8c86af13-7b9f-4fb3-a94e-45c0f06d477c.png">
> Here is the preview object
> 
> ```
> {
>     "message": {
>         "id": "U--hrant_abrahamyan-aOElIGXp8DVnIwnMD3Y0A",
>         "text": "",
>         "command": "giphy",
>         "html": "",
>         "type": "deleted",
>         "user": {
>             "id": "U--hrant_abrahamyan",
>             "role": "user",
>             "created_at": "2022-08-24T22:16:23.777485Z",
>             "updated_at": "2023-06-26T08:56:06.588814Z",
>             "last_active": "2023-07-11T14:17:33.912744314Z",
>             "banned": false,
>             "online": true,
>             "backend": true,
>             "profileIri": "/api/profile_members/122c151d-54c1-4253-8edc-9c963fcf8a1f",
>             "profileType": "ProfileMember",
>             "roles": [
>                 "ROLE_MEMBER",
>                 "ROLE_INVESTOR",
>                 "ROLE_USER"
>             ],
>             "profileId": "122c151d-54c1-4253-8edc-9c963fcf8a1f",
>             "avatar": "https://dev.assets.tiger21.com/all-uploads/2022-07-31/62e693f2ddc59076948519.png?Expires=1980713661&Signature=Xclq~TpDYCIYUXsnc8VEVvGBMUInZEvCgAlu4wuG63SAihvqhwW1-gKJCZ4QZpy4S-wR~X2eml1rpH19kHurvtaZIzYymSQFJzUDnuHqQYqsnVPtCv8gGGS~NIZsBBmTwOskueSTTKpR3PvaL~7v2DWmqOmcojm0eHNo2mOkJhRQ3OgprTmZeC09~V0CoYbbbO1P5Hn3v~0wdzhP2hJuKOsMmxW89YRtWjYF2fTBxAOpEz0MSf5czuprSa8T~1nkxP-geiGDjQ8NDe8C-xlIKuXHixUyFsvRV33lYLkZlDsGrYUpr83FcUHtb22CUfHNQvlbdEpEa1Bs8AcnHZZxLg__&Key-Pair-Id=KUO0XOOETMAH0",
>             "name": "Hrant Abrahamyan",
>             "userId": "d384b792-6b1e-4fce-9294-477001032481",
>             "userIri": "/api/users/d384b792-6b1e-4fce-9294-477001032481"
>         },
>         "attachments": [
>             {
>                 "type": "giphy",
>                 "title": "test",
>                 "title_link": "https://giphy.com/gifs/school-test-yeah-8RczH5vL2k7Ju",
>                 "thumb_url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/giphy.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=giphy.gif&ct=g",
>                 "giphy": {
>                     "original": {
>                         "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/giphy.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=giphy.gif&ct=g",
>                         "width": "245",
>                         "height": "153",
>                         "size": "996473",
>                         "frames": "35"
>                     },
>                     "fixed_height": {
>                         "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200.gif&ct=g",
>                         "width": "320",
>                         "height": "200",
>                         "size": "1509264",
>                         "frames": ""
>                     },
>                     "fixed_height_still": {
>                         "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200_s.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200_s.gif&ct=g",
>                         "width": "320",
>                         "height": "200",
>                         "size": "37183",
>                         "frames": ""
>                     },
>                     "fixed_height_downsampled": {
>                         "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200_d.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200_d.gif&ct=g",
>                         "width": "320",
>                         "height": "200",
>                         "size": "268421",
>                         "frames": ""
>                     },
>                     "fixed_width": {
>                         "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200w.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200w.gif&ct=g",
>                         "width": "200",
>                         "height": "125",
>                         "size": "629565",
>                         "frames": ""
>                     },
>                     "fixed_width_still": {
>                         "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200w_s.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200w_s.gif&ct=g",
>                         "width": "200",
>                         "height": "125",
>                         "size": "18138",
>                         "frames": ""
>                     },
>                     "fixed_width_downsampled": {
>                         "url": "https://media4.giphy.com/media/8RczH5vL2k7Ju/200w_d.gif?cid=c4b03675sluwvt1ui0jpy2vlf9xfopscghauz7e56e9saepy&ep=v1_gifs_search&rid=200w_d.gif&ct=g",
>                         "width": "200",
>                         "height": "125",
>                         "size": "116207",
>                         "frames": ""
>                     }
>                 }
>             }
>         ],
>         "latest_reactions": [],
>         "own_reactions": [],
>         "reaction_counts": {},
>         "reaction_scores": {},
>         "reply_count": 0,
>         "cid": "messaging:1688677863716",
>         "created_at": "2023-07-11T14:30:40.270128Z",
>         "updated_at": "2023-07-11T14:30:40.27015Z",
>         "deleted_at": "2023-07-11T14:30:44.252543481Z",
>         "shadowed": false,
>         "mentioned_users": [],
>         "silent": false,
>         "pinned": false,
>         "pinned_at": null,
>         "pinned_by": null,
>         "pin_expires": null,
>         "command_info": {
>             "name": "Giphy"
>         },
>         "args": "test"
>     },
>     "duration": "15.06ms"
> }
> ```

**Comment by MartinCupela** [comment]
@habrahamyanmabbly the issue should be fixed now. Could you please confirm whether you keep observing the problem? Thank you

**Comment by MartinCupela** [comment]
Closing the issue as solved.

**Comment by habrahamyanmabbly** [comment]
@MartinCupela The issue was fixed before, now it is still reproducible.

**Comment by DmitriyNikolenko** [comment]
The same for me, looks like it is a floating one, but in most cases, after removing a Giphy message it returns after refreshing the channel.

**Comment by therajumandapati** [comment]
@MartinCupela Can you re-open the ticket as we are currently actively encountering this issue?
