### ISSUE TITLE
Getting multiple time message.new event

### ISSUE THREAD

**Issue by siddharthJadhav** [GetStream/stream-chat-react#206]
Hello,

I am creating React js PWA using Getstream.

I want to show a push notification when I received a new message. But I got `message.new` event multiple times.

following code I am using to listen to the new message event
`channel.on('message.new', (event) => {
     console.log('new message', event);
  });`

Even I am unsubscribing all the event when the component is unmounted
`componentWillUnmount () {
      channel.off();
    }`

**Comment by siddharthJadhav** [comment]
any update?

**Comment by vishalnarkhede** [comment]
Hey @siddharthJadhav you got the multiple events for same message? Could you please paste here the event log with message id?

**Comment by siddharthJadhav** [comment]
@vishalnarkhede  Yes, I got the same message multiple times. 

Following the response, I got multiple time

`{
  "type": "message.new",
  "cid": "messaging:!members-ePKcufQ5heJ_bE9xoNmIszTgKwNA7OKl-u5_VrDofqk",
  "message": {
    "id": "1017-6d01824d-658f-4c27-ada8-825b6248d515",
    "text": "hiii",
    "html": "<p>hiii</p>\n",
    "type": "regular",
    "user": {
      "id": "1017",
      "role": "user",
      "created_at": "2020-03-16T05:24:50.15297Z",
      "updated_at": "2020-04-14T04:47:58.859669Z",
      "last_active": "2020-04-14T04:47:58.857052Z",
      "banned": false,
      "online": true,
      "image": "",
      "name": "SIDDHARTH ARORA"
    },
    "attachments": [],
    "latest_reactions": [],
    "own_reactions": [],
    "reaction_counts": null,
    "reaction_scores": {},
    "reply_count": 0,
    "created_at": "2020-04-14T04:48:45.442Z",
    "updated_at": "2020-04-14T04:48:45.442Z",
    "mentioned_users": [],
    "__html": "<p>hiii</p>\n",
    "status": "received"
  },
  "user": {
    "id": "1017",
    "role": "user",
    "created_at": "2020-03-16T05:24:50.15297Z",
    "updated_at": "2020-04-14T04:47:58.859669Z",
    "last_active": "2020-04-14T04:47:58.857052Z",
    "banned": false,
    "online": true,
    "image": "",
    "name": "SIDDHARTH ARORA"
  },
  "watcher_count": 1,
  "created_at": "2020-04-14T04:48:45.454266433Z",
  "total_unread_count": 0,
  "unread_channels": 0,
  "unread_count": 0,
  "received_at": "2020-04-14T04:48:44.511Z"
}`

**Comment by vishalnarkhede** [comment]
@siddharthJadhav I can't think of any reason why this should happen. Can you please share your code? Feel free to post it here in comment or send it to support@getstream.io

**Comment by siddharthJadhav** [comment]
@vishalnarkhede  Bellow is my channel preview component where I get multiple notifications

import React, { Component } from 'react';
import "./MyChannelPreview.css";
export class MyChannelPreview extends Component { 

   constructor(props){
      super(props);

      this.state = {
        name: this.props.channel.data.name,
        lastMeaasge: this.props.latestMessage,
        unreadCount: unreadCount,
        activeChannel: props.activeChannel
      }
      this.listenToChanges();
    }

    listenToChanges() {
      const {channel} = this.props;

      channel.on('message.new', (event) => {
        console.log('message event : ' , event);
          this.setState({
            lastMeaasge: event.message.text,
            unreadCount: channel.countUnread()
          });
        });

        channel.on('message.read', (event) => {
          console.log('message event read : ' , event);
            this.setState({
              unreadCount: channel.countUnread();
            });
          });
    }


    render() {
        return (
        <div >
          <button className="str-chat__channel-preview-messenger str-chat__channel-preview-messenger--unread">
            <div className="str-chat__channel-preview-messenger--left">
                <div className="img-placeholder">
                </div>
             </div>
            <div className="str-chat__channel-preview-messenger--right username-lable">
              <div className="str-chat__channel-preview-messenger--name">
                <span className="wrap-text">{this.state.name}</span> 
                <span className="dot">{this.state.unreadCount}</span>;
              </div>
              <div className="str-chat__channel-preview-messenger--last-message">{this.state.lastMeaasge}</div>
            </div>
          </button>
        </div>
      );
    }
  }


also, I am trying to unsubscribe the event 
`channel.off()`
But it is not working.

**Comment by ilionic** [comment]
Came across this as well, but Typescript was helpful indicating: 
```
TS2554: Expected 1-2 arguments, but got 0.  
index.d.ts(429, 7): An argument for 'callback' was not provided.
```
So `channel.off()` wasn't working and expecting to pass event name and callback. 
Works fine after that. CC @siddharthJadhav

**Comment by vishalnarkhede** [comment]
Thanks @ilionic . That makes sense, I missed this part from the code that @siddharthJadhav mentioned here.

@siddharthJadhav you need to use `channel.off('message.new')` instead of `channel.off()` while unsubscribing.

Hopefully that will solve the issue :)

**Comment by siddharthJadhav** [comment]
@vishalnarkhede  Thnank you. Its work.
