### ISSUE TITLE
bug: hex color as className in LoadingIndicator

### ISSUE THREAD

**Issue by alexander-teemyco** [GetStream/stream-chat-react#2071]
**Describe the bug**

https://github.com/GetStream/stream-chat-react/blob/d26f025603575f025127b55b075fad4c747952bf/src/components/Loading/LoadingIndicator.tsx#L11-L15

`'#006CFF'` is incorrect className
Why `color` is used as className?

**To Reproduce**

Source code

**Expected behavior**

**Package version**
- stream-chat-react: 10.8.8
- stream-chat-css: 3.10.3
- stream-chat-js: 8.10.1

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by sreenathkumar** [comment]
I think there is no reason to use the hexcode as a `className.` It's a bug

**Comment by oliverlaz** [comment]
hi @alexander-teemyco, @sreenathkumar thanks for catching this. 
This is indeed a bug. We will take care of this in one of our upcoming releases.
cc: @MartinCupela
