### ISSUE TITLE
Scroll to specific message/position

### ISSUE THREAD

**Issue by DmitriyNikolenko** [GetStream/stream-chat-react#2077]
**Motivation**
There are a couple of cases:
 1) A user leaves the page for some settings page, returns back and wants to stay on the same scroll position (preserve scroll)
 2) Some message in the chat is shared with a user and he wants to open it. The channel should be loaded and scrolled to the target message.

**Proposed solution**
Provide the ability to scroll to a specific message OR scroll position.

**Acceptance Criteria**
A user is able to open a list of channel messages in the same position when he stopped watching.
A user is able to be scrolled to a specific message when he opens a channel.

**Comment by MartinCupela** [comment]
@DmitriyNikolenko Thank you for raising this request. We register it in our backlog for now.

**Comment by therajumandapati** [comment]
@MartinCupela We're happy to make a PR to support this feature if you could point us in the right direction.

**Comment by MartinCupela** [comment]
This can be solved with [`jumpToMessage`](https://getstream.io/chat/docs/sdk/react/components/contexts/channel_action_context/#jumptomessage), [`jumpToLatestMessage`](https://getstream.io/chat/docs/sdk/react/components/contexts/channel_action_context/#jumptolatestmessage), [`jumpToFirstUnreadMessage`](https://getstream.io/chat/docs/sdk/react/components/contexts/channel_action_context/#jumptofirstunreadmessage). These function are exposed via `ChannelActionContext`. The reference to message id can be take from the URL or localStorage or sessionStorage, etc.
