### ISSUE TITLE
Combined queries using '$or' ignoring different permissions for different types

### ISSUE THREAD

**Issue by charltongroves** [GetStream/stream-chat-react#208]
Hey,

I have a page that queries all channels for a user, the query looks like this
```
{
  $or: [
    {
	  type: 'messaging',
      members: { $in: [String(chatUser.chatId)] },
    },
    {
      $or: [
        {
          type: 'noticeBoard',
          organisation: chatUser.organisationUuid,
        },
        {
          type: 'public',
          organisation: chatUser.organisationUuid,
        },
      ],
    },
  ],
}
```

type noticeBoard and public have permissions set up so that even if the user is not in the channels, they can still see them (ie, ReadChannel)

however, when combined like this in a query, it is only showing the noticeboard and public channels that they have created or are a part of (ie, it is not showing the user channels which they should be able to see even though they are not a member of them).

That happens to be exactly the permissions i've set up for the 'messaging' channel type, which does not allow people to read the channel if they are not in it (or didnt create it).

When i change the queries to just the one type, eg
```
{
  type: 'noticeBoard',
  organisation: chatUser.organisationUuid,
}
```
I get exactly what i expect given the permissions.

So i'm guessing there is a bug here where if you do these $or 'type' queries, the permissions get mangled and don't apply correctly. Please fix!

Also for more context, using 1.7.2 of stream-chat, and 0.10.0 of stream-chat-react-native (latest)

The query is being executed using `client.queryChannels()`

**Comment by vishalnarkhede** [comment]
Hey @charltongroves , could you please send your app_id on support@getstream.io? We will investigate and get back to you!!

**Comment by jaapbakker88** [comment]
@charltongroves is this still an issue or did this get resolved in support?
