### ISSUE TITLE
bug: Mobile app receives a push notification despite the "skip_push: true" option in add_member function.

### ISSUE THREAD

**Issue by sanjaydianapps** [GetStream/stream-chat-react#2086]
A mobile app based on stream-chat-react-native receives push notifications even though we send messages with the "skip_push: true" option in add_member. Basically, I do not want to receive a push notification when a user joins the group chat.

`await channel.addMembers(membersList, undefined, {
                hide_history: true,
                skip_push: true
            })`

**Expected behavior**

A mobile app does not receive a push notification if we add a member with the "skip_push: true" option.

**Package version**
- stream-chat-react: 10.8.5
- stream-chat-react-native: 5.15.3
- stream-chat-js: 8.10.0"

**Comment by Sanjuhub** [comment]
Sorry, this is not an issue. Found the other way around to stop the push notification.

**Comment by MartinCupela** [comment]
Closing the issue as it seems like an integration issue.
