### ISSUE TITLE
Permission denied when trying to push branch for PR

### ISSUE THREAD

**Issue by khanilov** [GetStream/stream-chat-react#209]
> remote: Permission to GetStream/stream-chat-react.git denied.
> fatal: unable to access 'https://github.com/GetStream/stream-chat-react.git/': The requested URL returned error: 403

Is it possible to make a PR for you?
Want to create a little PR for types.

**Comment by ferhatelmas** [comment]
Sure, please make a fork and send a PR from it.

See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request how to do it.
