### ISSUE TITLE
bug: The emoji is not aligned in centre on hovering the emoji.

### ISSUE THREAD

**Issue by piyushpatil4270** [GetStream/stream-chat-react#2094]
**Describe the bug**
In the chat app the emojis are not aligned properly inside the circle.
*Screenrecording:
https://github.com/GetStream/stream-chat-react/assets/126204079/50299c27-23ac-41a9-a79e-185d73e45bdb

To Reproduce

1. Go to the chat
2. Click on the emoji section
3. Hover the emojis

**Expected behavior**
The emojis should be aligned properly inside the circle 

**Package version**
- stream-chat-react:
- stream-chat-css:
- stream-chat-js:

Desktop

Smartphone

**Comment by MartinCupela** [comment]
@piyushpatil4270 thank you for raising this issue. We plan to tackle it in the near future
