### ISSUE TITLE
How to filter channel using channelData?

### ISSUE THREAD

**Issue by Sunil61** [GetStream/stream-chat-react#2102]
Hello,

I want to filter channels using channel-data ID, if channel-data ID is included in channels then it will filter or not as per the result. So I've added the channel-data ID while creating a new channel. I tried some solutions but nothing worked for me. I don't know how to filter that data. Please check the screenshot to get more idea of what I need.

![Screenshot_1 (1)](https://github.com/GetStream/stream-chat-react/assets/95528505/36ef410c-d83c-43d9-9859-e96f9841008b)

I also talked with the support, and he told me that you can filter the metadata available in the message. But I didn't get much.

**Comment by MartinCupela** [comment]
@Sunil61 I recommend to continue the communication over the support channel as this question is not necessarily related to `stream-chat-react`. Please try to explain in the support ticket, why the answers you were given did not work and try to explain steps to reproduce.
