### ISSUE TITLE
breaking changes in version 10.10.0 with polyfills of crypto and path

### ISSUE THREAD

**Issue by balavishnuvj** [GetStream/stream-chat-react#2111]
**Describe the bug**

Building an app using Webpack 5 gives errors for node modules `crypto` and `path`

**To Reproduce**
Error has started from version `10.10.0` and works fine until  `10.9.1`
Clean app with Webpack 5 without nodejs polyfills like `path-browserify` and `crypto-browserify`
Run build `npm run build` or similar

**Expected behavior**

The build should pass without error.

**Additional context**

Related file:
`node_modules/stream-chat-react/dist/index.cjs.js`

line of code

```
...
var crypto = require('crypto');
var uniqBy = require('lodash.uniqby');
var ReactIs = require('react-is');
var path$1 = require('path');
...
```
```
If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

ERROR in ../../node_modules/stream-chat-react/dist/index.cjs.js 40:13-28
Module not found: Error: Can't resolve 'path' in '/Users/balavishnu/Workspace/athena/node_modules/stream-chat-react/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
```

**Comment by MartinCupela** [comment]
@balavishnuvj in this case, you will need to adjust your build process. You can:

1. instruct Webpack to use the ESM build of stream-chat-react
2. instruct Webpack to fall back to `crypto-browserify`

**Comment by balavishnuvj** [comment]
@MartinCupela  
1. It is a much bigger change, we have other libraries which might break because of this.
2. If stream-chat-react uses `crypto-browserify` as a dependency, I would expect that to be part of the package.json. Webpack supports polyfills for legacy reasons, I wouldn't expect newer library versions to rely on that. Browser SDK shouldn't be using node packages like `crypto` and `path` without mentioning them in dependency.

Or this is breaking change, that requires a proper migration path and major release.

**Comment by MartinCupela** [comment]
@balavishnuvj this is a dependency of a dependency. That partucular dependency dropped support for CommonJS recently. We need to keep our deps up-to-date as much as possible. Is there a reason why you cannot adjust your build process to not to use cjs build?

**Comment by MartinCupela** [comment]
I will take a look at the possibility to include the fallback with the build. Still, I recommend to use our esm build

**Comment by MartinCupela** [comment]
@balavishnuvj how do you import the library into your source please? I am wondering, why would webpack use cjs (node build) for browser app.

**Comment by MartinCupela** [comment]
@balavishnuvj please, for now, adjust your webpack configuration as in the example below:

https://github.com/BitGo/BitGoJS/blob/cfacfc9021bfb16a2f532c573729f3597054ccd8/webpack/bitgojs.config.js#L22

**Comment by MartinCupela** [comment]
@balavishnuvj You can now install stream-chat-react@10.13.1. It should fix your issue.
