### ISSUE TITLE
bug: jumpToMessage doesn't work with system messages

### ISSUE THREAD

**Issue by ecemac** [GetStream/stream-chat-react#2114]
**Describe the bug**

I'm not sure if this would count as a bug, but `jumpToMessage` function in `useChannelActionContext` does not work with system messages. I was asked to provide a custom system message when I receive one from the backend, with a custom payload. This system message can also be replied to, and it shows up as a `QuotedMessage` in message list. However when I click on the quoted message with the custom system message, even though it has the correct id, it doesn't jump to the quoted system message.

**To Reproduce**

1. Create a [Custom System Message](https://getstream.io/chat/docs/sdk/react/guides/customization/system_message/)
2. Make it replyable with `setQuotedMessage`
3. Render it in `QuotedMessage`
4. Click the quoted system message

**Expected behavior**

It should jump to quoted system message, like every regular quoted message does.

**Package version**
- stream-chat-react: `10.8.0`
- stream-chat-css: `3.9.1`
- stream-chat-js: `8.6.0`

**Desktop (please complete the following information):**

- OS: Macbook Pro M1
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] `114.0.5735.198`

**Comment by MartinCupela** [comment]
@ecemac thank you for the report. Let us check this out in the upcoming few days.
