### ISSUE TITLE
question: adding a reaction isn't visible until scrolled

### ISSUE THREAD

**Issue by stephenarra** [GetStream/stream-chat-react#2127]
**Describe the bug**

Using the `VirtualizedMessageList` component, it doesn't autoscroll to bottom when the first reaction is added.

**To Reproduce**

1. Go to a demo using `VirtualizedMessageList` (eg. https://getstream.io/chat/demos/livestream/)
2. Add a reaction to the last message
3. Reaction is not visible on screen

**Expected behavior**

The entire message to be visible - it works as expected in the `MessageList`.

**Screenshots**

![Kapture 2023-10-13 at 11 53 16](https://github.com/GetStream/stream-chat-react/assets/5768905/4a14a26c-d2d3-4edf-a61f-329bd388b61a)

**Package version**
- stream-chat-react: v10.14.0

**Desktop (please complete the following information):**

- OS: iOS
- Browser: chrome

**Additional context**

I looked into using the [`autoscrollToBottom` function](https://github.com/GetStream/stream-chat-react/blob/799bfb0eb4139c6e23aa34ec984091e853e3a4c0/docusaurus/docs/React/components/message-components/message-ui.mdx#L166C5-L166C23) in the message context, but it seemed to have no effect.

**Comment by MartinCupela** [comment]
Hello @stephenarra, you can control this behavior by decreasing the threshold, where the list is still considered to be scrolled to the bottom. An example could be:

```
 <VirtualizedMessageList additionalVirtuosoProps={{atBottomThreshold:30}}/>
```
