### ISSUE TITLE
actionsEnabled is not switching from false to true inside thread

### ISSUE THREAD

**Issue by davinchee** [GetStream/stream-chat-react#213]
Hi, I am currently trying to do something once actionsEnabled switches from false to true, however for whatever reason this is not happening inside the thread. It does outside perfectly though.

**Comment by vishalnarkhede** [comment]
@davinchee can you please share a bit of code? Its hard understand the exact issue from the description :)

**Comment by tbarbugli** [comment]
@davinchee ping
