### ISSUE TITLE
bug: `Thread`s 401 upon opening, even though user is authenticated

### ISSUE THREAD

**Issue by jahseng-lee** [GetStream/stream-chat-react#2133]
**Describe the bug**

`Thread`s 401 upon opening, even though user is authenticated

**To Reproduce**

1. Create a channel and invite users
2. Reply in thread to a message
3. Close the thread and reopen
  * doesn't matter if opened by "X replies" or by clicking the "Reply" button
4. No replies show, error in console appears 

User is successfully authenticated using the chat normally, it's only threads that break.

**Expected behavior**

Threads can open without a 401

**Screenshots**
<img width="1438" alt="Screenshot 2023-10-17 at 5 11 12 pm" src="https://github.com/GetStream/stream-chat-react/assets/26918169/b0e439d9-bb4e-4ff3-b3dc-d7587dfd9a0a">
<img width="1006" alt="Screenshot 2023-10-17 at 5 12 08 pm" src="https://github.com/GetStream/stream-chat-react/assets/26918169/f67e1ee3-3729-4052-bd1a-b4ef4d4b6f59">

`{"StatusCode":401,"code":5,"details":[],"duration":"0","message":"GetReplies failed with error: \"stream-auth-type missing or invalid\"","more_info":"https://getstream.io/chat/docs/api_errors_response"}`

**Package version**
- stream-chat-react: 10.14.0
- stream-chat-css: 3.13.0

**Desktop (please complete the following information):**

- OS: MacOS Ventura 13.2
- Browser: Chrome
- Version: 117.0.5938.149

**Additional context**

```jsx
import React, { useState, useEffect } from "react";
import { createRoot } from "react-dom/client";
import { StreamChat } from 'stream-chat';
import {
  Chat as StreamChatComponent,
  Channel,
  ChannelHeader,
  ChannelList,
  MessageList,
  MessageInput,
  Thread,
  Window,
} from 'stream-chat-react';

const rootElement = document.getElementById("chat-root");
const userId = rootElement.dataset.streamUserId;
const displayName = rootElement.dataset.displayName;
const userToken = rootElement.dataset.streamUserToken;

const filters = { type: 'messaging', members: { $in: [userId]} };
const options = { state: true, presence: true };
const sort = { last_message_at: -1 };

const Chat = () => {
  const [client, setClient] = useState(null);

  useEffect(() => {
    const newClient = new StreamChat('s3u4gjg6hnj2');

    const handleConnectionChange = ({ online = false }) => {
      if (!online) return console.log('connection lost');
      setClient(newClient);
    };

    newClient.on('connection.changed', handleConnectionChange);

    newClient.connectUser(
      {
        id: userId,
        name: displayName,
      },
      userToken,
    );

    return () => {
      newClient.off('connection.changed', handleConnectionChange);
      newClient.disconnectUser().then(() => console.log('connection closed'));
    };
  }, []);

  if (!client) return null;

  return (
    <StreamChatComponent client={client}>
      <ChannelList
        showChannelSearch
        additionalChannelSearchProps={{ searchForChannels: true }}
        filters={filters}
        sort={sort}
        options={options} />
      <Channel>
        <Window>
          <ChannelHeader />
          <MessageList
            messageActions={['edit', 'delete', 'flag', 'mute', 'react', 'reply']}
            />
          <MessageInput focus grow />
        </Window>
        <Thread messageActions={['edit', 'delete', 'flag', 'mute', 'react', 'reply']}/>
      </Channel>
    </StreamChatComponent>
  );
}

const root = createRoot(rootElement);
root.render(<Chat />);
```

**Comment by MartinCupela** [comment]
Hey @jahseng-lee the questions, that come to my mind are:

1. What value does the `Stream-Auth-Type` header in the failing request has? 
2. Does the header `Authorization` have a valid value?

This seems like an integration issue. Could you please contact [our support](https://getstream.io/contact/support/)?

Thank you

**Comment by jahseng-lee** [comment]
@MartinCupela I'm using the [React UI Components SDK tutorial](https://getstream.io/chat/docs/sdk/react/) found here.

The only potential weird thing is that my application isn't a React SPA; it's a Rails 7 project that has a React component embedded in the page.

The page rendering React:
```html
    <%= render partial: "layouts/navbar" %>

    <div
        id="chat-root"
        class="chat-root mt-1"
        data-stream-user-id="<%= @stream_user_id %>"
        data-stream-user-token="<%= @stream_user_token %>"
        data-display-name="<%= current_user.display_name %>"
         ></div>
```

Where that secondary `div` is the element React is mounted on. However, this shouldn't affect requests being sent by the client.

**Comment by MartinCupela** [comment]
@jahseng-lee the issue was caused by regression in the dependency [stream-chat](https://github.com/GetStream/stream-chat-js/compare/v8.12.1...v8.12.2). We will be fixing this soon.

**Comment by MartinCupela** [comment]
@jahseng-lee please update your `stream-chat-react` version to [10.14.1](https://github.com/GetStream/stream-chat-react/releases/tag/v10.14.1) and make sure you have installed `stream-chat` version 8.13.1. It includes the fix.
