### ISSUE TITLE
bug: channel.query_members doesn't correctly apply the filter in Ruby client

### ISSUE THREAD

**Issue by jahseng-lee** [GetStream/stream-chat-react#2138]
**Describe the bug**

```
channel.query_members(
  filter_conditions: { id: { "$in" => [user_id] } }
)
```

always returns all members when using the Ruby client.
In this case `user_id = SecureRandom.hex`.

I've used `byebug` to double check a valid `user_id` was sent through in the `filter_conditions` yet I kept seeing a list of all users back.

**To Reproduce**

1. Create 2 users in Stream (I used the API to create users)
2. Use the `filter_conditions: { id: { "$in" => [user_id] } }` in `query_members`
3. Inspect the response

**Expected behavior**

Only the user which matches `user_id` to be returned

**Package version**

- stream-chat-react: 10.14.0
- stream-chat-css: 3.13.0

**Desktop (please complete the following information):**

- OS: MacOS Ventura 13.2
- Browser: Chrome
- Version: 118.0.5993.70

**Additional context**

N/A

**Comment by MartinCupela** [comment]
@jahseng-lee why are you using ruby client in a JS / React application?

**Comment by jahseng-lee** [comment]
sorry @MartinCupela, posted this in the wrong place. Will close an open this issue in the ruby client
