### ISSUE TITLE
question: Passing undefined to messages prop in MessageList

### ISSUE THREAD

**Issue by weiss-dhc** [GetStream/stream-chat-react#2158]
**Describe the bug**

I want to display custom messages sometimes and when I don't, the channel should default to displaying all messages. But when I pass undefined, the channel displays no messages.

**To Reproduce**

1) Have a channel with some messages
2) `<MessageList messages={undefined} />`
3) No messages are displayed

**Expected behavior**

Since this component expects messages or undefined, I would expect that it would default to show all messages.

FYI: <MessageList  /> rendering this shows all messages strangely.

**Info**
- stream-chat-react: "10.13.1"
- stream-chat: "^8.13.0"
- OS: Mac
- Browser Chrome

**Comment by MartinCupela** [comment]
Hello @weiss-dhc, passing undefined to the `messages` prop leads to overwriting the messages array, that is taken from the channel state. If you want to pass the messages through the `MessageList`'s props `messages`, then you have to handle the messages state in your app.

Please provide more information about the logic of displaying custom messages. What are the custom messages? Where are they taken from etc.

**Comment by weiss-dhc** [comment]
Hello @MartinCupela and thank you for engaging. 
Sure, I can explain what I am trying to achieve: I would love to have some kind of message search. For this I created an input and something like this:
```
const search = await chatClient.search(filters, messageSearch, {
  limit: 50,
  offset: 0,
});
```

Then I use the results as custom messages.

Is there maybe a better way? Ideally I could just highlight the results from all the messages? Thank you very much!

**Comment by MartinCupela** [comment]
Hey @weiss-dhc this would be my approach:

```
        <Channel channel={streamChannel}>
          <Container>
            {messages ? (
              <MessageList messages={messages} Message={CustomMessageUI} />
            ) : (
              <MessageList />
            )}
            <MessageInput />
          </Container>
        </Channel>
```

```
const CustomMessage = (props: MessageUIComponentProps) => {
  return (
        <MessageBackground key={i} active={i === searchIndex}>
          <Message {...props} />
        </MessageBackground>
  };
}
```

**Comment by weiss-dhc** [comment]
Thank you @MartinCupela. I am going to use that. Great way to customise and keep some functionality of the MessageList.

Closing this issue 👍

**Comment by weiss-dhc** [comment]
Sorry to bother again, but do you happen to know how I can pass my props to the custom message component @MartinCupela ?

I have done it like this now:
```
{messages ? (
              <MessageList
                messages={messages}
                Message={(props) => (
                  <CustomMessageUI
                    {...props}
                    searchIndex={searchIndex}
                    i={messages.findIndex((m) =>
                      props.message ? m.id === props.message.id : -1,
                    )}
                  />
                )}
              />
            ) : (
              <MessageList />
            )}
```

But it seems that I don't get any props like this. This is my CustomMessageUI:

```
type Props = MessageUIComponentProps & {
  searchIndex: number;
  i: number;
};

const CustomMessageUI = ({ searchIndex, i, message, ...props }: Props) => {
  console.log(props, message);
  if (!message) return null;

  return (
    <MessageBackground active={i === searchIndex}>
      <Message {...props} message={message} />
    </MessageBackground>
  );
};
```

The console.log returns: `{groupedByUser: undefined} undefined`
