### ISSUE TITLE
bug: Message Notification display wrong place when edit

### ISSUE THREAD

**Issue by minhth-1529** [GetStream/stream-chat-react#2160]
**Describe the bug**

Press key Enter before attachment finish uploading. Notification display wrong place.

**To Reproduce**

1. Add attachment
2. When file uploading press Enter key aim to show warning notification

**Expected behavior**

Notification have to show in Edit Input

**Screenshots**

https://github.com/GetStream/stream-chat-react/assets/17897146/266e2585-52ab-4cfd-8b5e-361d678d9ab0

![Screenshot 2023-11-07 at 11 33 26 AM](https://github.com/GetStream/stream-chat-react/assets/17897146/8f51182c-5ec4-4e87-a1c4-5f87afda76b2)

**Package version**
- stream-chat-react: 10.16.2
- stream-chat-css: 3.14.1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
@minhth-1529 thank you for the report. We plan to do overhaul for notifications system as it does not make much sense to show them only for that single message input. This is a breaking change that will not be released in short term. Looks like this specific case can be solved with z-index. 

<img width="928" alt="image" src="https://github.com/GetStream/stream-chat-react/assets/32706194/59123ecf-78cb-41c4-8a94-7d229b39a733">
