### ISSUE TITLE
Question: Using default Emojis with Expo web

### ISSUE THREAD

**Issue by weiss-dhc** [GetStream/stream-chat-react#2162]
Hello,

We have a chat with the default emojis. When developing locally I see that the emojis are getting loaded, as soon as I press on the emoji button the first time. It works, I can use them perfectly.

But when I now bundle the expo app for web and serve the bundle files, the app crashes doing the same thing. The emojis don't load in but the module is not found with the following error message:

![Screenshot 2023-11-07 at 16 38 11](https://github.com/GetStream/stream-chat-react/assets/138571746/70e02a23-721e-48df-b106-e7e608243af9)

My question is: What do I need to do, in order to use the Emojis also in a bundled version of the app?

Thank you!

**Comment by MartinCupela** [comment]
@weiss-dhc this is a question on how to use expo bundler probably. This is not related to the SDK itself. Have you tried another bundler?

**Comment by MartinCupela** [comment]
Closing the issue for inactivity.
