### ISSUE TITLE
Fetch all channels with unread messages

### ISSUE THREAD

**Issue by mariano-ramonda** [GetStream/stream-chat-react#2163]
**Motivation**
I'm building a chat app using the React SDK.
I'm using `ChannelList` two times, for different channel types.
In both cases: `const sort: ChannelSort = { has_unread: -1 };`, so channels with unread messages come first.
I'm also using: `const options: ChannelOptions = { watch: true, state: true, limit: 30 };`, where 30 is the max value for `limit`.
The issue is, if there are more than 30 channels with unread messages, those are not shown to the user when the app loads.
I could not find a neat way to achieve this by using the SDK components.
I'm using `InfiniteScroll` as well, which props have `loadNextPage`, that could be used in case all the first 30 channels have unread messages, but there's no way to implement such thing seamlessly.

**Proposed solution**
Add a boolean value in `options` so it can be requested to `ChannelList` to retrieve all the channels with unread messages on the initial channels load.
Let's call this option `getAllUnreadInitially`, which when it's set to `true`, it should imply `const sort: ChannelSort = { has_unread: -1, ... };`. Its default could be `false`.

**Acceptance Criteria**
When `ChannelList` initially loads the channels with `getAllUnreadInitially` as `true`, all the channels with unread messages should be retrieved.

**Comment by MartinCupela** [comment]
@mariano-ramonda the limit 30 channels per page is the upper bound for a single request. You can listen to `channels.queried` event (`client.on('channels.queried', callback)`) that is emitted after each successful channels query and keep paginating until you are satisfied. Of course, you will have to unsubscribe after the first page is loaded (after the first event is emitted).
