### ISSUE TITLE
bug: MessageList becomes empty when the user stops to scroll

### ISSUE THREAD

**Issue by dbogdanov-a** [GetStream/stream-chat-react#2164]
**Describe the bug**

When the user scrolls up and stops scrolling at some point (when needs to load more messages), the message list becomes empty.

**To Reproduce**

1. Go to https://getstream.io/chat/demos/messaging/
2. Scroll up to load prev. message (scroll bar at top of messages)
3. Stop scrolling somewhere between current messages and prev. that needs to be loaded
4. The user sees a blank screen

**Expected behavior**
User sees Messages

**Screenshots**

![photo_2023-11-08_01-13-22](https://github.com/GetStream/stream-chat-react/assets/119883323/17ce41c8-b027-4d54-ad10-f9b7df2773c9)

**Package version**
- stream-chat-react: 10.10.0 (we use, and at your example issue also reproducible)
- stream-chat: 8.11.0 (JS SDK for the Stream Chat API)

**Desktop (please complete the following information):**

Was not able to reproduce

**Smartphone (please complete the following information):**

- Device: iPhone 14 Pro
- OS: iOS 17.0.3
- Browser Safari / PWA (our app)

**Additional context**
See screenshot and video (sorry for music, I was listening to the radio during recording and didn't know that it would be also recorded)
Video recording was compressed due to load limitations.

When the scroll bar is at the top ( basically needs to load more messages ) and user at the moment stops to scroll up, messages disappear and the new one is not shown until you continue to scroll

1. From the 0 sec
https://github.com/GetStream/stream-chat-react/assets/119883323/ee2f0a68-a759-4201-bc05-b9e637f7f51c

2. From 40 sec to end
https://github.com/GetStream/stream-chat-react/assets/119883323/d10c1672-3a3c-4e4a-a5d8-5541f7c0fff4

**Comment by MartinCupela** [comment]
@dbogdanov-a thank you for reporting the issue. We aim to solve it with this PR:

https://github.com/GetStream/stream-chat-css/pull/248

**Comment by dbogdanov-a** [comment]
@MartinCupela, We're still reproducing the issue at Mac OS at Safari with the latest versions

"stream-chat": "8.16.0"
"stream-chat-react": "11.9.0"

+ I see the same https://getstream.io/chat/demos/messaging/ 

Regards,
Dmytro
