### ISSUE TITLE
customActiveChannel value not respected when search returns 0 channels

### ISSUE THREAD

**Issue by jkjustjoshing** [GetStream/stream-chat-react#2167]
I'm setting a `customActiveChannel` value on a `<ChannelList>` component. I'm also setting a filter that on first load returns 0 channels. However, the `customActiveChannel` is a channel that is (obviously) not returned in the list on first load.

Due to [this line](https://github.com/GetStream/stream-chat-react/blob/8603818312262f6fa1804ce08adf4caa897763d8/src/components/ChannelList/ChannelList.tsx#L209), my `customActiveChannel` is not being respected.

`if (!channel.length) return null` should be removed (or otherwise modified to work for my situation).

**Comment by MartinCupela** [comment]
@jkjustjoshing thank you for the report. What is the reason for triggering a channels query that does not return any channels? Why the query filters do not include the custom channel ID already?

**Comment by jkjustjoshing** [comment]
I am building a sidebar in my application to show the ChannelList. It has 2 sections - "All Messages" and "Pinned". A channel's "pinned" status is stored on a custom property on the chat object - an array of user IDs who have the channel pinned.

```
{
    type: 'messaging',
    id: 'channel-id-1',
    ...
    pinned: ['user-id-1', 'user-id-3']
}
```

The query for the "Pinned" filter view is

```
{
    "filter_conditions":{
        "pinned":{
            "$contains": loggedInUserId
        }
    }
}
```

Our application's routing is https://localhost:3000/chat/<channelId>. So if the page loads with a channelID in the URL, but the channel in question isn't pinned, and the user has 0 items pinned, then the channel query will return 0 items, but the active channel still needs to be set.

I was able to instead call `setActiveChannel` explicitly instead of relying on `customActiveChannel` prop on `ChannelList`. But it still seems weird that `customActiveChannel` doesn't work when an empty channel query comes back.
Feel free to close this ticket, I've solved my problem with this other method.

![image](https://github.com/GetStream/stream-chat-react/assets/813192/e8990c10-f59b-4224-8d75-a0358fb013fd)

**Comment by MartinCupela** [comment]
Hey @jkjustjoshing what come to my mind is:

If the user arrives to the url `https://localhost:3000/chat/channel_id_1`, can you redirect to `https://localhost:3000/chat` so that all the channels are loaded? In my opinion it could be confusing to be at URL `https://localhost:3000/chat/channel_id_1` and as the channel id does not meet the criteria, show a different channel in the UI at the same URL. In case the channel does not exist, then I would recommend to redirect to relevant URL. What are your thoughts on this?

**Comment by jkjustjoshing** [comment]
We need our users to be able to share URLs directly to channels in our UI, so the most important thing is if there is a channel ID in the URL that that channel gets loaded. It's ok if it doesn't show up in the channel list.

I came up with a workaround that involves calling `setActiveChannel()` directly on first render and not using `customActiveChannel` at all.
