### ISSUE TITLE
Edit quoted message not updating immediately

### ISSUE THREAD

**Issue by minhth-1529** [GetStream/stream-chat-react#2168]
**Describe the bug**

Mr.A: 1111111
Mr.B: quote (11111) 22222222

Edit Mr.A message to 333333 but Mr.B: (11111) 22222222 still 11111

**To Reproduce**

https://github.com/GetStream/stream-chat-react/assets/17897146/2320687e-0493-46b7-8e49-3c79a98b4f5a

**Expected behavior**

**Screenshots**

**Package version**
- stream-chat-react:
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
@minhth-1529 thank you for the report. We are aware of this limitation and we plan to solve it in the future.

**Comment by minhth-1529** [comment]
@MartinCupela Thank you so much!
