### ISSUE TITLE
Channel's "watchers" is empty even if "watchers_count" is more than 0

### ISSUE THREAD

**Issue by iamacatperson** [GetStream/stream-chat-react#217]
This is related to the issue I posted last time at: #207 

I have the same code as per the last amendments on the above issue. However, this time I am looking at the channel's "watchers" attribute because I realised I cannot just query the users as it will show all 'online' users regardless of which channel they're at. I need to know the users watching a particular channel.

As you can see below, it detects that there are 3 watchers in the channel but the "watchers" attribute doesn't show this list of 3 watchers.

![Screenshot 2020-04-21 at 1 31 16 PM](https://user-images.githubusercontent.com/3748487/79829156-f2eac900-83d4-11ea-9103-537df028e2c5.png)

Again, this is the channel initialisation code I have:

```
async componentDidMount() {
    const user = // user object //

    const chatClient = new StreamChat(envs.STREAM_API_KEY);

    await chatClient.setUser(
      {
        id: user.id,
        name: user.name
      },
      OUR_STREAM_TOKEN
    );

    const channel = chatClient.channel("livestream", STREAM_CHANNEL_ID);

    await channel.watch();

    this.setState(
      {
        chatClient,
        channel
      }
    );
  }
```

Why doesn't it tally?

**Comment by vishalnarkhede** [comment]
Hey @iamacatperson you will explicitly need to request for watchers.

`channel.watch{ watchers:{ limit:10 }}`

Example given here - https://getstream.io/chat/docs/channel_pagination/?language=js

**Comment by iamacatperson** [comment]
@vishalnarkhede Okay thanks that works, however when I increase the offset value to more than `0`, the watchers array is not returned. 

Like here, I created another function to query the list of watchers like so:

```
  getWatchers = async () => {
    const result = await this.state.channel.query({
      watchers: {
        limit: 2,
        offset: 0
      }
    });
    console.log(result);
    this.setState({ watchers: result.watchers });
  };
```
Just to test, I hardcoded the `limit` and `offset` values first. At this time there are 4 watchers in the channel. If I change the limit (and keep offset to `0`), the response returns the correct no. of watchers as per the limit count. However, when I change the offset to e.g. `1` or `2`, then the response no longer returns any watchers. E.g. 4 watchers, limit 2, offset 1 - this should return 2 watchers (last 2). But query doesn't return anything at all.

**Comment by vishalnarkhede** [comment]
Hey @iamacatperson looks like there is an issue with watcher's pagination. I will check with out backend team on some estimate regarding when it can be fixed and get back to you. Is it a complete blocker for you?

**Comment by iamacatperson** [comment]
@vishalnarkhede It's not a complete blocker for now (I can use the old method first) but hopefully, it can be fixed soon. Thank you!

**Comment by iamacatperson** [comment]
@vishalnarkhede Is there any estimate when it will be fixed though?

**Comment by dashawk** [comment]
@vishalnarkhede I have the same issue on this.

Here is some code snippet that I use to query the watchers.
```javascript
const result = await channel.query({
   watchers: { limit: 20, offset: 0 }, // This one works perfectly
});
```
Which returns this:
![image](https://user-images.githubusercontent.com/1437205/87512377-77ce4180-c6a9-11ea-9d23-8c12eafa9add.png)

And when I set the offset to a specific value example `3`:
```javascript
const result = await channel.query({
   watchers: { limit: 20, offset: 3 }, // This breaks everything!
});
```

Which returns this:
![image](https://user-images.githubusercontent.com/1437205/87512516-bc59dd00-c6a9-11ea-8123-fee2f375ce7d.png)

As you can see in the second screenshot, the `watchers` array is missing which I need to be displayed in my list of watchers.

We need a fix for this ASAP.

**Comment by jaapbakker88** [comment]
@dashawk @iamacatperson this should have been resolved on our backend, I'm going to close the issue. Please let us know if anything else comes up.
