### ISSUE TITLE
bug: User get message after some time.

### ISSUE THREAD

**Issue by krushita042023** [GetStream/stream-chat-react#2176]
**Describe the bug**

Some time web user get message after some time and the messages don't show immediately

**Comment by MartinCupela** [comment]
@krushita042023 unfortunately your report does not mention any details that could help us understand the nature of the issue. As this seems rather as an integration issue, we would like to ask you to contact our support team via our website: https://getstream.io/contact/support. Thank you

**Comment by krushita042023** [comment]
![283250479-95e8e119-26b4-4f7e-951e-0599e3d7f5f1 blure](https://github.com/GetStream/stream-chat-react/assets/129855948/c7e8f415-d1da-46a1-ab9a-25de21f91d0d)
