### ISSUE TITLE
bug:User get message after some time.

### ISSUE THREAD

**Issue by krushita042023** [GetStream/stream-chat-react#2178]
Some time web user get message after some time and the messages don't show immediately.

![283250479-95e8e119-26b4-4f7e-951e-0599e3d7f5f1 blure](https://github.com/GetStream/stream-chat-react/assets/129855948/c0397c3d-f6cc-45b6-8c6c-44e4ba49b8be)

**Comment by MartinCupela** [comment]
@krushita042023 have you contacted our support team as recommended in the previous issue you have opened? https://getstream.io/contact/support. If you want to report a bug in the SDK, you should provide steps for reproduction. It is impossible to reproduce an issue based on a screenshot. Could you please contact the support team? Thank you.
