### ISSUE TITLE
bug: HEIC File Not Rendered

### ISSUE THREAD

**Issue by tao-qian** [GetStream/stream-chat-react#2182]
**Describe the bug**

We just added the react SDK to our app without any customization, and HEIC images don't seem to be rendered properly. This is also reproducible on https://getstream.io/chat/demos/messaging/.

Here is an [example HEIC URL](https://ohio.stream-io-cdn.com/1266909/images/0c11431c-11a1-4b5a-ab65-4a88a18c7d4e.001?Key-Pair-Id=APKAIHG36VEWPDULE23Q&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9vaGlvLnN0cmVhbS1pby1jZG4uY29tLzEyNjY5MDkvaW1hZ2VzLzBjMTE0MzFjLTExYTEtNGI1YS1hYjY1LTRhODhhMThjN2Q0ZS4wMDE%7EKm9oPTYxMjAqb3c9ODE2MCoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MDE4Mzk2NDF9fX1dfQ__&Signature=LFVxf455nkvrBtypTENFO4K2ujiTa9%7E9ceZ0l7eGoztBTDTLSP4QN2J72smoT3Z6rx-HIaUGbm1leKdQDsT5HuMmCt5gSLynGgQrr7bqd%7E11ND8hTESX0M-qoq066b2jHQ0d0W%7E-NLcxmnH%7ENXBnZw7sKgEEfwo%7EnBulhogpG7yZmIl7fffxhKUBzkJRVBrHGtC818cnaS61cBN7l22lM9qhPTz6oieY8iQcNnLUApzVPPXtmuAUspv0P3nVXVy1nW4mQGAlTsJYFkF52eYywBirI-rTSbpiMXtN-9IuEVDAZwwOr2RyX8CcMEqIkXXupOsuPucHzjwLgHDkMZ9a6w__&oh=6120&ow=8160&h=690&w=1226). This is for a photo that's uploaded to the Stream CDN from a mobile device running an app using the Stream react-native SDK.

**To Reproduce**

1. Go to https://getstream.io/chat/demos/messaging/
2. Upload an heic image
3. It won't be shown in the preview or the channel

**Expected behavior**

**Screenshots**

**Package version**
- stream-chat-react:
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
Hey @tao-qian , thank you for raising the issue. It seems that something may be wrong with the image. We have tested with [another HEIC image](https://us-east.stream-io-cdn.com/1145265/images/730b68f0-86e2-4df4-9585-3d6db9f38926.dwsample-heic-640.heic?Key-Pair-Id=APKAIHG36VEWPDULE23Q&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy1lYXN0LnN0cmVhbS1pby1jZG4uY29tLzExNDUyNjUvaW1hZ2VzLzczMGI2OGYwLTg2ZTItNGRmNC05NTg1LTNkNmRiOWYzODkyNi5kd3NhbXBsZS1oZWljLTY0MC5oZWljPypvaD00Mjgqb3c9NjQwKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMTg2MDYzM319fV19&Signature=XaKVUordJpNdidnmccDICzlzMVEp3v92AANkfGI0njAGrWhAqJM26EPX5Pef33NQpAnhTkJoWoyNpZP5TfM4a61KLIQYaFZ6dsfhZgEvqvF71lHi3uAUGrOcVzN%7EF5A2if-tkznYLx5VYRutrg-cKb2YyBF7nW6o20gpIuNK6to08MQGiHloDqNt4Vy985JPUA18uLKG-0JKhtIcaGVRlPawUFCIabJ3OhagozPr3QnzqbCa-XOl4oL1EkPndBqGiZq3qdckbg%7EtitnABFa3i%7EdiGe-A0rIxdqMlqyNMXHJxRIIcULqAaSVGB-E45LGua-w5uesLLD2dyLGrUm1rRg__&oh=428&ow=640&h=592&w=886). What we plan to do is to introduce a nicer message fallback behavior, when the upload fails.

**Comment by tao-qian** [comment]
> Hey @tao-qian , thank you for raising the issue. It seems that something may be wrong with the image. We have tested with [another HEIC image](https://us-east.stream-io-cdn.com/1145265/images/730b68f0-86e2-4df4-9585-3d6db9f38926.dwsample-heic-640.heic?Key-Pair-Id=APKAIHG36VEWPDULE23Q&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy1lYXN0LnN0cmVhbS1pby1jZG4uY29tLzExNDUyNjUvaW1hZ2VzLzczMGI2OGYwLTg2ZTItNGRmNC05NTg1LTNkNmRiOWYzODkyNi5kd3NhbXBsZS1oZWljLTY0MC5oZWljPypvaD00Mjgqb3c9NjQwKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMTg2MDYzM319fV19&Signature=XaKVUordJpNdidnmccDICzlzMVEp3v92AANkfGI0njAGrWhAqJM26EPX5Pef33NQpAnhTkJoWoyNpZP5TfM4a61KLIQYaFZ6dsfhZgEvqvF71lHi3uAUGrOcVzN%7EF5A2if-tkznYLx5VYRutrg-cKb2YyBF7nW6o20gpIuNK6to08MQGiHloDqNt4Vy985JPUA18uLKG-0JKhtIcaGVRlPawUFCIabJ3OhagozPr3QnzqbCa-XOl4oL1EkPndBqGiZq3qdckbg%7EtitnABFa3i%7EdiGe-A0rIxdqMlqyNMXHJxRIIcULqAaSVGB-E45LGua-w5uesLLD2dyLGrUm1rRg__&oh=428&ow=640&h=592&w=886) and that one worked. What we plan to do is to introduce a nicer message fallback behavior, when the upload fails.

Hi Martin! Do you mind clarifying what you meant by 

> introduce a nicer message fallback behavior, when the upload fails.

I thought this is an issue with the rendering on web, not with the upload of the image. FWIW, the image I shared earlier was uploaded without on mobile, and can also be viewed without problem using the Stream react native SDK. It just doesn't display on the web using the web SDK..

**Comment by MartinCupela** [comment]
I have tested this image with web WhatsApp and Slack, and it does not get display neither. Instead a fallback is rendered.

**Comment by tao-qian** [comment]
> I have tested this image with web WhatsApp and Slack, and it does not get display neither. Instead a fallback is rendered.

That's a fair point. Even though the problem is not fixed, I agree that just rendering a fallback image is an appropriate resolution here. I think we will look into compression during upload, and just rely on the fallback in the cases when the compression doesn't work.

Thanks for looking into this!

**Comment by tao-qian** [comment]
Hi @MartinCupela!

We were just able to test out https://github.com/GetStream/stream-chat-react/pull/2183 after a version update. Overall we found the download button you added super helpful (especially since we couldn't figure out the compression piece I mentioned earlier in the past week), but have some small followup requests. Not sure if I should create a new issue, so I am just commenting on this old one for now. 

Here are the list of things:
- The download button only allows the download of one image. So when the mobile user sends multiple HEIC images (which is always the case for us..), the web user can only download and view one. 
<img width="374" alt="Screenshot 2023-12-08 at 11 44 13 AM" src="https://github.com/GetStream/stream-chat-react/assets/1585623/59643934-b1a9-42ae-b545-c518ec12bf49">

- It would be nice to disable the preview when user clicks on the image, when we know that the image can't be view anyway. Right now the user just sees something like this
<img width="554" alt="Screenshot 2023-12-08 at 11 46 41 AM" src="https://github.com/GetStream/stream-chat-react/assets/1585623/532a5ef9-56d5-4363-acfc-0951ba917b13">

**Comment by MartinCupela** [comment]
Hey @tao-qian I plan to provide the fixes this week.

**Comment by MartinCupela** [comment]
Issues: #2210 #2209

**Comment by minhth-1529** [comment]
Hi @MartinCupela, presently I store my file in other server, not your, when I upload file to my server after that submit to message with HEIC file can not render like above, can you please fix it as well, thank you

**Comment by MartinCupela** [comment]
@minhth-1529 please create a new issue and document the repro steps. Thank you

**Comment by MartinCupela** [comment]
@tao-qian the fixes have been released

**Comment by tao-qian** [comment]
Thank you! We just upgraded and everything seems to be working now!
