### ISSUE TITLE
Enable Individual Reaction Click Handling in ReactionsList

### ISSUE THREAD

**Issue by shroy** [GetStream/stream-chat-react#2206]
**Motivation**
In the current implementation, the `ReactionsList` component does not provide a way to handle click events on the reactions. This limits the ability to customize the behavior of reactions, such as incrementing the count of a reaction when it's clicked, similar to the behavior seen in Slack.

**Proposed solution**
Add an `onReactionClick` prop to the `ReactionsList` component. This prop should accept a function that gets called when a reaction is clicked. The function should receive the type of the clicked reaction as a parameter. This would allow us to handle what happens when a reaction is clicked, providing more flexibility and control over the behavior of reactions.

**Acceptance Criteria**

1. The `ReactionsList` component should accept an `onReactionClick` prop.
2. The `onReactionClick` prop should accept a function.
3. The function should be called when a reaction is clicked.
4. The function should receive the type of the clicked reaction as a parameter.
5. Clicking on a reaction should not cause any errors if the `onReactionClick` prop is not provided.
6. The existing behavior of the `ReactionsList` component should not be affected if the `onReactionClick` prop is not provided.

**Comment by arnautov-anton** [comment]
Hey, @shroy! Thank you for the suggestion but unfortunately we won't be adding such feature to the [`ReactionsList`](https://github.com/GetStream/stream-chat-react/blob/v11.1.1/src/components/Reactions/ReactionsList.tsx) component as it's fairly small and simple and provides "expected" default behavior - if you need to expand on it we'd suggest building your own and replacing it through our component context (`Channel`) as it might be much more feasible for you in the long run in case you decide to adjust it further.
