### ISSUE TITLE
Some jpeg images don't work with server side resizing

### ISSUE THREAD

**Issue by NitinSachdeo** [GetStream/stream-chat-react#2207]
**Describe the bug**
We have found that some images uploaded to the stream CDN aren't resized when requested for. See [example image](https://us-east.stream-io-cdn.com/102254/images/b7dab01c-a21b-43b1-839d-bf1c7ea341e0.Stream-Image-Nov-23.jpg?Key-Pair-Id=APKAIHG36VEWPDULE23Q&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy1lYXN0LnN0cmVhbS1pby1jZG4uY29tLzEwMjI1NC9pbWFnZXMvYjdkYWIwMWMtYTIxYi00M2IxLTgzOWQtYmYxYzdlYTM0MWUwLlN0cmVhbS1JbWFnZS1Ob3YtMjMuanBnPypvaD0xMjMzMSpvdz05MjQ4KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMzI4MzA2NH19fV19&Signature=co8tPar6ORsEZOlX-0acnQbCmytK58C5LIJt33JwB12PgSBMTBdDrTIgkAY6pgx%7Ec3r4GE2K9IR95G7DdgiOrxvgFdRuYCU0R5mz1AZF23RjFsoAnwUPLa5qllbyNq9umwhfSIIr9a7el3HiK500R7Q19d4-78zqoxkSMiiSx0WNbIqKDicSH59EYpUKIQjVQWvqDtqJhDGNVYCW162bMlk6va8F1yNg%7EOzbXYjes1EhggMxTKsqnL8tReS9b4MthFKgNNH-AjRlu%7E1j2h3hwJHQ2TD4A-rouLcE%7EpbRmCrMgeTPqpj3W6q6IGl1LKiEMWeb%7EjyA32T0cWhif6iM9g__&oh=12331&ow=9248&h=790&w=592
) which should be resized on the server before being returned but instead returns the full size ~3mb image. This causes significant performance issues when a single chat contains a lot of these unresizable images.

**To Reproduce**

1. The example image linked above can be downloaded and tried
2. I was able to reproduce it by uploading to the chat at https://getstream.io/chat/demos/messaging/ and reloading to request it back from the CDN

**Expected behavior**
The image should be resized

**Package version**
- stream-chat-react@11.1.1
- Reproduced on official chat demo

**Comment by MartinCupela** [comment]
@NitinSachdeo we are taking a look at this request

**Comment by MartinCupela** [comment]
Closing the issue as being solved through another support channel.
