### ISSUE TITLE
bug: Remove member from group but still active Message

### ISSUE THREAD

**Issue by minhth-1529** [GetStream/stream-chat-react#2222]
**Describe the bug**

Remove member from group but still active Message

**To Reproduce**

1. Create group
2. Using function channel.RemoveMembers()
3. Remove member
4. Member can see message of group but can not send message

**Expected behavior**

how to setActiveChannel(undefined) for that user or that member can not see message of group

**Screenshots**

https://github.com/GetStream/stream-chat-react/assets/17897146/112ad113-4d8e-4a53-9c5f-4d680886b14c

**Package version**
- stream-chat-react: 11.1.2
- stream-chat-css: 4.2.0
- stream-chat-js: 8.14.4

**Comment by MartinCupela** [comment]
@minhth-1529 thank you for the report, we will provide fix ASAP.

**Comment by MartinCupela** [comment]
After a brief deliberation I would recommend to register your custom event listener for `notification.removed_from_channel` event. Ideally this would be done in a custom `List` component. There you have access to the current array of channels, so you can set the first channel that the user was not removed from as an active channel. That way the old one will be removed from the UI.

Example:

```tsx
import React, { useCallback, useEffect} from 'react';
import { Event, StreamChat } from 'stream-chat';
import {
  Chat,
  Channel,
  ChannelHeader,
  ChannelList,
  VirtualizedMessageList as MessageList,
  MessageInput,
  Thread,
  Window,
  useChatContext,
  ChannelListProps,
  useChannelListContext,
  ChannelListMessenger
} from 'stream-chat-react';

const List: ChannelListProps['List'] = (props) => {
    const { client, setActiveChannel } = useChatContext();
    const {channels} = useChannelListContext();

    useEffect(() => {
      const handleEvent = (event: Event<StreamChatGenerics>) => {
        const newActiveChannel = channels.find((channel) => channel.cid !== event.cid);
        setActiveChannel(newActiveChannel)
      };

      client.on('notification.removed_from_channel', handleEvent);

      return () => {
        client.off('notification.removed_from_channel', handleEvent);
      };
    }, [client, channels, setActiveChannel]);

    return <ChannelListMessenger {...props}/>
};

const App = () => (
  <Chat client={chatClient}>
    <ChannelList filters={filters} sort={sort} options={options} List={List} showChannelSearch />
    <Channel>
      <RemoveMember/>
      <AddMember/>
      <Window>
        <ChannelHeader />
        <MessageList/>
        <MessageInput focus />
      </Window>
      <Thread />
    </Channel>
  </Chat>
);
```

**Comment by minhth-1529** [comment]
Hi @MartinCupela, I've considered your solution before, but I do not would channel auto-active unless the user really wants to read the message in this channel. The reason is that sometimes they are removed from the channel and the next channel auto-active has a new message, and then when they click on the other channel, they'll miss it or that message they've not really wanted to read.

**Comment by MartinCupela** [comment]
Then what would you like to do, when the user is removed from the channel?

**Comment by minhth-1529** [comment]
Hi @MartinCupela I'm looking for a way that when the user has been removed from the channel, no channel is active at this time, like setActiveChannel(undefined)
