### ISSUE TITLE
bug: Can not see message with dash line

### ISSUE THREAD

**Issue by minhth-1529** [GetStream/stream-chat-react#2227]
**Describe the bug**

When I typing '---------' sometime I would like to break above content with below content.

**To Reproduce**

Send message with --------------

**Expected behavior**

appear content

**Screenshots**

![image](https://github.com/GetStream/stream-chat-react/assets/17897146/b903c4cd-e588-4545-9c31-18d9febed8ef)

**Package version**
- stream-chat-react:
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
Hey @minhth-1529 this is not a bug but the result of parsing MD. You can customize the way how this MD element is parsed by providing own remark plugins to `renderText` function:

https://getstream.io/chat/docs/sdk/react/components/core-components/message_list/#rendering-message-text-with-rendertext-function

You can take an inspiration from the default SDK plugins:

https://github.com/GetStream/stream-chat-react/tree/e55a9bd21d691735d29f0205fb71f4f47bf52467/src/components/Message/renderText/remarkPlugins
