### ISSUE TITLE
bug: sending the very first message breaks virtualized list

### ISSUE THREAD

**Issue by teimurjan** [GetStream/stream-chat-react#2228]
**Describe the bug**

When I try to send the very first message using `VirtualizedMessageList`, I receive an error `TypeError: Cannot read properties of undefined (reading 'id')`.

After a small investigation, I found out that the error is happening [here](https://github.com/GetStream/stream-chat-react/blob/e55a9bd21d691735d29f0205fb71f4f47bf52467/src/components/MessageList/VirtualizedMessageList.tsx#L326). I've added the following logs before the return:

```ts
        console.log(index, numItemsPrepended)
        console.log(calculateItemIndex(index, numItemsPrepended))
        console.log(JSON.stringify(processedMessages, null, 2))
```

It logs the following things a couple of times:

1.
```
10000001 0
1
[
  {
    "customType": "message.date",
    "date": "2023-12-27T16:25:12.309Z",
    "id": "message.date-2023-12-27T16:25:12.309Z"
  },
  {
    "__html": "1",
    "attachments": [],
    "created_at": "2023-12-27T16:25:12.309Z",
    "html": "1",
    "id": "<sensitive>",
    "mentioned_users": [],
    "reactions": [],
    "status": "sending",
    "text": "1",
    "type": "regular",
    "user": {
      "id": "<sensitive>",
      "role": "user",
      "created_at": "2023-12-05T04:34:26.774012Z",
      "updated_at": "2023-12-27T16:24:52.764164Z",
      "last_active": "2023-12-27T16:17:20.994793Z",
      "banned": false,
      "online": true,
      "invisible": false,
      "devices": [],
      "mutes": [],
      "channel_mutes": [],
      "unread_count": 0,
      "total_unread_count": 0,
      "unread_channels": 0,
      "name": "<sensitive>",
      "image": "<sensitive>"
    }
  }
]
```
2.
```
10000000 0
0
[
  {
    "customType": "message.date",
    "date": "2023-12-27T16:25:12.309Z",
    "id": "message.date-2023-12-27T16:25:12.309Z"
  },
  {
    "__html": "1",
    "attachments": [],
    "created_at": "2023-12-27T16:25:12.309Z",
    "html": "1",
    "id": "<sensitive>",
    "mentioned_users": [],
    "reactions": [],
    "status": "sending",
    "text": "1",
    "type": "regular",
    "user": {
      "id": "<sensitive>",
      "role": "user",
      "created_at": "2023-12-05T04:34:26.774012Z",
      "updated_at": "2023-12-27T16:24:52.764164Z",
      "last_active": "2023-12-27T16:17:20.994793Z",
      "banned": false,
      "online": true,
      "invisible": false,
      "devices": [],
      "mutes": [],
      "channel_mutes": [],
      "unread_count": 0,
      "total_unread_count": 0,
      "unread_channels": 0,
      "name": "<sensitive>",
      "image": "<sensitive>"
    }
  }
]
```

Finally, before the error I get:

```
10000001 1
2
[
  {
    "customType": "message.date",
    "date": "2023-12-27T16:25:12.309Z",
    "id": "message.date-2023-12-27T16:25:12.309Z"
  },
  {
    "__html": "1",
    "attachments": [],
    "created_at": "2023-12-27T16:25:12.309Z",
    "html": "1",
    "id": "<sensitive>",
    "mentioned_users": [],
    "reactions": [],
    "status": "sending",
    "text": "1",
    "type": "regular",
    "user": {
      "id": "<sensitive>",
      "role": "user",
      "created_at": "2023-12-05T04:34:26.774012Z",
      "updated_at": "2023-12-27T16:24:52.764164Z",
      "last_active": "2023-12-27T16:17:20.994793Z",
      "banned": false,
      "online": true,
      "invisible": false,
      "devices": [],
      "mutes": [],
      "channel_mutes": [],
      "unread_count": 0,
      "total_unread_count": 0,
      "unread_channels": 0,
      "name": "<sensitive>",
      "image": "<sensitive>"
    }
  }
]
```

**To Reproduce**

1. Follow the [VirtualizedMessageList example](https://getstream.io/chat/docs/sdk/react/components/core-components/virtualized_list/).
2. Send the very first message within a chat.
3. See the error in the console.

**Expected behavior**

The error should not be thrown.

**Screenshots**

<img width="716" alt="Screenshot 2023-12-27 at 22 32 49" src="https://github.com/GetStream/stream-chat-react/assets/17337276/489e5225-019f-49ee-974f-ea857214630b">

**Package version**
- stream-chat-react:  11.2.1
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 120

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
Hey @teimurjan thank you for the report. Could you please confirm the repro steps? Thank you

**Comment by Peterl561** [comment]
I'm getting a similar error message with `VirtualizedMessageList`, but it only happens when `disableDateSeparator` is `false`. Might it be that the prepended date separator message is breaking the calculation in `computeItemKey`?

**Comment by MartinCupela** [comment]
@teimurjan @Peterl561 we had this issue in the past, but after the fix for [v10](https://github.com/GetStream/stream-chat-react/releases/tag/v10.22.1) and [v11](https://github.com/GetStream/stream-chat-react/releases/tag/v11.1.1) I have a hard time to reproduce the issue. The reason for this in the past was the optimistic UI update and subsequent updates from the back-end with different message timestamps. This lead to message swaps based on the updated timestamp and sudden index discrepancy. And yes, it was reserved to `disableDateSeparator={false}` setting.

Could you please share a video of the user behavior when the issue appears?

On my end it works, please see the attached video:

[vml_msg_swap_test.webm](https://github.com/GetStream/stream-chat-react/assets/32706194/5906ba46-4d13-46da-b09f-828c37d97a96)

**Comment by Annastrin** [comment]
@MartinCupela We have the same issue with "stream-chat-react": "10.22.2".
Here's the screencast:
[Screencast from 13-01-24 12:39:29.webm](https://github.com/GetStream/stream-chat-react/assets/27924565/244a5144-9de0-49a7-8c1a-b84cf34bf47d)

I've added custom `computeItemKey` and `components: { Item }` as `additionalVirtuosoProps`, with fixes like on the screenshots below and it seems to help.
![Screenshot from 2024-01-13 15-06-47](https://github.com/GetStream/stream-chat-react/assets/27924565/5489f925-11c9-4357-a00e-9d63877c01c6)
![Screenshot from 2024-01-13 15-07-03](https://github.com/GetStream/stream-chat-react/assets/27924565/95d586ab-319c-46ea-b652-902f9e480091)

**Comment by teimurjan** [comment]
Hey @MartinCupela. The issue happens only when `disableDateSeparator={false}` on my side. I can't share the whole UI & the codebase, because the project is private, but let me try to share a part of it.

1. I have the following JSX for the conversation page:

<img width="672" alt="Screenshot 2024-01-13 at 15 08 36" src="https://github.com/GetStream/stream-chat-react/assets/17337276/0094223c-dff0-4a29-8d4b-d5e8ab13b434">

2. Within the `ConversationMessageList` I render the `VirtualizedMessageList` from Stream:

<img width="305" alt="Screenshot 2024-01-13 at 15 08 49" src="https://github.com/GetStream/stream-chat-react/assets/17337276/ea5fa772-f029-4c79-861a-603b7066fede">

3. Here is the screen recording of the issue happening. It's handled by ErrorBoundary:

https://github.com/GetStream/stream-chat-react/assets/17337276/58a2a4ea-d9c9-4ded-8b85-227bf7702392

4. Here is what I get in the console:

<img width="818" alt="Screenshot 2024-01-13 at 15 11 28" src="https://github.com/GetStream/stream-chat-react/assets/17337276/6adfa22e-6963-4f17-b508-7f1801673615">

5. Here is where the console stack trace is pointing to:
6. 
<img width="672" alt="Screenshot 2024-01-13 at 15 08 36" src="https://github.com/GetStream/stream-chat-react/assets/17337276/58f5176a-5ccb-41a9-9809-88a334728ae6">
