### ISSUE TITLE
bug: peer dependency error with React 16 / React 17

### ISSUE THREAD

**Issue by MPeloquin** [GetStream/stream-chat-react#2234]
**Describe the bug**

The peer dependencies have `"react": "^18.0.0 || ^17.0.0 || ^16.8.0"`, but if you install it with react 16.8, there will be peer-dependencies issues because of `react-markdown` `9.0.0` which has `"react": ">=18"` in its peer-dependencies.

It seems to work at runtime for us locally, but was breaking our tests & build

It is ok to drop support for old React versions, but it should be clear in the peer-dependencies so we don't try to update yet

**To Reproduce**

1. Have project with React 16
2. Install latest `stream-chat-react`
3. run install
4. See peer-dependencies issue:

```
└─┬ stream-chat-react 11.2.1
  └─┬ react-markdown 9.0.1
    └── ✕ unmet peer react@>=18: found 16.14.0

```

**Expected behavior**

Peer-dependencies of `stream-chat-react` should reflect real version needs

**Package version**
- stream-chat-react: 11.2.1

**Desktop (please complete the following information):**

- OS: macos
- Browser chrome
- Version latest

**Comment by MartinCupela** [comment]
@MPeloquin thank you for raising the issue. We will try that the react-markdown lib incorporates wider range for peer deps. We need to keep our libraries up-to-date, but at the same time need to support those that have not migrated to v18 yet. Thank you for understanding.
