### ISSUE TITLE
Unread message notifications do not disappear after reading the message

### ISSUE THREAD

**Issue by vihan85** [GetStream/stream-chat-react#2297]
**Describe the bug**

Notifications do not disappear after reading the message

**To Reproduce

https://github.com/GetStream/stream-chat-react/assets/104440194/b96d4a12-0a88-4dc5-932b-5d0157ea88eb

ce**

**Expected behavior**

**Screenshots**

**Package version**
- stream-chat-react:
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
Hello @vihan85 the stream-chat-react dep have been updated for the demo apps. The issue should be resolved.
