### ISSUE TITLE
Unread message notifications do not disappear after reading the message

### ISSUE THREAD

**Issue by vihan85** [GetStream/stream-chat-react#2298]
I think the problem has not been completely resolved, I still have the same situation as the attached video.

**To Reproduce**

https://github.com/GetStream/stream-chat-react/assets/104440194/91da7fac-d151-49bd-bb7f-1d810f6679c9

**Expected behavior**

**Screenshots**

**Package version**
- stream-chat-react:
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
Hello @vihan85 how did the unread message banner in the Social Demo channel appeared? Was it due to mark unread request or due to a new message from another user?

**Comment by vihan85** [comment]
> Hello @vihan85 how did the unread message banner in the Social Demo channel appeared? Was it due to mark unread request or due to a new message from another user?

hi @MartinCupela 
It is a new message from another user.

**Comment by MartinCupela** [comment]
Hey @vihan85 by design, the unread UI is removed after leaving and returning back to the channel.
