### ISSUE TITLE
bug: messageInput autocomplete for emotes (e.g `<3`) sends the message without cleaning the input state

### ISSUE THREAD

**Issue by kennyvallejodev** [GetStream/stream-chat-react#2316]
**Describe the bug**

**To Reproduce**

1. Go to [getstream-chat-demo-team](https://getstream.io/chat/demos/team/)
2. Click on Message Input
3. Type `<3` and press enter
    - You will see how is send `<3` as a plain text
    - You will also see how the input value is now `❤️<` 
    (Looks like after pressing enter, is now replacing <3 with the actual ❤️) 

not only that, this also works the same for the mentions, if you mention someone that has for example `<3` at the end of the name (e.g Kenny <3) it will be bugged as well and when you press enter, the mention is first send as a plain text (with no mention interaction) and the input state will remain having the value.

**Expected behavior**

Do the replace of the emotes once the message is send? Send the message properly (in the case of mentions) and not as a plain text.

**Screenshots**

https://github.com/GetStream/stream-chat-react/assets/42121336/7eaeaaf5-11d1-4fe3-979b-6c4d75e91f33

**Package version**
- stream-chat-react: 11.12.0
- stream-chat-css: (no idea- using just stream-chat-react and stream-chat)
- stream-chat-js: 8.22.0

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] Chrome  
- Version [e.g. 22] 122.0.6261.112

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] N/A
- OS: [e.g. iOS8.1]N/A
- Browser [e.g. stock browser, safari]N/A
- Version [e.g. 22]N/A

**Additional context**

**Comment by myandrienko** [comment]
Thanks for the report @kennyvallejodev! This has been [fixed](https://github.com/GetStream/stream-chat-react/pull/2332) and [released](https://github.com/GetStream/stream-chat-react/releases/tag/v11.12.1) in v11.12.1.

**Comment by kennyvallejodev** [comment]
> Thanks for the report @kennyvallejodev! This has been [fixed](https://github.com/GetStream/stream-chat-react/pull/2332) and [released](https://github.com/GetStream/stream-chat-react/releases/tag/v11.12.1) in v11.12.1.

Thank you for taking the time on fixing this one!
