### ISSUE TITLE
bug: Command and Mention popup overlap with play button

### ISSUE THREAD

**Issue by minhth-1529** [GetStream/stream-chat-react#2318]
**Screenshots**

![Screenshot 2024-03-11 at 9 52 57 AM](https://github.com/GetStream/stream-chat-react/assets/17897146/44b822d8-02a3-4338-bc86-36606f0d4e15)
![Screenshot 2024-03-11 at 9 53 05 AM](https://github.com/GetStream/stream-chat-react/assets/17897146/964443aa-3a28-4ce6-8d38-33cf89e1b158)

**Package version**
- stream-chat-react: 11.11.0
- stream-chat-css: 4.8.0
- stream-chat-js: 8.20.0

**Comment by MartinCupela** [comment]
Hey @minhth-1529, this issue is being addressed: https://github.com/GetStream/stream-chat-css/pull/282
