### ISSUE TITLE
Component crashing due to undefined items

### ISSUE THREAD

**Issue by kjacques** [GetStream/stream-chat-react#237]
Hello,

since the version 0.11.16, we are having issues with the chat room component where sometimes it just crash the whole component trying to read an id on an undefined items.

The problems seems to come from this PR : https://github.com/GetStream/stream-chat-react/commit/324a6f637034f5375b369139a37820f4960bd02a

the filter can return undefined items and then when it goes to this code portion in the MessageSimple component:

else if (readBy.length !== 0 && !threadList && !justReadByMe) {
      const lastReadUser = readBy.filter(	
        (item) => item.id !== client.user.id,	  
      )[0];

item is item undefined and the component crash.

UPDATE:
it's not just the PR that did the problem, even reverting before, we still have the error sometimes

**Comment by jaapbakker88** [comment]
@kjacques we're looking into this, can you share the error message you're getting when the app crashes and in which specific case it happens.

**Comment by kjacques** [comment]
@jaapbakker88 Here is the error we have in the consolewhen the problem happens:
![image](https://user-images.githubusercontent.com/23341835/81307089-3b99b780-904e-11ea-8291-21712676da0f.png)

For the specific case, it looks like its bound to readBy message.

**Comment by jaapbakker88** [comment]
@kjacques we just released version `0.12.0` which includes a fix for this issue. Please let me know if it's resolved for you.

**Comment by kjacques** [comment]
@jaapbakker88 It actually fixes things but break in another place:

![image](https://user-images.githubusercontent.com/23341835/81403317-1ca82d80-9101-11ea-8258-4fafb471e98d.png)

**Comment by jaapbakker88** [comment]
could you email us at support@getstream.io, I'd like to run some tests to make sure this won't happen anymore. Can you share:
- user_id
- api key
- channel type and id

**Comment by kjacques** [comment]
@jaapbakker88 just to be sure what do you mean by user_id ?

**Comment by jaapbakker88** [comment]
@kjacques the user_id of the user connected to the client when this error happens

**Comment by kjacques** [comment]
@jaapbakker88 WIth the latest 1.0.1 version, seems like its fixed (Will send another ticket if we see something unusual)

thanks
