### ISSUE TITLE
Invalid CSS generated

### ISSUE THREAD

**Issue by tomas-c** [GetStream/stream-chat-react#238]
[This line](https://github.com/GetStream/stream-chat-react/blob/78c027bfcbfc3d3516461262c1513f245b7c07b0/src/styles/MessageTeam.scss#L57
) leads to the following invalid CSS to be generated:

```
> .str-chat__message-team-actions > span:not(:last-of-type) {
            border-right: 1px solid #e0e0e0; }
```

( line 4174 in node_modules/stream-chat-react/dist/css/index.css of version  v0.11.17 )

Wanted to create a PR to fix it but not sure the original intention of that line.

**Comment by jaapbakker88** [comment]
@tomas-c this should be resolved in `0.12.0`
