### ISSUE TITLE
bug: invalid SVG urls in dist/css/v2/index.css fails to compile with NextJS dev using Turbopack

### ISSUE THREAD

**Issue by grahamplace** [GetStream/stream-chat-react#2395]
**Describe the bug**

@font-face in `node_modules/stream-chat-react/dist/css/v2/index.css` is using an invalid syntax for referencing SVG font files. Usage like src:url("../../assets/icons/stream-chat-icons.svg#stream-chat-icons") includes a #stream-chat-icons, which causes NextJS projects with turbopack dev to fail to compile.

If I remove all the `#{whatever}` usage from the file locally, it solves the problem.

If I run next dev without turbopack, it works.

**To Reproduce**

1. [Code Sandbox](https://codesandbox.io/p/devbox/nextjs-turbo-stream-slylp5)
2. `pnpm dev` is the working case, using normal next + webpack
3. `pnpm dev-turbo` is the error case, using `next dev --turbo`  

**Expected behavior**
- Code which depends on `stream-chat-react` should compile 

**Screenshots**

![CleanShot 2024-05-21 at 17 05 00](https://github.com/GetStream/stream-chat-react/assets/19509185/7d923274-a0ee-410a-b030-37383123dbb6)

**Package version**
  stream-chat:
    specifier: 8.33.0
    version: 8.33.0
  stream-chat-react:
    specifier: 11.18.1
    version: 11.18.1(@types/react@18.2.48)(jquery@3.7.1)(react-dom@18.2.0)(react@18.2.0)(stream-chat@8.33.0)(ws@8.17.0)

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 124.0.6367.208 (Official Build) (arm64)

**Additional context**

**Comment by MartinCupela** [comment]
@grahamplace this seems like an issue related to the Turbo configuration. The requested assets exist on path `../../assets/icons/`: https://unpkg.com/browse/stream-chat-react@11.19.0/dist/assets/icons/

I have seen other people reporting similar problem with Turbo: https://github.com/vercel/next.js/issues/64684

Please make sure to investigate how to setup Turbo properly.

**Comment by grahamplace** [comment]
> The requested assets exist on path ../../assets/icons/: https://unpkg.com/browse/stream-chat-react@11.19.0/dist/assets/icons/

@MartinCupela my flag wasn't that these assets _didn't exist_, it's that they contain usage of the `#` fragment identifier (`src:url("../../assets/icons/stream-chat-icons.svg#stream-chat-icons")` which (as best I can tell) is incompatible with next turbo

I can definitely try to configure turbopack on my end to work around this

**Comment by trozzelle** [comment]
@grahamplace Were you able to make any progress on this? I'm running into the same issue.

**Comment by yudhistiraak** [comment]
@grahamplace Were you able to make any progress on this? I'm running into the same issue.

**Comment by yudhistiraak** [comment]
> @grahamplace Were you able to make any progress on this? I'm running into the same issue.
> 
> Update: I was able to fix this by updating to `next@14.3.0-canary.79`, which also requires updating to React 19 RC, which might not work for everyone, but it does resolve the issue.
> 
> I believe the earliest 14.3.0 canary build that doesn't require React 19 is `next@v14.3.0-canary.68`. I tested this version and it also resolves the issue.

i fix it by removing the #iefix #stream-chat-icons in index.css file, and its work

**Comment by amanolar94** [comment]
> > [@grahamplace](https://github.com/grahamplace) Were you able to make any progress on this? I'm running into the same issue.
> > Update: I was able to fix this by updating to `next@14.3.0-canary.79`, which also requires updating to React 19 RC, which might not work for everyone, but it does resolve the issue.
> > I believe the earliest 14.3.0 canary build that doesn't require React 19 is `next@v14.3.0-canary.68`. I tested this version and it also resolves the issue.
> 
> i fix it by removing the #iefix #stream-chat-icons in index.css file, and its work

@yudhistiraak how did you remove them?
