### ISSUE TITLE
bug: mention inside a thread reply doesn't add the mentioned-user to be part of the `thread_participants`

### ISSUE THREAD

**Issue by kennyvallejodev** [GetStream/stream-chat-react#2401]
**Describe the bug**

- If you're inside a Thread
   - and you reply mentioning someone else (that is not the thread-original-parent-message author) this new mentioned user is not part of the `thread_participants`
   - This leads to a problem, and is that the user will no receive a `thread_message_new` chat event and neither a `thread_unread_count` on the `getUnreadState` 

**To Reproduce**

1. Go to  Chat
2. Send a message
3. Create a reply to that message (so it opens a thread) and mention someone else
4. (Print out the channel data) you will see how the new mentioned user is not part of the thread_participants

**Expected behavior**

It should add the mentioned user (and the person mentioning the other user (if is not added) to the thread_participants and send the respective events.

**Screenshots**

**Package version**
- stream-chat-react:^11.14.0
- stream-chat-css: N/A
- stream-chat-js:^8.25.1

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] Version 125.0.6422.61 (Official Build) (arm64)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] N/A
- OS: [e.g. iOS8.1]N/A
- Browser [e.g. stock browser, safari]N/A
- Version [e.g. 22]N/A

**Additional context**

**Comment by MartinCupela** [comment]
@kennyvallejodev this feature should be supported in the following days. Will keep you updated.

**Comment by vishalnarkhede** [comment]
@kennyvallejodev could you reach out to support@getstream.io providing your appID? So that I can deploy this for your app as priority

**Comment by luisgereda** [comment]
Hi @kennyvallejodev, please create a support request using this link:
https://getstream.io/contact/support/

So we can take a closer look

**Comment by kennyvallejodev** [comment]
I just receive the message from support saying that the feature is enabled in my apps. and yess, problem solved!

thanks to you folks, great work and great fast response. really appreciate it 🙏🏻 
@luisgereda @vishalnarkhede @MartinCupela
