### ISSUE TITLE
bug: issue with "renderText" handling line breaks

### ISSUE THREAD

**Issue by 4gn10** [GetStream/stream-chat-react#2409]
**Describe the bug**

The issue occurs when the input message text string contains both line breaks (\n) and inline markdown elements (such as bold or italic). In these cases, line breaks after the markdown elements are not rendered correctly.

**To Reproduce**

[Code Sandbox Example](https://codesandbox.io/p/sandbox/react-markdown-multilinebreaks-54zsmk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwujpei800063b6mn8vgspou%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwujpei700023b6mencwvasu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwujpei700033b6mr1z22uzf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwujpei700053b6m7eu941ly%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwujpei700023b6mencwvasu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwujpei700013b6mfttq2j3f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clwujpei700023b6mencwvasu%2522%252C%2522activeTabId%2522%253A%2522clwujpei700013b6mfttq2j3f%2522%257D%252C%2522clwujpei700053b6m7eu941ly%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwujpei700043b6mrd3v75yk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwujpei700053b6m7eu941ly%2522%252C%2522activeTabId%2522%253A%2522clwujpei700043b6mrd3v75yk%2522%257D%252C%2522clwujpei700033b6mr1z22uzf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwujpei700033b6mr1z22uzf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Case 1: Text without Inline Markdown Elements

Input Text:
```
Hello world \n\nThis is the second line
```
Actual Output:
```
Hello world
<br/>
This is the second line

```

Result: Line breaks are correctly converted to `<br>`  tags.

Case 2: Text with Inline Markdown Elements

Input Text:
```
Hello world\n\n\nThis is **the second** line\n\n\nThis is the third line
```
Expected Output:
```
Hello world
<br/><br/>
This is <strong>the second</strong> line
<br/><br/>
This is the third line
```

Actual Output:

```
Hello world
<br/><br/>
This is <strong>the second</strong> line
This is the third line
```

Result: Only the line breaks before the inline markdown elements are correctly converted to `<br>` tags. Line breaks after the markdown elements are ignored.

**Screenshots**

<img width="1674" alt="Screenshot 2024-05-31 at 4 51 20 PM" src="https://github.com/GetStream/stream-chat-react/assets/102326359/b90e5dea-3f94-4e60-877c-ff59a6f1d8aa">

**Package version**
- stream-chat-react: ^11.5.0
- stream-chat: ^8.15.0

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS Sonoma 14
- Browser [e.g. chrome, safari] chrome

**Comment by MartinCupela** [comment]
Hey @4gn10, thank you for reporting this. We will take a look into this issue in the near future.
