### ISSUE TITLE
Some components are heavy

### ISSUE THREAD

**Issue by LongJohnSilver1504** [GetStream/stream-chat-react#2424]
Motivation
I am currently integrating stream-chat-react components into our application. I’ve noticed that some components, such as Channel, ChannelHeader, MessageInput, MessageList, and Window, have unusually large sizes, specifically a bundle size of 1.5M (gzipped: 400.4k). This large size leads to increased load times and potentially affects the performance of our application, especially on devices with limited resources. I am always frustrated when the performance and user experience of our application are compromised due to unnecessarily large third-party components.

Proposed Solution
I would like to see an optimized version of stream-chat-react where the size of these components is significantly reduced without compromising functionality. Potential solutions could include:

	•	Breaking down the library into more granular components to ensure that we only import what we need.
	•	Implementing more efficient coding practices or using lighter alternatives within the library to reduce the overall footprint.
	•	Offering a separate package for essential features with optional imports for additional features.

Acceptance Criteria

	1.	The overall gzipped size of essential components (Channel, ChannelHeader, MessageInput, MessageList, Window) should be reduced by at least 30%.
	2.	The performance of these components on low to mid-range devices should be demonstrably improved, with load times reduced by at least 20%.
	3.	The optimized version should maintain all current functionalities and be fully backward compatible with existing implementations.
	4.	Documentation should be updated to guide developers on how to utilize the optimized components for maximum efficiency.
	
	
![Screenshot 2024-06-14 at 13 42 28](https://github.com/GetStream/stream-chat-react/assets/53310608/934ee3a4-0122-41b1-96a5-ff6b517c79b0)

**Comment by MartinCupela** [comment]
Hey @LongJohnSilver1504, thank you for your suggestions. Have you tried to setup tree shaking with your bundler?

Regarding the component size we have to account for the functionality that the components offer.

We keep in mind that the code can be constantly optimized and of course, we would like to apply refactors to the parts of SDK in the future.

You can of course use only low-level client to perform API calls and state management and implement your own React components. In that case you will be able to determine, what functionality makes sense for you.
