### ISSUE TITLE
bug: message options (reactions, threads...) disappear when you change channels

### ISSUE THREAD

**Issue by Nathan-P2** [GetStream/stream-chat-react#2426]
**Describe the bug**

Hi, we've noticed a bug when we change the channel. When we instantiate the channel and the messages for the first time, all the messages have the options (such as threads and reactions) normally. However, when we change the channel, the options disappear and only come back when we send a new message.

**To Reproduce**

1. As soon as we instantiate a channel, on the first load of the page, it loads all the options normally.

https://github.com/GetStream/stream-chat-react/assets/68254838/a9d5a141-9da7-4d00-86e6-14c083029e9e

2. After we change the channel, it hides all the options and only comes back when we send a new message

https://github.com/GetStream/stream-chat-react/assets/68254838/6ec0decd-df87-48f2-93d0-26914a8e0f12

3. Some users have also reported that editing a message or marking it as unread also causes the options to be removed, but I haven't been able to reproduce this for you.

```
<Chat client={client} theme='messaging light'>
        <Channel channel={channel}>
          <div id='channel-container'>
            {
              showMenu ?
                <div className='menu-container'>
                  <div className='menu-header'>
                    <h1>{courseName ? courseName : 'Comunidade'}</h1>
                  </div>
                  <div className='menu-items'>
                    {channels.map((chan, index) => (
                      <div className={`menu-card ${channel?.id === chan.id ? 'menu-card-actived' : ''}`} key={index} onClick={() => handleItemClick(chan.id, chan.data?.name)}>
                        <img src={ `${ ( chan.data?.image ? chan.data?.image : 'https://ui-avatars.com/api/?name='+chan.data?.name ) }` }/>
                        <div className='card-text'>
                          <div className='card-header'>
                            <b>{chan.data?.name}</b>
                            <small>{ chan.state.last_message_at ? formatDate( chan.state.last_message_at) : ''  }</small>
                          </div>
                          <p>{chan.state.messageSets[0].messages.length > 0 ? chan.state.messageSets[0].messages[chan.state.messageSets[0].messages.length-1].text : ''}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              : <></>
            }
            {
              showChat ?
                <div className='chat-container'>
                  {
                    !hideHeader ? 
                    <div className='chat-header-container'>
                      <ChannelHeader />
                    </div> : <></>
                  }
                  <MessageList />
                  <MessageInput />
                </div>
              : <></>
            }
            {
              showThread ? 
                <div className='thread-container'><Thread /></div>
              : <></>
            }
          </div>
        </Channel>
      </Chat>
```

```
const handleItemClick = async (channelId: any, channelNameReceived: any) => {
    if (!client) return;

    const channel = client.channel(scope || '', channelId || '', {
      name: channelNameReceived || '',
      members: [alunoId || '']
    });

    setChannel(channel);

    enableChatContainer();

    await setupMemberList(channelId)
  };
```

1. Access a new channel
5. Hover over the messages
6. You will see that the options are unavailable
7. Send a new message
8. You'll see that the options return

**Expected behavior**

We hope that as soon as you change channels, all the message options will be available, such as threads, reactions, marking as unread... etc.

**Screenshots**

We send you the videos

**Package version**
- stream-chat-react: ^11.15.2
- stream-chat: ^8.26.0
- react: ^18.2.0

**Desktop (please complete the following information):**

- OS: macOS 14.5
- Browser: Arc
- Version: V1.47

**Smartphone (please complete the following information):**

- Device: iPhone 15 Pro
- OS: iOS 17.5.1
- Browser: Chrome
- Version: latest

**Additional context**

**Comment by MartinCupela** [comment]
Hello @Nathan-P2, this looks more as an integration bug than an SDK bug. Could you please create a reproduction with our pre-made [sandbox](https://codesandbox.io/p/devbox/priceless-forest-g64slj)? As you can see, the behaviour is not reproducible with SDK defaults. Thank you

**Comment by MartinCupela** [comment]
@Nathan-P2 can I close this issue?

**Comment by Nathan-P2** [comment]
Yes, thank you for the help.
