### ISSUE TITLE
Can not possible to review previous messages in the thread

### ISSUE THREAD

**Issue by vihan85** [GetStream/stream-chat-react#2433]
**Describe the bug**
Cannot review  past messages in thread

**To Reproduce**

1. Go to channel
2. Scroll to message (05/23/2024)
3. Click the reply count button
4. The reply count button shows five messages, but there is only one message in the thread

**Screenshots**
![image](https://github.com/GetStream/stream-chat-react/assets/104440194/7e54cefc-3369-4069-a6b0-d8cc8d6b44b7)

**Package version**
-  stream-chat-react: ^11.21.0
- stream-chat-css:^4.16.1
- stream-chat-js:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
Hello @vihan85 , the repro steps you provide are actually not repro steps, as I can take a first message with 5 replies I find and open it and I see 5 replies

<img width="1175" alt="image" src="https://github.com/GetStream/stream-chat-react/assets/32706194/7624c033-ba12-416b-9293-80ce670507c3">

Then I tried to reply to another message - see the replies appearing, refreshed and the replies are loaded again correctly.

Please provide more details about how the inconsistent situation has been created.

**Comment by vihan85** [comment]
hi @MartinCupela 

Go to channel
Scroll to message (05/23/2024 or older) 
Click the reply count button of  message (05/23/2024 or older)

**Comment by vihan85** [comment]
hi @MartinCupela 
You can watch the video to see more specifically

In this video:

Step 1: Create a new thread and send 6 mesage (it runs correctly)
Step 2: Scroll to a message with a thread created on June 14, 2024 and open it (it runs incorrectly)

[Link-video](https://drive.google.com/file/d/1gana8Gl57Ctl71rmFx7yJP25g7kl0GG4/view?usp=drive_link)
