### ISSUE TITLE
question: How to remove Hyperlinks format?

### ISSUE THREAD

**Issue by minhth-1529** [GetStream/stream-chat-react#2446]
**To Reproduce**

1. Typing 'a.styles'
2. In sent message '[a.styles](url)' is a link format

**Expected behavior**

how to remove Hyperlinks format?

**Screenshots**

![Screenshot 2024-07-08 at 2 25 25 PM](https://github.com/GetStream/stream-chat-react/assets/17897146/129fba46-b9d1-4f6c-a06d-a3f2360ba901)

**Package version**
- stream-chat-react: 11.23.0
- stream-chat-css: 4.17.3
- stream-chat-js: 8.37.0

**Comment by MartinCupela** [comment]
Hello @minhth-1529 , this is a valid uri with top level domain ".style". You can see more [here](https://www.shopify.com/domains/style#:~:text=style%20domain%20name%3F-,.,who%20write%20about%20these%20topics.). 

However if you type a.styles, it is correctly not considered a link.

**Comment by minhth-1529** [comment]
Hi @MartinCupela , getstream will auto detect if the text is valid uri, it will auto format hyperlink, right?
