### ISSUE TITLE
Icon and name not set to chat

### ISSUE THREAD

**Issue by m-peko** [GetStream/stream-chat-react#2451]
**Describe the bug**

When creating new channel, channel name and icon are not being saved.

**To Reproduce**

Here is the code I am using to create new channel:

```
const channelId = createChannelID(tokenChainID, tokenAddress);
const streamToken = await fetchStreamToken(userAddress);
if (!streamToken) {
  console.error("Failed to fetch stream token");
  return;
}

const newUser = {
  id: userAddress,
  name: userAddress,
  image: `https://getstream.io/random_png/?name=${userAddress}`,
};

const client = StreamChat.getInstance(apiKey);
await client
  .connectUser(newUser, streamToken)
  .then(async () => {
    const channel = client.channel("livestream", channelId, {
      image: iconURL,
      name: name,
    });

    await channel.create();
  })
  .catch((e) => console.error("Failed to connect user", e));
```

**Expected behavior**

I would expect channel name and icon being set, but they are not.

**Screenshots**

![image](https://github.com/user-attachments/assets/7a3f7b8f-6459-4791-89c8-b87100c8fb9e)
![image](https://github.com/user-attachments/assets/0cb794db-a52d-4db4-9318-17d1d0ea2914)

**Package version**

- stream-chat-react: 11.19.0
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**

- OS: Fedora Linux, OSX, etc.
- Browser: Brave, Chrome, etc.

**Comment by MartinCupela** [comment]
Hello @m-peko , are you using any demo application here? The default `ChannelHeader` component loads the image provided via `image` prop, or determines the image as the other member's user image. I guess here you have only one member that is the creator of the channel + you are not passing the `image` prop.
