### ISSUE TITLE
bug: React versions <18 fail to compile

### ISSUE THREAD

**Issue by kylemellander** [GetStream/stream-chat-react#2455]
When installing in a project that using React > 16.8 or React 17, compilation fails when attempting to resolve `react/jsx-runtime`.  The reason for this failure is the pinned version of `react-markdown` requires React > 18.

**To Reproduce**

1. I created [a simple reproduction of the issue here](https://codesandbox.io/p/devbox/nostalgic-brattain-xnmn4n?file=%2Fpackage.json).
2. run `yarn build` to see the failure.

**Expected behavior**

I would expect the JavaScript to compile OR the requirement to be clear that you need to be on React > 18.

**Screenshots**

<img width="1450" alt="Screenshot 2024-07-24 at 9 23 02 AM" src="https://github.com/user-attachments/assets/fe050734-9229-4a99-877d-c03ab32d5d2d">

**Package version**
- stream-chat-react: 11.23.3
- stream-chat-css: n/a
- stream-chat-js: n/a

**Additional context**

I know that it is possible to work around this with configuration of the build process, but this problem ends up bubbling up through all our projects that utilize the library (even indirectly), and it feels janky to have that need for configuration to leak out.

**Comment by MartinCupela** [comment]
Hey @kylemellander we are looking into the option how to alleviate the inconvenience.
