### ISSUE TITLE
question: Anyway to implement bubble chat?

### ISSUE THREAD

**Issue by minhth-1529** [GetStream/stream-chat-react#2456]
My business implement a page as demo. Currently, I would like to can chat in any page, I think about bubble chat like facebook messenger, I would like to ask have anyway to implement it?

**Comment by MartinCupela** [comment]
Hey @minhth-1529 this is a broad question that would need to be narrowed down a bit. What specific obstacles do you see in implementing such a chat?

**Comment by MartinCupela** [comment]
Hey @minhth-1529 is this issue still relevant or we can close it, please?

**Comment by MartinCupela** [comment]
Closing the issue for inactivity
