### ISSUE TITLE
bug:Getting 500 error on https://chat.stream-io-api.com/threads api new feature on thread 2.0

### ISSUE THREAD

**Issue by mahfuj-friends-corp** [GetStream/stream-chat-react#2467]
When Call await threads = await client.queryThreads();

getting 500 error 

{
  "code": -1,
  "message": "QueryThreads failed with error: \"\"",
  "StatusCode": 500,
  "duration": "0.00ms",
  "more_info": "https://getstream.io/chat/docs/api_errors_response",
  "details": []
}

**Comment by MartinCupela** [comment]
Hey @mahfuj-friends-corp , please use our [support service](https://getstream.io/contact/support/) to address non-SDK related issues. Please attach the APP ID to your request created through the support service to speed the process up. Thank you.
