### ISSUE TITLE
Change default file upload icon and send message icon

### ISSUE THREAD

**Issue by GuysmoB** [GetStream/stream-chat-react#2476]
Hi,

I would like to know if there is a way to change these icons without creating a new whole input message ?
If no, adding a new props for `<MessageInput/>` to let the user choose his icons could be interesting.

Thank you !

**Comment by arnautov-anton** [comment]
Hey, @GuysmoB, you're probably looking for a `FileUploadIcon` prop on `Channel` component (passed to `MessageInput` through `ComponentContext`):

```tsx
const CustomFileIcon = () => (
    <svg .../>
);

<Channel FileUploadIcon={CustomFileIcon} >...</Channel>
```

**Comment by GuysmoB** [comment]
Thank you @arnautov-anton
