### ISSUE TITLE
question: Field time for new message

### ISSUE THREAD

**Issue by minhth1529** [GetStream/stream-chat-react#2501]
**Describe the question**

I don't know whether we have any field that records the last time a message was read based on the message time rather than real time. This means that if the last time I read a message was yesterday, and today there are new unread messages, then the last time I read would be today at the time the message was sent.

Example

- The last read message was yesterday.

- received a new message at 11 AM today.

- the_field_i_need: 11 AM

- continue receiving messages 11:01 AM

- continue receiving messages 11:02 AM

- the_field_i_need: 11 AM

The reason I need that field is because I'm developing a time count up, how long it's been since we got new messages.

Example, based on the above example.

- present is 11:15 AM.
 
I will show the count up time of 15 minutes (the new message has been 15 minutes do not answer yet).
 
In my example, when there is a new message today, if I use the field `last_message_at` and show the count up, it will display the hour from yesterday.

**Screenshots**

**Package version**
- stream-chat-react: 11.23.5
- stream-chat-css: 4.17.4
- stream-chat-js: 8.37.0

**Comment by MartinCupela** [comment]
Hello @minhth1529 , I am not sure whether I understand well the request. 

A. Would you like to know what is the time of the last message in the channel?
or
B. Would you like to know what is the time of last read message in the channel?

**Comment by MartinCupela** [comment]
@minhth1529 can I close this issue?

**Comment by minhth1529** [comment]
Hi @MartinCupela  thanks for your response, I found the solution, please close this issue.
