### ISSUE TITLE
question: component to show mentions

### ISSUE THREAD

**Issue by Nathan-P2** [GetStream/stream-chat-react#2517]
Hi

We need a component that displays the number of messages mentioned in the channel in the ChannelList component and also a button to go directly to the message that mentions the user.

Is there anything ready in this regard?

**Comment by MartinCupela** [comment]
Hello @Nathan-P2 , we do not keep the number of mentioned messages. This is something you will need to record on your back-end side. To go directly to a message, you can use [`jumpToMessage` function from channel action context](https://getstream.io/chat/docs/sdk/react/components/contexts/channel_action_context/#jumptomessage).
