### ISSUE TITLE
Having problem building this app on windows

### ISSUE THREAD

**Issue by Apoorv-Negi** [GetStream/stream-chat-react#2540]
### Having Problem while building the app on windows by running yarn build.
The following error is coming:
![image](https://github.com/user-attachments/assets/91cb6b0f-83ab-4d3c-aab0-40655aa40521)

After Manually copying the files described in copy-css.sh script.
If I try to tun tsc scripts/bundle.ts separately, then this error is coming: 
![image](https://github.com/user-attachments/assets/7a8c37bc-8e6d-4b08-b10c-f9c0bb89db75)

Even allowJs is true in tsconfig file.
Can anybody Help me with building this app on windows?

**Comment by MartinCupela** [comment]
Hello @Apoorv-Negi , may I ask you why are you trying to build the RC version of the SDK?

**Comment by Apoorv-Negi** [comment]
Wanted to test it on windows.

**Comment by MartinCupela** [comment]
What would you like to test?

**Comment by Apoorv-Negi** [comment]
i have cloned the project and then i tried giving build (yarn build) after yarn install on my mac system build is generated successfully but on windows i see the above error

**Comment by MartinCupela** [comment]
I would guess that Windows does not recognize forward slashes as valid path delimiters. Please take into consideration that this question is not related to the support of the SDK functionality (focus of the repo Issues section).
