### ISSUE TITLE
bug: A horizontal scroll bar appears with long white space before the text

### ISSUE THREAD

**Issue by vihan85** [GetStream/stream-chat-react#2541]
**Describe the bug**

A horizontal scroll bar appears with long white space before the text

**To Reproduce**

1. Go to: input
2. type:  

>                                                                                                                                                text

**Expected behavior**

Trim white space

**Screenshots**

![image](https://github.com/user-attachments/assets/7cff0f3d-1d66-465f-a611-b48c79b4281e)

**Package version**

- stream-chat-react: `v12.2.2`
- stream-chat-css:
- stream-chat-js: `v8.40.9`

**Comment by MartinCupela** [comment]
hey @vihan85 , thank you for the report. Is this an issue for the UI of demo application?

**Comment by minhth1529** [comment]
Hi @MartinCupela, this issue occur on demo, I founded it on v11.23.6

**Comment by vihan85** [comment]
> hey @vihan85 , thank you for the report. Is this an issue for the UI of demo application?
@MartinCupela 
yes, I found it on your demo.

**Comment by MartinCupela** [comment]
So the issue description confused me, as I was typing characters and spaces, but the actual thing to type is not shown correctly by the Github markdown parser. After setting the issue description to edit mode I have seen the below:

![image](https://github.com/user-attachments/assets/7232e16c-fab8-4fc5-a688-ed5aefd04729)

 But if you take a look at how GH parses the markdown, it is the same as the message. I cannot therefore consider this a bug

![image](https://github.com/user-attachments/assets/330c443e-7fd3-46bb-a744-204267c90e09)

**Comment by minhth1529** [comment]
@MartinCupela it just show example, you can test that on you demo page

**Comment by MartinCupela** [comment]
Yes, but it behaves as expected. See how it is rendered in this issue description

**Comment by MartinCupela** [comment]
You are quoting something, so the white spaces will not be trimmed

**Comment by minhth1529** [comment]
I just typing:                                                      test. do not quote

**Comment by MartinCupela** [comment]
Quoting in markdown is putting character `>` at the beginning of the line. That is what your issue description contains. Your last message is confusing.

**Comment by minhth1529** [comment]
oh That wasn't my intention, I just wanted it to appear similar to the demo


https://github.com/user-attachments/assets/e861cbb4-7777-4005-bde5-d3b037940b5f

**Comment by MartinCupela** [comment]
test

The same thing happens in GitHub as you can see above in this message

**Comment by MartinCupela** [comment]
This is not a bug

**Comment by vihan85** [comment]
Hi @MartinCupela 

You can watch the video below.

Can you support line breaks like when entering a consecutive string that doesn't contain spaces?

https://github.com/user-attachments/assets/3960306f-126e-47f2-96fe-c0dc76d6fca4

**Comment by MartinCupela** [comment]
Hey @vihan85 , the whitespace is not trimmed, because that is how MD is interpreted by the parser. It is by design. If you would like to change the behavior, I encourage you to provide you custom remark plugins. The guide is available here:

https://getstream.io/chat/docs/sdk/react/components/message-components/render-text/#custom-remark-and-rehype-plugins

You can take an inspiration from an existing plugin in the SDK:

https://github.com/GetStream/stream-chat-react/blob/master/src/components/Message/renderText/remarkPlugins/keepLineBreaksPlugin.ts
