### ISSUE TITLE
bug: Some HEIC images are not converted to supported one after uploading to Stream

### ISSUE THREAD

**Issue by DmitriyNikolenko** [GetStream/stream-chat-react#2546]
**Describe the bug**

We upload HEIC files as attachments. The problem is that sample HEIC images uploaded from the internet are successfully displayed, but HEIC images made via iPhone camera are not displayed. It looks like iPhone camera images are not converted, because following the final Stream link I can download it and see open on my Mac.

**To Reproduce**

1. Go to Chat
2. Click on the image attachment icon
3. Attach HEIC image (https://drive.google.com/file/d/18HiCC2MCRpUwnkfWV4AR85Wi9a6GROs8/view?usp=sharing)
4. See that neither of the HEIC previews is displayed properly

**Expected behavior**

HEIC images are correctly displayed

**Screenshots**

<img width="695" alt="Screenshot 2024-10-28 at 10 38 32" src="https://github.com/user-attachments/assets/aebc18c9-bc95-4ab0-b127-c676fef6c581">

<img width="493" alt="Screenshot 2024-10-28 at 10 41 31" src="https://github.com/user-attachments/assets/4ef61299-39a2-45c2-9fdd-d1e09372d5b3">

```
{
    "file": "https://us-east.stream-io-cdn.com/1206230/images/6ffb3134-02a9-43d7-b522-73bd3fd2f25b.heic-iryna-IMG_8758.heic?Key-Pair-Id=**XXXXX**",
    "duration": "1228.84ms"
}
```

**Package version**
 - "stream-chat": "8.37.0"
   - "stream-chat-react": "11.23.1"

**Desktop:**

- OS: Mac Sonoma 14.5
- Browser Chrome 129.0.6668.90

**Comment by MartinCupela** [comment]
@DmitriyNikolenko Stream is not converting your assets. You will need to integrate a 3rd party provider for format conversion.

**Comment by MartinCupela** [comment]
That behavior depends on the browser, not the SDK. The browser renders the images and throws error if it cannot.

**Comment by DmitriyNikolenko** [comment]
The docs describes that HEIC are supported
![Uploading SmartSelect_20241028_112704_Chrome.jpg…]()

**Comment by MartinCupela** [comment]
The link you provided is not valid

**Comment by MartinCupela** [comment]
I remember you claimed some HEIC images were displayed and some not. Again, if the message can be rendered depends on the browser, not the SDK.
