### ISSUE TITLE
Cannot find namespace 'JSX'

### ISSUE THREAD

**Issue by GuysmoB** [GetStream/stream-chat-react#2575]
Hi,

After upgrading to React 19, I'm not able to build my app with `npm run build`
![image](https://github.com/user-attachments/assets/456ad21e-fc33-4c0c-a00f-e2eef7a8b5ce)

I updated these libs according to the React 19 upgrade guide : [https://react.dev/blog/2024/04/25/react-19-upgrade-guide](url) 
- npm install --save-exact react@^19.0.0 react-dom@^19.0.0
- npm install --save-exact @types/react@^19.0.0 @types/react-dom@^19.0.0

**Package version**
- stream-chat-react: 12.7.1,
- next: 14.2.20
- "@types/react": "19.0.0",
- "@types/react-dom": "19.0.0",
- "react": "^19.0.0",
- "react-dom": "^19.0.0",
		
**Desktop:**
- OS: W10
- Browser: Brave

Thanks !

**Comment by MartinCupela** [comment]
Hey @GuysmoB , note react versions supported by the lib in the peerDependencies in the package.json: https://github.com/GetStream/stream-chat-react/blob/0577ffdbd2abf11b6b99a2e70caa938ea19635e9/package.json#L146

We have not gone to React 19 yet.

**Comment by GuysmoB** [comment]
Thanks @MartinCupela
