### ISSUE TITLE
bug: cant react(reaction) a message in version 12 please fix it

### ISSUE THREAD

**Issue by yudhistiraak** [GetStream/stream-chat-react#2582]
cant react(reaction) a message in version 12, why?

**Comment by MartinCupela** [comment]
Hello @yudhistiraak , please file a proper issue description. The original template you erased guides you through proper filing.

**Comment by yudhistiraak** [comment]
Describe the bug

when im send message and react it, the reaction pop up doesnt show 

To Reproduce
Steps to reproduce the behavior:

Go to main chat screen
Click on open reaction icon button in message list
Expected behavior

i've tried any version, doesnt work on version 12 up

https://drive.google.com/file/d/1TAq_uPPIy1pjCVAHVWPRO8zmfCnxih_m/view?usp=drive_link

Package version

stream-chat: ^8.45.0,
stream-chat-react": ^12.6.0
