### ISSUE TITLE
bug: cant react(reaction) a message in stream-chat-react version 12

### ISSUE THREAD

**Issue by yudhistiraak** [GetStream/stream-chat-react#2583]
Describe the bug

when im send message and react it, the reaction selector doesnt open

To Reproduce

Go to main chat screen
Click on open reaction icon button in message list
Expected behavior

i've tried any version, doesnt work on version 12 up

https://drive.google.com/file/d/1TAq_uPPIy1pjCVAHVWPRO8zmfCnxih_m/view?usp=drive_link

Package version

stream-chat: ^8.45.0,
stream-chat-react": ^12.6.0

**Comment by MartinCupela** [comment]
@yudhistiraak we will need more information about you customizations to message list. Also is this a development environment with strict mode?

the google drive link is not accessible publicly.

As can be seen in the [demo](https://getstream.io/chat/demos/messaging/), the selector opens.

**Comment by MartinCupela** [comment]
Could you please share the sandbox from your video?

**Comment by yudhistiraak** [comment]
the sandbox is from https://getstream.io/chat/react-chat/tutorial/

**Comment by MartinCupela** [comment]
I am not able to reproduce the issue from your video. As can be seen from the screenshots, I am able to open the reaction selector, both on the tutorial page as well as on the sandbox page. Have you performed any customizations to the sandbox? 

<img width="891" alt="image" src="https://github.com/user-attachments/assets/d76c5aee-babc-4278-aab3-94426175224f" />

<img width="1495" alt="image" src="https://github.com/user-attachments/assets/a95a83f5-9764-473b-860b-913e8fbed421" />

**Comment by yudhistiraak** [comment]
in that sandbox tutorial the stream-chat-react version is ^11.15.0, please chek it at package.json,
change it with ^12.xx.xx version
