### ISSUE TITLE
Project using v0.12.2 Fails to Compile

### ISSUE THREAD

**Issue by reujwils** [GetStream/stream-chat-react#274]
I just started integrating GetStream into my app.  Once I import the css index like this:

import 'stream-chat-react/dist/css/index.css';

I get the following compilation error:

./node_modules/stream-chat-react/dist/css/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/stream-chat-react/dist/css/index.css)
Module not found: Can't resolve '../../assets/str-chat__reaction-list-sprite@1x.png' in '/Users/reujwils/code/src/highr/node_modules/stream-chat-react/dist/css'
Compiling...
Failed to compile.

./node_modules/stream-chat-react/dist/css/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/stream-chat-react/dist/css/index.css)
Module not found: Can't resolve '../../assets/str-chat__reaction-list-sprite@1x.png' in '/Users/reujwils/code/src/highr/node_modules/stream-chat-react/dist/css'

If I go into the node_modules/stream-chat-react directory and copy the assets folder in dist and place it one level up in the directory structure everything compiles ok.

**Comment by vicnicius** [comment]
Hello, @reujwils. Thanks for reporting this issue. The 1.0 release we did today should have the fix. You'll find more information about this new version [here](https://github.com/GetStream/stream-chat-react/blob/master/CHANGELOG.md#100-2020-05-15).

Feel free to reopen this or open a new issue if you face other problems.
