### ISSUE TITLE
Channels reloading from failing request

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#279]
We are currently using teams, and most of the time when switching from one channel to another it keeps refreshing.

The problem is a constant failing request returning 401.

`https://chat-us-east-1.stream-io-api.com/channels/messaging/e6a49dbf-3bfc-4163-872e-8d3534a2e30d/query?user_id=00010e42-8a60-45f2-be6e-4dda93c8683d&api_key=xxxxxxxxxx&connection_id=eef563c1-5bbd-434c-94f3-6eb7fe9ad26c`

The payload being sent is something like this:

```
data: {}
messages: {
    limit: 100,
    id_lt: "00019df6-e8a1-42e1-9e40-df21291166bb-ae9975d0-0108-43dc-9c10-fb8bb10e6490"
},
state: true}
```

Notice the payload is missing the "team" in the data

```
"data": {
    "team": "TEAM_ID_HERE"
}
```

**Comment by jaapbakker88** [comment]
@alexlopezit what do you mean by: 
> We are currently using teams

**Comment by alexlopezit** [comment]
> @alexlopezit what do you mean by:
> 
> > We are currently using teams

@jaapbakker88 "Multi-Tenant & Teams"

**Comment by jaapbakker88** [comment]
@alexlopezit confirmed this bug, we're looking into it.

**Comment by jaapbakker88** [comment]
@alexlopezit this issue should be fixed on our backend. Can you confirm if it's working now?

**Comment by alexlopezit** [comment]
Thanks @jaapbakker88 , trying it know and seems I am not getting the channel refresh again.
