### ISSUE TITLE
Option to disable react and reply message buttons

### ISSUE THREAD

**Issue by khanilov** [GetStream/stream-chat-react#280]
- components: `MessageList` and `Message`
- stream-chat-react version `0.11.18`
- import method `es`
- react version `16.3.1`

### What is happening?
There are no option to disable reply and react buttons in Message component.

### What should be happening?
Add reply and react options to `messageActions`, in order to control this two features.

**Comment by jaapbakker88** [comment]
@khanilov you can disable these features on the Stream dashboard, this should hide the options from the component.

**Comment by khanilov** [comment]
@jaapbakker88 I was told, that in dashboard it's only possible to disable options completely.
In our case we need to disable react & reply depending on some conditions, like user role.

**Comment by jaapbakker88** [comment]
@khanilov alright, willl look into this.

**Comment by khanilov** [comment]
@jaapbakker88 is it possible to give any timetable on this feature? Thanks.

**Comment by jaapbakker88** [comment]
@khanilov right now we're refactoring a bunch of component and taking it on as soon as we're ready to work on the relevant components. Of course you can help, what questions do you have?

**Comment by jaapbakker88** [comment]
@khalinov, this was added in version 2.6.0.
