### ISSUE TITLE
MessageInput errorHandler prop not exposed in types or docs

### ISSUE THREAD

**Issue by DamonOehlman** [GetStream/stream-chat-react#282]
Within the `<MessageInput>` component, there are a couple of call sites which reference `this.props.errorHandler`.  Unfortunately, if an error does occur, it's quite likely that this isn't set and thus causes an error itself.

![no-error-handler](https://user-images.githubusercontent.com/609693/82274292-1b111c00-99c3-11ea-8d4d-33a483d96672.png)

We hit this error because we take care of uploading attachments to our own storage buckets, and occasionally on very large file uploads the upload will fail (we are still to implement resumable uploads).

I'd be more than happy to provide an `errorHandler` to the `<MessageInput>` component but without a nasty cast in TypeScript this currently isn't possible.  Additionally, the property isn't covered in the documentation.

**Comment by DamonOehlman** [comment]
Looks like d3336ea27d0b9ec4e4c7081333c9ee88c5fb9b78 fixes this.  Is this correct?

**Comment by jaapbakker88** [comment]
@DamonOehlman this is correct!
