### ISSUE TITLE
Load and focus on particular message in MessageList

### ISSUE THREAD

**Issue by khanilov** [GetStream/stream-chat-react#289]
Hi.
We have to implement message search in our application.

We stacked on step when we have message object and need to open corresponding channel focused on that message.

The message may be long time ago, so besides focusing we also need to load that history chunk containing searched message.

Can you, please, give us some suggestions on how we can do it with current SDK components.
Thanks in advance.

**Comment by jaapbakker88** [comment]
@khanilov right now this is not technically supported yet with our components, but we're looking into solutions to actually make this a possibility.
