### ISSUE TITLE
How to customize styles?

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#29]
I've seen the [section in the readme that mentions how to customize styles](https://github.com/GetStream/stream-chat-react#customizing-styles). I don't quite understand - if we want to customize the styles, should we should be no longer using the `stream-chat-react` npm module? How do we specify to stream react chat that we want to use our styles instead of those defaults? 

It appears that styles are automatically inserted into the DOM by the component: 

![image](https://user-images.githubusercontent.com/140930/61441854-c1753680-a946-11e9-84a6-6728afb0dbac.png)

For instance, I see that `.str-chat` is has a height of `100vh` - how do I change this?

**Comment by vishalnarkhede** [comment]
Hey @codekiln 

There are two ways to customize the styles:

1. You can override the css classes (of stream-chat-react) in your project, and they will take precedence over the default classes. You can check this codepen example where I have changed the background color of chat screen and font-weight of text: https://codepen.io/vishtree/pen/rXNyep

2. You can clone the repository on your end and manually edit the styles in repository. This is the way mentioned in readme file: https://github.com/GetStream/stream-chat-react#customizing-styles

**Comment by codekiln** [comment]
Thanks, this helps. I'll use method one, so that resolves it for me. 

I'm curious though about number two - if we clone your repository and commit our scss changes into our project's repository, wouldn't that make it difficult to get updates to the components?
