### ISSUE TITLE
@mentions in a channel appear to only select from top 100 members

### ISSUE THREAD

**Issue by TravisHardman** [GetStream/stream-chat-react#290]
We came across an issue where many users in a channel were not appearing in the autocomplete for @mentions. It looks like the flow works as follows:

- Channel info retrieved by a call to the "query channels" api
- Each channel has a "members" attribute with a maximum of 100 members in it
- When typing @mentions, those 100 members are the only ones who appear in the autocomplete, even if the channel has thousands more

It seems like the autocomplete for @mentions should either trigger an API call to get all members in the channel, or otherwise the component should pull a complete list of members for the channel from the start, rather than a list of only 100.

Is there a workaround to this issue or is a fix needed?

**Comment by kmutlow** [comment]
It would be really handy if there was an extension point so that we could override the default @mentions user lookup behaviour. Not sure if it exists but we haven't stumbled across it thus far. An example use-case would be to @mention someone that is not currently in the channel and invite them in.

**Comment by vishalnarkhede** [comment]
Hey @TravisHardman @kmutlow We are already working on the fixing this and providing API endpoint to fetch members for channel. It's currently in testing phase and will be published soon within couple of weeks. I will let you guys know once it is ready :)

**Comment by vicnicius** [comment]
Since [1.2.0](https://github.com/GetStream/stream-chat-react/blob/master/CHANGELOG.md#120-2020-06-16) mentions will now use the `queryMembers` endpoint if the channel has more than 100 members.
