### ISSUE TITLE
Typescript issues with MessageSimple

### ISSUE THREAD

**Issue by khanilov** [GetStream/stream-chat-react#291]
- components: `MessageSimple Prop Types`
- stream-chat-react version `1.0.1`
- react version `16.13.1`
- typescript version `3.9.2`

### What is happening?
Changes in types in 8d72c986439121ddefc0007e0ab9cb89f558f444 produce typescript errors.

### Steps to reproduce issue

1. Use Typescript
2. Try to pass `MessageSimple` as prop to `MessageList`

### Error message in console

```
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<MessageListProps>): MessageList', gave the following error.
    Type 'typeof MessageSimple' is not assignable to type 'ComponentClass<MessageUIComponentProps, any> | FunctionComponent<MessageUIComponentProps> | undefined'.
      Type 'typeof MessageSimple' is not assignable to type 'ComponentClass<MessageUIComponentProps, any>'.
        Types of parameters 'props' and 'props' are incompatible.
          Type 'MessageUIComponentProps' is not assignable to type 'Readonly<MessageSimpleProps>'.
            Types of property 'isMyMessage' are incompatible.
              Type '((message: MessageResponse) => boolean) | undefined' is not assignable to type '(message: MessageResponse) => boolean'.
                Type 'undefined' is not assignable to type '(message: MessageResponse) => boolean'.
  Overload 2 of 2, '(props: MessageListProps, context?: any): MessageList', gave the following error.
    Type 'typeof MessageSimple' is not assignable to type 'ComponentClass<MessageUIComponentProps, any> | FunctionComponent<MessageUIComponentProps> | undefined'.
      Type 'typeof MessageSimple' is not assignable to type 'ComponentClass<MessageUIComponentProps, any>'.  TS2769
```

### Code

https://github.com/GetStream/stream-chat-react/blob/5976bf4cf6987dbc7d45838428fa65fdd2cc060d/types/index.d.ts#L988-L991

https://github.com/GetStream/stream-chat-react/blob/5976bf4cf6987dbc7d45838428fa65fdd2cc060d/types/index.d.ts#L976-L980

but

https://github.com/GetStream/stream-chat-react/blob/5976bf4cf6987dbc7d45838428fa65fdd2cc060d/types/index.d.ts#L25-L28

https://github.com/GetStream/stream-chat-react/blob/5976bf4cf6987dbc7d45838428fa65fdd2cc060d/types/index.d.ts#L324-L326

**Comment by vicnicius** [comment]
Hello, @khanilov, thanks for reporting this issue. I'll have a look at it today.
