### ISSUE TITLE
Custom message style

### ISSUE THREAD

**Issue by itwaze** [GetStream/stream-chat-react#294]
How can I change the message style?
```
<Message style={{ background: 'yellow' }} />
```
or 
```
const styledRef = React.useRef()
console.log(styledRef.current) // undefined

<Message ref={styledRef} />
```
Style and ref props not working

**Comment by jaapbakker88** [comment]
@itwaze this doesnt work as we don't pass the style prop down. To customize styling you want to customize the css included in the package.

**Comment by itwaze** [comment]
@jaapbakker88 Ok, but how can I change the message style? Can you give an example?

**Comment by jaapbakker88** [comment]
You can do it two ways:

- import our css that's included in the package and override the css for the classes you want to change
- or you can import the scss files from the package and manually rebuild the styles like this: https://github.com/GetStream/stream-chat-react#customizing-styles
