### ISSUE TITLE
Change default reactions preset

### ISSUE THREAD

**Issue by khanilov** [GetStream/stream-chat-react#297]
Hello,
We need to replace default reaction options in Message's ReactionSelector.

This one:
![Screenshot 2020-05-25 at 17 09 23](https://user-images.githubusercontent.com/52448226/82822428-7143fa80-9eae-11ea-9804-333def3c2279.png)

[Docs](https://getstream.github.io/stream-chat-react/#reactionselector) describe `reactionOptions` prop in `ReactionSelector`, that should take care of it, but looked into the library code I realised that this prop is not passed down from any of Message implementation components. So as far as I see, this prop seems unusable now.

Am I right in my assumption? If yes, can it be implemented any time soon, because AFAIK ios and android SDK's support changing default reactions preset.

Thanks

**Comment by khanilov** [comment]
Maybe you can, at least, add `ReactionSelector` and `ReactionList` to `MessageSimple` component props, with default values to current components?
Same way as done with for ex: Attachments.

It would be very handy, cause in order to change one of this two components I need to copy MessageSimple too.

**Comment by jaapbakker88** [comment]
@khanilov right now we're in the middle of refactoring these components. After that's done I'll make sure to have a look at it.

**Comment by vicnicius** [comment]
Hello, @khanilov. On the latest release, you should be able to override both the `ReactionSelector` and the `ReactionList` component from any of our message components. 

A contrived example: 
```jsx
const CustomReactionSelector = ({ handleReaction }) => (
  <ul>
    <li>
      <button onClick={(e) => handleReaction('smile-emoticon', e)}>
        :)
      </button>
    </li>
    <li>
      <button onClick={(e) => handleReaction('sad-emoticon', e)}>:(</button>
    </li>
  </ul>
);
const CustomMessage = (props) => (<MessageSimple {...props} ReactionSelector={CustomReactionSelector} />);
// ...
```
