### ISSUE TITLE
Large vertical images are not displayed correctly

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#310]
Currently when we upload vertical images and click to view, parts of the image are hidden and can't see the full image.

**Comment by jaapbakker88** [comment]
@alexlopezit we're aware of this issue and working on a fix for this!

**Comment by alexlopezit** [comment]
Great, thank you

**Comment by jaapbakker88** [comment]
@alexlopezit just released version `1.2.4` which should fix this issue.
