### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#311]
```
} else if (a.type === 'video' || a.mime_type.indexOf('video/') !== -1) {
```

Looks like `mime_type` is undefined for some reason, I just pasted a link to a page from our application in to a channel and got the error, tried to replicate on https://getstream.github.io/stream-chat-react/#channel but could not get the same result.

**Comment by jaapbakker88** [comment]
@alexlopezit what version are you on, I think this issue was fixed in a recent release.

**Comment by alexlopezit** [comment]
Thanks @jaapbakker88 , we where using version 1.0.0 updating to 1.0.1 solved it
