### ISSUE TITLE
Typescript Issues with t and tDateTimeParser

### ISSUE THREAD

**Issue by bluetoken-luke** [GetStream/stream-chat-react#354]
We are suddenly experiencing typescript errors with code that has been in place an untouched for some time.  It appears that suddenly the Channel component and MessageList component require the props t and tDateTimeParser.

![image](https://user-images.githubusercontent.com/49762288/84835488-54a46980-aff9-11ea-8644-12e9b4b69781.png)

![image](https://user-images.githubusercontent.com/49762288/84835613-96351480-aff9-11ea-993c-2c736ba2eb49.png)

EDIT: I should note that everything is working just fine if I have ts ignore the lines.

EDIT 2: Current versions...
"stream-chat": "^1.11.4",
"stream-chat-react": "^1.2.0",
"typescript": "^3.9.5",

**Comment by DamonOehlman** [comment]
Also having this problem.  Looks it was introduced in 17f49a84444a2072b80becabd345d75ed643f64a when the properties on the `TranslationContextValue` interface were marked as required.

**Comment by jaapbakker88** [comment]
@bluetoken-luke @DamonOehlman we've released a fix on v1.2.1 for this issue. We're still in the progress of tightening up our types system so this won't happen again.

**Comment by DamonOehlman** [comment]
Thanks @jaapbakker88 - just did the upgrade to `1.2.1` and I can confirm that it all builds nicely now :)
