### ISSUE TITLE
Allow Moderators to Edit and Delete Messages Without Being Admin

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#36]
Note: I've opened a [StackOverflow question GetstreamIO Chat Moderation](https://stackoverflow.com/questions/57210019/getstreamio-chat-moderation) about this, though the post here goes in to more detail. 

I see that in the Getstream.IO docs under [Default Permission Policies](https://getstream.io/chat/docs/#channel_permission_policies) a moderator is able to update and delete messages. I can also see that in [the tests for `channel_permissions` in `stream-chat-js`](https://github.com/GetStream/stream-chat-js/blob/master/test/channel_permissions.js#L371) that a moderator is indeed supposed to be able to edit and delete messages, just as the permissions matrix in the documentation specifies.  I cannot get a user that has been added as a `moderator` on a channel to successfully edit or delete messages that they did not create, however.

It does not seem to me that the current implementation of the `MessageList`, `Message`, `MessageActionsBox ` and other components have been designed for this. I also do not see an easy way to override these components.

[`MessageList` instantiates a raw `Message` component](https://github.com/GetStream/stream-chat-react/blob/929cd7ea7c35382e7334fdb1af370276f6e554e3/src/components/MessageList.js#L518), passing it a `Message` render prop with, for example, `LivestreamMessage` or another implementation. Upon render, the `Message` component [instantiates a `LivestreamMessage` but passes _itself_ as the `Message` render prop](https://github.com/GetStream/stream-chat-react/blob/929cd7ea7c35382e7334fdb1af370276f6e554e3/src/components/Message.js#L301), which makes it so that when [`MessageActionsBox` tries to retrieve its available actions, it must be from `stream-chat-react`'s implementation that excludes moderators](https://github.com/GetStream/stream-chat-react/blob/929cd7ea7c35382e7334fdb1af370276f6e554e3/src/components/MessageActionsBox.js#L61).

Going a bit deeper, `Message.canDeleteMessage` and `Message.canEditMessage` call `this.isMyMessage(message) || this.isAdmin();` and surprisingly do not attempt to query channel permissions; `this.isAdmin()` only queries whether the user has the global role of Admin. In addition to having these functions query whether a user is moderator, I would expect the implementation to check whether the user has that role app-wide or whether the user has that role only on the specific channel that has been instantiated. For example, I would expect to see something like: 

```
  isModerator = () => this.props.members[this.props.client.userID].role === 'moderator';
  isAdmin = () => this.props.members[this.props.client.userID].role === 'admin';
  canEditMessage = (message) => this.isMyMessage(message) || this.isModerator() || this.isAdmin();
  canDeleteMessage = (message) => this.isMyMessage(message) || this.isModerator() || this.isAdmin();
```

I was expecting to get typical (non-AI) moderation out of the box with `stream-chat-react` - is this even possible?

UPDATE 1:
I was able to get a user that was added as a `moderator` on a channel to be able to edit and delete actions by making moderators admins. This is a poor workaround, as moderators in my implementation are third party entities that should not have elevated permissions. Is there a way to give moderator permissions without conferring an admin role?

**Comment by tschellenbach** [comment]
Yes, this is definitely supported. Note that our moderation dashboard isn't live yet. It's almost done though, so that will make it easier to setup moderation. 

@tbarbugli can help configure the permissions

**Comment by jaapbakker88** [comment]
@codekiln I updated `stream-react-chat` to version `0.6.17` which includes support for moderators to edit and delete posts. I hope this solves your issue, let me know if you run into anything else!

**Comment by josephto** [comment]
why are Owners of the chat allowed to edit and delete anybody's chat messages? 

https://github.com/GetStream/stream-chat-react/blob/master/src/components/Message.js#L212

**Comment by tschellenbach** [comment]
Permissions can be configured per channel type: https://getstream.io/chat/docs/channel_permissions/?language=js

So you can set this up to fit your use case. What are you building?

**Comment by josephto** [comment]
A professional community platform. We're adding chat to it. 

I tried using updating the role of the channel creator from 'owner' to 'member' on channel creation as suggested in the link you provided, but it just adds the 'roles' object to the channel.data object. It doesn't seem to be modifying the channels's member.user.role

**Comment by tschellenbach** [comment]
You can ping support to ask for help with setting this up: https://getstream.io/support

**Comment by josephto** [comment]
I think I may have misunderstood the documentation. It seems like that's actually for updating a channel type? not a specific channel that's already created?

**Comment by jaapbakker88** [comment]
You can set permissions in the dashboard for your whole app. this way you can make sure Channel creators are not able to delete and edit messages. But for example only admins and moderators.
