### ISSUE TITLE
Mute and Flag actions do not appear to do anything

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#37]
As far as I can tell in version `0.6.15`, the `mute` and `flag` buttons do not do anything:
![image](https://user-images.githubusercontent.com/140930/61979183-2c66e300-afc1-11e9-8659-2732419e5b86.png)

I'm using a "livestream" type channel roughly equivalent to [the livestream example Getstream.IO has put on codepen](https://getstream.io/chat/#chat-livestream-example): 

```
const LiveObserverChatApp = ({chatChannelId, chatUserId, chatAppId, chatImage, chatName, chatUserToken}) => {
  const chatClient = new StreamChat(chatAppId);
  const chatUser = {
      id: chatUserId,
      name: chatName,
      image: chatImage
    };

  chatClient.setUser(chatUser, chatUserToken);

  const channel = chatClient.channel('livestream', chatChannelId, {});

  return <Chat client={chatClient} theme={'messaging light'}>
    <Channel channel={channel}>
      <Window hideOnThread>
        <MessageList Message={MessageLivestream}/>
        <MessageInput/>
      </Window>
      <Thread Message={MessageLivestream} fullWidth/>
    </Channel>
  </Chat>
}
```

When I log in as a user added as a moderator to the channel using the server side API or if I log in as a typical user, I do not see any result from pressing either of these actions buttons. For example, if I click "Flag", there is no indication a message is flagged. If I click "Mute", messages from that user are not muted. Are they as yet unimplemented in the components?

**Comment by tschellenbach** [comment]
@vishalnarkhede is working on the UI for this, right now the API calls are triggered, but there is no visible UI feedback

**Comment by vishalnarkhede** [comment]
@codekiln Visual response for these actions should be published today. Will let you know!!

**Comment by vishalnarkhede** [comment]
Hey @codekiln you can use v0.6.16 now.

- Have added visual response (notification) to indicate result of flagging/muting
- You can customize the message shown on screen as well by providing following functions as prop to MessageList component. Check the [component doc](https://getstream.github.io/stream-chat-react/#messagelist) for details about this function: 
    - getFlagMessageSuccessNotification
    - getFlagMessageErrorNotification
    - getMuteUserSuccessNotification
    - getMuteUserErrorNotification


Please reopen in case it doesn't work for you!
