### ISSUE TITLE
ChannelList lockChannelOrder type missing

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#378]
Currently using "stream-chat-react": "1.2.2"

"lockChannelOrder" type is missing from "ChannelListProps"

cc @tbarbugli

**Comment by jaapbakker88** [comment]
@alexlopezit I just made a release with this type added to ChannelListProps. It's on `v1.2.3`.

**Comment by alexlopezit** [comment]
Awesome, thanks @jaapbakker88
