### ISSUE TITLE
Export LoadingChannels in stream-chat-react/src/components/index.js

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#38]
I noticed [`LoadingChannels`](https://getstream.github.io/stream-chat-react/#loadingchannels) in the react component docs. I'd like to use this component while waiting for the `setUser` promise to complete, but it looks like `stream-chat-react/src/components/index.js` doesn't export it.  Is there a reason it's not exported?

**Comment by vishalnarkhede** [comment]
Looks like its missing from export list. We shall export it soon and update you!

**Comment by jaapbakker88** [comment]
I just released version `0.6.17` of `stream-chat-react`. This exports the LoadingChannels component
