### ISSUE TITLE
Allow to pass a custom LoadingIndicator to MessageList

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#382]
As some of the other component allow to pass a custom loading indicator, would be good to also allow it for the `MessageList` for UI consistency

cc @tbarbugli

**Comment by jaapbakker88** [comment]
@alexlopezit thanks for the suggestion. Will try to get that in this week.

**Comment by jaapbakker88** [comment]
@alexlopezit added the LoadingIndicator prop to MessageList in `v1.2.5`
