### ISSUE TITLE
can you make it possible to provide MessageUpdate?

### ISSUE THREAD

**Issue by plandem** [GetStream/stream-chat-react#384]
Right now we can provide component for a new message via MessageInput, but it's not possible to provide a MessageUpdate, since it's hardcoded inside of all these MessageSimple/MessageLivestream and etc.

**Comment by jaapbakker88** [comment]
@plandem, do you mean the MessageInput for editing messages is not overridable?

**Comment by plandem** [comment]
yes. E.g. it's hardcoded here: 
https://github.com/GetStream/stream-chat-react/blob/8514804c9af8c9755f0e1a7620a8efab7feb80fc/src/components/Message/MessageLivestream.js#L375

**Comment by plandem** [comment]
``` <Chat client={chat} theme="livestream">
          <Channel channel={channel}>
              <ChannelHeader live/>
                    <MessageList Message={MessageView} dateSeparator={DateSeparator} />
                    <MessageInput Input={MessageCreate} disabled={!isOnline} />
          </Channel>
        </Chat>
```
also `dateSeparator` is kinda not consistent with other names for passing components like `Message`, `Input` and etc. It's `camelCase`.

**Comment by jaapbakker88** [comment]
@plandem right now we don't support this, but I'll add it to the backlog as well. As the naming convention goes, you're right, we'll update it soon and will deprecate this old one.

**Comment by DanC5** [comment]
@plandem sorry for the delay, but the EditMessageForm can now be overridden with the EditMessageInput prop on your message UI component, https://github.com/GetStream/stream-chat-react/releases/tag/v3.4.5
