### ISSUE TITLE
How to make components aware of features?

### ISSUE THREAD

**Issue by plandem** [GetStream/stream-chat-react#385]
I.e. we don't need attachments, but we can't remove this button in message input's or action bar

**Comment by jaapbakker88** [comment]
@plandem right now we don't support this, but it's in our backlog. Please keep an eye out on this repo to see when we launch this. 

What you could do as a temporary fix is set maxNumberOfUploads to 0 and hide the button with css.

**Comment by plandem** [comment]
I tried, but button was still visible. It was disabled, but visible!

**Comment by plandem** [comment]
oh, sorry. missed that I have to update styles also!
