### ISSUE TITLE
Disable file uploads for certain users

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#39]
I'm seeking to disable file uploads for our normal users, and only enable them for our moderators. 

Using the Python API I have created a custom channel type with the following permissions, which eliminate the `UploadAttachment` permission normal users, and instead adds it to the permissions for `channel_moderator` users:
 
![image](https://user-images.githubusercontent.com/140930/62073726-48f85a80-b20f-11e9-9c1a-96dcdfaea59d.png)

When I log in as a non-moderator on a channel that is associated with that custom channel type, I'm still able to see the Upload button, and it still works as a drop zone. How do I disable file upload for certain users?

Note: here are the custom permissions: 
```
<class 'dict'>: {'permissions': [{'action': 'Allow', 'name': 'admin can do almost anything', 'resources': ['CreateChannel', 'ReadChannel', 'UpdateChannelMembers', 'UpdateChannel', 'DeleteChannel', 'CreateMessage', 'UpdateMessage', 'DeleteMessage', 'BanUser', 'UploadAttachment', 'DeleteAttachment', 'UseCommands', 'AddLinks', 'EditUser', 'RunMessageAction'], 'roles': ['admin'], 'owner': False, 'priority': 999}, {'action': 'Allow', 'name': 'Owner permissions', 'resources': ['UpdateMessage', 'DeleteMessage', 'EditUser', 'DeleteAttachment'], 'roles': [], 'owner': True, 'priority': 80}, {'action': 'Allow', 'name': 'User permissions', 'resources': ['ReadChannel', 'CreateChannel', 'CreateMessage', 'AddLinks'], 'roles': ['user', 'channel_moderator', 'channel_member'], 'owner': False, 'priority': 70}, {'action': 'Allow', 'name': 'Moderator only features', 'resources': ['ReadChannel', 'CreateChannel', 'CreateMessage', 'UpdateMessage', 'DeleteMessage', 'UploadAttachment', 'DeleteAttachment', 'UseCommands', 'RunMessageAction', 'BanUser'], 'roles': ['channel_moderator'], 'owner': False, 'priority': 60}, {'action': 'Deny', 'name': 'deny all policy', 'resources': ['*'], 'roles': ['*'], 'owner': False, 'priority': 1}], 'name': 'livestream_custom_01', 'typing_events': False, 'read_events': False, 'connect_events': False, 'search': False, 'reactions': True, 'replies': True, 'mutes': False, 'message_retention': 'infinite', 'max_message_length': 500, 'automod': 'disabled', 'automod_behavior': 'flag', 'commands': []}
```

**Comment by tbarbugli** [comment]
Hiding the upload box based on permissions is very prone to error, I suggest we at least expose a prop function like `uploadEnabled` that accepts `(user, channel)` and returns a boolean.

**Comment by codekiln** [comment]
Using the suggestion in https://github.com/GetStream/stream-chat-python/issues/6#issuecomment-516333762, I was recently able to remove channel commands, and I can see that this changes the commands available in the autocomplete. 

Similar to above, I've removed the permission for non-moderator / non-admin users to ban and unban and I would like a way to make it so that regular users do not see  the option to ban and unban. Is there a prop I can pass to limit the autocomplete commands for those users that are not moderator and do not or should not have the permission to ban and unban?

**Comment by vishalnarkhede** [comment]
Hey @codekiln ,

Thank you for bringing this up. I will discuss with team and add the things mentioned by you in our list of upcoming enhancements :)
