### ISSUE TITLE
check for event in handleDelete

### ISSUE THREAD

**Issue by plandem** [GetStream/stream-chat-react#393]
https://github.com/GetStream/stream-chat-react/blob/f89b2364199ca3490ca347d9d6cd953546ac9c4c/src/components/Message/Message.js#L324

all actions should behave in same way for consistency, e.g. like in `handleEdit`

**Comment by jaapbakker88** [comment]
Please elaborate on this

**Comment by plandem** [comment]
here you check for an event:
https://github.com/GetStream/stream-chat-react/blob/f89b2364199ca3490ca347d9d6cd953546ac9c4c/src/components/Message/Message.js#L315

but here you dont and just call `preventDefaults`:
https://github.com/GetStream/stream-chat-react/blob/f89b2364199ca3490ca347d9d6cd953546ac9c4c/src/components/Message/Message.js#L324

it's not consistent behaviour, since both handlers - action's handler from same pop menu. behaviour should be same - event required or optional.

**Comment by jaapbakker88** [comment]
@plandem thanks for elaborating, will add to the backlog of changes we need to make.

**Comment by jaapbakker88** [comment]
Ran through the code today and don't see this as an issue. Just a result of different people working on the code. With the recent addition of typescript we actually know if the event is being passed or not. Going to close this issue.
