### ISSUE TITLE
custom fields for message?

### ISSUE THREAD

**Issue by plandem** [GetStream/stream-chat-react#395]
`stream-js` allows to use custom fields for message. How to add custom fields using your react SDK? From fast scanning mode it looks like you totally rid off that functionality. Am I right (hope note, but need a help in that case)?!

**Comment by jaapbakker88** [comment]
@plandem I think you mean `stream-chat-js` and yes our components do not use the functionality of custom fields. If you want this, you would have to write your own MessageInput component, which is totally doable.

**Comment by plandem** [comment]
Well, while it's true that I could write own MessageInput, but e.g. we already had to rid off 80-90% of these react components and created own because we can't customize/remove/add something here. I would say more - this SDK is toooo coupled and hardcoded and hardly to customize at all. Even for simple cases like MessageInput.

e.g.:

this one way is hardly to customize, I have to create own components and can't pass prop based on parent container for example.
```jsx
 <MessageInput Input={MessageCreate} disabled={!isOnline} />
```

but this way is would be much easier to customize, because I don't have to jump around with context and all this things just to make `MessageCreate` aware of some props from container:
```jsx
 <MessageInput Input={<MessageCreate {...props}  />} disabled={!isOnline} />
```

And that was only one example why it's so hard to use this SDK in real project that need something not from hardcoded demos.

P.S.: we literally use only Chat, Channel, MessageInput, MessageList from this SDK. every possible `coupled` component already rewritten by us and from components that I mentioned we use only few handlers/callbacks. What is the reason to have SDK if end-user have to re-create everything by own.

**Comment by jaapbakker88** [comment]
What exactly do you want to do? Because you could do something like if you know what fields you want to add to the component:
```
const InputComponent = props => {
    const sendMessage = (message) => {
        const newMessage = {
            extraField: 'blha',
            ...message
        }

        return props.sendMessage(newMessage);
    }

    return <MessageInputLarge sendMessage={sendMessage} {...props} />
}
```

and then add it to our MessageInput as a custom component:

```
<MessageInput Input={InputComponent}/> 
```

But if you want to customise the look and feel of it, at some point you're going to have to write your own, there's only a certain amount of customisability we can offer out of the box.

**Comment by plandem** [comment]
and it will not work for edit/update :(

**Comment by jaapbakker88** [comment]
@plandem, had a look at this, this code works:

```
const InputComponent = props => {
  const channelContext = useContext(ChannelContext);
  const sendMessage = async (message, channelCid) => {
      const newMessage = {
        ...message,
      }
      newMessage.extraField = 'test 123123';

      await channelContext.channel.sendMessage(newMessage)
      // 
  }

  return <MessageInputLarge overrideSubmitHandler={sendMessage}  {...props} />
}
```
