### ISSUE TITLE
TypeError: Cannot read property 'findIndex' of undefined

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#402]
Getting the error when deleting 2 channels one after the other one

https://github.com/GetStream/stream-chat-react/blob/c8b98967ea955853955c21447d24023c732156e6/src/components/ChannelList/hooks/useChannelDeletedListener.js#L13

**Comment by vishalnarkhede** [comment]
Hey @alexlopezit , we will fix this issue soon!! The fix is ready in this PR - https://github.com/GetStream/stream-chat-react/pull/396/files#diff-30f700884e8387a6109e17184b107a5c

**Comment by jaapbakker88** [comment]
@alexlopezit this should be fixed in the latest release `2.0.1`

**Comment by alexlopezit** [comment]
Thank you
