### ISSUE TITLE
When will hooks be exported?

### ISSUE THREAD

**Issue by brandonhall** [GetStream/stream-chat-react#421]
Use Case: We want to mention users that aren't in a chat

I implemented this feature with `stream-chat-react-native` fairly easily by passing a trigger object, but passing triggers isn't supported in `stream-chat-react`. I was going to build a modified version of `MessageInputFlat` with a modified `ChatAutoComplete` in order to change the triggers, but was stopped out by the `useMessageInput` hook. `useMessageInput` contains a significant amount of logic and re-implementing the hook seems so dirty. Anyway, if the hook was exported I'd be able to work around the trigger deficiency.

1. Are there plans to allow triggers to be passed?
2. Can you export the hooks for use by developers?

Thanks!

**Comment by jaapbakker88** [comment]
@brandonhall right now we're in the process of refactoring and moving everything to hooks. This is still a work in progress, but end of next week we should have a release that includes these hooks so they can be used by anyone writing their own components. 

I'll have to look into the triggers, but if you can wait a bit on the hook this should make it easier for you to built a custom component.

**Comment by brandonhall** [comment]
Thanks for the reply @jaapbakker88. For what it's worth, I believe the ability to modify triggers would be the simplest approach.

**Comment by jaapbakker88** [comment]
@brandonhall let me look into how React Native handles it and if I can move it to the this library easily.

**Comment by jaapbakker88** [comment]
@brandonhall we've just released version 2.0.1 which exports the useMessageInput hook and also allows setting autocompleteTriggers on the MessageInput components to override the triggers that come with the components. Hope that allows you to do what you want to do.

**Comment by brandonhall** [comment]
@jaapbakker88 Thank you!
