### ISSUE TITLE
The app allows you to send empty messages 

### ISSUE THREAD

**Issue by jiaskedulo** [GetStream/stream-chat-react#425]
**Steps to reproduce** 

1. Send a picture first
2. Press Enter key 

**Actual results**
It allows you to send empty messages

<img width="1162" alt="Screen Shot 2020-07-09 at 2 38 13 pm" src="https://user-images.githubusercontent.com/56703852/87000156-b2dafb80-c1f7-11ea-8ffd-e4a6999b97dd.png">

**Comment by alexlopezit** [comment]
cc @tbarbugli

**Comment by jaapbakker88** [comment]
@alexlopezit @jiaskedulo thanks for your report, we're looking into this.

**Comment by jaapbakker88** [comment]
@alexlopezit @jiaskedulo we just released version 2.0.1 which should resolve this issue, let me know if it works for you.
