### ISSUE TITLE
MessageInput disable file upoload and paste

### ISSUE THREAD

**Issue by kovacsmarcellcodinglab** [GetStream/stream-chat-react#447]
MessageInput disable file upoload and paste

How to solve this request?
I set up Channel props, but nothing happend:
multipleUploads?: boolean => false
acceptedFiles?: string[] => []
maxNumberOfFiles?: number => 0

I could use doFileUploadRequest, doImageUploadRequest method? How to cancel upload before insert tumbnail into textarea?
How to reach onPaste method in MessageInputUIComponentProps? I could overwrite it?

Thx your help.

Marcell

**Comment by jaapbakker88** [comment]
@kovacsmarcellcodinglab not sure what you want to do exactly, do you want to completely disable file uploads? Or just uploading onPaste?

**Comment by kovacsmarcellcodinglab** [comment]
Hi,

I'd like to disable both of them.

Thx
Marcell

**Comment by jaapbakker88** [comment]
@kovacsmarcellcodinglab I looked into this, but it seems that setting maxNumberOfFiles to 0 does the trick:

```
<Channel  maxNumberOfFiles={0}> 
```
