### ISSUE TITLE
ChannelList sending unnecessary requests

### ISSUE THREAD

**Issue by yangyu0311ugroop** [GetStream/stream-chat-react#451]
Hi, 

I am encountering an issue the channel list component will resend the query Channel request whenever re-render occurs. Before 1.1.2 I do not have this problem, the issue occurs after the Channel list rewrites via React hooks. To be more specific, I am trying to adjust the channel list height when window resize occurs. Is there any way, I can stop the request, due to the rate-limit, if the user always resizes the window, soon it will hit the rate limit exceeded, then an error will occur. 

My expected result is whenever UI re-render shall not trigger the query channel call. 

Thank you

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/4482'>Zendesk ticket #4482</a>:<br><br>Hi,

Thanks for getting in touch.
I'm passing this on to one of our React developers.
He'll get back to you shortly.

Best regards,
Seni

**Comment by jaapbakker88** [comment]
@yangyu0311ugroop can you share a bit of the code you're using to render the ChannelList, and what do you exactly mean by rerendering when you're resizing the height? How are you resizing the height? Also what version of our library are you on?

**Comment by yangyu0311ugroop** [comment]
I am using a lib `ReactResizeDecetor` My goal is always to keep the chat height = window.height - header.height - menubar.height. 

I have a working version using 1.0.0, which channel list is still using React PureComponent class. After the ChannelList rewrite as React hooks, I always have this problem, and now I am using 2.0.1. Still, the same issue, whenever I try to recalculate the height, the loading indicator shows, and a bunch of channel requests are called.

![Screen Shot 2020-07-16 at 11 53 58 pm](https://user-images.githubusercontent.com/22187779/87679546-ab02f480-c7bf-11ea-9730-4cc79444bcaf.png)
 
```
<Chat client={props.streamChat} theme="team light" data-testid="Chat">
      <ReactResizeDetector handleWidth handleHeight onResize={onResize} />
      <ChannelList
        EmptyStateIndicator={EmptyStateIndicator}
        LoadingErrorIndicator={ChatDown}
        List={ChannelListTeam}
        Preview={ChannelListPreview}
        filters={props.filters}
        sort={props.sort}
        lockChannelOrder
        setActiveChannelOnMount={false}
        onAddedToChannel={onAddedToChannel}
        onRemovedFromChannel={onRemovedFromChannel}
        onChannelDeleted={onChannelDeleted}
        onMessageNew={onMessageNew}
        Paginator={InfiniteScrollPaginator}
      />
        <Channel>
          <Window
            innerStyle={{
              height: props.height - height,
              borderRight: '1px solid rgba(220,220,220,0.5)',
              borderBottom: '1px solid rgba(220,220,220,0.5)',
            }}
          >
            <ChannelHeader />
            <MessageList
              HeaderComponent={MessageHeaderComponent}
              Message={MessageTeam}
            />
            <MessageInput Input={input} focus />
          </Window>
          <Thread />
          <ChannelDetail width={dimensions.width} />
        </Channel>
</Chat>
```

Also if you see the props I passed on the channel list, It doesn't matter if I use `ChannelListTeam` from your lib or I provide my own same thing. 
In fact, if I provide my own ChannelListTeam, make the situation even worse, because the way I customize the ChannelList is connected to the redux store using a selector, it seems to me that will also cause channel query request fired a few times.

**Comment by vishalnarkhede** [comment]
@yangyu0311ugroop we only redo `/channels` api call on filters change. Any chance, your `props.filter` changes (by reference) when you resize?

**Comment by yangyu0311ugroop** [comment]
@jaapbakker88 @vishalnarkhede I don't think it has anything to do with the filter 

https://github.com/ugr00p/stream-chat-react/tree/2.0.1

I fork your project and modified the example codes in messaging 

https://github.com/ugr00p/stream-chat-react/blob/2.0.1/examples/messaging/src/App.js

You can see the channel request are firing endlessly until the server disconnect the client.

**Comment by jaapbakker88** [comment]
@yangyu0311ugroop so we figured out the issue and will update our examples. Because your setting state on every resize we will rerender the component. And because it has some constants(`filters`, `sort`, `options` and `InfiniteScrollPaginator`) defined in the render function, these will get updated and passed down on every state change, so everything starts rerendering. You can fix it in the following way:

```
/* eslint-disable */
import React, { Component } from 'react';
import Grid from '@material-ui/core/Grid';
import { StreamChat } from 'stream-chat';
import ReactResizeDetector from 'react-resize-detector';
import {
  Chat,
  Channel,
  MessageList,
  MessageInput,
  MessageInputFlat,
  MessageSimple,
  ChannelHeader,
  ChannelPreviewMessenger,
  InfiniteScrollPaginator,
  ChannelListMessenger,
  ChannelList,
  Window,
  Thread,
  TypingIndicator,
} from 'stream-chat-react';
import 'stream-chat-react/dist/css/index.css';
import './App.css';

const urlParams = new URLSearchParams(window.location.search);
const theme = urlParams.get('theme') || 'light';


// Move these here, outside your App component.
const filters = { type: 'messaging' };
const sort = {
  last_message_at: -1,
  updated_at: -1,
  cid: 1,
};
const options = { state: true, watch: true, presence: true };
const Paginator = (props) => (
  <InfiniteScrollPaginator threshold={300} {...props} />
);


class App extends Component {
  
  constructor(props) {
    super(props);
    this.chatClient = new StreamChat('qk4nn7rpcn75');
    // if (process.env.REACT_APP_CHAT_SERVER_ENDPOINT) {
    //   this.chatClient.setBaseURL(process.env.REACT_APP_CHAT_SERVER_ENDPOINT);
    // }
    this.chatClient.setUser(
      {
        id: 'example-user',
      },
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZXhhbXBsZS11c2VyIn0.HlC0dMKL43y3K_XbfvQS_Yc3V314HU4Z7LrBLil777g',
    );
    this.state = {
      width: -1,
    }
  }

  componentDidMount() {
    setInterval(() => {
      this.setState({
        width: this.state.width + 1
      });
    }, 3000);
  }

  onResize = (parentWidth)=>{
     this.setState({
       width: parentWidth
     });
  }

  render() {

    return (
      <Grid container direction={'column'}>
        <Grid>
          Header
        </Grid>
        <Grid>
          Menu
        </Grid>
        <Grid>
          <ReactResizeDetector handleWidth handleHeight onResize={this.onResize} />
          <Chat client={this.chatClient} theme={`messaging ${theme}`}>
            <ChannelList
              List={ChannelListMessenger}
              Preview={ChannelPreviewMessenger}
              filters={filters} // move this out of the component in its own constant
              sort={sort} // move this out of the component in its own constant
              options={options} // move this out of the component in its own constant
              Paginator={Paginator}. // move this out of the component in its own constant
            />
            <Channel>
              <Window>
                <ChannelHeader />
                <MessageList TypingIndicator={TypingIndicator} />
                <MessageInput Input={MessageInputFlat} focus />
              </Window>
              <Thread Message={MessageSimple} />
            </Channel>
          </Chat>
        </Grid>
      </Grid>
    );
  }
}

export default App;
```

**Comment by yangyu0311ugroop** [comment]
@jaapbakker88 Thank you for the update. I think that will solve the issue in the example. 
However, I have a question, let's say I want to provide my own List Component called `MyChannelListTeam`. 

In that component, I have my own logic to connect the redux store by using a selector. So let's say this component will render 3 times, because of the selector, so based on my testing, the channels requests will be called 3 times. I think it's a waste. Also below is the code that how I use in react-stream-chat 1.0.0, as you can see `filter`  and `sort` are passed as props. Re-rendering will happen height is re-calculated.  Any suggestion how can I overcome it? 

So in summary, I encounter two issues that re-render is not something I can avoid, the first case, customize the List component. the second case is that filter and sort are passed as props from the parent component, any changing state will cause render. 

PS. I can set a debounce to achieve the page height resize, but I feel like it's just a workaround. 

```
<Chat client={props.streamChat} theme="team light" data-testid="Chat">
      <ReactResizeDetector handleWidth handleHeight onResize={onResize} />
      <ChannelList
        EmptyStateIndicator={EmptyStateIndicator}
        LoadingErrorIndicator={ChatDown}
        List={ChannelListTeam}
        Preview={ChannelListPreview}
        filters={props.filters}
        sort={props.sort}
        lockChannelOrder
        setActiveChannelOnMount={false}
        onAddedToChannel={onAddedToChannel}
        onRemovedFromChannel={onRemovedFromChannel}
        onChannelDeleted={onChannelDeleted}
        onMessageNew={onMessageNew}
        Paginator={InfiniteScrollPaginator}
      />
        <Channel>
          <Window
            innerStyle={{
              height: props.height - height,
              borderRight: '1px solid rgba(220,220,220,0.5)',
              borderBottom: '1px solid rgba(220,220,220,0.5)',
            }}
          >
            <ChannelHeader />
            <MessageList
              HeaderComponent={MessageHeaderComponent}
              Message={MessageTeam}
            />
            <MessageInput Input={input} focus />
          </Window>
          <Thread />
          <ChannelDetail width={dimensions.width} />
        </Channel>
</Chat>
```

**Comment by yangyu0311ugroop** [comment]
hm, I just noticed that you guys added the React.memo around the channel list. Maybe that will solve the problem, I will test it and let you know.

**Comment by jaapbakker88** [comment]
@yangyu0311ugroop I'll make a new release later today which will include this change
