### ISSUE TITLE
Non responsive hamburger menu

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react#457]
When the browser window is shrunk a hamburger menu appears in the channel header (instead of the peaking channel list element like in your examples). This menu icon is non-responsive.

<img width="661" alt="Screen Shot 2020-07-20 at 10 30 02 AM" src="https://user-images.githubusercontent.com/7548096/87949568-30163400-ca74-11ea-9c33-105c20c7548f.png">

This is the code:

```
      <Chat client={chatClient} theme="messaging light">
        <ChannelList filters={filters} sort={{ last_message_at: -1 }} />
        <Channel>
          <Window>
            <ChannelHeader />
            <MessageList />
            <MessageInput />
          </Window>
          <Thread />
        </Channel>
      </Chat>
```

I've basically copied the examples, however the UI appears different from CodePen. This is on v1.2.5.

**Comment by jaapbakker88** [comment]
@amardeepranu are you on v1.2.5 or the codepen examples?

**Comment by amardeepranu** [comment]
v1.2.5 doesn't run on codepen unfortunately, the latest example I could run is v1.1.0 (https://cdn.jsdelivr.net/npm/stream-chat-react@1.1.0/dist/browser.full-bundle.min.js) - and this issue is reproduced there in a different way: the channel completely disappears with no hamburger menu.

Also, I can't even run v0.11.3 (the codepen version) locally because there are internal typescript errors in index.ts preventing me from compiling:

```
Interface 'ChannelPreviewProps' incorrectly extends interface 'ChatContextValue'.
  Types of property 'setActiveChannel' are incompatible.
    Type '(channel: Channel, watchers?: ImmutableObject<{ [user_id: string]: User; }> | undefined, e?: BaseSyntheticEvent<object, any, any> | undefined) => void' is not assignable to type '(channel: Channel, event: SyntheticEvent<Element, Event>) => void'.
      Types of parameters 'watchers' and 'event' are incompatible.
        Type 'SyntheticEvent<Element, Event>' is not assignable to type 'ImmutableObject<{ [user_id: string]: User; }>'.
          Type 'SyntheticEvent<Element, Event>' is missing the following properties from type 'ImmutableObjectMixin<{ [user_id: string]: User; }>': set, setIn, getIn, asMutable, and 5 more.
```
