### ISSUE TITLE
Stream react docs can’t be viewed on mobile

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react#459]
The docs (https://getstream.github.io/stream-chat-react) are blocked by a full screen channel screen - it can’t be dismissed.

![6E1A86CE-4A21-46D5-9A7A-AF0A0563734A](https://user-images.githubusercontent.com/7548096/87997429-0fc19600-cac3-11ea-9e88-45d78d6d8850.png)

gz#4534

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/4534'>Zendesk ticket #4534</a>:<br><br>Hi,

Thanks for getting in touch.
I'm not sure I understood your report. Are you using React components on mobile ?
React components are for web integration, for mobile we offer React-Native, iOS and Android SDKs.

Best regards,

**Comment by amardeepranu** [comment]
This is not an integration issue, its your documentation website when opened in Safari on iPhone.

To reproduce:

1. Open this url on your mobile device: https://getstream.github.io/stream-chat-react

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/4534'>Zendesk ticket #4534</a>:<br><br>Hello - thank you for the report. Our entire website is getting a bit of an overhaul later this year and we'll be sure to include better responsiveness on our documentation.
