### ISSUE TITLE
Missing props in ChannelListUIComponentProps

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react#464]
In the documentation for the `ChanneList` https://getstream.github.io/stream-chat-react/#channellist it states the following for the `List` prop:

```
It has access to some additional props:

setActiveChannel {function} Check chat context
activeChannel Currently active channel object
channels {array} List of channels in channel list
```

These are present however they are missing from the type definition:

https://github.com/GetStream/stream-chat-react/blob/53f85bf515e8bc959f44914b873abe0f8ad68b57/types/index.d.ts#L244-L267

Could you please add them? Thanks!

gz#4550

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/4550'>Zendesk ticket #4550</a>:<br><br>Hi,

Thanks for the report.
I'm passing this on to our React team.

Best regards,

**Comment by jaapbakker88** [comment]
They are present but you want to get them using `useContext(ChatContext)` we're slowly deprecating these props that are being passed down.

**Comment by amardeepranu** [comment]
Sounds good - will do!

**Comment by amardeepranu** [comment]
@jaapbakker88 How would I access the channels in the channel list via the ChatContext? it's not listed a property.

What we're trying to do is customize the message preview UI (use our own component) and display that as the list in the ChannelList, but now I can't access the channels the ChannelList currently has to accomplish this.

Any ideas? Much thanks!
