### ISSUE TITLE
client Required by ChatContextValue breaks withChatContext

### ISSUE THREAD

**Issue by bluetoken-luke** [GetStream/stream-chat-react#467]
Updating stream-chat and stream-chat-react today in an effort to hopefully resolve a different issue.  When updating i ran into the following TS issue that seems to break or render withChatContext useless.

Example:

```
type TComponentProps = IComponentCustomProps & ChatContextValue;

const CustomComponent = withChatContext(
  ({
    customId,
    customProp1,
    customProp2,
    client,
    ...props
  }: TComponentProps) => {
```

```
export interface ChatContextValue {
  client: Client.StreamChat;
  channel?: Client.Channel;
  setActiveChannel?(
    channel?: Client.Channel,
    watchers?: { limit?: number; offset?: number },
    event?: React.SyntheticEvent,
  ): void;
  navOpen?: boolean;
  openMobileNav?(): void;
  closeMobileNav?(): void;
  theme?: string;
  mutes?: Client.Mute[];
}
```

I am using withChatContext to get access to the chat client.  However, because client is now required on ChatContextValue, I can not use 
```
<CustomComponent />
```
 without passing in client which defeats the point of using withChatContext.

Curious if this is a bug or if I missed some change to withChatContext?  Maybe withChatContext no longer returns ChatContextValue?

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/4582'>Zendesk ticket #4582</a>:<br><br>Assigning **Jaap Bakker**​

**Comment by bluetoken-luke** [comment]
Following up, I was able to work around the issue above by doing the following.  Not sure if that helps resolve the root issue at all.  Figured I'd throw it out there.

```
type ClientlessChatContextValue = Omit<ChatContextValue, 'client'>;
interface CustomChatContextValue extends ClientlessChatContextValue {
  client?: StreamChat;
}
```

**Comment by jaapbakker88** [comment]
@bluetoken-luke I will look into this issue, I do have to note that we're going to deprecate the HOCs for context and switching to the useContext hook implementation completely.

**Comment by bluetoken-luke** [comment]
Fantastic.  Wasn't aware of the useContext hook.  I like the idea of that much more than using the HOC as well.  I will look to get switched over to the hook here today.

**Comment by jaapbakker88** [comment]
Awesome, let us know if you need any help!

**Comment by bluetoken-luke** [comment]
Was able to get this converted over.  All good

**Comment by jaapbakker88** [comment]
Good to hear!
