### ISSUE TITLE
Unable to query channels by members using $autocomplete

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react#468]
We're trying to search for channels by member name but it looks like the `$autocomplete` query function is disabled. I receive the following error:

```
Error: StreamChat error code 4: QueryChannels failed with error: "autocomplete is not enabled for field channels.members."
```
for the following query:

```
{ type: "messaging", members: { $in: [props.userId], $autocomplete: "a" } };
```

So I'm trying to find all channels that I belong to that also have the users with names that contain "a".

Will this be enabled anytime soon?

I'm guessing the workaround here is to query all users with $autocomplete then use those ids in the the channel query?

gz#4583

**Comment by jaapbakker88** [comment]
@amardeepranu you cant use the autocomplete for members on the queryChannels function, this only works on the queryMembers function. So your second solution is probably the best workaround right now.

**Comment by amardeepranu** [comment]
Sounds good - thanks!

**Comment by amardeepranu** [comment]
@jaapbakker88 when querying channels with this:

`{ type: "messaging", members: { $in: [props.userId, "263"] } }`

I get all chats that `props.userId` are a part of AND chats that `263` are a part of. How do I query for channels that they are both participants of together only?

**Comment by amardeepranu** [comment]
I've tried the `$and` operator as per the mongo docs, but I get back this error from the API:

```Error: StreamChat error code 4: QueryChannels failed with error: "operator $and doesn't support matching array values"```

**Comment by jaapbakker88** [comment]
@amardeepranu you'd want to do it like this:
```
$and: [ members: { $in:[ a ] }, { members: { $in: [ b ] } } ]
```
