### ISSUE TITLE
Hooks typescript definitions are missing

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react#481]
The typescript definitions for all the custom hooks are missing.

gz#5207

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5207'>Zendesk ticket #5207</a>:<br><br>Thanks for the heads up. The team is working on adding TS support for all of our applicable repo's, but it is taking some time.

**Comment by vicnicius** [comment]
Hello, @amardeepranu. We [just released v.3.2.2](https://github.com/GetStream/stream-chat-react/releases/tag/v3.2.2), which comes with type definitions for custom hooks.
