### ISSUE TITLE
Channel sorting broken on v2 and above

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react#483]
- When a message is sent in a channel the list's sorting does not update (the channel in which the message was sent doesn't go to the top and the preview does not update)
- The preview is updated if another channel is selected but the sorting is still not updated
- This doesn't happen on v1.2.5
- No errors in the console

gz#5223

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5223'>Zendesk ticket #5223</a>:<br><br>Hello, what is the filter and sort parameter you're using for the channelList component please. I will try to reproduce.

**Comment by amardeepranu** [comment]
const filters = { type: "messaging", members: { $in: [props.userId] } };
  const sort = { has_unread: -1, last_message_at: -1, created_at: -1 };

**Comment by amardeepranu** [comment]
To reproduce: have multiple channels in the channel list -> select a channel thats not on the top -> send a message -> observe the channel list not updating

**Comment by jaapbakker88** [comment]
@amardeepranu can you share a bit more of your code, I'm not able to reproduce this issue in our sample apps.

**Comment by amardeepranu** [comment]
Sure! My code is below, perhaps its caused by the initialization of the stream client in the effect hook?

```
import React, { useEffect, useState } from "react";
import axios from "axios";
import {
  Chat as ChatContainer,
  ChannelList,
  Window,
  MessageList,
  MessageInput,
  Thread,
  Channel as ChannelComponent,
  ChannelHeader,
} from "stream-chat-react";
import { StreamChat } from "stream-chat";

const initializeStreamChat = async (id: string, csrfToken: string, streamChatClient: StreamChat) => {
  const fetchToken = async () => {
    const response = await axios.post("/chat/authenticate", {
      authenticity_token: csrfToken,
    });

    if (!response.data?.token) {
      throw new Error("Failed to authenticate chat");
    }

    return response.data.token as string;
  };

  const info = await streamChatClient.setUser({ id: id }, async () => {
    const token = await fetchToken();
    return token;
  });

  return info;
};

interface ChatProps {
  userId: string;
  isAdmin: boolean;
  csrfToken: string;
  streamAPIKey: string;
  memberId?: string;
}

const Chat = (props: ChatProps) => {
  const [chatClient] = useState(new StreamChat(props.streamAPIKey));
  const filters = { type: "messaging", members: { $in: [props.memberId || props.userId] } };
  const sort = { has_unread: -1, last_message_at: -1, created_at: -1 };

  useEffect(() => {
    initializeStreamChat(props.userId, props.csrfToken, chatClient);
  }, [props]);

  return (
    <ChatContainer client={chatClient} theme="messaging light">
      <ChannelList filters={filters} sort={sort as any} />
      <ChannelComponent>
        <Window>
          <ChannelHeader />
          <MessageList />
          <MessageInput />
        </Window>
        <Thread />
      </ChannelComponent>
    </ChatContainer>
  );
};

export default Chat;
```

**Comment by amardeepranu** [comment]
@jaapbakker88  I've fixed this by only passing the client prop to the Chat component once the setUser method has been called. It's strange though that this wasn't an issue for v1 but broke channel list sorting for v2

**Comment by jaapbakker88** [comment]
@amardeepranu thanks for letting us know, I'll investigate further as this behaviour seems weird.
