### ISSUE TITLE
How to refresh channel list when hiding / reappearing channel

### ISSUE THREAD

**Issue by bizley** [GetStream/stream-chat-react#484]
Hi, guys. Great work with this service, I love it.
I've got only one problem with it - I don't know how to force channel list to refresh when user hides the channel.

I'm using this set of components:

```js
<Chat client={client} theme={'livestream light'}>
    <ChannelList
        filters={filters}
        sort={{last_message_at: -1}}
    />
    <Channel>
        <Window>
            <ChannelHeader/>
            <MessageList/>
            <MessageInput/>
        </Window>
        <Thread/>
    </Channel>
</Chat>
```

1. I've got custom `Preview` component for `ChannelList` that adds button to hide the channel when it's of `one-to-one` type. Hiding itself just triggers `props.channel.hide()`.
2. I've got additional component that allows to search for channel users and to select one or more to start group channel between them (`one-to-one`).

- When creating new channel that was never active before and activating it everything works like expected, channel's list is refreshed.
- When clicking the hide button (for the channel in custom `Preview` component) the list is not refreshed although after the manual page refresh list appears without hidden channel so hiding itself works.
- When restarting the previously hidden conversation I call `watch()` on it and in callback I check if it's hidden - and if so I call `show()` on it and activate the channel - activated channel is indeed the one I want to see but it's not appearing on the channel list. (Again after manual refresh it appears).

I don't want to delete such channels instead of hiding them to not lose the history of messages.

Could you point me to the right direction with this? I'm using stream-chat v1.14.0 and stream-chat-react v2.2.0.

gz#5240

**Comment by jaapbakker88** [comment]
#485 this should add support for the `channel.hidden` event and remove it from the list. 

still working on `channel.visible`.

**Comment by bizley** [comment]
Cheers :) I can confirm, it works.
