### ISSUE TITLE
React duplicate keys

### ISSUE THREAD

**Issue by tomdebuyser** [GetStream/stream-chat-react#489]
I created some channels and show them by using the code shown in the react chat tutorial for a channel list. It gives me react warnings about duplicate keys (image below)

Not breaking, but worth mentioning.

<img width="648" alt="Screenshot 2020-08-17 at 15 27 55" src="https://user-images.githubusercontent.com/8437849/90401561-690aee00-e09e-11ea-8701-a98a950a654e.png">

gz#5363

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/5363'>Zendesk ticket #5363</a>:<br><br>Thanks for bringing this up. As you mention, this should not be breaking but it is worth some attention.
