### ISSUE TITLE
Client not updating activeChannels when deleting a channel

### ISSUE THREAD

**Issue by santipalenque** [GetStream/stream-chat-react#490]
calling `await channel.delete();` does not update the activeChannels prop on chat client

gz#5430

**Comment by jaapbakker88** [comment]
Can you give a bit more details about this problem. What happens, what do you expect to happen.

**Comment by santipalenque** [comment]
Sure, so I have this layout: 
`<Chat client={chatClient} theme={"messaging light"} initialNavOpen={false}>
                <div className="list-group">
                    <ChannelList
                        filters={{type: "messaging", members: {$in: [user.id]}}}
                        sort={{last_message_at: -1}}
                        List={ChannelListMessenger}
                        Preview={CustomChannelPreview}
                        EmptyStateIndicator={CustomEmptyStateIndicator}
                        setActiveChannelOnMount={false}
                        me={user}
                    />
                    <hr/>
                </div>
                <Users user={user} />
                <ConversationBox chatClient={chatClient} user={user} openDir={openDir} />
            </Chat>`

On `CustomChannelPreview` which is a `withChatContext` component I added a button to delete the channel that just does : 
`
setActiveChannel(null);
await channel.delete();
`
Now Users component is also a `withChatContext` and checks client.activeChannels to filter the users we display so we only show users without an activeChannel. Problem is after I delete a channel, client.activeChannels remains untouched listing all channels including the one I deleted. Only when I refresh I get an updated list of active channels. I would expect to see the activeChannels collection in client update when I delete a channel and remove that channel from the activeChannels list.

Thank you in advance, let me know if you need any more details please.

**Comment by jaapbakker88** [comment]
@santipalenque this is an issue we ran in to recently and we're looking into fixing this on the client, for now you can just reset the activeChannels yourself:
```
delete client.activeChannels[chan.cid]
```

Let me know if that works.

**Comment by santipalenque** [comment]
Thank you @jaapbakker88 . I worked around it by hiding and showing channels instead of deleting and creating.
