### ISSUE TITLE
ChannelPreview has incorrect last_message_at for a channel receiving a new message

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-react#493]
I have a custom ChannelPreview component, that seems to be getting incorrect data when I create a new message on a channel.

Inside the component I have  - 

```
console.log(`channel ${props.channel.id}, unread ${props.unread}`); 
console.log(`channel ${props.channel.id}, lastMessageDate ${props.channel.data.last_message_at}`);
```

which runs on each render, where the first log is correctly logs out the unread count at 1, but the second log is logging out the incorrect value, it will keep logging out the same value, which seems to be the value of the last message when the component mounted.  Refreshing the screen shows the correct last_message_at timestamp again.

gz#5520

**Comment by veloware** [comment]
Any pointers on this? Is there another place I can get the date / time of the most recent message after sending a message to a channel?

**Comment by jaapbakker88** [comment]
@veloware this seems like a bug on the client, can you try getting the last message from `props.latestMessage` and getting the created_at from that message? I'll make sure this will get added to our backlog.

**Comment by veloware** [comment]
Thanks for the reply, yes I can get it from there when a new message gets added to the channel, however its `undefined` on first load, so it's a bit of a mixture, looks like I can get the date from `props.channel.data.last_message_at` when first loading the screen, but then use `props.lastMessage.created_at` when any further messages have been added. Not ideal - 

`props.lastMessage?.created_at ? props.lastMessage?.created_at : props.channel.data.last_message_at;`
