### ISSUE TITLE
message.created_at PropType warning

### ISSUE THREAD

**Issue by notthatnathan** [GetStream/stream-chat-react#496]
The message being passed to `<Message />` includes `created_at` as a date, but this [validation requires a string](https://github.com/GetStream/stream-chat-react/blob/master/src/components/Message/Message.js#L139). This error is logged:

```
Warning: Failed prop type: Invalid prop `message.created_at` of type `date` supplied to `Message`, expected `string`.
```

gz#5578

**Comment by jaapbakker88** [comment]
closing because a duplicate of #488
