### ISSUE TITLE
Chat is not recovering on watch's timeouts or any other error

### ISSUE THREAD

**Issue by plandem** [GetStream/stream-chat-react#500]
This piece of code is potential issue, since if watch will be timed out (and default setting for `stream-chat-js` is 3s for any network request), then whole chat will be broken - it will render `LoadingIndicatorError`, but there is no way to recover from it. That particular case ruined experience of few our clients. And 3s timeout can easily happen on slow internet connection.

https://github.com/GetStream/stream-chat-react/blob/23056b9b1f6b88e88cf2829ee5baae8668626af4/src/components/Channel/Channel.js#L222

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/5749'>Zendesk ticket #5749</a>:<br><br>you can increase the timeout using the code found here: https://getstream.io/chat/docs/increasing_timeout/?language=js&q=timeout

**Comment by plandem** [comment]
1) And how it will help to recover if timeout happens?! 

2) We can’t increase timeout infinitely, We still would prefer to have timeouts for other network requests  as well, like sending messages and etc.

**Comment by mahboubii** [comment]
@plandem Thanks for reporting this. There are 2 scenarios where we show `LoadingErrorIndicator` if the network request fails:

1. Using the `Channel` component without passing down an uninitialized `channel` as a prop, which leads to `channel.watch` getting [called](https://github.com/GetStream/stream-chat-react/blob/23056b9b1f6b88e88cf2829ee5baae8668626af4/src/components/Channel/Channel.js#L217) and in case of an error, `LoadingErrorIndicator` will be rendered.

2. Using the `ChannelList` component which [queries](https://github.com/GetStream/stream-chat-react/blob/master/src/components/ChannelList/hooks/usePaginatedChannels.js#L30) all the user's channel and again in case of an issue, `LoadingErrorIndicator` will be rendered.

These two only happens in the first render of the app(initializing) or if ChannelList tries to load more channels. I would recommend increasing the timeout a bit and adding a custom `LoadingErrorIndicator` which has a refresh button, make it easier to just refresh the entire page.

The Websocket connection always recovers, but it's not the same for the above requests. We will consider making these requests retryable.
