### ISSUE TITLE
Disable slash commands based on role

### ISSUE THREAD

**Issue by shelbyt** [GetStream/stream-chat-react#506]
Related to the request in #36 
Is there a resolution to this issue:
> I'm still seeking an easy way to get slash commands to not show up if the user shouldn't have permission for the action underpinning a slash command

Looked around all of the related docs but couldn't find anything. Ideally the current user context can be detected and only the flags enabled for a certain role should show up. 

Alternatively even if I could just do something like: 
                           ` <MessageInput commandInput={["giphy"]} />` or  ` <MessageInput role={"user"} />`

that would be great but right now all user roles have all commands. Is there any quick workaround for this?

gz#5826

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/5826'>Zendesk ticket #5826</a>:<br><br>Hi Shelbyt

Thanks for reaching out to us.
Can I ask for your App Id and User Id, please?
I will get this checked with an Engineer and let you know.

Cheers
Seetha

**Comment by jaapbakker88** [comment]
@shelbyt, it's not necessary to send your appId or userId on GH. This is currently not possible. The only way to customize this would be to supply `autocompleteTriggers` to the MessageInput component. Only problem here is, it overrides the default triggers, so you would have to copy over our triggers and customize them yourself.

**Comment by shelbyt** [comment]
Understood. Thanks. Could you clarify this part:
> Only problem here is, it overrides the default triggers, so you would have to copy over our triggers and customize them yourself.

Could you provide a short example about how to do this and approx where I can find the triggers code?

Related question, I see this component `<ChatAutoComplete>` which has a "commands array" prop. This component doesn't have a clear description, but the autocompleteTriggers-prop says it overrides ChatAutoComplete. What is the relationship between these components (I assume I can't use ChatAutoComplete/commands-array directly for my needs)

**Comment by jaapbakker88** [comment]
@shelbyt this is correct. ChatAutoComplete is what handles commands(/giphy, /ban), mentions and emoji. The triggers(`:`, `@` and `/`) are passed down to this component. 

https://github.com/GetStream/stream-chat-react/blob/4f64abcda95c77344a973b2972965a70b0cd8295/src/components/ChatAutoComplete/ChatAutoComplete.js#L80

This is where we get/set the triggers. This is also the format we expect. You could copy these triggers over into your `autocompleteTriggers` prop. Note, this should be an object, not an array.

**Comment by jaapbakker88** [comment]
@shelbyt going to close this issue. Please let us know if we can assist with any other issues.
