### ISSUE TITLE
Link Avatar Icons to Pages

### ISSUE THREAD

**Issue by shelbyt** [GetStream/stream-chat-react#508]
Is there anyway to have chat icons have onclick actions i.e. redirecting to a user's personal page when someone clicks their in-chat avatar?

gz#5842

**Comment by jaapbakker88** [comment]
@shelbyt you can provide `onUserClick` and `onUserHover` to the `<Message />` Component.

**Comment by shelbyt** [comment]
hi @jaapbakker88 apologies for bringing this up again, I had one more question related. The way that I've been using the chat component has just been like this;
```
          <Channel channel={channel}> 
               <Window>
                    <ChannelHeader />
                        <MessageList />
                            <MessageInputSmall />
                 </Window>
                <Thread />
             </Channel>
```

How do I modify the` <Message />` component here like you've suggested?

**Comment by shelbyt** [comment]
Of course I figured it out shortly after posting it... 

For future reference I'm posting my solution here:
`const MyMessage = props => <><MessageTeam {...props} onUserClick={(() => console.log("clicked"))} /></>;`
This overrides the MessageTeam component and exposes the onuserclick prop so that when the user icon is clicked the console.log displays.
