### ISSUE TITLE
ChannelList filtering including wrong channel type

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-react#509]
I have channels with a type of `messaging` which I am filtering as part of a`ChannelList` component - 

```
<ChannelList
          filters={filters}
          sort={sort}
          showSidebar={false}
          Preview={ChannelListPreview}
          LoadingIndicator={Loading}
          EmptyStateIndicator={NoResults}
          setActiveChannelOnMount={false}
          customActiveChannel={chatId}
        />
```

where `filters` is - 

`{ type: 'messaging', members: { $in: getConnectionIds().concat(props.profile.id) } }`

this works fine.

I then have another custom channel type to manage audio/video call channels, type = `call`, to be used alongside Voxeet.

When I call a user, I create a channel (server-side) - 

```
async startCall(createdBy: string, invites: string[]): Promise<string> {
    const channelId = short.generate();
    const data = {
      members: [createdBy, ...invites],
      invites,
      created_by: { id: createdBy },
    };
    await this.client
      .channel(CustomChannelTypes.call, channelId, data)
      .create();
    return channelId;
  }
```

however now my channel list for messaging contains the new call channel, here's a log from my `ChannelListPreview` component for the channels that are being rendered in the list - 

<img width="491" alt="Screenshot 2020-09-09 at 10 10 51" src="https://user-images.githubusercontent.com/61578546/92579249-df0d0a00-f284-11ea-8a13-c99fdda1a38b.png">

Any thoughts?

gz#5865

**Comment by jaapbakker88** [comment]
@veloware the issue here is the filter is only applied during querying for channels. It doesn't filter the incoming events, so in this case when you create a new channel the user that gets added to the channel, get's an event and the channel get's added tot the list.

There is a way around this, you can provide a custom event handler to the `onMessageNew` and `onAddedToChannel` props on the ChannelList:

```
customHandler = (setChannel, e) => {
    // get the channel using event data
    // check current team and discard if needed
    // move channel to starting position
    setChannels((channels) => {
       return uniqBy([channel, ...channels], 'cid');
    });
}
```

**Comment by veloware** [comment]
Thank you, that seems to work
