### ISSUE TITLE
Custom Emoji-Mart Filter Prop

### ISSUE THREAD

**Issue by agallagher777** [GetStream/stream-chat-react#522]
Hi,

We're building out a streaming application for schools (ranging from elementary school to high school) attending lectures at our organization.  Really happy with the quality of this package so far, but given that our target audience is largely children we need to filter down the allowed list of emojis — namely some of the more "evocative" emojis.

I'm wondering if it is possible to request an enhancement to include an optional prop object at the MessageInput level that spreads over the default props for the [EmojiPicker](https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageInput/MessageInputFlat.js#L38).  I'd imagine that this override object would be in the shape of the [EmojiPicker's props](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/emoji-mart/dist-es/utils/shared-props.d.ts#L62)

Please let me know if you would like for me to open a PR for something like this.

Thanks!

gz#6013

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6013'>Zendesk ticket #6013</a>:<br><br>Hi

Thanks for reaching out to us.
I will get this checked for you.
Meanwhile, can you please confirm if you are a Stream customer? Sorry, couldn't confirm your details with the email id - agallagher777@stream-chat-react.com . Thanks.

Cheers
Seetha

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6013'>Zendesk ticket #6013</a>:<br><br>Hi

Apologies for the confusion. Please ignore the email id (agallagher777@stream-chat-react.com) That's generated by the tool.

Cheers
Seetha

**Comment by agallagher777** [comment]
Hi,

We have an account registered as barnesfoundation

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6013'>Zendesk ticket #6013</a>:<br><br>Hi,

Nice to know. Thanks for the update.
I am checking your request with our react team, will update you when I have more information.

Thanks for your patience.

Cheers
Seetha

**Comment by jaapbakker88** [comment]
@agallagher777 we're looking into adding this as a feature. Will update you here once I know more.

**Comment by jaapbakker88** [comment]
@agallagher777 we're working on this here: https://github.com/GetStream/stream-chat-react/pull/530

**Comment by DanC5** [comment]
@agallagher777 we just merged our emoji-mart optimization PR and will make a new release shortly, either tomorrow or early next week.

For your issue of removing certain emojis, you can now pass an `emojiData` prop into the Channel component to fully customize the data set that appears in the picker. This prop accepts a JSON object containing all of the data for the set of emojis you will display. We now by default show the facebook.json data set and have trimmed it down even more to our own custom set, stream-emoji.json.

https://github.com/GetStream/stream-chat-react/blob/master/src/stream-emoji.json

In addition, you can also now customize the following UI components we pull from emoji-mart, also props on the Channel component. All of these values, including `emojiData`, can now be found within the `emojiConfig` object in the ChannelContext. So feel free to pull `const { emojiConfig } = useContext(ChannelContext)` anywhere you need the data.

- Emoji: overrides default NimbleEmoji component
- EmojiIndex: overrides default NimbleEmojiIndex component
- EmojiPicker: overrides default NimblePicker component

Thank you very much for your patience with this issue!
