### ISSUE TITLE
ChannelList doesn't refresh when a message gets added to a hidden channel

### ISSUE THREAD

**Issue by MondeoWu** [GetStream/stream-chat-react#523]
Hi,
Stream is so easy to use, but i have an urgent problem needs you guys' help:
step 1:  A chat with B, we get a channel in the ChannelList ,right?
step 2: A hide the channel by using channel.hide(), and the channel get removed in the channelList;
step 3: B send a new message to A, A receive the message, i can catch the event, and unread count is 1 now, but the channel doesn't show up in A's ChannelList. Both happen in one to one chat and group chat.
step 4: I jump to other page and come back, or just re-render the <ChannelList/>, the channel show up.

I tried 999+ ways to solve this but all failed..

Looking forward to hearing from you guys soon.

gz#6030

**Comment by jaapbakker88** [comment]
@MondeoWu can you elaborate a bit more. I'm not sure what the behaviour is your expecting in step 3 and 4.

**Comment by MondeoWu** [comment]
> @MondeoWu can you elaborate a bit more. I'm not sure what the behaviour is your expecting in step 3 and 4.

**Comment by MondeoWu** [comment]
> @MondeoWu can you elaborate a bit more. I'm not sure what the behaviour is your expecting in step 3 and 4.

user A hide the channel in step 2 and Stream remove the channel from the channelList ,so A cannot see the channel in his page.and user B still can send msg to A ,so B send a new msg to A, when A receive the msg, the hidden channel doesn't show up in the channel list.

**Comment by jaapbakker88** [comment]
@MondeoWu when you're hiding the channel you should also call `channel.stopWatching()`. This will make sure you'll get the `notification.*` events for that channel and the channel will reappear when a new message get's added tot the channel. Hope this solves your issue.

**Comment by MondeoWu** [comment]
@jaapbakker88  awesome! It works! Thanks a lot.
