### ISSUE TITLE
How to handle new message notifications / stop watching channels

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-react#524]
Im confused on the correct way on how to handle notifications for new messages to a channel.

I have added chat into my existing application that would be under `/chat`.  Outside of that route, you still have chat context.  I am trying to solve for displaying notifications of unread channels only when you are outside of the `/chat` route.  From what I see in the docs, there is a `notification.new_message` event that gets fired for channels that you are not watching.  This works fine once you have first loaded my application and not yet navigated to `/chat`.  I get the event and can see the unread channel count.

My problems arise when you then navigate to `/chat` and in turn, mount the `<ChannelList />` component, and when in `chat/:id` I would mount the `<Channel></Channel>` component.  I would assume I have started to watch channels now.  However if I navigate back out of the `/chat` route (and would unmount the ChannelList and Channel components) I still seem to be watching all channels as I no longer receive the `notification.new_message` event.

I see there is a `channel.stopWatching()` function, however it doesn't seem right that I have to manually call `.stopWatching()` on all of my channels, as I didn't have to call something similar to start watching?

Any help is appreciated, thanks

app id: 92633

gz#6031

**Comment by jaapbakker88** [comment]
@veloware, you probably want to call `stopWatching` in this case. The `ChannelList `automatically watches the channels it renders but when you unmount it doesnt unwatch them. So if you still have an active client in the `ChatContext` it will not receive notifications unless you stop watching. 

What's your use case here though, do you actually need the `notification.new_message` event or can you also use the `message.new` event, because that one fires if you are watching the channel.

**Comment by veloware** [comment]
My use case is that when outside of the `/chat` route (that could be thought of being the chat system), that in I receive an indicator of the number of unread channels in my Nav component. `Chat` component is high up in the tree, so my Nav does have access to the chat context.

I initially tried to use `message.new` however this causes the unread channels indicator in the Nav to show / increment by 1 for the channel that I am active in, and when the next event comes in straight after, `message.read` it hides the indicator again.  So I get a notification appearing then disappearing for an active channel, due to the `message.new` then straight after, the `message.read` event

**Comment by veloware** [comment]
I have also hit error in the past with 'too many requests' I would be worried about hitting said error if I were to call `stopWatching()` on a lot of channels - out of curiosity, at what number of requests is that error returned?

**Comment by jaapbakker88** [comment]
@veloware you can find all our rate limits here: https://getstream.io/chat/docs/rate_limits/?language=js

Does that solve your issue or are you going to call this endpoint a lot. To me it seems that outside of `/chat` you probably still have a ChannelList open that watches the channels and prevents the `notification.new_message` from being sent.

**Comment by veloware** [comment]
Hi, yes I believe, `stopWatching()` has allowed me to get the notifications behaving correctly.  Thanks for sending on the rate limits.  I don't think it is of immediate concern around 1,000 calls to `stopWatching()` so thats probably fine for us in the meantime.

Thanks for your help
