### ISSUE TITLE
Create user on sever-side success, but create channel with that user on client-side failed.

### ISSUE THREAD

**Issue by MondeoWu** [GetStream/stream-chat-react#527]
Hi guys,
1. Our app already have many users when we integrate Stream.
2. I read the docs, it says i should use client.setUser() to create a user on Stream by client-side.
3. So if a user never logged in since we integrated Stream, we cannot call setUser(), so he is not created on Stream, and  other users cannot send a message to him.
4.So our solution is: if user A never logged in, when user B create channel with A, we call .setUser() on our server-side, create a user&token for A on our server-side.

Here is the problem:
5. Our server returns success, and the log shows A is created. So we call 
`
client.channel('messaging', {
    members: [A, B],
}); 
`
to create an one to one chat,  but Stream throw an error says:
`
{
StatusCode:400,
code:4,
duration:'0.00ms'
message:"GetIrCreateChannel failed with error: "The following users are specified in channel.members but don't exist:[5027],please create the user objects before setting up the channel""
}
`
Not all users failed. Just some of them are created failed.

Do you guys know why ?
How to create a User if this user never logged in?
Thanks a lot .

gz#6058

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6058'>Zendesk ticket #6058</a>:<br><br>Hi

Thanks for reaching out to us.

You wouldn't be using setUser() to create a new user **server-side**.

You might want to use these -

 `client.updateUser` or `client.upsertUser`


> Create the user server-side with one of the above methods. Alternatively, setUser actually performs the upsert for you, so there is actually no need to create the user server-side.


Please let us know how you go.

Cheers
Seetha

**Comment by MondeoWu** [comment]
@shodgetts  Thanks a lot. I should read the docs more carefully.
