### ISSUE TITLE
StreamChatMessageType does not extend string

### ISSUE THREAD

**Issue by ZNackasha** [GetStream/stream-chat-react#528]
i am trying to use client.on to subscribe to events. how ever when i try to create a EventHandler i am told the following

`Type 'StreamChatMessageType' does not satisfy the constraint 'string'.ts(2344)`

please let me know if i am doing something wrong 

here is my code

```ts
  componentDidMount() {
    this.props.client?.on(this.streamEventsListener);
  }

  componentWillUnmount() {
    this.props.client?.off(this.streamEventsListener);
  }

  streamEventsListener: EventHandler<
    StreamChatReactChannelType,
    StreamChatReactUserType,
    StreamChatMessageType
  > = event => {
}
````

note that EventHandler expects string

```ts
type EventHandler<
  AttachmentType extends UnknownType = UnknownType,
  ChannelType extends UnknownType = UnknownType,
  CommandType extends string = LiteralStringForUnion,
  EventType extends UnknownType = UnknownType,
  MessageType extends UnknownType = UnknownType,
  ReactionType extends UnknownType = UnknownType,
  UserType extends UnknownType = UnknownType
>
```

gz#6087

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6087'>Zendesk ticket #6087</a>:<br><br>Hi

Thanks for getting back.
Typescript issue. Can you please let me know the version of the stream-chat-react you are in?

Cheers
Seetha

**Comment by ZNackasha** [comment]
oh sorry i was using 2.4.0 at the time.

**Comment by nhannah** [comment]
@ZNackasha For unused generics between assigned generics some value is needed e.g. `{}` or `Record<string, unknown>` or `Record<string, any>` or `string & {}` for commands (the string & {} preserves intellisense while allow any string).

For your use
```
EventHandler<
    Record<string, unknown>,
    StreamChatReactChannelType,
    string & {},
    Record<string, unknown>,
    StreamChatMessageType,
    Record<string, unknown>,
    StreamChatReactUserType,
  >
```

should be correct I believe.
