### ISSUE TITLE
Hidden channels do not show when new message comes in.

### ISSUE THREAD

**Issue by santipalenque** [GetStream/stream-chat-react#529]
It used to work as the doc says, when you hide a channel it remains hidden until a new message comes into that channel, but is no longer working, hidden channels remain hidden even if a user sends a new message.

gz#6125

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6125'>Zendesk ticket #6125</a>:<br><br>Hi

Thanks for reaching out to us.
I can get this checked for you.

Cheers
Seetha

**Comment by jaapbakker88** [comment]
@santipalenque when you hide the channel, please also call `channel.stopWatching()`. That should fix it.

**Comment by santipalenque** [comment]
Thank you @jaapbakker88  !!! it works now
