### ISSUE TITLE
Audio type for facebook might be wrong

### ISSUE THREAD

**Issue by ferhatelmas** [GetStream/stream-chat-react#53]
Firstly, I'm not sure if it's a real issue.

[Following snippet](https://github.com/GetStream/stream-chat-react/blob/011cc14dad7c5306adaa44d4ab0eb645a363b53e/src/components/Audio.js#L72) seems suspicious since both side of `if` returns same result. 

```js
type={
  audio.type === 'audio/vnd.facebook.bridge'
    ? 'audio/mp3'
    : 'audio/mp3'
}
```

Moreover, if I do a quick googling, seemed to me that `type` should be `audio/vnd.facebook.bridge` in that case.

**Comment by jaapbakker88** [comment]
I believe we use a library to support audio playback which doesnt like the `audio/vnd.facebook.bridge` type.  It only works if we use the `audio/mp3` I think. But I'll have to look into this to see if it's actually an issuue.
