### ISSUE TITLE
Add current search value for mentions in autocomplete header

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#531]
https://github.com/GetStream/stream-chat-react/blob/3e4ef46182818c556178284f13ef2ca3743e590f/src/components/AutoCompleteTextarea/List.js#L144

Could it be possible to support the current search value for mentions the same way as it currently is for commands and emojis?

Something like this
```
return `People matching <strong>${value.replace('@', '')}</strong>`;
```

gz#6149

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6149'>Zendesk ticket #6149</a>:<br><br>Hi

Thanks for reaching out to us.
I can get this checked for you.

Cheers
Stream Team

**Comment by jaapbakker88** [comment]
@alexlopezit I have added this to our backlog. Hopefully we can get this picked up soon.

**Comment by DanC5** [comment]
Hey @alexlopezit sorry for the delay but we just added this feature and will likely make a release tomorrow, thanks
https://github.com/GetStream/stream-chat-react/pull/669
