### ISSUE TITLE
Infinite loop of calls to GetStreamAPI from channel.watch()

### ISSUE THREAD

**Issue by hochoy** [GetStream/stream-chat-react#533]
## Issue:
When we implemented the example in the GetStream blog, the `channel.watch()` call in line 55 resulted in an infinite loop of calls to the getStream API. It also resulted in timeout errors.

https://getstream.io/blog/securing-a-chat-app-with-react-and-auth0/#add-chat-functionality-with-stream:~:text=section.-,Add%20chat%20functionality%20with%20Stream

## to reproduce:
Here is a minimal reproduction of the issue with instructions:
https://github.com/hochoy/debug-getstream

Please let me know if I have configured it wrongly. I've copied the example almost word by word except for some static values for debugging.

## Error on my end and in the repo above
<img width="707" alt="Screen Shot 2020-09-17 at 4 14 47 PM" src="https://user-images.githubusercontent.com/12564636/93540662-3e17f200-f909-11ea-80f0-0face31c261b.png">

<img width="1264" alt="Screen Shot 2020-09-17 at 4 03 39 PM" src="https://user-images.githubusercontent.com/12564636/93540671-44a66980-f909-11ea-8a56-a26f30808a2a.png">

## Code from the blog:

<img width="597" alt="Screen Shot 2020-09-17 at 5 16 41 PM" src="https://user-images.githubusercontent.com/12564636/93540787-951dc700-f909-11ea-9ea4-62bb3c344f27.png">

gz#6084

**Comment by vishalnarkhede** [comment]
Hey @hochoy I have sent a PR with a fix that should resolve the issue for now - https://github.com/hochoy/debug-getstream/pull/1/files

We will fix the real issue soon in our stream-chat-react package.

**Comment by vishalnarkhede** [comment]
@hochoy We have published a patch for fixing this issue - `stream-chat-react@2.4.1`

Thanks for bringing this up :)
