### ISSUE TITLE
Emojis have opacity when editing a message

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#536]
https://github.com/GetStream/stream-chat-react/blob/f1ee8b4bd22476f056229895e199aeb83c3b70be/src/styles/EditMessageForm.scss#L33

![image](https://user-images.githubusercontent.com/1654135/94094549-1e318280-fe63-11ea-9ad9-acbdda2e0edd.png)

The linked line is adding an opacity to the emoji buttons that should not be there.

gz#6213

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6213'>Zendesk ticket #6213</a>:<br><br>Hi

Thanks for reaching out to us.
I can get this checked for you.

Cheers
Stream Team

**Comment by jaapbakker88** [comment]
@alexlopezit thanks for reporting this issue. We have a fix on the way!

**Comment by alexlopezit** [comment]
Awesome, thanks
