### ISSUE TITLE
Type for client on ChantContextValue issue

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#542]
https://github.com/GetStream/stream-chat-react/blob/bab02525137e064348ff69615375679c203cf098/types/index.d.ts#L70

Currently the ChannelList and it's hooks have type issues as the client here is type `StreamChatReactClient` but the code expects `StreamChat`

ChannelList
![image](https://user-images.githubusercontent.com/1654135/94230261-f1559c00-ff44-11ea-9601-17858b0e4ed2.png)

gz#6242

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6242'>Zendesk ticket #6242</a>:<br><br>Hi

Thanks for reaching out to us.
We can get this checked for you.

Cheers
Stream Team

**Comment by alexlopezit** [comment]
Sorry forgot to mention the version, I was upgrading these:

"stream-chat-react": "2.1.3" to "2.5.0"
"stream-chat": "1.14.0" to "2.4.0"

Also the types on the `Channel` seem to have changed.

This is an example on the `client.queryChannels` which was returning type `Channel[]` which worked perfect

Before on 2.1.3
![image](https://user-images.githubusercontent.com/1654135/94238172-49939a80-ff53-11ea-9456-c0020e725c0d.png)


After the upgrade to 2.5.0 this is the returning type which causes compile errors in Typescript everywhere we use the channel now.

![image](https://user-images.githubusercontent.com/1654135/94238554-e6563800-ff53-11ea-9632-ba2bc835f7b4.png)

**Comment by nhannah** [comment]
> Sorry forgot to mention the version, I was upgrading these:
> 
> "stream-chat-react": "2.1.3" to "2.5.0"
> "stream-chat": "1.14.0" to "2.4.0"
> 
> Also the types on the `Channel` seem to have changed.
> 
> This is an example on the `client.queryChannels` which was returning type `Channel[]` which worked perfect
> 
> Before on 2.1.3
> ![image](https://user-images.githubusercontent.com/1654135/94238172-49939a80-ff53-11ea-9456-c0020e725c0d.png)
> 
> After the upgrade to 2.5.0 this is the returning type which causes compile errors in Typescript everywhere we use the channel now.
> 
> ![image](https://user-images.githubusercontent.com/1654135/94238554-e6563800-ff53-11ea-9632-ba2bc835f7b4.png)

@alexlopezit Can you give me some more details on the second issue? The client now accepts a list of generics corresponding to the custom fields you may want to use in the application. By default they are all `Record<string, unknown>`. The Channels returned is now more detailed than before but in essence the same, just extendable. The first issue I will put a PR in for shortly.

**Comment by alexlopezit** [comment]
Hi @nhannah 

I just went to the `examples/typescript-app` updated it to version 2.6.1 and added this small code to test the types

```
const ChannelDetails: React.FC<{}> = ({ }) => {
  const { channel } = React.useContext(ChannelContext)

  return (
    <div style={ { width: '300px' } }>
      <h1>Number of members { channel.data.member_count }</h1>
    </div>
  )
}
```

And add that after the `Thread` component

```
...
        <Channel>
          <Window>
            <ChannelHeader />
            <MessageList />
            <MessageInput Input={ MessageInputFlat } focus />
          </Window>
          <Thread Message={ MessageSimple } />
          <ChannelDetails /> {/* New sample component */}
        </Channel>
...
```

Then you will be able to see the code does not compile while `channel.data.member_count` should be valid as in version 2.1.3 which is the one I got at the moment

![image](https://user-images.githubusercontent.com/1654135/94653033-45de8a00-033e-11eb-8481-f30f9dc6d51c.png)

**Comment by alexlopezit** [comment]
Hi @jaapbakker88 , types are still not working in 3.0.0 as for the sample test I posted above, so this issue is still not resolved.

cc. @tbarbugli

**Comment by jaapbakker88** [comment]
@alexlopezit problem with the ChannelContext is that its values can technically be undefined since its default value is just an empty object. In our library we use optional chaining to solve the issue. We tried solving this issue but haven't found a satisfying way:

In your example you would have to: 
```
const ChannelDetails: React.FC<{}> = ({ }) => {
  const { channel } = React.useContext(ChannelContext)

  return (
    <div style={ { width: '300px' } }>
      <h1>Number of members { channel?.data?.member_count }</h1>
    </div>
  )
}
```

**Comment by alexlopezit** [comment]
@jaapbakker88 that solution worked fine for Stream fields, however how would I make it work for custom fields?

![image](https://user-images.githubusercontent.com/1654135/94876956-7e947580-049c-11eb-9e41-6d3a3b5f6ab2.png)

**Comment by nhannah** [comment]
> @jaapbakker88 that solution worked fine for Stream fields, however how would I make it work for custom fields?
> 
> ![image](https://user-images.githubusercontent.com/1654135/94876956-7e947580-049c-11eb-9e41-6d3a3b5f6ab2.png)

@alexlopezit I have made a [PR](https://github.com/GetStream/stream-chat-react/pull/557) that will extend the base type with `Record<string, any>`, the stream-js client was recently update to full typescript and now supports custom data via a variety of generics. This will be coming to stream-chat-react and will solve the problem you currently are seeing and give you full custom typings on extended fields.

**Comment by alexlopezit** [comment]
Awesome news, thanks and can't wait to try it out

**Comment by jaapbakker88** [comment]
@alexlopezit we just released v3.0.1 which should resolve this issue.

**Comment by alexlopezit** [comment]
Hi @jaapbakker88, I'm just trying this out and seems to be working so far, and noticed this type now returning unknown

`client.user.total_unread_count` Type (before `number`, now `unknown`)


One thing I'd like to clarify when using `ChannelContext` as you mention  

> values can technically be undefined since its default value is just an empty object

Is this from the API or the library only?

**Comment by jaapbakker88** [comment]
@alexlopezit this is the library only. Problem is(which we're going to solve in the future) that we're using JSdoc to typecheck our components. But this comes with some limitations. This issue should be solved when we completely move to Typescript.
