### ISSUE TITLE
Question - how to create a system-like message?

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-react#549]
Hi,

I am looking to create and send a message to a channel that is more of an informational message rather than speech.  For example we have stream working alongside video calling, and I would like to display an informational message to show that a call occurred between multiple people.  If user X called user Y, I would like to display something like - 'You called Y' for user X and 'X called you' for user Y.

I tried to use silent messages, and whilst that works to a degree in that it doesn't increment unread counter etc, it displays as a speech bubble for the two participants and they will both receive the same message, not a message tailored to them individually, and it still feels like a regular 'speech' message

I tried to also send `type` as `system` but I got an error saying that 'type' is a reserved word.

(client side)
```
const message = {
      type: 'system',
      text: 'You called them',
      user: { id: currentUserID },
      silent: true,
    };
channel.sendMessage(message)`
``` 

Any help is appreciated

Thanks

gz#6285

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/6285'>Zendesk ticket #6285</a>:<br><br>Hello, for this you will want to use the channel.update method and add in some text. You can read more here
https://getstream.io/chat/docs/channel_update/?language=js
-S
