### ISSUE TITLE
Type definitions: ExtendedAttachment images Array property invalid (possibly TS 4.x related)

### ISSUE THREAD

**Issue by DamonOehlman** [GetStream/stream-chat-react#550]
I suspect this is an issue after we recently moved to using TypeScript `4.x` for our project compilation as it's not something I noticed earlier, and notice that the change was introduced 19 days ago as part of 0448d3474f712d78d557980f94c66e78e2d0c2f4.

```
$ tsc --noEmit
node_modules/stream-chat-react/types/index.d.ts:692:12 - error TS2314: Generic type 'Array<T>' requires 1 type argument(s).

692   images?: Array;
```

gz#6310

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6310'>Zendesk ticket #6310</a>:<br><br>Hi Damon

Thanks for reporting this to us.
We will get this checked.

Cheers
Seetha
