### ISSUE TITLE
Urgent: Including browser.full-bundle.min.js overwrites Image in browser global scope, breaks Facebook Pixel event tracking

### ISSUE THREAD

**Issue by tkrevh** [GetStream/stream-chat-react#553]
Hello!

We're a paying customer and we've had issues with Facebook Pixel tracking for some months now. Finally today we were able to find the reason why FB Pixel tracking isn't working. It's because when loading your browser.full-bundle.min.js package, it overwrites the Image class on the browser window global scope. FB pixel tracks events by creating a new Image() and then setting it's src attribute to their tracking server URL; and with your bundle replacing the Image in global scope, this functionality is then broken.

Issue is in this file:
https://github.com/GetStream/stream-chat-react/blob/master/src/components/Gallery/Image.js

Can we please ask you to issue an urgent update to this and release a version where the global scope Image is not overwritten?

Thank you!

gz#6339

**Comment by mahboubii** [comment]
@tkrevh fixed in [v3.0.0](https://github.com/GetStream/stream-chat-react/releases/tag/v3.0.0)

**Comment by tkrevh** [comment]
That's some serious speed 👍 Thank you very much 🥇
