### ISSUE TITLE
How to use the user.presence.changed event?

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-react#563]
I have two places where I need to react to when other members login / logout that I can't seem to get working. In a header above the active channel, using withChannelContext, and also in my channel list, using the ChannelList component.

1) withChannelContext

Looking at https://getstream.github.io/stream-chat-react/#section-withchatcontext

I should be able to get the number of online users for the channel, using `props.online` (saying that, the TS definition shows it should be a boolean rather than a number?) however is always comes through as `undefined`

2) ChannelList component

I've added the `{ presence: true}` option to the channel list as per the demo app

```
<ChannelList
          filters={filters}
          sort={sort}
          options={{ presence: true }}
...
```

using `console.log`s, I can see my Custom Preview component rerendering, so I assume the `presence: true` is watching for presence changes correctly.  However in the Preview component, there is nothing in the props to show whether users of the channnel are online or not?

Could you please give some advice on how to get realtime presence in the above 2 scenarios please?

p.s. I also tried to call `client.queryUsers()`, then `client.on('user.presence.changed', handler)` from within the Preview component, to try and handle the event there, though i'm hitting a rate limit of 60 on the `/users?` call (going by the response headers) - though i thought there was meant to be a rate limit of 1000 on that endpoint?

gz#6483

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6483'>Zendesk ticket #6483</a>:<br><br>Hi

Thanks for reaching out to us.
We will get this checked for you.

Cheers
Stream Team

**Comment by shodgetts** [comment]
Regarding your rate limit... this is a per-user rate limit (read more here https://getstream.io/chat/docs/rate_limits/?language=js). 

You should only need to call client.queryUsers() with presence:true once, then listen to events. It sounds like it might be in a loop if it's being called >60 times /minute from the same client? Are you receiving presence changes?

Read more here (https://getstream.io/chat/docs/presence_format/?language=js#listening-to-presence-changes)

**Comment by veloware** [comment]
Thank you for clarifying the rate limits.  When I was hitting the rate limits it was because I was admittedly trying to do something that i _shouldnt_ need to do, as you say.  I was doing that simply because I couldn't get presence events from the first two scenarios I mentioned.

Regarding the second scenario, I seem to seeing the same issue as raised here - https://github.com/GetStream/stream-chat-react/issues/182

**Comment by mahboubii** [comment]
Hey @veloware,
1. You can get the number of currently online members/watchers in a channel using `ChannelContext`:
`const { watcher_count } = useContext(ChannelContext);`

> You can see this being used in [ChannelHeader](https://getstream.github.io/stream-chat-react/#!/ChannelHeader) component.


2. If you want to see if a specific user is online or offline, you can read it again from `ChannelContext`, this can trigger the rerender you need, but I'd suggest stick to the `watcher_count`:
```
const { members } = useContext(ChannelContext);
members[user_id]?.user.online
```

**Comment by mahboubii** [comment]
Alternatively, you can always listen to the events including `user.presence.changed` directly from `StreamChat` client

```
const { client } = useContext(ChatContext); 
client.on('user.presence.changed', (event) => console.log(event));
```

**Comment by mahboubii** [comment]
closing this for housekeeping. In case you still have this issue, please let us know to reopen it.
