### ISSUE TITLE
"Edit Message" and "Delete" message buttons display issue

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#564]
There is an issue on the message actions that we can't replicate but we get it now and then, we have no steps to reproduce as it happens randomly.

The problem is that sometimes we can see the "..." icon on someone else messages which allows the user to click on both `Edit Message` and `Delete` message buttons. We know the backend is preventing the editing or deleting in these cases which is good, but when this happens is a bit confusing for the user.

We are currently using v3.0.1

![image](https://user-images.githubusercontent.com/1654135/95421312-937f7600-0980-11eb-80b2-f60c32342a13.png)

gz#6517

**Comment by mahboubii** [comment]
Hey @alexlopezit, couple of questions:
1. How random is this behavior? any chance it's happening only for/to some type of users?
2. Which Message component are you using?
3. Could you share your JSX code?
4. Are you using `useUserRole()` hook provided by the library?
5. Have you set custom permissions for users or the channel type you are using?

**Comment by alexlopezit** [comment]
Thanks @mahboubii 

It's very random
All our users are type `user` but so far has happened for 3 of our users
We are using `MessageTeam`

Code looks like:
```
<MessageList
    messageActions={['edit', 'delete']}
    Message={MessageTeam}
/>
```
And we have not set custom permissions

**Comment by mahboubii** [comment]
@alexlopezit I was not able to reproduce this issue, also the logic seems to be ok. If a user is `owner` (of a channel) or `admin` or `moderator` or `channel_moderator`  will have access to delete or edit a message, but the fact that you mentioned the API rejects the request means this is not the case. Would be great if you could capture more data next time this happens, including the message data, user data, and the rejected network request.

``` 
  const isMyMessage =
    !!message?.user && !!client?.user && client.user.id === message.user.id;
  const isAdmin =
    client?.user?.role === 'admin' ||
    channel?.state?.membership?.role === 'admin';
  const isOwner = channel?.state?.membership?.role === 'owner';
  const isModerator =
    channel?.state?.membership?.role === 'channel_moderator' ||
    channel?.state?.membership?.role === 'moderator';

  const canEditMessage = isMyMessage || isModerator || isOwner || isAdmin
```

**Comment by alexlopezit** [comment]
Ok, this is still happening randomly but we managed to get some more info, we suddenly got the ellipsis menu showing on a message from another user, then I clicked the "Edit" button, then clicked on the submit button and here is the failing request I got from that action.

But from what I see still does not explain why I was able to see the actions menu.

Channel "cid": "messaging:79f67b41-1cdb-4191-a360-e5179314221e"
User I was loged in with:  "id": "0055B000000sTrhQAE@00D5B0000000Ye4UAE"

```
POST /messages/0055B000002WFSXQA4@00D5B0000000Ye4UAE-b5447653-1279-47d3-8f77-30816fd26bda?user_id=0055B000000sTrhQAE%4000D5B0000000Ye4UAE&api_key=dtndubxnmhpr&connection_id=a7t53364-cfg2-4afd-84e5-465667f24hd0 HTTP/1.1
Host: chat-us-east-1.stream-io-api.com
Connection: keep-alive
Content-Length: 2433
Accept: application/json, text/plain, */*
stream-auth-type: jwt
Authorization: [REMOVED_TOKEN]
x-stream-client: stream-chat-react-3.1.7-stream-chat-javascript-client-browser-2.7.3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
Content-Type: application/json;charset=UTF-8
Origin: https://jiateam.my.website.com
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://jiateam.my.website.com/messaging
Accept-Encoding: gzip, deflate, br
Accept-Language: en-AU,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,la;q=0.6
```

```
HTTP/1.1 403 Forbidden
Server: fasthttp
Date: Thu, 19 Nov 2020 07:01:37 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 241
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
X-Ratelimit-Remaining: 999
X-Ratelimit-Reset: 1605769320
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: x-requested-with, content-type, accept, origin, authorization, x-csrftoken, x-stream-client, stream-auth-type, x-csrf-token, content-encoding
Cache-Control: no-cache
X-Ratelimit-Limit: 1000
Access-Control-Max-Age: 86400
Content-Encoding: gzip
Keep-Alive: timeout=58, max=1000
Connection: keep-alive
```

```
{"code":17,"message":"UpdateMessage failed with error: \"User '0055B000000sTrhQAE@00D5B0000000Ye4UAE' with role channel_member is not allowed to access Resource UpdateMessage on channel type messaging\"","StatusCode":403,"duration":"0.00ms","more_info":"https://getstream.io/chat/docs/api_errors_response"}
```

Then I reloaded the browser to see if I could get it again, but this time was fine and no options to edit where displayed on the other user's message.

**Comment by kmutlow** [comment]
Hi @mahboubii, just checking in on behalf of @alexlopezit to see if there has been any progress on this issue?

**Comment by DanC5** [comment]
Hey @kmutlow I'll take a look at this first thing tomorrrow, thanks

**Comment by DanC5** [comment]
@kmutlow @alexlopezit I'm not able to recreate this trying a bunch of things in a sample app. But small change here, have you tried saving ['edit', 'delete'] as a constant and passing the constant in as a prop? I wonder if passing the array directly is causing some kind of async rendering where the Message receives a new copy of the actions array causing it to show the actions menu. That's the only thing I can think of as everything else seems very standard.

**Comment by kmutlow** [comment]
Thanks @DanC5 we'll give that a try and see what we get. It was always intermittent on our side so not surprised that you can't repro it. Will keep an eye out for this and let you know how we get on.

**Comment by DanC5** [comment]
@alexlopezit @kmutlow Do you two have any more updates regarding this issue? Are you still experiencing a problem?
