### ISSUE TITLE
Do not show message actions if there are no actions

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#592]
Is it possible to not display the message actions button and menu when there are no actions?

Using "stream-chat-react": "3.1.6"

We have a component called SilentMessage where we only want to allow reactions, so we tried to use the `getMessageActions` with an empty array which seems to work, but we can still see the empty dropdown and icon.

<img width="1202" alt="Screen Shot 2020-10-28 at 1 20 23 pm" src="https://user-images.githubusercontent.com/1654135/97387193-49efce80-1921-11eb-83cb-0e377939110d.png">

The code we are currently using looks like:

```
import React from 'react'
import { MessageTeam, MessageTeamState, MessageUIComponentProps } from 'stream-chat-react'

type IMessageProps = MessageUIComponentProps & MessageTeamState

/**
 * This is a wrapper of the current Message with some pros disabled and custom styles to display system messages
 *
 * @param {props<IMessageProps>} GetStream message props
 */
export const SilentMessage: React.FC<IMessageProps> = props => {
  /**
   * Returning an empty array will ensure the message does not have any actions available
   */
  const getMessageActions = () => ['']

  return (
    <div className="messaging__system-message">
      <MessageTeam
        {...props}
        groupStyles={['top']}
        actionsEnabled={false}
        editing={false}
        getMessageActions={getMessageActions}
      />
    </div>
  )
}
```

cc @tbarbugli 

gz#6910

**Comment by tbarbugli** [comment]
makes sense to not show the action button when there are no actions

**Comment by jaapbakker88** [comment]
@alexlopezit Thanks for your report, right now you're passing one action, an empty string, which we don't know how to render. While we look into a way to do this more gracefully, this should do the trick:
```
 const getMessageActions = () => []
```

**Comment by alexlopezit** [comment]
Thanks @jaapbakker88, have missed such a small detail, with no empty string works perfect.
