### ISSUE TITLE
How to customize user's Avatar ?

### ISSUE THREAD

**Issue by HN00** [GetStream/stream-chat-react#600]
I only set the user's Id (without Image, without the name). When I customize the Message component in order to show avatar, I must rewrite all components to do it. So, Do we have another case to do it ?

gz#7110

**Comment by mahboubii** [comment]
Unfortunately, We don't support this at the moment. Could you share more detail about render details of Avatar in case there is no image and no name to fall back to? If it's a general case we can discuss adding support for it.

**Comment by HN00** [comment]
I would like to use another image from my database and put it into the MessageList component.

**Comment by mahboubii** [comment]
> I would like to use another image from my database and put it into the MessageList component.

If you don't need to change the UI behavior of the Avatar component, you might be able to achieve this by inserting the field directly into `message.user` object at Message or MessageList level. Could you share more detail about the specifics of your use case?

**Comment by HN00** [comment]
I’m using typescript. And I just read it

**Comment by alexlopezit** [comment]
+1 for a custom Avatar.

In our case we add the images to the user object but for security reasons every image url expires after 15 minutes is the user is not active on our system, when images expire the Avatar component falls back to the 2 letters.

So if we could use a custom component to replace the current Avatar would solve our problem as we will provide the updated images ourselves.

**Comment by DanC5** [comment]
Alex, it's on my list to allow override of the Avatar component with a custom prop. I should get around to rolling this out next week, thanks!

**Comment by DanC5** [comment]
All default Avatar components can now be overridden via custom components passed through props: https://github.com/GetStream/stream-chat-react/releases/tag/v3.3.0
