### ISSUE TITLE
overrideSubmitHandler and optimistic UI update

### ISSUE THREAD

**Issue by alexlopezit** [GetStream/stream-chat-react#605]
I am currently trying to use `overrideSubmitHandler` and noticed that the message gets populated after the `sendMessage` promise, is there a way to make it work so the optimistic update (message is populated in the `MessageList`) still happens as soon as the user sends the message without needing to wait for the request response?

Code I am testing for reference

```
import React from 'react'
import { Message } from 'stream-chat'
import { ChannelContext, MessageInput, MessageInputProps } from 'stream-chat-react'

export const MessageInputWrapper: React.FC<MessageInputProps> = (props) => {
  const { channel } = React.useContext(ChannelContext)

  const overrideSubmitHandler = async (message: Message) => {
    // Analytics tracking here

    // Now send the message
    channel.sendMessage(message)
  }

  return <MessageInput {...props} overrideSubmitHandler={overrideSubmitHandler} />
}
```

gz#7205

**Comment by mahboubii** [comment]
you can leverage the `sendMessage` which already has the optimistic update.

```js
const { sendMessage } = React.useContext(ChannelContext)
const overrideSubmitHandler = async (message: Message) => {
   // Analytics tracking here
   sendMessage(message)
}
```

**Comment by alexlopezit** [comment]
Thanks @mahboubii that seems to work, however looks like there is an issue on the type as `text` is required here https://github.com/GetStream/stream-chat-react/blob/8c081163d0cadcfa61a1391c3c1fe6e522789d3b/types/index.d.ts#L110 but optional on `Message`. Is this something that perhaps needs a separate issue?

**Comment by mahboubii** [comment]
I think you are right and this can be optional. In the meantime, you can pass in an empty string to stay consistent with the library.

**Comment by alexlopezit** [comment]
Thanks @mahboubii but I am actually passing a message with text, it's just Typescript complaining for the different types.

For now I solved that by doing `sendMessage(message as any)`

**Comment by mahboubii** [comment]
@alexlopezit #613 should cover this.
