### ISSUE TITLE
Support typing events in threads

### ISSUE THREAD

**Issue by AnatolyRugalev** [GetStream/stream-chat-react#609]
Hi there.

`stream-chat-js` has the ability to distinguish typing events between the main channel and a thread. This is done with an optional `parent_id` parameter in `keystroke` method (parent_id is the ID of the thread): https://github.com/GetStream/stream-chat-js/blob/master/src/channel.ts#L882

This feature is there for a while now, but it was not documented to this moment. You can find updated version of JS documentation here: https://getstream.io/chat/docs/typing_indicators/.

**Comment by mahboubii** [comment]
pending https://github.com/GetStream/stream-chat-js/pull/505/

**Comment by DanC5** [comment]
https://github.com/GetStream/stream-chat-react/pull/662
