### ISSUE TITLE
Messages marked as delivered even though they aren't

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-react#612]
If I put my client in airplane mode and send a message from the react client, the message is marked as "delivered", however the client has no connection, so it was not delivered. Is this by design? Thanks!

gz#7436

**Comment by mahboubii** [comment]
@amardeepranu The SDK supports optimistic UI updates and it should fail if the message is not successfully sent.
can you update to `stream-chat` to [v2.8.1](https://github.com/GetStream/stream-chat-js/releases/tag/v2.8.1) and test?
