### ISSUE TITLE
MessageListInner sometimes has duplicate keys.

### ISSUE THREAD

**Issue by Tenkir** [GetStream/stream-chat-react#615]
Occasionally we will get two messages in the list with the same key, leading to unexpected behavior such as duplication or jumping of messages.

```
Warning: Encountered two children with the same key, `sara-ravid-914602cc-0936-48b8-b5f0-ad21952c45c7`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in ul (created by MessageListInner)
    in div (created by InfiniteScroll)
    in InfiniteScroll (created by MessageListInner)
    in MessageListInner
    in MessageListInner (created by MessageList)
    in div (created by MessageList)
    in MessageList (created by Context.Consumer)
    in Unknown (created by Context.Consumer)
    in Component (at chat.tsx:126)
   ...
```

gz#7463

**Comment by mahboubii** [comment]
Hey @Tenkir, thanks for reporting this. Which version of the `stream-chat` and `stream-chat-react`  library are you using?
What are the steps to reproduce this issue?

**Comment by Tenkir** [comment]
`stream-chat`: 2.7.0
`stream-chat-react`: 3.1.6

This only seems to happen locally to the user sending a message. It happens sporadically, so we haven't been able to pin down a way to reproduce.

**Comment by mahboubii** [comment]
by any chance are you manually using `addMessageSorted` or `addMessagesSorted` functions? do you have any custom logic related to Channel or MessageInput components?

**Comment by mahboubii** [comment]
@Tenkir can you update to `stream-chat` to [v2.8.1](https://github.com/GetStream/stream-chat-js/releases/tag/v2.8.1) and test?

**Comment by Tenkir** [comment]
> by any chance are you manually using `addMessageSorted` or `addMessagesSorted` functions? do you have any custom logic related to Channel or MessageInput components?

We do not. We are updating to v2.8.1 for testing now.

**Comment by shodgetts** [comment]
Did this resolve your issue?
