### ISSUE TITLE
Messages do not appear in the channel if two users initialized a one-to-one conversation at the same time

### ISSUE THREAD

**Issue by romankrru** [GetStream/stream-chat-react#619]
Messages do not appear in the channel if two users initialized a one-on-one conversation  with each other at the same time.

To initialize one-to-one conversation, I use the following code:
```javascript
const {setActiveChannel, client} = useContext(ChatContext)

const startOneToOne = async (userId) => {
  const channel = client.channel('messaging', {
    memebers: [curentUserId, userId],
  })

  await channel.create()

  /* NOTE: I need the newly created conversation to be active*/
  setActiveChannel(channel)
}
```

To reproduce the problem you need to:
1. On the `user1` side, call 
```js
startOneToOne(user2Id)
```
2. On the `user2` side, call 
```js
startOneToOne(user1Id)
```
3. Create a message in the channel from `user1`
4. `user2` ***does not receive*** any message
5. Create a message in the channel from `user2`
6. `user1` receives messages from `user2`

| User1 | User2 |
| --- | --- |
| ![Screenshot from 2020-11-30 23-04-37](https://user-images.githubusercontent.com/4049739/100658816-b1ee6600-3360-11eb-8668-d2faadef0ce8.png) | ![Screenshot from 2020-11-30 23-04-49](https://user-images.githubusercontent.com/4049739/100658842-bd419180-3360-11eb-896d-d285f8eba159.png) |

If I reload the page, you can see that both messages were sent successfully:

| User1 | User2 |
| --- | --- |
| ![Screenshot from 2020-11-30 23-05-26](https://user-images.githubusercontent.com/4049739/100658870-c7fc2680-3360-11eb-8ec8-b7a0351b2821.png) | ![Screenshot from 2020-11-30 23-05-36](https://user-images.githubusercontent.com/4049739/100658886-d0546180-3360-11eb-9e63-c3caa5ab5a8e.png) |

The chat components look like this:
```jsx
<Chat client={client} theme="messaging dark">
  <UsersList />

  <ChannelList
    setActiveChannelOnMount={false}
    LoadingIndicator={CustomLoading}
    Preview={CustomPreview}
    options={{presence: true, watch: true}}
    filters={{members: {$in: [props.userId]}, type: 'messaging'}}
  />

  <Channel>
    <Window>
      <CustomHeader />
      <MessageList />
      <MessageInput />
    </Window>
  </Channel>
</Chat>
```

Hope you can help.

gz#7665

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/7665'>Zendesk ticket #7665</a>:<br><br>Hello, what is the Stream appID you are using please?

Curious why you try to create the channel twice? Can you also change the channel.create() to channel.watch() instead and let us know if that makes a difference.

**Comment by romankrru** [comment]
@shodgetts 

Should I post my appId here on github?

>why you try to create the channel twice

I need the ability to create one-to-one conversations for users between each other. I have a list of users and 'Start conversation' button next to each user. If 2 users decide to start a conversation with each other at the same time, they will try to create the same channel twice. Should I somehow check that the channel already exists inside the `startOneToOne` function?

Replacing `channel.create` with `channel.watch` didn't change anything.

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/7665'>Zendesk ticket #7665</a>:<br><br>Yes, you can post appID or key here, no problem.

You could check if it exists. But does this seem like a likely situation? Two users opening a channel with each other at _**exactly**_ the same time?

**Comment by DanC5** [comment]
@romankrru Since we haven't heard back on this item I'm going to close the issue. I would tend to agree with Stephen here that it's highly unlikely two users would create a channel with each other at the exact same time. However, do let us know if this somehow is a blocker for you, as we'd likely need to involve the backend team, as such an issue wouldn't be solved by adjustments to the front end component library.
