### ISSUE TITLE
Question: Is there different UI for channel moderators?

### ISSUE THREAD

**Issue by chenghw** [GetStream/stream-chat-react#620]
Hi,

I'm currently working on an implementation for a multi-tenant 'messaging' channel type app. If a user is a channel_moderator, is there a different UI that ships with this package for a moderator to take advantage of their additional features such as banning or removing users from a channel?

Versions
"stream-chat": "2.8.4"
"stream-chat-react": "3.2.4"

gz#7672

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/7672'>Zendesk ticket #7672</a>:<br><br>Hi there,

As a moderator, you'll have more options in the message actions box such as delete and edit. If you'd like to customize this further, I'll link you to the component docs on this here. You could also take advantage of the built in /ban command if this better fits your use case.

**Comment by chenghw** [comment]
Hi,

Thanks for the quick response. Sure, can you please link me to the components that would need to be customized to best handle the ban/remove commands?

Thanks,

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/7672'>Zendesk ticket #7672</a>:<br><br>the /ban command is available out-of-the-box. You can enable / disable this from your dashboard: chat overview -> channel type -> commands. If you'd like to customize the message actions box, take a look here: https://getstream.github.io/stream-chat-react/#messageactionsbox (sorry, my hyperlink didn't seem to work in that last one).
