### ISSUE TITLE
ChannelList reaload everytime parent state change

### ISSUE THREAD

**Issue by tranlehaiquan** [GetStream/stream-chat-react#623]
Hello,
I want to change my location from message -> message/:channelId when the user clicks on the channel. But I face with the problem that every time location changes (eg: message/channel1 -> message/channel2). I find it out because this line in usePaginatedChannels.js. useEffect always run because it can't compare `filters`.  (line 82) I replace it with `use-deep-compare-effect` and it work.

```
useEffect(() => {
    queryChannels('reload');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filters]);
```
To
```
import useDeepCompareEffect from 'use-deep-compare-effect'

useDeepCompareEffect(() => {
    queryChannels('reload');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filters]);
```

**Comment by DanC5** [comment]
While I understand what you're trying to do here, I don't think it makes sense for us to make a customer-wide change for this implementation. I'm worried about the performance impacts our other customers would see by running the deep compare at all times. One thing I'll suggest is to make sure your filters object is outside of the render cycle so it's reference is unchanging and it's not triggering unnecessary reloads. For example...

```
const filters = { type: 'messaging'  }

const App = () => { // chat app here }

```

instead of...

```
const App = () => {
  const filters = { type: 'messaging'  }
  // chat app here
}
```

**Comment by tranlehaiquan** [comment]
What If I have userId get from hook? @DanC5

**Comment by tranlehaiquan** [comment]
Okie got it, I must create another component that store filter and pass it down to App chat. I will try, thank u.

**Comment by DanC5** [comment]
> Okie got it, I must create another component that store filter and pass it down to App chat. I will try, thank u.

Yes that will be the best move since the reference will ideally not have to change. Good luck!

**Comment by tranlehaiquan** [comment]
Can you please add more info about this in the document? Your customer will very happy (our customer selected you to be the chat of our website)

**Comment by DanC5** [comment]
> Can you please add more info about this in the document? Your customer will very happy (our customer selected you to be the chat of their website) @DanC5

Yes, we're currently rolling out new examples and we're highlighting this piece, thanks.
