### ISSUE TITLE
Issue with Custom Message and Attachment Types

### ISSUE THREAD

**Issue by nandakishorebhandari** [GetStream/stream-chat-react#624]
Hi Team,

Use Case:

I want to create a custom attachment component to show a button with a link to navigate to another route when the user types ''/appointment'. But unable to display the attachment. 

![Screenshot 2020-12-08 at 8 53 34 AM](https://user-images.githubusercontent.com/34581284/101436034-6aa14000-3933-11eb-9f98-3ff5110c5029.png)

SDK: React Web

Tutorial followed: Custom Message and Attachment Types

Error:
<img width="680" alt="Screenshot 2020-12-08 at 12 33 53 AM" src="https://user-images.githubusercontent.com/34581284/101436043-6d9c3080-3933-11eb-85e7-d1522425fee0.png">

Actual UI:

![Screenshot 2020-12-08 at 8 52 10 AM](https://user-images.githubusercontent.com/34581284/101436055-70972100-3933-11eb-9ec4-237b6a8fce9c.png)

gz#7831

**Comment by DanC5** [comment]
Hello, we're rolling out a React MML (https://www.npmjs.com/package/mml-react) support shortly which will help you implement this solution. The pull request has been opened so it's only a matter of time before we merge and create a new release.

https://github.com/GetStream/stream-chat-react/pull/562

Feel free to follow that pull request and I'm going to close this issue, thanks!

**Comment by nandakishorebhandari** [comment]
@DanC5 Thanks, Will this React MML also work for react native?

**Comment by DanC5** [comment]
> @DanC5 Thanks, Will this React MML also work for react native?

At the moment this is only web-based since it's built on html, but we're considering re-purposing for React Native but haven't prioritized it yet.
