### ISSUE TITLE
Type: Component create with withChatContext required client for prop

### ISSUE THREAD

**Issue by tranlehaiquan** [GetStream/stream-chat-react#626]
I'm creating a Component use withChatContext and it required the Client props for nothing.
![require](https://user-images.githubusercontent.com/17347993/101601467-488ce800-3a2f-11eb-914d-b60a0f75f62d.PNG)

Expect: exclude from props return component

source Component:

```
import { withChatContext, ChatContextValue } from 'stream-chat-react';

const EmptyChannels: React.FC<ChatContextValue> = () => {
  return (
    <p>empty</p>
  );
};

export default withChatContext(EmptyChannels);

```

Another question: Some time props is React Function Component and some time it is React.Node? In this case we do not pass any props to EmptyComponent so why we use React Function Component?

gz#7888

**Comment by DanC5** [comment]
Do you need any of the chat context values in the `EmptyChannels` component? If so, I'd recommended removing the `withChatContext` higher order component and instead pull the values from context directly via the hook,

`const chatContext = useContext(ChatContext)`

 If not, you can remove the higher order component entirely. This might be a bug with our typing implementation of the higher order components, which I know are low priority for us and aren't used very often any more. We're updating to full Typescript in January, so if this is a bug then we'll catch it then. But for now I'd say either pull directly from context if you need, or remove the higher order component if you don't. Thanks.

**Comment by tranlehaiquan** [comment]
@DanC5 

Ok, thank you I will try. I do this because:
I want to show a specific screen when the user has zero channels. The first time I try to create a whole new component but I face a problem that I don't when it loaded with result zero channels or just start and loading to show and custom screen. So I use EmptyIndicator to work around.

**Comment by DanC5** [comment]
Sounds good, yeah if you don't need to access your instance of the StreamChat or any other aspects from `ChatContext` in your empty state component you can leave off the higher order component. Thanks!
