### ISSUE TITLE
Upload images from another source than the filesystem

### ISSUE THREAD

**Issue by jgoux** [GetStream/stream-chat-react#631]
Hello,

is there any props / hooks that I can use to add a new image to the chat that doesn't come from the user's file system but from another source like the phone's camera (user getUserMedia)?

Thanks for your help. :)

gz#7973

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/7973'>Zendesk ticket #7973</a>:<br><br>Hello, is this concerning the React or React-native SDK?

**Comment by jgoux** [comment]
It's for react in our case.

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/7973'>Zendesk ticket #7973</a>:<br><br>In which case it isn't in our roadmap to be adding the phone camera to the React SDK unfortunately. Sorry,

**Comment by DanC5** [comment]
You will need to create your own file upload component to replace our `FileUploadButton`, https://github.com/GetStream/react-file-utils/blob/master/src/components/FileUploadButton.js. Support for accessing native functionality is not included with our React SDK, only React Native.

**Comment by jgoux** [comment]
@DanC5 The getUserMedia is a pure web API and can be used in any PWA. 😄 

Ok, I'll need to fork the component then, thanks for the answer!

**Comment by jgoux** [comment]
Sorry for the double post, but would you consider exposing the FileUploadButton as a prop of MessageInputLarge so we have a chance to provide our own instead of forking the whole MessageInputLarge?
