### ISSUE TITLE
Just show channel when it has message

### ISSUE THREAD

**Issue by tranlehaiquan** [GetStream/stream-chat-react#634]
Hi Get stream,

When I start a channel with one - one the user from both sides (a - b) can see the channels with zero message. 

Example:
  - A initial chat with B
  - A, B can see the channel (one - one)

Expect: 
  - A initial chat with B
  - A can see the channel chat (one - one)
  - When A send the first message
  - B can see the channel (one - one)

Thank you.

gz#7989

**Comment by SeniYG** [comment]
Hi,

This is the API default behavior when creating a new channel with the members defined.
The best way for you to achieve this use-case would be to hide the channel for user B after the channel creation.
https://getstream.io/chat/docs/channel_delete/?language=js#hiding-a-channel

Regards,

**Comment by tranlehaiquan** [comment]
Hi, @SeniYG . Thank you for your response.
 
I have some feels more question:

- So after getting the channel instance, I must detect if it is the first time (with message = 0) and hide that channel for user B?
- I also have tried to hide the channel from the client-side. But it warned it just support only from the server-side. So I must create an API for this?

**Comment by mahboubii** [comment]
@DanC5 Accepting a custom filter function in ChannelList might be a good idea. it also solves the #617

**Comment by SeniYG** [comment]
Hi @tranlehaiquan , 

In the meantime,

> So after getting the channel instance, I must detect if it is the first time (with message = 0) and hide that channel for user B?
Yes, you could do that, or listen to `member.added` webhook event and triggers the channel.hide() accordingly.
Client-side you could also listen to `member.added` and `notification.added_to_channel` websocket events to handle this. However, for the latest, you won't get notified if the user is offline.

> I also have tried to hide the channel from the client-side. But it warned it just support only from the server-side. So I must create an API for this?
The `channel.hide()` method should be accessible client-side and server-side. Can you show us your code for this call?

Thanks in advance.

**Comment by tranlehaiquan** [comment]
> @DanC5 Accepting a custom filter function in ChannelList might be a good idea. it also solves the #617

So after merge, I can use the filter for complete this?

**Comment by tranlehaiquan** [comment]
any news?

**Comment by DanC5** [comment]
@tranlehaiquan this feature was behind a couple others, but we're now prioritizing it and will hopefully have something very soon, we'll respond back when the time comes, thanks

**Comment by mahboubii** [comment]
hey @tranlehaiquan, please check out [v3.5.3](https://github.com/GetStream/stream-chat-react/releases/tag/v3.5.3). You can pass in a `channelRenderFilterFn`  prop to `ChannelList` to filter the channel without messages.
