### ISSUE TITLE
New users can be added to one-to-one channels

### ISSUE THREAD

**Issue by jz222** [GetStream/stream-chat-react#635]
I would like to build an in-app chat feature. That allows users to chat with each other in one-to-one chats. Only after a certain match, two users should be able to message each other.

I have the following express endpoint that returns the API key and the user's token.

```javascript
app.post('/join', async (req, res) => {
    const { username } = req.body;
    
    const token = serverSideClient.createToken(username);
    
    return res
        .status(200)
        .json({ user: { username }, token, api_key: process.env.STREAM_API_KEY });
});
```

And the following React component.

```javascript
import React, { useState, useEffect } from 'react';
import './App.css';
import {
    Chat,
    Channel,
    ChannelHeader,
    Window,
    MessageList,
    MessageCommerce,
    MessageInput,
} from 'stream-chat-react';
import { StreamChat } from 'stream-chat';
import axios from 'axios';

import 'stream-chat-react/dist/css/index.css';

let chatClient;

function App() {
    const [channel, setChannel] = useState(null);
    
    useEffect(() => {
        const username = prompt('Please enter a username');
        
        async function getToken() {
            try {
                const response = await axios.post('http://localhost:5500/join', {
                    username,
                });
                const { token } = response.data;
                const apiKey = response.data.api_key;
                
                chatClient = new StreamChat(apiKey);
                
                await chatClient.setUser(
                    {
                        id: username,
                        name: username,
                    },
                    token
                );
                
                const channel = chatClient.channel('messaging', {
                    members: ['joker', 'batman'],
                });
                
                await channel.watch();
                
                setChannel(channel);
                
            } catch (err) {
                console.log(err);
            }
        }
        
        getToken();
    }, []);
    
    if (channel) {
        return (
            <Chat client={chatClient} theme="commerce light">
                <Channel channel={channel}>
                    <Window>
                        <ChannelHeader />
                        <MessageList Message={MessageCommerce} />
                        <MessageInput focus />
                    </Window>
                </Channel>
            </Chat>
        );
    }
    
    return <div></div>;
}

export default App;
```

I face two issues. The users `joker` and `batman` should be allowed to chat with each other. However, if a different username is provided, that user will be added to jokers and batmans conversation, which should of course not be possible since everyone could easily read their conversation, with a little coding. Secondly, because there is no restriction, every user could start a chat with another user. This chat could only be hidden in the frontend. The channel and the messages would be created in getstream.io

Talk.js has the option to create chats exclusively on the backend https://talkjs.com/docs/Features/Security_Settings/Browser_Synchronization.html

gz#7996

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/7996'>Zendesk ticket #7996</a>:<br><br>Hi,

Can you please provide the App ID related to your issue ?

Thanks in advance.

**Comment by jz222** [comment]
Hi,

sure, it is `103463`.

**Comment by SeniYG** [comment]
Hi again,

You currently have Permissions Checks disabled on your app, which explains why currently, any user can access any channel on the app.
You will need to enable them back via the dashboard. This should fix your issue.

Regards,

**Comment by jz222** [comment]
Thank you. I was looking for this feature in the documentation, but couldn't find it. Could you please show me where I can find these settings?

**Comment by SeniYG** [comment]
From your app dashboard : https://dashboard.getstream.io/dashboard/v2/organization/59957/app/103463/chat
Scroll down to "Authentification" section -> uncheck "Disable Permissions checks"
