### ISSUE TITLE
Close button icon doesn't show in IOS thread

### ISSUE THREAD

**Issue by tranlehaiquan** [GetStream/stream-chat-react#636]
The close button's icon doesn't show up in mobile view.

![IMG_2257](https://user-images.githubusercontent.com/17347993/102065881-ace2e980-3e2b-11eb-87b3-f32739bad21c.PNG)

I don't have MacOS to debug, so sorry for no pull request.

gz#8010

**Comment by yetieaterxb1** [comment]
We have put in a fix that will be deployed in our next release.

https://github.com/GetStream/stream-chat-react/pull/648
