### ISSUE TITLE
Export UploadsPreview component

### ISSUE THREAD

**Issue by jgoux** [GetStream/stream-chat-react#643]
Hello,

I need to customize the MessageInputLarge component but I noticed that the UploadsPreview component isn't exported.

Is it possible to expose this component?

I also noticed that the EmojiPicker component is exported but its types definition are missing.

Thanks for your help.

gz#8048

**Comment by DanC5** [comment]
@jgoux just made a PR to add this to the library, so it will be available to import as soon as we make a build, https://github.com/GetStream/stream-chat-react/pull/647. Closing the issue as it will be live very soon, thanks!
