### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by TylerAHolden** [GetStream/stream-chat-react#649]
https://github.com/GetStream/stream-chat-react/blob/0b7e1635ad2a4f2efe0eda19c0816eeafaa2a14d/src/components/MessageList/MessageList.js#L329

Missing react and reply.

gz#8293

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8293'>Zendesk ticket #8293</a>:<br><br>Hi Tyler

Thanks for reaching out to us.
You are referring to `MessageList.js`, Please refer to the Message component where all the actions including React and Reply can be found.
https://github.com/GetStream/stream-chat-react/blob/0b7e1635ad2a4f2efe0eda19c0816eeafaa2a14d/src/components/Message/Message.js

Also, please take a look at MessageList which has the default props as below -

    MessageList.defaultProps = {  Attachment,  Avatar,  Message: MessageSimple,  MessageSystem: EventComponent,  threadList: false,  DateSeparator: DefaultDateSeparator,  LoadingIndicator: DefaultLoadingIndicator,  TypingIndicator: DefaultTypingIndicator,  EmptyStateIndicator: DefaultEmptyStateIndicator,  unsafeHTML: false,  noGroupByUser: false,  messageActions: Object.keys(MESSAGE_ACTIONS),};


Please let me know if this helps or if you need more information.

Cheers
Seetha

**Comment by TylerAHolden** [comment]
Huh? On the docs for the components it clearly says its a prop for MessageList and in the description (the line I opened an issue with) has incorrect array values as examples. It’s missing react and reply. I shouldn’t have to search through the source code to find deep in the message component folder there is a utils file with this ambiguous MESSAGE_ACTIONS constant lol.
<img width="1665" alt="Screen Shot 2020-12-28 at 7 27 55 PM" src="https://user-images.githubusercontent.com/38476278/103252732-a2ecda80-4943-11eb-9c47-bee29ba6d55d.png">

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8293'>Zendesk ticket #8293</a>:<br><br>Hi Tyler

Thanks for the feedback. I will request our Engineering team to have a look at this and update the docs if need be.

Cheers
Seetha

**Comment by DanC5** [comment]
Hey Tyler, the list of message actions in the docs wasn't meant to be exhaustive, more just an example of possible actions. Though I totally see your point here, and where it could lead to confusion. I'll get these updates into the library to prevent this same issue from popping up in the future, thanks.

**Comment by TylerAHolden** [comment]
@DanC5 Yea I know but MESSAGE_ACTIONS I don't think is defined anywhere in the docs so you pretty much have to look in the source code. Right now the typing in index.d.ts is `messageActions?: Array<string>;` so it could be anything. Are yall still going to migrate everything to typescript?

**Comment by shodgetts** [comment]
Agent comment from Dan Carbonell in <a href='https://getstream.zendesk.com/agent/tickets/8293'>Zendesk ticket #8293</a>:<br><br>Yeah the TS migration is happening starting in the new year (so next week). It'll be our top priority for Q1. Feel free to check out the react native library to get an idea of how it'll look, lot of generic usage for client-controlled custom typing.

**Comment by DanC5** [comment]
https://github.com/GetStream/stream-chat-react/pull/654
