### ISSUE TITLE
Uncaught TypeError: lastRead.getTime is not a function

### ISSUE THREAD

**Issue by TylerAHolden** [GetStream/stream-chat-react#653]
## Steps to reproduce:
1. Update examples/commerce/package.json 
`"stream-chat": "^2.10.0",`
`"stream-chat-react": "^3.4.3"`
2. Run example
3. Type message
4. send message
5. close message list
6. open message list again

```
Uncaught TypeError: lastRead.getTime is not a function 
    at insertDates (MessageListInner.js:54)
    at MessageListInner.js:199
```

https://user-images.githubusercontent.com/38476278/103257188-d20c4780-4955-11eb-9104-724b0c9e8f33.mov

gz#8295

**Comment by DanC5** [comment]
@TylerAHolden just opened a PR for both of your GH issues. We'll get this merged and make a new release shortly. Feel free to follow the PR and in the meantime I'm going to close both issues, thanks.

https://github.com/GetStream/stream-chat-react/pull/654

**Comment by TylerAHolden** [comment]
Awesome thanks!
