### ISSUE TITLE
Type definition errors

### ISSUE THREAD

**Issue by DamonOehlman** [GetStream/stream-chat-react#658]
There are multiple instances in the type definitions for the types in the package that cause the types to fail validation.  One example is the [following](https://github.com/GetStream/stream-chat-react/blob/7d7e685899358be3d058623542090dfa9edf19f6/types/index.d.ts#L407-L413):

```ts
export function useMentionsHandlers(
  onMentionsHover?: (e: React.MouseEvent, user?: Client.UserResponse) => void,
  onMentionsClick?: (e: React.MouseEvent, user?: Client.UserResponse) => void,
): (
  e: React.MouseEvent<HTMLSpanElement>,
  mentioned_users: UserResponse[],
) => void;
```

This particular error is caused by `UserResponse` being used without the `Client` namespace in the last occurrence.  Just wondering if there's any possibility of adding something into the repo to ensure that the type definitions are correct with each version that is published. 

gz#8464

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8464'>Zendesk ticket #8464</a>:<br><br>Hi Damon,

Sure, We'll take a look into this as soon as we can.

Cheers
Stream Team

**Comment by DanC5** [comment]
@DamonOehlman thanks for pointing out this error, just pushed the type fix, https://github.com/GetStream/stream-chat-react/pull/660. Also, we're beginning a full Typescript conversion for this library in two weeks, so we'll be sure to catch all the other little inconsistencies during that process. Look for a full TS release of the library sometime near the end of Q1.

**Comment by DamonOehlman** [comment]
@DanC5 Great - thanks Dan.  Really appreciate you folks jumping on this one quickly.
