### ISSUE TITLE
Unsupported Image types should be uploaded as files not images

### ISSUE THREAD

**Issue by hablodoug** [GetStream/stream-chat-react#671]
Dragging in a PSD file into the Chat in order to send it to another user causes an error:

Error: StreamChat error code 4: UploadImage failed with error: "File type image/vnd.adobe.photoshop is not supported"

I wouldn't expect it to recognise the image of complex image formats like PSD, but it should instead upload it as a file (like it would with office documents) so that they can still be sent via Chat.

gz#8626

**Comment by DanC5** [comment]
@hablodoug great catch, the photoshop mime type is prepended with `image/`. This PR fixes it, we'll likely make a new release end of week, https://github.com/GetStream/stream-chat-react/pull/673

**Comment by hablodoug** [comment]
nice one, thanks!
