### ISSUE TITLE
Emoji picker not opening.

### ISSUE THREAD

**Issue by nandakishorebhandari** [GetStream/stream-chat-react#679]
After clicking on emoji picker, nothing happens.

![Screenshot 2021-01-23 at 2 17 52 AM](https://user-images.githubusercontent.com/34581284/105544862-6c776500-5d21-11eb-8ad6-6ceffa584633.png)

gz#8821

**Comment by DanC5** [comment]
@nandakishorebhandari this has been fixed in version 3.5.2, thanks!

**Comment by nandakishorebhandari** [comment]
@DanC5 Thanks.
