### ISSUE TITLE
livestream chat should not include join notifications

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#68]
I have specified `connect_events: False` on my custom livestream type, and yet my customers are seeing "[Username] has joined the chat" notifications. This seems like a bug. On livestream style chat, connect notifications become very noisy when there are a lot of participants. 

![screenshot of getstreamIO livestream settings with "connect events" set to false](https://user-images.githubusercontent.com/140930/66348075-b1f10280-e923-11e9-9252-5c9af716a7d0.png)

Can you recommend a workaround until this is solved?

UPDATE - I found a workaround by putting this in my CSS: 
```
.str-chat__event-component__channel-event {
    display: none;
}
```

UPDATE 2: 
We are using:

python:
stream-chat==0.4.3

js: 
stream-chat-react==0.6.20
stream-chat==1.0.4

**Comment by jaapbakker88** [comment]
hi @codekiln, thank you for reporting this, I think this is a bug and we'll look into this. We'll update here once we have a solution.

**Comment by vishalnarkhede** [comment]
Hey @codekiln , `Connect Event` toggle on dashboard only controls `user.start_watching` and `user.stop_watching` event. We will add a support for prop to allow custom UI component for these event message/notification. Using that you can control weather to show or hide these notifications.

**Comment by vishalnarkhede** [comment]
@codekiln `Connect Event` toggle only handles `user.start_watching` and `user.stop_watching` events. In next release we will add support for prop to customize UI component for these event notifications. Using that you can control weather to show or hide or customize as per your need.
