### ISSUE TITLE
Is automatic message translation supported?

### ISSUE THREAD

**Issue by wmadden** [GetStream/stream-chat-react#680]
Testing this myself I see that the message is being translated as promised by the Stream server, but the result is never displayed by the Stream React components.

<img width="692" alt="Screen Shot 2021-01-22 at 21 58 01" src="https://user-images.githubusercontent.com/12165/105546062-2c05f000-5cfd-11eb-9cdb-68a6eaffaf53.png">

I believe I've covered all the prerequisites mentioned in [the translation docs](https://getstream.io/chat/docs/translation/?language=js):
* the user receiving the message has `language="en"`
* the user sending the message has `language="de"`
* `auto_translation_enabled` is set to `true` on the app level _and_ the channel level
* the channel `auto_translation_language` is set to "en", just to be sure

I had a quick look at the implementation in `stream-chat-react` and it looks like message translation is ignored.

The `<MessageText>` component gets the message display text from `message.text`, ignoring `message.i18n`:
https://github.com/GetStream/stream-chat-react/blob/382cd6ac05ac7369af030196320b285f6fb14309/src/components/Message/MessageText.js#L49

And there are no references to `message.i18n` in the repository.

It's possible that the transformation happens somewhere else and I'm just missing it.

gz#8822

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8822'>Zendesk ticket #8822</a>:<br><br>Hi,

Thanks for getting in touch. We will look into this for you and get back to you as soon as possible.

--Ryan

**Comment by yetieaterxb1** [comment]
Hi there,

We have put in a fix for this. Text will now render in the language set on the receiving user, if one is set and it matches what is in the i18n object. A new release will be out this week including this change. 

https://github.com/GetStream/stream-chat-react/pull/683
