### ISSUE TITLE
Attach card to message component

### ISSUE THREAD

**Issue by EasonWang01** [GetStream/stream-chat-react#681]
![tes](https://user-images.githubusercontent.com/11001914/105709770-20ab0280-5f51-11eb-992b-8a4b45fab965.png)
Hi, is it possible to attach a card component every time when a user clicks on a channel, just like the picture above?

I have considered using sendMessage, but it will result in a duplicate card showing in the chat list, as I want the card to always show at the bottom.
gz#8866

**Comment by DanC5** [comment]
Hello, I'm not sure I follow the issue 100% but let's see if we can clarify. So are you saying, every time a user navigates to a channel you would like to display a React component at the bottom of the message list similar to your attached image?

If so, I can think of two ways you might be able to make this happen...
- insert a custom component between your list and input and pull the sendMessage method off the ChannelContext
<Channel>
  <MessageList />
  <CustomCardComponent />
  <MessageInput />
</Channel>

- use our MML library to render custom components within the message list, https://getstream.io/chat/docs/mml_overview/?language=js
