### ISSUE TITLE
Unable to trigger client event "user.updated"

### ISSUE THREAD

**Issue by SSTPIERRE2** [GetStream/stream-chat-react#684]
Hello,

I'm trying to listen to some client events including `user.updated` but I can't get it to trigger. 
```
const CLIENT_EVENT_TYPES = ['user.updated', 'user.presence.changed', 'notification.added_to_channel'];
CLIENT_EVENT_TYPES.forEach((eventType) => {
        this._client.on(eventType, this._handleClientEvent);
});
```
Here `_client` is an instance of StreamChat and `_handleClientEvent` is a function with a switch case for the event's `type`. The use case is when a user updates their profile image in our application, we update their user in GetStream, ideally all users connected to chat receive the `user.updated` client event and see that user's new photo. 

I've tried updating the GetStream user on the server side with `partialUpdateUsers` and `upsertUsers` as well as client side with `client.setUser` but to no avail - the chat module doesn't receive any client event at that time, while the "notification.added_to_channel" client event triggers as expected.

Am I approaching this correctly or is this not an intended use case?

Versions
"stream-chat": "2.8.4",
"stream-chat-react": "3.2.4"

gz#8929

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/8929'>Zendesk ticket #8929</a>:<br><br>Hi there,

This is not immediately obvious in the documentation, however, To first subscribe to user status events, you must call either queryUsers() or queryChannels() with `presence: true` in the options argument. Here is an example of that:


     const queryUsersResponse = await client.queryUsers(   { id: { $in: [userID] } }, {}, { presence: true } ); const update = await client.updateUser({   id: "userID",   customField: "this should be updated", }); client.on("user.updated", (event) => console.log(client.user, 'updated!'));

**Comment by SSTPIERRE2** [comment]
@shodgetts Thanks for the quick response, I'll try that. One thing I forgot to mention is we are have teams enabled with the multi-tenant option enabled - might that be a factor here as well?

**Comment by SSTPIERRE2** [comment]
@shodgetts Good news, your suggestion worked for me! We make a global channel that all users are added to, so I queried that channel right after initializing it with `presence: true` and bam, we're good to go, thanks a bunch 🎉

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/8929'>Zendesk ticket #8929</a>:<br><br>Awesome, glad to hear it! No worries, happy to help!
