### ISSUE TITLE
Messages are not sent if user paste text that includes an image.

### ISSUE THREAD

**Issue by Matti93GL** [GetStream/stream-chat-react#686]
**Describe the bug**
When we paste a text with an image, the images don't load and the text it's not visible

**Dev environment info**

Package version 
`"stream-chat-react": "^3.5.0",`
`"react": "^16.13.1",`

**Aditional**
This bug happend on the demo too

**To Reproduce**

Enter to the chat
Enter to https://en.wikipedia.org/wiki/John_Neal_(writer)#:~:text=John%20Neal%20and%20his%20twin,Neal%20and%20Rachel%20Hall%20Neal.
Copy text and image
Paste on the chat

**Expected behavior**
the message looks correct with the image

**Screenshots**
![done](https://user-images.githubusercontent.com/62907714/106191841-22abd600-618a-11eb-969e-14bcf92fa423.gif)

gz#8969

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8969'>Zendesk ticket #8969</a>:<br><br>Hi,

Thank you for bringing this to our attention. We will look into this as soon as possible. Could you please provide your App ID when you have a moment?

Best,
Ryan

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8969'>Zendesk ticket #8969</a>:<br><br>To solve this you will need to attach the image and the text separately.
