### ISSUE TITLE
ChannelHeader doesn't allow to have avatar if image doesn't exist in channel

### ISSUE THREAD

**Issue by IvanRodriCalleja** [GetStream/stream-chat-react#696]
Hi,

I am trying to configure this component to show the avatar of the other person in each of the chat. In my case i have an Agent chat that messages to a Client and i want to configure in the Agent chat to have the client image and client name and for the client the same but with the agent data. For that reason i don't want to add the `image` property to `chatClient.channel('commerce', chatId)`. As i see if i don't set the image to chat the **ChannelHeader** doesn't render the **Avatar** even if is custom or not. https://github.com/GetStream/stream-chat-react/blob/83fdd0603aa9af094a596e8e8ecb8472f7c4ad99/src/components/ChannelHeader/ChannelHeader.js#L27-L33

This "if" avoids to render any **Avatar** (custom or default) but the default **Avatar** component set the name initials if not image is provided https://github.com/GetStream/stream-chat-react/blob/83fdd0603aa9af094a596e8e8ecb8472f7c4ad99/src/components/Avatar/Avatar.js#L63-L68 This makes me think that maybe the condition in **ChannelHeader** is contradictory and maybe should not be checked.

A possible fix to me is add a random image or text as image in the chat but this is something i won't use , other possible fiss is to create my own  **ChannelHeader**. Maybe i am little bit lost on how to sow the avatar and the name to each contact (Like WhatsApp).

Could you tell me if i am doing in the right way and if i am right, is it a bug?

Thanks!!

**Comment by DanC5** [comment]
@IvanRodriCalleja I see what you are saying here, Ivan. The ChannelHeader component is meant to be more of a UI example than something that is highly flexible and customizable, but I'll add an image prop to it so you can pass your own image to the component. However, I'd still recommend building your own header, as that's definitely the most common use case among our clients since headers are pretty UI specific and don't contain much functionality.

**Comment by IvanRodriCalleja** [comment]
Sorry i closed wrongly.

Thanks for the answer

**Comment by DanC5** [comment]
@IvanRodriCalleja just merged this PR which adds `image` as a prop to the ChannelHeader. So feel free to either take advantage of this new prop or create your own header. We'll be making a release tomorrow, thanks!

https://github.com/GetStream/stream-chat-react/pull/697

**Comment by IvanRodriCalleja** [comment]
Amazing!!
