### ISSUE TITLE
 ChannelList component onAddedToChannel will not fire after a channel re-created after deletion. 

### ISSUE THREAD

**Issue by yangyu0311ugroop** [GetStream/stream-chat-react#709]
Hi All, 

I cannot receive any callback on `onAddedToChannel` if a channel is created after its deletion. 

These are the step to reproduce. 

1. CreateChannel first time
2. OnAddedToChannel gets called 
3. Delete the Channel 
4. Create the Channel with the same CID
5. OnAddedChannel didn't get called at all. 

gz#9434

**Comment by DanC5** [comment]
Can you set up an event listener and report back which events fire for each step in the process? I have a feeling `'notification.added_to_channel'` is not getting called on the second creation, therefore the `onAddedToChannel` custom handler is not being executed.

`client.on('all', (event) => console.log(event))`

**Comment by yangyu0311ugroop** [comment]
hi Dan, you are right. I follow what you said, after the second creation, I do not receive any event.

So this is not react component issue, but the stream-chat issue. 

I am using stream-chat 2.8.4, stream-chat-react 3.4.0
