### ISSUE TITLE
Error when clicking on image attachment

### ISSUE THREAD

**Issue by SSTPIERRE2** [GetStream/stream-chat-react#711]
Hello,

I'm testing the file upload feature and running into an issue with images in particular. I can upload files as described in the docs and I can click on/download text files or pdfs, but with images I get an error when clicking on them after upload
![image](https://user-images.githubusercontent.com/19779234/108124879-af550000-7075-11eb-855e-c8fb375f3ff4.png)
(code is bundled so I can't tell exactly what line is causing this). 

When inspecting an image attachment's data I can see it's been uploaded and is accessible at a [GetStream url](https://stream-chat-us-east-c7.imgix.net/99940/images/e6590685-f7d1-49d6-9b44-63b7db58dcf5.alexa2.jpg?ro=0&s=e90c9b34495a275f5a17b979489d7f62). Is there a special or recommended way to handle image attachments, or what else might be going on here?

Here's a snippet of our GetStream UI:
```
const GetStreamConversationView = withChatContext(({ currentConversationId, setActiveChannel }) => {
    const _chatContext = useContext(ChatContext);
    const _client = _chatContext.chatManager._client;
    const channel = _client._channels[currentConversationId];

    useEffect(() => {
        setActiveChannel(channel);
    }, [channel]);

    return (
      <Client client={_client}
          <Channel>
              <Window>
                  <MessageList />
                  <MessageInput Input={MessageInputFlat} />
              </Window>
              <Thread Message={MessageSimple} />
          </Channel>
       </Client>
    );
});
```
 
Versions
"stream-chat": "2.8.4",
"stream-chat-react": "3.2.4"

gz#9460

**Comment by SeniYG** [comment]
Hi,

Thanks for reaching out. 
This `"stream-chat-react": "3.2.4"` version only supports "stream-chat" up to 2.7.x versions. 
You are actually using version 2.8.4 of this stream-chat library. 
Could you try upgrading to more recent versions and give it another try?

Best,

**Comment by SSTPIERRE2** [comment]
Hey @SeniYG thanks for the response. I'm trying that upgrade today but running into an error `ICAL is not defined`
![image](https://user-images.githubusercontent.com/19779234/108226334-cf82ce80-710a-11eb-9476-fe2b3d04fd0b.png)
I don't use ICAL, might this be related to my build config? I also use rollup
![image](https://user-images.githubusercontent.com/19779234/108226731-28526700-710b-11eb-8ce9-c3c8e72606e6.png)

**Comment by SSTPIERRE2** [comment]
@SeniYG upon further investigation I found this error starts happening with version [3.4.0](https://github.com/GetStream/stream-chat-react/releases/tag/v3.4.0) might that help point towards the issue?

**Comment by DanC5** [comment]
@SSTPIERRE2 you need to make some rollup adjusts on your side for ical, try adding this to your rollup config...

`prepend('window.ICAL=window.ICAL||{};')`

Let me know if that fixes it, thanks!

**Comment by SSTPIERRE2** [comment]
@DanC5 That fixed it, woohoo, thanks! 🚀

**Comment by DanC5** [comment]
Great news! Yeah it's a little funky having multiple rollup configs but glad it's all working now. Closing the issue, let us know if you need anything further, thanks!
