### ISSUE TITLE
Allow override of "Enter" key behavior

### ISSUE THREAD

**Issue by gambitasto** [GetStream/stream-chat-react#712]
Our end users do not like the current behavior that pressing "Enter" submits the message (when not holding down Shift), they would prefer to use the send button instead so that they don't accidentally send an incomplete message. In this case pressing "Enter" would just create a new line.

"Enter should submit, but not if you're pressing shift"

Could this be made configurable so that I could override it via, for example "MessageInputProps"?

gz#9466

**Comment by SeniYG** [comment]
Hi,

Thanks for reaching out.
Unfortunately, the current MessageInput component does not support this as it doesn't yet have the necessary props to override this behavior. It requires some work from our React team to add it. They'll push this feature soon in a future version.
Sorry for the inconvenience.

**Comment by wildebeast** [comment]
@SeniYG @mahboubii any updates on this feature?
