### ISSUE TITLE
Message reaction not working 

### ISSUE THREAD

**Issue by nandakishorebhandari** [GetStream/stream-chat-react#715]
Nothing happens after clicking on emoji.

Version: 4.0.1

![Screenshot 2021-02-18 at 11 40 37 PM](https://user-images.githubusercontent.com/34581284/108401939-e75d6e00-7242-11eb-8815-d81c9bb4ef3f.png)

gz#9506

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/9506'>Zendesk ticket #9506</a>:<br><br>Hi there,

Are you receiving any Stream related errors? Could you please send over a code snippet of your implementation?

**Comment by DanC5** [comment]
@nandakishorebhandari can you share the code you're using the build the app? If you're using our virtualized list component you won't be able to add reactions. Also we've seen this issue in the past when messages or a channel have been deleted, so our api won't react on old data. But please try using a non-virtualized MessageList component and ensure the channel is active

**Comment by nandakishorebhandari** [comment]
`        <Chat client={chatClient} theme="messaging light">
          <Channel channel={channel} LoadingIndicator={Loader}>
            <Window>
              <MessageList />
              <MessageInput />
            </Window>
            <Thread />
          </Channel>
        </Chat>`

**Comment by nandakishorebhandari** [comment]
Could you refer me to docs for using non-virtualized MessageList

**Comment by nandakishorebhandari** [comment]
After using a non-virtualized MessageList, I see no options to add a reaction.

![Screenshot 2021-02-19 at 12 49 56 AM](https://user-images.githubusercontent.com/34581284/108409791-a5d1c080-724c-11eb-98a9-249f978df16c.png)

**Comment by nandakishorebhandari** [comment]
This issue happens in a new active channel

**Comment by nandakishorebhandari** [comment]
Any update?

**Comment by DanC5** [comment]
@nandakishorebhandari Petyo is working on this right now and we'll include in our next release, likely later this week.

**Comment by DanC5** [comment]
@nandakishorebhandari Merged this issue in, will release later this week 👍🏻
