### ISSUE TITLE
Message linkifying incorrectly parses URLs inside Markdown syntax

### ISSUE THREAD

**Issue by kainosnoema** [GetStream/stream-chat-react#718]
Two cases I've found so far that are being incorrectly parsed. We're running into these several times a day just during our own personal usage:

### 1. URLs inside code blocks:

Message text:
```markdown
This is a url inside a code fence: `google.com`
```

Actual rendered HTML:
```html
<p>This is a url inside a code fence: <code>[google.com](http://google.com)</code></p>
```

Expected HTML:
```html
<p>This is a url inside a code fence: <code>google.com</code></p>
```

Which is obviously incorrect.... text inside code fences should not be changed.

### 2. Markdown link labels containing URLs

Message text:
```markdown
This is a url inside a Markdown link label: [google.com](https://google.com)
```

Actual rendered HTML:
```html
<p>This is a url inside a Markdown link label: [<a href="http://google.com" target="_blank" rel="nofollow noreferrer noopener">google.com</a>](https://google.com/)</p>
```

Expected HTML:
```html
<p>This is a url inside a Markdown link label: <a href="https://google.com" target="_blank" rel="nofollow noreferrer noopener">google.com</a></p>
```

## Solution

It seems to me like this two issues are related. Essentially `linkifyjs` is parsing URLs that are inside Markdown syntax and shouldn't be linkified (or linkified again). It might be really tough to ensure that `linkifyjs` doesn't look inside Markdown tags, so maybe it's safe to assume that a message is either Markdown or not and only linkify if there's no Markdown syntax detected?

Haven't yet taken a stab at a fix, but the relevant code is over here: https://github.com/GetStream/stream-chat-react/blob/e1b74d9850c8ab0c6cde7f630334d9a9f2a9eae2/src/utils.js#L95-L109

gz#9516

**Comment by DanC5** [comment]
Hey @kainosnoema, we just added a regex check in the render text function to check whether a code block contains a URL, https://github.com/GetStream/stream-chat-react/pull/733. 

This has already been merged to master and will be release tomorrow morning US mountain time. Thanks for pointing out this issue and let us know if you have further questions.

**Comment by kainosnoema** [comment]
@DanC5 thanks, will check it out when it's released.

FWIW, it doesn't look like you've addressed the issue with URLs inside other markdown syntax that I mentioned, such as link labels (# 2 in the issue above)—this is the one that's biting us most consistently actually. I do wonder if it makes sense to skip linkifying *entirely* when markdown syntax is present? Unless there's some more consistent and complete way to detect markdown...

**Comment by DanC5** [comment]
<img width="369" alt="Screen Shot 2021-02-25 at 7 11 37 AM" src="https://user-images.githubusercontent.com/43552931/109165376-b72d3800-7738-11eb-891f-0027aca66b1e.png">

@kainosnoema link labels are now rendering like this on our end, let us know if you see something different after we release shortly and tag @yetieaterxb1 on your response, thanks!

**Comment by kainosnoema** [comment]
@DanC5 your screenshot demonstrates the issue perfectly—that's being rendered incorrectly. When a link is present in the label, the Markdown is being wrapped in an additional link (notice the square brackets, parenthesis, and URL tacked on the end), preventing `ReactMarkdown` from parsing and displaying the original outer link. Your example should actually look like this:

link label: [google.com](https://google.com)

Of course Github renders it correctly. I know this is a little confusing because there are two levels of Markdown happening here, but that's exactly the problem.... the linkify package is not aware of the markdown syntax and applying an additional link even if it's already linked.

**Comment by DanC5** [comment]
Oh I see what you're saying, I thought you meant the actual message text was unfurling the entire `a` tag in the message list. @yetieaterxb1 please take a look at this, thanks.

**Comment by yetieaterxb1** [comment]
Hey @kainosnoema the update should have actually fixed the way those links render. Let me take another look today and see whats happening

**Comment by DanC5** [comment]
@kainosnoema I believe this new release should fix the link markdown issue. I'll keep open for a few days while you have a chance to test, https://github.com/GetStream/stream-chat-react/releases/tag/v4.1.1

https://github.com/GetStream/stream-chat-react/pull/742/commits/f9b18d5eb62f2dabc5df8cd569f4263e0cd909dc

**Comment by yetieaterxb1** [comment]
@kainosnoema I see the issue you are having and I just submitted a PR for review. The new fix will also ignore the label of the markdown link. This should give you the result you are looking for. 

https://github.com/GetStream/stream-chat-react/pull/776
