### ISSUE TITLE
Can't sent Image file

### ISSUE THREAD

**Issue by coolman-dev425** [GetStream/stream-chat-react#735]
I can send all files except image files. I tried to fix this issue on my side but didn't fixed yet.
what's the reason? help me~~

gz#9708

**Comment by SeniYG** [comment]
Hi,

Thanks for reaching out.
Can you describe the behavior when attempting to upload an image? Do you have any error messages?
Are you able to share any code snippet/sample around the MessageInput component (if you're using it ofc)?

Thanks.

**Comment by DanC5** [comment]
@coolman-dev425 also let us know what type of image file you're trying to send, and like Seni said, please share the code you're using, thanks

**Comment by coolman-dev425** [comment]
props.isRecordingUrl === 'N' && <div className="col-md-3">
                        <div className="video-sidebar">
                            <div className="video-sidebar-tab">

                                <ul className="nav nav-tabs" role="tablist">
                                    <li role="presentation" className={activeTab === 1 ? "active" : ''}><a href="javascript:void(0)" onClick={() => setActiveTab(1)} aria-controls="people-id" role="tab" data-toggle="tab"><i className="fa fa-users margin-right-8"></i>People</a></li>
                                    <li role="presentation" className={activeTab === 2 ? "active" : ''}><a href="javascript:void(0" onClick={() => setActiveTab(2)} aria-controls="chat-id" role="tab" data-toggle="tab"><i className="fa fa-comments margin-right-8"></i>Chat</a></li>
                                </ul>

                                <div className="tab-content">
                                    <div role="tabpanel" className={`tab-pane ${activeTab === 1 ? 'active' : ''}`} id="people-id">
                                        {
                                            props._participants && props._participants.map((val) => {

                                                if (val.name === undefined) {
                                                    return false;
                                                }

                                                let trackAudioStatus = audioVideoStatus('audio', val.id);
                                                let trackVideoStatus = audioVideoStatus('video', val.id);

                                                let name = val.name.split('_');

                                                // name.filter(a => a).length > 3 ? `${interfaceConfig.DEFAULT_IMAGE_URL}${name[3]}` :
                                                return (<>
                                                    <div className="people-list-box ">
                                                        <div className="col-md-8">
                                                            <div className="row">
                                                                {/* <span className="col-md-4 people-img">
                                                                                            <img src={`../../images/main/images/user.png`} alt="logo" className="img-responsive" />
                                                                                        </span> */}
                                                                <span className="col-md-8 people-name">
                                                                    <h3>{name[0] ? name[0] : 'Guest'}</h3>
                                                                    {/* <p>{name[0]}</p> */}
                                                                </span>
                                                            </div>
                                                        </div>
                                                        <div className="col-md-4 text-right">
                                                            {val.local ?
                                                                <>
                                                                    <a className="cir_plus" href="javascript:void(0)" onClick={() => _setAudioMuted(!trackAudioStatus, 'audio')}  >
                                                                        <i className={`fas fa-microphone${trackAudioStatus ? '-slash' : ''} mr-5`}></i>
                                                                    </a>
                                                                    <a className="cir_plus" href="javascript:void(0)" onClick={() => _setAudioMuted(!trackAudioStatus, 'audio')} >
                                                                        <i className={`fas fa-video${trackVideoStatus ? '-slash' : ''}`}></i>
                                                                    </a>
                                                                </> : isAdmin === 'N' ?
                                                                    <>
                                                                        <a className="cir_plus" href="#"  >
                                                                            <i className={`fas fa-microphone${trackAudioStatus ? '-slash' : ''} mr-5`}></i>
                                                                        </a>
                                                                        <a className="cir_plus" href="#"  >
                                                                            <i className={`fas fa-video${trackVideoStatus ? '-slash' : ''}`}></i>
                                                                        </a>
                                                                    </> : <>
                                                                        <a className="cir_plus" href="javascript:void(0)" onClick={() => _setRemoteAudioVideoMuted(trackAudioStatus, name[1], 'audio')}  >
                                                                            <i className={`fas fa-microphone${trackAudioStatus ? '-slash' : ''} mr-5`}></i>
                                                                        </a>
                                                                        <a className="cir_plus" href="javascript:void(0)" onClick={() => _setRemoteAudioVideoMuted(trackVideoStatus, name[1], 'video')} >
                                                                            <i className={`fas fa-video${trackVideoStatus ? '-slash' : ''}`}></i>
                                                                        </a>
                                                                    </>
                                                            }
                                                        </div>
                                                    </div>
                                                    <div className="clearfix"></div>
                                                </>
                                                )
                                            })
                                        }
                                    </div>
                                    <div role="tabpanel" className={`tab-pane ${activeTab === 2 ? 'active' : ''}`} id="chat-id">
                                        {/* {props.chat} */}
                                    <Chat client={chatClient}>
                                        <Channel channel={channel}>
                                        {/* <div className="str-chat__main-panel" style={{ height: '825px'}}> */}
                                            <Window>
                                            {/* <ChannelHeader /> */}
                                                <MessageList />
                                                <MessageInput />
                                            </Window>
                                        {/* </div> */}
                                        {/* <Thread /> */}
                                        </Channel>
                                    </Chat>
                                    </div>
                                </div>
                            </div>
                        </div>



Here is my source code.

**Comment by coolman-dev425** [comment]
![image](https://user-images.githubusercontent.com/78760448/109270163-7ed23c00-77c2-11eb-829a-72cdbd7d61bb.png)

**Comment by coolman-dev425** [comment]
![image](https://user-images.githubusercontent.com/78760448/109270218-901b4880-77c2-11eb-8fb7-3708934bbf3d.png)

**Comment by coolman-dev425** [comment]
![image](https://user-images.githubusercontent.com/78760448/109270286-a88b6300-77c2-11eb-9408-d522ba9ff478.png)

**Comment by DanC5** [comment]
@coolman-dev425 this is not a Stream error, as you'd be getting a specific error response code for a failed upload. So something unrelated to sending the image is causing the error. Are you trying to create a React Portal? Did you add the Portal's div and id to you index.html?
