### ISSUE TITLE
GetOrCreateChannel fails unexpectedly with new GetStream application

### ISSUE THREAD

**Issue by SSTPIERRE2** [GetStream/stream-chat-react#739]
Hello,

I'm trying to deploy my Chat application with a new production GetStream application I just created. As a user trying to watch my first channel I get this permissions error
![image](https://user-images.githubusercontent.com/19779234/109232914-03a76080-7797-11eb-9b00-a6535ebeea8e.png)

I've been developing this chat app using a separate development GetStream application for a while and it works great, but here's the snippet of where it fails using the new production application:

* Client constructor and setup function
```
this._client = StreamChat.getInstance(options.apiKey);
...
await this._client.connectUser({ id: userId }, token);
this._globalChannel = await this._setupGlobalChannel();
```
* _setupGlobalChannel()
```
async _setupGlobalChannel() {
        const { userId, teamNamespace } = this.options;
        const channel = this._client.channel('messaging', `GLOBAL__${teamNamespace}`, {
            name: 'global',
            team: teamNamespace,
        });
        // Error occurs at channel.watch
        await channel.watch({ presence: true });
        await channel.addMembers([userId]);
        await this._client.queryChannels({ type: 'messaging', id: { $in: [`GLOBAL__${teamNamespace}`] } }, [], {
            presence: true,
        });

        return channel;
}
```

I can confirm the user is in the same team as the channel. Why might I be running into this error? Any help is appreciated, thanks!

gz#9729

**Comment by shodgetts** [comment]
Hello, you're running into a permissions error, most likely because you're trying to watch a channel for which this user is not a member of. Our default permissions do not grant read permissions to a messaging type channel without membership. Try a Livestream type channel instead, which allows open read/write permissions to any users! 
-Big Steve
