### ISSUE TITLE
4.1.0 - ReactionList not updating in MessageTeam

### ISSUE THREAD

**Issue by Fnopster** [GetStream/stream-chat-react#740]
Hi,

I'm using stream-chat-react 4.1.0, and the reaction list in MessageTeam does not update when I click on the reaction actions.

To repo:
1. click on the reaction icon in the message actions menu
2. click on any emoji on the pop-up menu
3. the reaction counter on the popup does not update and the emoji list does not update until the page is refreshed

In my debug console, I can see the channel is receiving `reaction.new` and `reaction.delete` events.  Is this a known issue in the latest build? Or is my customization messing something up?

Our chat component setup:
```
      <Chat client={streamchat} theme={'team dark'}>
        <Channel channel={selectedChannel}>
          <Window hideOnThread={false}>
            <MessageList
              DateSeparator={DateSeparator}
              Message={MessageTeam}
            />
            <MessageInput />
          </Window>
        </Channel>
      </Chat>
```

gz#9734

**Comment by DanC5** [comment]
@Fnopster thanks for raising the issue. I think we've pinpointed a caching issue coming from the backend. I'll update you as soon as it's handled.

**Comment by DanC5** [comment]
@Fnopster new releases to fix this issue, thanks!

https://github.com/GetStream/stream-chat-react/releases/tag/v4.1.1
https://github.com/GetStream/stream-chat-js/releases/tag/v3.1.2

**Comment by Fnopster** [comment]
Thanks Dan!

**Comment by Fnopster** [comment]
Hi Dan, I've updated to 4.1.1 but the reaction list is still not updating for me. Could we reopen this issue? Do you guys need code to repo this problem?

**Comment by Fnopster** [comment]
Oh my bad, I didn't update the stream-chat-js package. Thanks again!
