### ISSUE TITLE
Export helper render functions such as getLatestMessagePreview

### ISSUE THREAD

**Issue by tobiasbueschel** [GetStream/stream-chat-react#746]
Hey 👋

it would be great if utility functions such as `getLatestMessagePreview`, `getDisplayTitle`, etc. could be exported within the bundle. For my use case I'm leveraging the `ChannelList` and `ChannelPreview` components, but in some situations I don't want to render the components, and instead a custom ChannelList for displaying my channel search results.

For this it would be nice to be able to re-use the utility functions above instead of having to re-implement it.

https://github.com/GetStream/stream-chat-react/blob/85c75524cafdcdf3b64f04995b608de88ac6d23c/src/components/ChannelPreview/utils.js#L1-L22

gz#9850

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/9850'>Zendesk ticket #9850</a>:<br><br>Hi there,

Thanks for the feedback. I can definitely share this with the rest of the team to see if this is something we can facilitate in the future.

**Comment by DanC5** [comment]
Hey @tobiasbueschel, we just added these helper functions to our exports, https://github.com/GetStream/stream-chat-react/pull/750.

We'll likely make a new release end of next week, thanks!

**Comment by tobiasbueschel** [comment]
Thanks a lot @DanC5 that's very helpful! Happy Monday
