### ISSUE TITLE
Incorrect prop type for MessageInputLarge.numberOfUploads

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#75]
I noticed that the recently added [prop types for MessageInputLarge specify that `numberOfUploads` should be an object](https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageInputLarge.js#L78). 

Farther down in that file, `renderUploads` calls this prop as so: 

```jsx
<ImageDropzone
  accept={this.props.acceptedFiles}
  multiple={this.props.multipleUploads}
  disabled={
    this.props.numberOfUploads >= this.props.maxNumberOfFiles
      ? true
      : false
  }
  handleFiles={this.props.uploadNewFiles}
>
```

The [docs for `channel` still say `maxNumberOfFiles` should be a number](https://getstream.github.io/stream-chat-react/#channel), which sounds more correct.

**Comment by vishalnarkhede** [comment]
@codekiln Thanks for reporting this. We will fix it in next release :)

**Comment by codekiln** [comment]
@jaapbakker88 it looks like this is not fixed in master: https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageInputLarge.js#L40

**Comment by jaapbakker88** [comment]
@codekiln I'll have a look at it.
