### ISSUE TITLE
Prop Type warnings on Channel and MessageList components

### ISSUE THREAD

**Issue by bshimrit** [GetStream/stream-chat-react#757]
Hi, 

I am on version 4.0.1. I am getting a lot of prop type warnings though I didn't set any values to these props so they should resolve to default values.

On Channel component, for example:
```Failed prop type: Channel: prop type `LoadingErrorIndicator` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.```

I assume this is due to the fact that the propTypes on Channel component is set on Channel.propTypes but the default props values are set on ChannelInner.

On MessageList component,  for example: 
```Warning: Failed prop type: MessageList: prop type `dateSeparator` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.```

this is due to the prop variable being dateSeparator and the default prop is DateSeparator. 

Please your assistance to avoid these warning.

Thanks.

Shimrit.

gz#9967

**Comment by DanC5** [comment]
Hello @bshimrit, we are aware of some of the type mismatches in the current release and are actually in the process of converting the whole library to TypeScript. Look for a major release with full TypeScript support within the next 2-3 weeks. This should handle any lingering type issues, thanks!
