### ISSUE TITLE
a11y support

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#76]
I work in the edtech space, where a11y support is a top priority. 

It would be a lot easier to sell `stream-chat-react` to my team's stakeholders if GetstreamIO publicly shared this priority. And as a component kit, `stream-chat-react` is uniquely positioned to be able to differentiate itself with a11y support.

1.) Will you consider adding a11y support as a product goal in GetstreamIO's marketing materials?

2.) Will you pursue [an a11y audit](https://www.deque.com/resources/what-to-expect-from-an-accessibility-audit/) and remediate a11y concerns?

**Comment by jaapbakker88** [comment]
Definitely something we want to look at but right now we're adding it to the backlog of features to add.
