### ISSUE TITLE
Should channel creation happen on backend or on client?

### ISSUE THREAD

**Issue by AdityaAnand1** [GetStream/stream-chat-react#765]
Should channel creation happen on backend or on client?

Any security concerns for doing it on client in production?

Backend isn't really doing anything different and in our use-case client has all the data needed to create channels. What's the best practice?

gz#10028

**Comment by shodgetts** [comment]
Hi @AdityaAnand1, as this is not really an issue with the React SDK, can we please move this conversation to our support system? This question is more of an architecture question rather than a technical issue with the SDK. Please email support@getstream.io with your app_id you're using :)
