### ISSUE TITLE
The name of members in channels can't be updated in channel widget

### ISSUE THREAD

**Issue by ahmeddahy** [GetStream/stream-chat-react#778]
Hello, I am using v1.0.1 and an unexpected behavior happened when update user name.
In my app when update the user name, It reflected in channel list but not on the channel widget.
This image describes this behavior. the same user with two different name.
Is there any way to fix that ?
![tempsnip](https://user-images.githubusercontent.com/19478517/111149363-78e7a380-8595-11eb-92ab-60afa6b70763.png)

gz#10199

**Comment by DanC5** [comment]
@ahmeddahy I see the issue here. The channel list looks for `client.user.id` and the message looks for `message.user.id`, so they don't map 1-to-1 to each other, will look into this...

**Comment by yetieaterxb1** [comment]
Hi @ahmeddahy,

You will need to pull dispatch from the channel context.

Next, you need to add a listener on the ‘user.updated’ event.

Await channel.watch() will re-query the list of messages which will have the updated user name on them.

You then need to call dispatch to update the messages in state.

Below is an example:
` const { channel, dispatch } = useChannelContext();

  const dispatchFunc = async (event) => {
      await channel.watch({ presence: true });
      return dispatch({ channel, type: 'copyStateFromChannelOnEvent' });
  };
  
  useEffect(() => {
    chatClient.on('user.updated', dispatchFunc);
    return () => chatClient.off('user.updated', dispatchFunc);
  }, []);`

**Comment by ahmeddahy** [comment]
@yetieaterxb1 
Thanks for your effort but I have some question
Where can I find this method?
useChannelContext();

**Comment by ahmeddahy** [comment]
@yetieaterxb1 
The values of channel and dispatch are always undefined 
This is my code 
![Capture](https://user-images.githubusercontent.com/19478517/112467023-31200380-8d6f-11eb-9d12-693f9915ee9d.PNG)

**Comment by yetieaterxb1** [comment]
@ahmeddahy sorry about that I was using the latest version of stream-chat-react. You wont have access to that context hook in older version so you will need to use `useContext(ChannelContext)` instead.

**Comment by ahmeddahy** [comment]
@yetieaterxb1 
l upgraded to the last version 
And still  channel and dispatch have undefined value

**Comment by yetieaterxb1** [comment]
@ahmeddahy I believe your issue may be because your component `<ChannelWindow/>` is not within `<Channel/>` so it does not have that context yet. `<ChannelWindow/>` needs to be a child of `<Channel/>`
