### ISSUE TITLE
Channel is duplicated after pressing on "load more" button and press at the channel

### ISSUE THREAD

**Issue by ahmeddahy** [GetStream/stream-chat-react#779]
Hello, I have some strange behavior happened when following these steps:
1- press at **load more** button.
2- press at any channel in the loaded channels.
Then the channel will be duplicated. 

Note: this behavior is not permanent , it is unexpected.
the version I used is 1.0.1
![Untitled](https://user-images.githubusercontent.com/19478517/111153006-11802280-859a-11eb-8109-6eb6e51149fd.png)

gz#10200

**Comment by shodgetts** [comment]
Hello 👋  Stephen here from the Customer Success team. For customers on our paid plans, you are welcome to email support@getstream.io. Can I please ask the app_id or organization name that you're using please.

**Comment by DanC5** [comment]
@ahmeddahy for both of these GH issues you've raised, it's going to be challenging to debug given the version mismatch from our current release. We're currently on v4.1.3. Are you able to upgrade and see if these issues are fixed? Developing on this old of a release is going to be challenging as much of our documentation will not be relevant and you'll be missing key features that have been adding in the last few major versions.

**Comment by ahmeddahy** [comment]
@DanC5 
I upgraded the version to 4.1.3 and still I have the same two issues.
Can you help to solve them ?

**Comment by ahmeddahy** [comment]
@shodgetts 
App_Id:  **75cqufzm7uhu**
Organization: **OpenWater DEV**

**Comment by DanC5** [comment]
@ahmeddahy can you confirm you're also on the latest version of `stream-chat`?

**Comment by ahmeddahy** [comment]
@DanC5 
currently, I am using the latest version of these two packages:
stream-chat: 3.6.0
stream-chat-react: 4.1.3
And still this odd behavior happens

**Comment by DanC5** [comment]
@ahmeddahy can you share the app code you're using? This isn't an issue we've ever received before, so hopefully it's just a quick fix with your setup

**Comment by ahmeddahy** [comment]
@DanC5 
This is my app code: 75cqufzm7uhu

**Comment by ahmeddahy** [comment]
@DanC5 
you can see the behavior in this video from [here](https://user-images.githubusercontent.com/72095565/111155421-8589de80-8538-11eb-88b7-35671538c400.mp4)

**Comment by DanC5** [comment]
@ahmeddahy Sorry I mean an actual copy/paste of the code you're using to initiate the chat app. A screenshot(s) would be fine, as I just want to see what components you're using and what actions are firing.

**Comment by ahmeddahy** [comment]
You can check these screenshots 
![Capture](https://user-images.githubusercontent.com/19478517/111453712-8d09dd00-871c-11eb-896f-1b815d780b27.PNG)
![Capture](https://user-images.githubusercontent.com/19478517/111453875-b591d700-871c-11eb-9b9e-45fff69e1e04.PNG)

**Comment by ahmeddahy** [comment]
@DanC5 
Hello,
Are there any new updates for this issue?

**Comment by shodgetts** [comment]
Agent comment from Dan Carbonell in <a href='https://getstream.zendesk.com/agent/tickets/10200'>Zendesk ticket #10200</a>:<br><br>Sorry for the delay here, we're about to make a significant release that converts the entire library to TypeScript, likely tomorrow, so we were a bit wrapped up in other items last week. This is still very much on my radar though, and I plan to look into your issue tomorrow or Tuesday.

**Comment by shodgetts** [comment]
Agent comment from Anna Baldwin in <a href='https://getstream.zendesk.com/agent/tickets/10200'>Zendesk ticket #10200</a>:<br><br>Hi, thanks for the screenshots. Can you also send a screenshot of the exact code where you are initiating the chat app? It should be the same file as the code you've already sent.
Thanks!

**Comment by ahmeddahy** [comment]
@shodgetts 
This is the main file to initiate my app.

![Capture](https://user-images.githubusercontent.com/19478517/112163848-1413f500-8bf6-11eb-8a97-69828fd5fb02.PNG)

It uses the component which I refers at past screenshots.

**Comment by ambaldwin** [comment]
@ahmeddahy great, what actually would be helpful is the code where you're initializing the chatClient (`StreamChat.getInstance()` or new `StreamChat()`). Can you screenshot that whole file including that code? Thanks!

**Comment by ahmeddahy** [comment]
@ambaldwin 
Okay 
I think you mean this 
![IMG_20210323_212241](https://user-images.githubusercontent.com/19478517/112206027-2144da00-8c1e-11eb-9709-d0cb15677906.jpg)

**Comment by ambaldwin** [comment]
Great, thanks! Where are you calling getChatClient()? I suspect it's in the file with the main Chat Components. Can you send a screenshot of the entire file please? Thanks.

**Comment by ahmeddahy** [comment]
@ambaldwin 
I am so sorry for the last comment, It is wrong file

This is the chat client initialization in the same file that I refered in this comment https://github.com/GetStream/stream-chat-react/issues/779#issuecomment-800973058
![IMG_20210323_230010](https://user-images.githubusercontent.com/19478517/112217727-894ded00-8c2b-11eb-8892-198b629ce72e.jpg)

**Comment by ambaldwin** [comment]
Can you send me that entire file, please? Thanks!

**Comment by ahmeddahy** [comment]
@ambaldwin 
This is the entire file 
[Layout.txt](https://github.com/GetStream/stream-chat-react/files/6196132/Layout.txt)

**Comment by ambaldwin** [comment]
Hi, @ahmeddahy, Thanks for the Layout file.
From the screen recording video you sent, it looks like the issue with the channels is actually upon message creation? 

If you could send the file(s) with the code where you're handling new message creation, that should help. Thanks.

**Comment by ahmeddahy** [comment]
@ambaldwin 
You can check this file
[chat-widget.txt](https://github.com/GetStream/stream-chat-react/files/6204544/chat-widget.txt)

**Comment by ambaldwin** [comment]
Hi @ahmeddahy it's not immediately clear to me what the issue might be.

Can you send a new screen recording video with you going through the issue slowly? The first video is a little fast and the duplicate channel names makes it confusing so I'm not totally clear on what you're showing me.

One more thing, can you please confirm again that the issue is actually the channel duplicating after there's a new message (this is what I think I'm seeing in the video) and NOT actually channel duplication when pressing 'load more' (which is what you wrote in the first message)? Thanks.

**Comment by ahmeddahy** [comment]
@ambaldwin 
I named all the channels with numbers from 1 to 199 (unique) then record the attached video.

https://user-images.githubusercontent.com/19478517/112857863-95b1ca00-90b1-11eb-90cd-0359fe7c681e.mp4

you can check these steps to reproduce:
1-press at load more button (more than 3 times).
2-choose some channel from the channel list. (the channel may be duplicated after this step or after the next step)
3-send message in the channel which I chose then the channel would be duplicated.

this behavior is not permanent. sometimes happen and sometimes not.

thanks.

**Comment by ambaldwin** [comment]
Hi @ahmeddahy thanks for the video with the channels with unique ids.

My instinct is that you're manually duplicating functionality that actually comes out of the box with our library. My suggestion would be for you to start searching for places where you're manually adding channels to the channel list (both when clicking load more and when adding a new message), maybe try commenting out event listeners to see if that helps detect where unnecessary manual work is located.
