### ISSUE TITLE
messagelist-scroll-fix bug

### ISSUE THREAD

**Issue by abf6ug** [GetStream/stream-chat-react#78]
There was a recent fix that dealt with fixing scrolling when there are images loading in the chat.  This works part of the time, but if you have a slow connection or there are many images, it still improperly loads the chat in the MessageList/ReverseInfiniteScrollList.

Possible solutions I can think of:
- Use a placeholder for these slow images, then onload, replace placeholder with real image
- Using onload, adjust scrollTop as the images load
- Something more complicated and fancy?

**Comment by jaapbakker88** [comment]
#99

**Comment by jaapbakker88** [comment]
This issue was fixed in a recent release, closing this ticket.
