### ISSUE TITLE
ChannelList does not update when new conversation is made

### ISSUE THREAD

**Issue by bimusiek** [GetStream/stream-chat-react#79]
Hey,
I am trying to make channel list be updated when new conversation is created.

Our use case:
1. User signs up, we create new channel for him
2. Our agents have chat support UI opened
3. New channel does not pop up on top
4. When refreshing page, it is there and then it pops up when there is new message

Channel has 1 member only (user that signed up).
Agents have admin permissions.

I guess because of this it does not trigger any event for admin user when channel is created as he is not added as member to the channel.

Is there a way to get event saying there is new conversation in case of admin user?

**Comment by jaapbakker88** [comment]
@bimusiek We don't support this right now. Why don't you add the admin as a member to the channel? This would give you to get the appropriate events.

**Comment by bimusiek** [comment]
@jaapbakker88 Ya, thats what we did at the end. 👍
