### ISSUE TITLE
Image modal backdrop z index is less than message input z index 

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#80]
When clicking on an image preview in 0.7.9, the image modal backdrop is behind the message input, which does not seem correct: 

![shows picture of black hole in a modal with the message input area popping out against the dark background](https://user-images.githubusercontent.com/140930/68037273-bfd54180-fc9d-11e9-9721-2bafa917a05f.png)

This happens because [`MessageInputLarge` has a hardcoded zIndex of 100](https://github.com/GetStream/stream-chat-react/blob/88b8eb26becb22f623bdcbfa39a629f3625862ba/src/components/MessageInputLarge.js#L135) whereas react-images has a z-index of 1.

**Comment by jaapbakker88** [comment]
Ah thanks for reporting this. Will get a fix out ASAP

**Comment by jaapbakker88** [comment]
@codekiln i released version `0.7.11` which should fix this issue. Let me know if it resolves it.

**Comment by codekiln** [comment]
Will check later today, thanks @jaapbakker88

**Comment by jaapbakker88** [comment]
@codekiln I'm going to close this issue, let me know if this is still a problem.
