### ISSUE TITLE
URGENT: Stream React Chat broken in production

### ISSUE THREAD

**Issue by tkrevh** [GetStream/stream-chat-react#802]
Hello!

Today we started seeing this error, when trying to load Stream React Chat in our application:
stream-chat-react:54 Uncaught ReferenceError: jsxRuntime is not defined at stream-chat-react:54

We're loading Stream Chat as per your instructions, and it was fine until today:
<script src="https://cdn.jsdelivr.net/npm/react@16.13.1/umd/react.production.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/react-dom@16/umd/react-dom.production.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/stream-chat"></script>
<script src="https://cdn.jsdelivr.net/npm/stream-chat-react"></script>

gz#10444

**Comment by petyosi** [comment]
Hi @tkrevh .

Yesterday we published a new major version of the package. We are going to examine the problem you have reported, but in the meantime, can you please switch your code to using a versioned URL? Something like this:

**Comment by tkrevh** [comment]
Hello,

thank you for your quick answer. We did switch back to stream-chat-react@4.1.3 which resolved the issue.

**Comment by DanC5** [comment]
@tkrevh we just made a patch fix to correct this issue, thanks!

https://github.com/GetStream/stream-chat-react/releases/tag/v5.0.1

**Comment by tkrevh** [comment]
Great, thank you!
