### ISSUE TITLE
Version 5.0.x doesn't expose TS types

### ISSUE THREAD

**Issue by kainosnoema** [GetStream/stream-chat-react#804]
Just upgraded to v5.0, and it doesn't seem to work with Typescript any longer. Looks like the types files aren't in `dist` and are incorrectly linked in `package.json`. The `typings` property links to a file that doesn't exist:

https://github.com/GetStream/stream-chat-react/blob/1eceae9a08dba87c59193cc33b125113372cf4be/package.json#L7

gz#10463

**Comment by ambaldwin** [comment]
Hi @kainosnoema, we will put out a patch fix today and can update you here once we do. Thanks!

**Comment by DanC5** [comment]
Hey @kainosnoema can you try this new version and see if all works on your end? Thanks.

https://github.com/GetStream/stream-chat-react/releases/tag/v5.0.2

**Comment by kainosnoema** [comment]
@DanC5 the types seem to be there now, so that's a start!

Unfortunately the exposed types seem to have changed a bit (`MessageTeamState` is gone, etc). Seems like we can work around it by adjusting how we extend `MessageTeam`, but it was a bit of a breaking change for us. Appreciate the major version bump to warn of the risk. Will keep testing. 👍

**Comment by DanC5** [comment]
Thanks for the feedback, and glad to know the types are building properly now. I should have clarified in the change log that the JS functionality was non-breaking, but yeah, we did consolidate some of the old types as you found. Hopefully no significant hurdles for you in upgrading the types, thanks!
