### ISSUE TITLE
About DateTimeParser and Dayjs&Moment

### ISSUE THREAD

**Issue by hydRAnger** [GetStream/stream-chat-react#808]
Version: stream-chat-react@5.0.2

In [document](https://getstream.github.io/stream-chat-react/#section-streami18n), it mentioned both Dayjs and Moment can be used for DateTimeParser

```
DateTimeParser (function)

Moment or Dayjs instance/function
```

But in node_modules/stream-chat-react/built/types/src/i18n/Streami18n.d.ts, the type of DateTimeParser was defined as Dayjs (DateTimeParser?: typeof Dayjs;), so use Moment here will get a TypeScript error:
```
(property) DateTimeParser?: typeof dayjs
Type 'typeof moment' is missing the following properties from type 'typeof dayjs': extend, isDayjs, Dayjs, Lsts(2739)
Streami18n.d.ts(15, 5): The expected type comes from property 'DateTimeParser' which is declared here on type 'Options'
```

Yes, Dayjs is more lightweight than Moment, but for some locale requirement(for example, like 「昨日」(yesterday) in Japanese), Moment is irreplaceable here.

If it's necessary, May I make a PR to sovle it?

gz#10545

**Comment by SeniYG** [comment]
Hi, 
Thanks for bringing this to our attention.
One of our React engineers will pick this up shortly.

Best,

**Comment by DanC5** [comment]
@hydRAnger I understand your concern here, we did remove Moment a ways back to reduce the bundle size. But now that we're on TypeScript, we can import the Moment type without having to draw the entire library. Would adding the Moment type to the `Streami18n` `Options` type be all you need, something like the below on line 164 in the latest version of the library?

```
DateTimeParser?: typeof Dayjs | typeof Moment;
```

**Comment by DanC5** [comment]
@hydRAnger just looked into this added Moment type support to the library. We'll make a new release sometime within the next week, thanks!

https://github.com/GetStream/stream-chat-react/pull/809

**Comment by hydRAnger** [comment]
@DanC5  @SeniYG 

`we can import the Moment type without having to draw the entire library.

Thanks, guys!
Sure, I think that's a better idea, too.
