### ISSUE TITLE
Attach file on Chrome in fullscreen mode

### ISSUE THREAD

**Issue by bshimrit** [GetStream/stream-chat-react#814]
version 5.0.3

I have a scenario that I open the chat on a fullscreen mode using `element.requestFullscreen`.
When I try to attach a file on fullscreen mode on Chrome the fullscreen mode is exited(which is fine) but the selected file is not attached. 
- Drag and drop is working as expected.
- Other browsers in fullscreen mode upload file button is working as expected:
 -- Safari exits the fullscreen mode but attaches the selected file.
 -- Firefox doesn't exit fullscreen mode and attaches the file.

see a video showing the issue:
https://drive.google.com/file/d/1ZHvoMfI74OBpKMF-xSy-SuvvjSrYf0XK/view

Please advise what can be done.

Thank you.

**Comment by yetieaterxb1** [comment]
The app exiting fullscreen when attaching a file seems to be a known problem on Chrome. The selected file not being attached is interesting though. Are there any errors you are receiving when this happens?

**Comment by bshimrit** [comment]
@yetieaterxb1 no, unfortunately there are no messages on the dev console.

**Comment by yetieaterxb1** [comment]
@bshimrit not too sure what could be causing this issue. Could you send a snippet of the code where this button is implemented?

**Comment by bshimrit** [comment]
@yetieaterxb1 we have a custom hook useFullScreen on an component that contains the chat.

```import React, { useState, useLayoutEffect } from 'react'

export default function useFullscreen(fullscreenElement) {
  const [isFullscreen, setIsFullscreen] = useState(false)

  useLayoutEffect(() => {
    if (document.onfullscreenchange !== undefined &&
      document.fullscreen !== undefined
    ) {
      document.onfullscreenchange = () => setIsFullscreen(document.fullscreen)
    }
    else if (document.onwebkitfullscreenchange !== undefined &&
      document.webkitIsFullScreen !== undefined
    ) {
      document.onwebkitfullscreenchange = () => setIsFullscreen(document.webkitIsFullScreen)
    }

    return () => {
      if (document.onfullscreenchange !== undefined) {
        document.onfullscreenchange = undefined
      }
      else if (document.onwebkitfullscreenchange !== undefined) {
        document.onwebkitfullscreenchange = undefined
      }
    }
  }, [])

  const requestFullscreen = () => {
    if (fullscreenElement.current.requestFullscreen) {
      return fullscreenElement.current.requestFullscreen()
    }
    else if (fullscreenElement.current.webkitRequestFullscreen) {
      return fullscreenElement.current.webkitRequestFullscreen()
    }
  }

  function exitFullscreen() {
    if (document.exitFullscreen) {
      return document.exitFullscreen()
    }
    else if (document.webkitExitFullscreen) {
      return document.webkitExitFullscreen()
    }
  }

  const setFullscreen = () => {
    if (fullscreenElement.current == null) return

    if (isFullscreen) {
      exitFullscreen()
      setIsFullscreen(false)
    }
    else {
      requestFullscreen()
      setIsFullscreen(true)
    }
  }

  return [isFullscreen, setFullscreen]
}
```

you can call it on any component set useRef on the element you want to set as fullscreen: 

```
const liveEventElement = useRef()
 const [isFullscreen, setIsFullscreen] = useFullscreen(liveEventElement)
```

Then the button onClick just executes setIsFullscreen.

**Comment by yetieaterxb1** [comment]
https://user-images.githubusercontent.com/46791845/113323817-a5a8f400-92d3-11eb-9154-4d5dceeb4e00.mov

@bshimrit I used the code snippet you gave me to implement a fullscreen button and didn't have any issues with Chrome. The attachment seemed to be there after the application exits fullscreen.

**Comment by bshimrit** [comment]
@yetieaterxb1 10x. I will try to remove other code and see if something else is causing the problem.

**Comment by bshimrit** [comment]
issue resolved.

My messageInput component is a const inside the Chat component:

```
const MessageInputComponent =props => {
    return <MessageInputLarge
      SendButton={SendButton}
      EmojiIcon={EmojiIcon}
      FileUploadIcon={FileUploadIcon}
      grow={canGrow} // fix input resizing on collapse
      additionalTextareaProps={{ maxLength: MESSAGE_MAX_LENGTH }}
      {...props} />
  }
```

cause I also use it on Thread as you explain on your documentation:
`MessageInput={props => <MessageInput parent={props.parent} Input={MessageInputComponent} /> `

https://getstream.github.io/stream-chat-react/#thread

since the component const MessageInputComponent is created on each render it somehow causes the attachment to fail. I wrapped it with useCallback:

```
 const MessageInputComponent = useCallback(props => {
    return <MessageInputLarge
      SendButton={SendButton}
      EmojiIcon={EmojiIcon}
      FileUploadIcon={FileUploadIcon}
      grow={canGrow} // fix input resizing on collapse
      additionalTextareaProps={{ maxLength: MESSAGE_MAX_LENGTH }}
      {...props} />
  },[])
```

it resolved the issue for the messageList. 

Also had to wrap the Thread MessageInput:
`const ThreadMessageInput = useCallback(props => {
    return <MessageInput
      parent={props.parent}
      Input={MessageInputComponent} />
  }, [])`

and then set MessageInput prop to ThreadMessageInput
`MessageInput={ThreadMessageInput}`

**Comment by yetieaterxb1** [comment]
Glad to hear its resolved @bshimrit
