### ISSUE TITLE
Consider including send button

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#82]
Our careful QA team has noticed a UI inconsistency between "Edit Message" and "Message Input" modes. They would like to request more consistency with Skype with respect to a Send action. 

Skype has a "send" button (paper airplane icon), and when you edit a post, it turns to a "cancel" icon (X icon), which turns to a "send" button (paper airplane icon) when you start to modify a post that is in edit mode. 

## Send Action Icon
![Send Action Icon](https://user-images.githubusercontent.com/140930/68132930-81ce5c80-feed-11e9-8d4d-989f5bf58f00.png)

## Edit Message Action Icon [no modifications]
![Edit Message Action Icon [no modifications]](https://user-images.githubusercontent.com/140930/68132984-9c083a80-feed-11e9-8715-b09e10969dab.png)

## Edit Message Icon [with modifications]
![Edit Message Icon [with modifications]](https://user-images.githubusercontent.com/140930/68133048-b6421880-feed-11e9-8370-5f5544c45663.png)

## GetstreamIO - no "send" button on new messages
![GetstreamIO - no "send" button on new messages](https://user-images.githubusercontent.com/140930/68133167-e1c50300-feed-11e9-9450-852ae07d8228.png)

## GetstreamIO - "send" and "cancel" button on edit messages
![GetstreamIO - "send" and "cancel" button on edit messages](https://user-images.githubusercontent.com/140930/68133210-f3a6a600-feed-11e9-8cf9-36f140025007.png)

**Comment by jaapbakker88** [comment]
@codekiln Right now we have a sendbutton that only displays on mobile, this could be tweaked through css to display also on desktop. Will that solve this issue?

**Comment by jaapbakker88** [comment]
Closing this ticket due to inactivity.
