### ISSUE TITLE
MessageInput's 'disableMentions' property doesn't work

### ISSUE THREAD

**Issue by adam-crey** [GetStream/stream-chat-react#820]
Hi there,
I've tried to disable the mention feature in my application but even if I add disableMentions to MessageInput component as prop it doesn't work. After when I type '@' in the MessageInput the SuggestionList always pops up. 
In my opinion, this currentTrigger value causes this problem but I am not sure.
https://github.com/GetStream/stream-chat-react/blob/aed3750749bfd958cd6c23984e4fad92adff17c0/src/components/AutoCompleteTextarea/Textarea.js#L656

**Comment by yetieaterxb1** [comment]
Hi @adam-crey,

I am struggling to reproduce this bug. What version of stream-chat-react are you using? 

The following code example seems to be working as intended on my end when testing.

`<MessageInput Input={MessageInputFlat} disableMentions />`

**Comment by adam-crey** [comment]
Hi @yetieaterxb1,
Thanks for the quick help. I used an older one (4.1.3) but since I've updated that to the recent version it works like a charm. 🤩
