### ISSUE TITLE
How VirtualizedMessageList render message from bottom ?

### ISSUE THREAD

**Issue by khiemvinh97** [GetStream/stream-chat-react#824]
I have used VirtualizedMessageList to render a list of Messages from the channel. 
But the list did not come from the bottom. 
How I can do to render Messages come from the bottom?

**Comment by yetieaterxb1** [comment]
Hello and thanks for submitting an issue to our GithHub repository. We’re glad you’re getting hands on with the product. The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.

In case our understanding is incorrect and you are describing a bug, we apologize, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.
