### ISSUE TITLE
Can't set my channel active

### ISSUE THREAD

**Issue by nguyenhiep97ht** [GetStream/stream-chat-react#829]
i have task that set channel active without send new message or click to channel on channelList, i tried using setActiveChannel at ChatContext but its wasn't work, what's the reason? help me~~

```
const { setActiveChannel } = useContext(ChatContext);
  const createOneChannel = async user => {
    try { 
      const name =
        chatClient?.user?.name +
        ' - ' +
        (unit?.name && asset.hiddenUnitName === false ? unit.name : unit.code) +
        (asset?.name && asset.hiddenAssetName === false ? ', ' + asset.name : '') +
        ', ' +
        unit?.district?.name +
        ', ' +
        unit?.province?.name;
      setLoading(true);
      let conversation = chatClient.channel(
        `team`,
        `${user?.idAssetManager + '-' + chatClient?.user?.id + '-' + unit.id + '-' + asset.id}`,
        {
          members: [`${user?.idAssetManager}`, `${chatClient?.user?.id}`],
          name: name,
        },
      );
      await conversation.watch();
      setActiveChannel(conversation, { limit: 0, offset: 1 }, () => {});
      setLoading(false);
      openChat();
    } catch (error) {
      message.error(error.message);
      setLoading(false);
    }
  };
```

**Comment by ath92** [comment]
Hi @nguyenhiep97ht, can you give a little bit more information about the issue? Are you seeing any errors? I reduced your code to a slightly more minimal reproduction, which does work on my side. Here's what that looks like:

```
const Button = () => {
  const { setActiveChannel } = React.useContext(ChatContext);
  const createOneChannel = async () => {
    try { 
      let conversation = chatClient.channel(
        `team`,
        `someChannelId`,
        {
          members: [`user-1`, `user-2`],
          name: "Channelname!",
        },
      );
      await conversation.watch();
      setActiveChannel(conversation, { limit: 0, offset: 1 }, () => {});
    } catch (error) {
      console.warn(error)
    }
  };

  return <button onClick={createOneChannel}>create one channel</button>
};
```

After placing this button in a place where it has access to `ChatContext`, clicking it will cause a new channel to be created, and the app switches to that channel.

**Comment by nguyenhiep97ht** [comment]
> Hi @nguyenhiep97ht, can you give a little bit more information about the issue? Are you seeing any errors? I reduced your code to a slightly more minimal reproduction, which does work on my side. Here's what that looks like:
> 
> ```
> const Button = () => {
>   const { setActiveChannel } = React.useContext(ChatContext);
>   const createOneChannel = async () => {
>     try { 
>       let conversation = chatClient.channel(
>         `team`,
>         `someChannelId`,
>         {
>           members: [`user-1`, `user-2`],
>           name: "Channelname!",
>         },
>       );
>       await conversation.watch();
>       setActiveChannel(conversation, { limit: 0, offset: 1 }, () => {});
>     } catch (error) {
>       console.warn(error)
>     }
>   };
> 
>   return <button onClick={createOneChannel}>create one channel</button>
> };
> ```
> 
> After placing this button in a place where it has access to `ChatContext`, clicking it will cause a new channel to be created, and the app switches to that channel.

i want to create a new channel and it jumps to top of channelList and highlight, but in my code, it jumps to bottom and also not highlight, i will try your suggesstion, thank @ath92 to reply me
