### ISSUE TITLE
Clone => yarn build => failure on Windows

### ISSUE THREAD

**Issue by ntziolis** [GetStream/stream-chat-react#83]
We are trying to extend MessageSimple to allow displaying both the auto translated message + original message. The translations are added as custom data to new messages via webhook. 

We have performed the following steps:

- Cloned repo (today, master)
- Run `yarn install`
- Run `yarn build`

Result:
- Errors logged during build process (seem scss related)
- `dist/index.css` still contains scss (see below)

FYI:
Same result when running make.

## yarn build log
```
$ yarn build
yarn run v1.19.1
$ mkdir -p dist/assets assets && rollup -c

src/index.js → dist/index.js, dist/index.es.js...

Error:
        Invalid CSS after "}": expected 1 selector or at-rule, was "../../../node_modul"
Solution:
        fix your Sass code
Line:   164
Column: 2


Error:
        Invalid CSS after "}": expected 1 selector or at-rule, was "../../../node_modul"
Solution:
        fix your Sass code
Line:   164
Column: 2

dist/css/index.css 125 kB
dist/css/index.css 125 kB
created dist/index.js, dist/index.es.js in 7.8s

src/index.js → ./dist/browser.full-bundle.min.js...
[COPY] src/assets/str-chat__alert.svg to dist/assets/str-chat__alert.svg
[COPY] src/assets/str-chat__icon-chevron-down.svg to dist/assets/str-chat__icon-chevron-down.svg      
[COPY] src/assets/str-chat__icon-search.svg to dist/assets/str-chat__icon-search.svg
[COPY] src/assets/str-chat__icon-send.svg to dist/assets/str-chat__icon-send.svg
[COPY] src/assets/str-chat__icon-sprite.png to dist/assets/str-chat__icon-sprite.png
[COPY] src/assets/str-chat__icon-sprite@1x.png to dist/assets/str-chat__icon-sprite@1x.png
[COPY] src/assets/str-chat__connection-error.svg to dist/assets/str-chat__connection-error.svg        
[COPY] src/assets/str-chat__loading-indicator.svg to dist/assets/str-chat__loading-indicator.svg      
[COPY] src/assets/str-chat__icon-sprite@2x.png to dist/assets/str-chat__icon-sprite@2x.png
[COPY] src/assets/Poweredby_100px-White_VertText.png to dist/assets/Poweredby_100px-White_VertText.png
[COPY] src/assets/str-chat__reaction-list-sprite@1x.png to dist/assets/str-chat__reaction-list-sprite@1x.png
[COPY] src/assets/str-chat__reaction-list-sprite@2x.png to dist/assets/str-chat__reaction-list-sprite@2x.png
[COPY] src/assets/str-chat__file-file.svg to dist/assets/str-chat__file-file.svg
[COPY] src/assets/str-chat__reaction-list-sprite@3x.png to dist/assets/str-chat__reaction-list-sprite@3x.png
[COPY] src/assets/str-chat__icon-sprite@3x.png to dist/assets/str-chat__icon-sprite@3x.png
[COPY] src/assets/str-chat__reactions-sprite@2x.png to dist/assets/str-chat__reactions-sprite@2x.png        
[COPY] src/assets/str-chat__reactions-sprite@1x.png to dist/assets/str-chat__reactions-sprite@1x.png        
[COPY] src/assets/str-chat__reactions-sprite@3x.png to dist/assets/str-chat__reactions-sprite@3x.png
created ./dist/browser.full-bundle.min.js in 20.6s
Done in 29.85s.
```

## dist/index.css
```
/* fonts */
$main-font: 'IBM Plex Sans', sans-serif;
$second-font: 'Helvetica Neue', Helvetica, Arial, sans-serif;
$mono-font: Consolas, 'Andale Mono WT', 'Andale Mono', 'Lucida Console',
  'Lucida Sans Typewriter', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono',
  'Liberation Mono', 'Nimbus Mono L', Monaco, 'Courier New', Courier, monospace;

$base-font-weight: 400;
$heavy-font-weight: 700;

/* colors */
$primary-color: magenta;
$secondary-color: #006cff;
$secondary-faded: #bcd8ff;

$dt-bg-team: #1d1f22;

$border-color: rgba(0, 0, 0, 0.08);

$black: black;
$white: white;
$grey: #f0f0f0;

/* miscellaneous */
$border-radius: 16px;
...
```

**Comment by jaapbakker88** [comment]
Thanks for reporting this issue @ntziolis . Can you share a bit more about your setup, what version of yarn and node are you running? Thanks

**Comment by ntziolis** [comment]
We are using yarn version 1.19.1 (should be lastest).
We have tried multiple different node version from 10 all the way through to 13.

We have also tried multiple different system configurations
- WSL
  -  This produces the error seen
- Windows
  - Fails no matter the node/yarn version due to build script containing `mkdir -p dist/assets` (-p flag does not exist on windows)
  - we replaced the directory creation part of the the build script to `mkdir dist & cd dist & mkdir assets & cd..`´which got us over the intial `mkdir -p` issue
  - cmd
    - produces same result as reported above
  - powershell
    - produces an entirely different error (something with missing prop-types), but since cmd produced the same as the linux counterpart lets NOT focus on this for now

**Comment by ntziolis** [comment]
Also is there any way to set set a logging level during build to something like `Verbose` ?

**Comment by ferhatelmas** [comment]
@ntziolis could you run yarn with `--frozen-lockfile` flag?

For environment, you can inspect one of the latest successful build for example
for convenience: https://travis-ci.org/GetStream/stream-chat-react/builds/608668612

@jaapbakker88 we might add `before_install` for `yarn` because travis uses an old yarn by default.

**Comment by ferhatelmas** [comment]
@jaapbakker88 https://github.com/GetStream/stream-chat-react/pull/85 for yarn version

**Comment by ntziolis** [comment]
Checking now, getting back to you within the hour

**Comment by ntziolis** [comment]
Sry for the delay. The `--frozen-lockfile` flag did not help. We did setup a completely fresh system to test things out but with the same result (using 100% same versions as menioned in your travis builds.

We did find a few things:
- Changing `../../../node_modules/emoji-mart/css/emoji-mart.css`to `@import "../../../node_modules/emoji-mart/css/emoji-mart"` in `emojii-mart.scss` + the same change in `react-file-util.scss` did resolve the css errors above.
- But once those were gone we immediately got the next css related errors
```
Error:
        Invalid CSS after "...__actions-box {": expected 1 selector or at-rule, was "background: #fff;"
Solution:
        fix your Sass code
Line:   164
Column: 2

Error:
        Invalid CSS after "...__actions-box {": expected 1 selector or at-rule, was "background: #fff;"
Solution:
        fix your Sass code
Line:   164
Column: 2
```

Since build runs through for you and im assuming you are doing so on a Linux machine I have a hunch that this all could be related to line endings. Line endings because we run into issues even on WSL. The only thing the WSL gets from windows is the checked out code files (done from windows with auto line ending conversions)

Have you ever build this lib on a windows machine?

**Comment by ferhatelmas** [comment]
@ntziolis we didn't put any effort building on windows but it will be better to cover.

I will add windows building into CI so that we can find out the issue and fix it.

**Comment by ntziolis** [comment]
@ferhatelmas That you that would be much appreciated. Right now we are working with hands tied behind our back:
- we are checking in the dist folder and are removing the `prepare` script
- we can only make changes to js part of the components as we cannot compile the css portion properly
- that means after building we discard the generated broken css (and leverage the ones that come with the original package)

Obviously this isn't a long term solution bu this way we could at least move forward with development.

If there is anything you need from our side like validation etc let us know as this is top on our list to straiten out.

**Comment by ntziolis** [comment]
@ferhatelmas Were you able to run a build on windows in your CI environment? Or if not yet any ideas where the issues come from so we could monkey-path it on our end?

**Comment by ferhatelmas** [comment]
@ntziolis started, running and it seems fixing it will require some bumps in dependencies. Checking it today and accordingly, will keep you updated.

**Comment by ntziolis** [comment]
Awesome thank you. I'm just glad we now have confirmation that we were not to dumb getting it up and running :D

**Comment by ntziolis** [comment]
@ferhatelmas Any update on ability to build on windows?

**Comment by ntziolis** [comment]
Any update? We are desperately waiting for this to be fixed. Please let us know if we can expect this anytime soon, otherwise we will have to find other solutions

**Comment by ferhatelmas** [comment]
@ntziolis sorry for yhe inconvenience it slided a bit but I will ensure it's ready for Monday.

**Comment by ferhatelmas** [comment]
@ntziolis do you have any chance to use the linux subsystem in windows? I tested with Windows 10 + ubuntu and it works nicely.

**Comment by ntziolis** [comment]
@ferhatelmas We have been using the subsystem for linux (same config WIndows 10 + Ubuntu) since shortly after opening the issue. But we were not able to build the css files properly. Are you saying by now building the css works in the linux subsystem? If so we can make due with that no prob.

**Comment by ntziolis** [comment]
Still running into the same issue as before when using WLS. Tested on multiple devices all running Windows 10 + Ubuntu.

**Comment by KirankumarAmbati** [comment]
I am facing similar issue. I cloned [repo](https://github.com/GetStream/stream-chat-react.git), ran `yarn` and `yarn start`

Getting below error:

```
$ yarn start
yarn run v1.21.1
$ mkdir -p dist/assets assets && rollup -c -w
The syntax of the command is incorrect.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Environment Info:

Windows 10
yarn 1.21.1
node v10.15.0

Please help me if I'm doing something wrong. Thanks!

**Comment by ntziolis** [comment]
Is it possible now to run a build on Windows or still only possible in WSL?

**Comment by jaapbakker88** [comment]
As far as I know it's still only possible on WSL

**Comment by ntziolis** [comment]
Are they any plans to change that as right now it breaks or CI process.
