### ISSUE TITLE
Supported devices of stream-chat-react v5.1.0

### ISSUE THREAD

**Issue by chinhtran52** [GetStream/stream-chat-react#830]
`"stream-chat": "3.7.0",
 "stream-chat-react": "5.1.0",`
 
 I build a web app this version and it worked amazing on several devices. I tested on Firefox, Chrome, Safari and Edge latest version, all of them have no issues with these libraries.
 
 However, I tested on Safari - iOS 9.3.5 (iPad 3) and It isn't worked. Some old version browsers (such as Firefox 47.0.3, IE 11, ...) have the same problems with Safari iOS 9.3.5.
 
Can you give me the browser support range (on Mac and Windows) or explain this issue come from other libs instead of stream-chat-react?
 
 Thank for your amazing lib.

**Comment by yetieaterxb1** [comment]
Hi @chinhtran52,
 
Currently these are the browser settings we build to
```
  "browserslist": [
    ">0.2%",
    "not ie <= 11",
    "not op_mini all"
  ]
```
0.2%: All browsers that have at least 0,2% of global market share
not ie <= 11: Exclude IE 11 and older versions
not op_mini all: Exclude Opera Mini

Unfortunately older versions of browsers will lose support as time goes on and we dont have the capacity at this moment to keep up with all outdated browser versions.
