### ISSUE TITLE
messageActions on MessageLivestream component

### ISSUE THREAD

**Issue by bshimrit** [GetStream/stream-chat-react#833]
version 5.1.0

I am using messageActions prop to limit actions on MessageList.jsx
I want to use it on Thread too. so tried to pass the prop value on the Message component. like this:

```
const MESSAGE_ACTIONS = ['edit', 'delete', 'react', 'reply']. 

const MessageComponent = props => <MessageLivestream {...props} EditMessageInput={EditInputComponent} messageActions={MESSAGE_ACTIONS} />
```

this prop doesn't seem to effect the actions neither on MessageList or Thread messages. though it shows on documentation it should. 

please advise.

**Comment by ath92** [comment]
Hi @bshimrit , 

I think our docs are off in this case, in fact I think you've spotted a bug in our type system, which is used to auto generate the docs. 

You should be able to set the `additionalMessageListProps` on `Thread` with the same value you were previously using on `MessageList`. This will inject your custom value for `messageActions` into the message list that is used inside the `Thread` component. 

Let me know if that works for you.

**Comment by bshimrit** [comment]
@ath92,it worked as expected. Thanks!
