### ISSUE TITLE
Allow ability to change autocomplete minchar value by trigger

### ISSUE THREAD

**Issue by cenzovit** [GetStream/stream-chat-react#838]
We would like to be able to make it so that the emoji auto complete trigger requires a user to input two characters after a colon in order to trigger the emoji search instead of just one; however, this functionality does not appear to be configurable.

**Comment by cenzovit** [comment]
Semi-related, why does the header of the autocomplete only display the proper text when the first character of the textinput value is the trigger? (IE when a user inputs text into the textfield and then types a colon, the header "Emoji matching" for the emoji search autocomplete is incorrectly missing)

**Comment by ath92** [comment]
Hi @cenzovit, thanks for reaching out about this.

> Semi-related, why does the header of the autocomplete only display the proper text when the first character of the textinput value is the trigger? (IE when a user inputs text into the textfield and then types a colon, the header "Emoji matching" for the emoji search autocomplete is incorrectly missing)

This is a bug, I opened a PR (#839) that should fix this issue, thanks for letting us know.

> We would like to be able to make it so that the emoji auto complete trigger requires a user to input two characters after a colon in order to trigger the emoji search instead of just one; however, this functionality does not appear to be configurable.

It is currently possible to define your own set of autocomplete triggers (see `autocompleteTriggers` in https://getstream.github.io/stream-chat-react/#messageinput) and pass those into your message input component. If you want to keep the default set of triggers, this would require you to copy over some part of the trigger functionality, but it would allow you more flexibility regarding the actual way the autocomplete suggestions work.

**Comment by cenzovit** [comment]
Correct me if I am wrong, but due to how this is implemented and how little documentation there is around how to shape your own triggers (although it appears you guys copied https://github.com/webscopeio/react-textarea-autocomplete under the hood), it looks like it would be rather frustrating to reverse engineer all the normal triggers just to change some small parts of the emoji search. Happy to give it a whirl, but would appreciate some enhancements to this functionality. It appears to me based on a cursory pass of the source code that at least exporting the default trigger object would be a boon for developers trying to interface with this functionality and would lead to less brittle code as they would not have to pay as close attention to changes to the default functionality.

**Comment by cenzovit** [comment]
Upon further review it looks like it isn't even possible to replicate some of the default functionality (@ trigger user searching) because the default functionality has access to local react state variables (searching and setSearching) that passed in triggers would not be able to access.

**Comment by cenzovit** [comment]
It also appears that from https://github.com/GetStream/stream-chat-react/pull/331 y'all removed some functionality that was provided by the library you forked making it hard (impossible?) to stop autocomplete after a user enters a space because you trim the whitespace from the query string?

**Comment by ath92** [comment]
hi @cenzovit, thanks for investigating further. I think you're right when you say this part of the SDK is not easy to customize at the moment. We're looking into refactoring some of the components around the MessageInput at the moment, we'll also look at making it easier to customize triggers.

It sounds like your original request (being able to only show suggestions when the query has more than 2 characters) may not be the only thing you need here. If so, could you give us a more detailed description of what you're building, so we can get a better sense of what the SDK should support?

**Comment by cenzovit** [comment]
The modifications we would like to make to the emoji autocomplete trigger is that it triggers two characters after the colon and stops suggesting after the user enters whitespace (essentially ending that autocomplete). This would allow users to enter basic emoticon (which often convert into emoji anyways -- ie :P) without being prompted and would end the autocomplete prompt as soon as the user starts another word. I believe this is similar functionality to Slack. I think in general if you are going to expose customization like the autocompleteTriggers attribute on MessageInput, it should be possible to match the default behavior with little effort even if you have to do some reverse engineering to make further modifications to that behavior. Thanks for your timely responses! Excited to see what y'all come up with.

**Comment by ath92** [comment]
Hi @cenzovit, 

we're still working on the refactor  that will enable trigger customisation, but I can give you a little preview of what's to come:

We're introducing a new prop for `MessageInput` called `TriggerProvider`. This is a component that lets you override the triggers by injecting the correct value into the newly added `MessageInputContext`. You can check out the `context-refactor` branch to get a complete view of what we're adding (fair warning: it's quite a lot of new code), but in particular you may want to have a look at a file called `DefaultTriggerProvider` (inside the `MessageInput` component folder). 

If you want to override the triggers, you'll have to create a custom TriggerProvider. Here's an example of what that component may look like for you:

```javascript
import { useCommandTrigger, useUserTrigger } from 'stream-chat-react';
import { useCustomEmojiTrigger } from './useCustomEmojiTrigger';
const CustomTriggerProvider = ({
  children,
}) => {
  const currentValue = useMessageInputContext();
  const defaultAutocompleteTriggers: TriggerSettings = {
    '/': useCommandTrigger(),
    ':': useCustomEmojiTrigger(currentValue.emojiIndex), // note: here we use a custom hook
    '@': useUserTrigger(
      currentValue.mentionQueryParams,
      currentValue.onSelectUser,
      currentValue.mentionAllAppUsers,
    ),
  };
  const newValue = {
    ...currentValue,
    autocompleteTriggers: defaultAutocompleteTriggers,
  };
  return <MessageInputContextProvider value={newValue}>{children}</MessageInputContextProvider>;
};
``` 

We need to create `useCustomEmojiTrigger` here, which will override the default emoji trigger hook: 

```typescript
import { EmoticonItem } from 'stream-chat-react';
import type { EmojiTriggerSetting } from 'stream-chat-react';

export const useEmojiTrigger = (emojiIndex?: NimbleEmojiIndex): EmojiTriggerSetting => ({
  component: EmoticonItem,
  dataProvider: (query, _, onReady) => {
    if (query.length === 1 || query.includes(' ')) return []; // note: this line adds your features
    if (query.length === 0 || query.charAt(0).match(/[^a-zA-Z0-9+-]/)) {
      return [];
    }
    const emojis = emojiIndex?.search(query) || [];
    // emojiIndex.search sometimes returns undefined values, so filter those out first
    const result = emojis.filter(Boolean).slice(0, 10);
    if (onReady) onReady(result, query);
    return result;
  },
  output: (entity) => ({
    caretPosition: 'next',
    key: entity.id,
    text: `${'native' in entity ? entity.native : ''}`,
  }),
});
``` 

And finally, here's how you can actually apply the code that we just wrote:

```javascript
<MessageInput TriggerProvider={CustomTriggerProvider} />
```

There's still a bit of code to write to override the trigger behavior, but you do have full control now. Does this work for you?
