### ISSUE TITLE
Ability to make private channels (one to one channel) without owner role

### ISSUE THREAD

**Issue by ahmeddahy** [GetStream/stream-chat-react#851]
Hello, 
In my app, I need to create one to one channels (friends).So if I create it, someone of these users will have "owner" role which means that this user will have the ability to edit and delete messages of his friend (the other user in the channel) which is not expected in this channel.
Any help in this case.
Thanks.

**Comment by DanC5** [comment]
Hey @ahmeddahy I see the issue here and agree with you that this behavior is not desired. I'm going to adjust in the library and make a new release, likely later today or tomorrow. I'll message back when it's live, thanks.

**Comment by DanC5** [comment]
@ahmeddahy please check out our latest release, https://github.com/GetStream/stream-chat-react/releases/tag/v5.1.7.

We removed channel creator ability to edit/delete all messages. Thanks raising the issue, and I'm going to close as it should be handled.
