### ISSUE TITLE
Pin and Unpin is unstable

### ISSUE THREAD

**Issue by ahmeddahy** [GetStream/stream-chat-react#852]
Hello, 
In this channel, when I pin message for "Ahmed Dahy" user, give me this error.
![Untitled](https://user-images.githubusercontent.com/19478517/114571776-33db8d80-9c77-11eb-973f-b9ab77a67e82.png)

In the same channel when I pin another message for the same user "Ahmed Dahy", it is pinned successfully.
![Untitled](https://user-images.githubusercontent.com/19478517/114572119-83ba5480-9c77-11eb-89fe-2801d130f8da.png)

any help to fix this odd behavior ?

**Comment by DanC5** [comment]
@ahmeddahy can you share the network response when the pin message request errors? If it works some of the time then it doesn't seem to be a permissions issue unless you tried the pin action from different users with different roles.

**Comment by ahmeddahy** [comment]
@DanC5 
I got it.
I will explain to you the case clearly

I am using two users to test pin and unpin 
1- System Admin User (moderator at "General" channel)
2- Ahmed Dahy380 (member at "General" channel)

When pin message by "System Admin User" it is pinned successfully and no problem at this operation.
![Untitled](https://user-images.githubusercontent.com/19478517/114685829-7ef6ae80-9d12-11eb-8bd3-66f17c22ab82.png)

when I use "Ahmed Dahy380" user to pin or unpin messages, it works successfully for only messages that the moderator "System Admin User" pinned or unpinned (make any pin operation on it). 


If "System Admin User" doesn't make any pin operation on some message, "Ahmed Dahy380" user will not have the ability to pin or unpin this message.


![bandicam 2021-04-14 12-34-58-199](https://user-images.githubusercontent.com/19478517/114702471-67282600-9d24-11eb-94e1-fa426a13ba33.gif)

**Comment by DanC5** [comment]
@ahmeddahy This is very interesting, have you adjusted pin permissions (or the `messageActions` array in the MessageList) for the user role of `member`? Also, what channel type are you using here?

By default, members can only pin messages in `messaging` and `team` type channels and require permissions updates in the dashboard for other types. If you're using any channel type other than messaging/team then the pin request should fail (which I assume is what's happening here), but it's odd that the request would succeed on messages that had previously been pinned.

Let me know the answers to those questions and I'll work on this, thanks.

**Comment by ahmeddahy** [comment]
@DanC5 
I haven't adjusted messageActions but I changed my permissions you can check it and my channel type is "team"
`
[
	{
		"action": "Allow",
		"name": "admin can do almost anything",
		"resources": [
			"CreateChannel",
			"ReadChannel",
			"UpdateChannelMembers",
			"UpdateChannel",
			"DeleteChannel",
			"CreateMessage",
			"UpdateMessage",
			"DeleteMessage",
			"BanUser",
			"UploadAttachment",
			"DeleteAttachment",
			"UseCommands",
			"AddLinks",
			"EditUser",
			"RunMessageAction",
			"CreateReaction",
			"DeleteReaction",
			"PinMessage",
			"CreateDistinctChannelForOthers"
		],
		"roles": [
			"admin"
		],
		"owner": false,
		"priority": 999
	},
	{
		"action": "Deny",
		"name": "No guests or anonymous access",
		"resources": [
			"*"
		],
		"roles": [
			"anonymous",
			"guest"
		],
		"owner": false,
		"priority": 90
	},
	{
		"action": "Allow",
		"name": "Owner permissions",
		"resources": [
			"ReadChannel",
			"UpdateChannelMembers",
			"UpdateChannel",
			"DeleteChannel",
			"UpdateMessage",
			"DeleteMessage",
			"EditUser",
			"DeleteAttachment",
			"DeleteReaction",
			"PinMessage"
		],
		"roles": [],
		"owner": true,
		"priority": 80
	},
	{
		"action": "Allow",
		"name": "Channel member permissions",
		"resources": [
			"ReadChannel",
			"CreateChannel",
			"CreateMessage",
			"UploadAttachment",
			"UseCommands",
			"AddLinks",
			"RunMessageAction",
			"CreateReaction",
			"PinMessage",
			"CreateDistinctChannelForOthers"
		],
		"roles": [
			"channel_member",
			"channel_moderator"
		],
		"owner": false,
		"priority": 70
	},
	{
		"action": "Allow",
		"name": "Users can create channels",
		"resources": [
			"CreateChannel",
			"CreateDistinctChannelForOthers"
		],
		"roles": [
			"user"
		],
		"owner": false,
		"priority": 60
	},
	{
		"action": "Allow",
		"name": "Moderator only features",
		"resources": [
			"UpdateChannelMembers",
			"UpdateChannel",
			"UpdateMessage",
			"DeleteMessage",
			"BanUser",
			"DeleteAttachment",
			"UploadAttachment",
			"PinMessage"
		],
		"roles": [
			"channel_moderator"
		],
		"owner": false,
		"priority": 50
	},
	{
		"action": "Deny",
		"name": "deny all policy",
		"resources": [
			"*"
		],
		"roles": [
			"*"
		],
		"owner": false,
		"priority": 1
	}
]
`

**Comment by ahmeddahy** [comment]
@DanC5 
any updates about this issue ?

**Comment by DanC5** [comment]
@ahmeddahy I have an idea for what's going on here and am meeting with another team member to check something later today. In the meantime, can you provide the following info?

- `client.user.role` for Ahmed Dahy380
- `channel.state.members[// Ahmed Dahy380's user ID].role` if the user is a member of the channel

**Comment by DanC5** [comment]
Hey @ahmeddahy, I made a patch release of the library (v5.1.8) that adjusts the permissions handling logic a bit. Also in your permissions object make sure the role `channel_member` gets the `UpdateMessage` resource. We just noticed in our defaults that members have pin access but not update access, and pin calls update so you need them both. After you make these two adjustments let me know if you're still seeing any odd behavior, thanks!

**Comment by s4admin** [comment]
I'm getting the same issue.  here's the error:

TeamMessage.js:12 Uncaught (in promise) Error: StreamChat error code 4: UpdateMessage failed with error: "expected string for field "message.mentioned_users[0]" but got object"
    at StreamChat.errorFromResponse (/node_modules/stream-chat/dist/browser.es.js:5432)

does the update fix the?

**Comment by DanC5** [comment]
@s4admin what version of `stream-chat` are you on? There was an api bug with pinning messages containing mentioned users, but this was fixed a month or so ago.

**Comment by s4admin** [comment]
"stream-chat": "^2.12.0",
"stream-chat-react": "^3.6.0"

**Comment by DanC5** [comment]
@s4admin upgrading to the latest versions should fix this issue, we're on 3.7.0 for `stream-chat` and the caret likely isn't bumping you major versions

**Comment by smendez-dev** [comment]
I'm still able to reproduce this eventhough I got the latest versions

**Comment by DanC5** [comment]
@smendez-dev did you add the `UpdateMessage` resource to your channel type permissions for the user role in question that is receiving the error?

**Comment by smendez-dev** [comment]
@DanC5  update, I just did that and it seems to work partially, whenever I pin the message the server request stays in "pending" cause the screen to freeze, and when I refresh the page the message is pinned

**Comment by DanC5** [comment]
@smendez-dev I'm not really sure why this particular request would hang like this. Have you seen the pending status on any other actions? Also can you share the request payload to see that it's all structured properly?
