### ISSUE TITLE
Click: div.str-chat__gallery. > div.str-chat__gallery-image > img (ResizeObserver loop limit exceeded)

### ISSUE THREAD

**Issue by YohaanYoon** [GetStream/stream-chat-react#854]
stram-chat-react: v5.1.6
stream-chat: v3.1.4

I received errors from the Sentry many time.
I attached a image as follows:

 ![스크린샷 2021-04-16 오후 12 00 52](https://user-images.githubusercontent.com/6019966/114965414-7e455000-9eab-11eb-936f-c558c7fb8d8b.png)

Please let me know any issues.

**Comment by petyosi** [comment]
@YohaanYoon you can safely ignore this error - check [this StackOverflow answer](https://stackoverflow.com/a/50387233) for more information.
