### ISSUE TITLE
No support for Nodejs LTS in Ubuntu

### ISSUE THREAD

**Issue by zahidirfan** [GetStream/stream-chat-react#858]
I get the following error. It seems that the dependency rgrove/parse-xml@3.0.0 does not support the nodejs LTS 10.18 in Ubuntu. 

`@rgrove/parse-xml@3.0.0:` The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.18.1"

How to get rid of this ? Any work around since the official Ubuntu still not allows to install Node LTS 14

**Comment by ambaldwin** [comment]
Hi @zahidirfan I don't believe we've seen this issue raised before and don't have a workaround currently. Are you able to upgrade node to >=12.0.0 so that the dependency works? Let us know, thanks.
