### ISSUE TITLE
Using the mock-builders

### ISSUE THREAD

**Issue by kyriacos** [GetStream/stream-chat-react#869]
Hi, I've been playing with the examples using my own chat api key etc.. I feel it would be faster to get the example up and running with a few mock messages and examples just so i can style it differently.

We want to use the chat obviously in our application but with custom styling. Might be easier to see what needs changing if it was pre-populated.

Is there a way i can use the mock-builders to populate a chat with a few channels and messages? 
Or an easy way to use them in a mock server environment?

Thanks!

**Comment by ambaldwin** [comment]
Hi, @kyriacos please refer to the [Stream CLI](https://github.com/GetStream/stream-cli) to generate data for your app while you're taking a look around.

Let us know if you have any questions or issues and we are happy to help, otherwise I am going to close this issue. Thanks!
