### ISSUE TITLE
Ability to customize ReactionSelector of a Message component in Chat

### ISSUE THREAD

**Issue by SonikJhang** [GetStream/stream-chat-react#880]
Is there a way to customize MinimalEmoji list to include custom icon which allows to expand to a full emoji library without 
having to reconstruct ReactionSelector component?

**Comment by yetieaterxb1** [comment]
Hi @SonikJhang,

You can supply `ReactionSelector` the `reactionOptions` prop consisting of emojis you would like as reactions.  For custom functionality outside of that you would need to build your own custom component. 

Feel free to reach out to support@getstream.io if you have other questions about the library implementation.
