### ISSUE TITLE
How to remove / hide the messages ? 

### ISSUE THREAD

**Issue by mrudangshah** [GetStream/stream-chat-react#883]
While by following the [documentation](https://getstream.io/chat/docs/react/channel_delete/?language=javascript#hiding-a-channel), I am trying to hide the channel message when a user connects to the channel, so that the previous message history will not be shown to a user.

```
const App = () => {

  const [chatClient, setChatClient] = useState(null);
  const [channel, setChannel] = useState(null);

  useEffect(() => {
    const initChat = async () => {
      const client = StreamChat.getInstance(env.API_KEY);

      const _channel = await client.channel('livestream', env.ROOM_NAME);
      setChatClient(client);
      setChannel(_channel)
    };
    initChat();
  }, []);
  
  useEffect(() => {
    const hideChat = async () => {
      channel && await channel.hide();
    }
    hideChat(); 
  }, [channel])

  return (
      <Chat client={chatClient}>
        <Channel channel={channel}>
          <Window>
            <VirtualizedMessageList />
          </Window>
        </Channel>
      </Chat>
  );
};

export default App;
```
I am going to hide the messages through channel.hide() method after the state value of channel is updated, but this line throws an error `Error: Channel livestream:johndoe hasn't been initialized yet. Make sure to call .watch() and wait for it to resolve`

- [ ] [Mentioning](https://github.blog/2011-03-23-mention-somebody-they-re-notified/) the authors so that they can notify.
Authors:@jaapbakker88 @DanC5 @mahboubii @vishalnarkhede @vicnicius @yetieaterxb1 @JelteF @nhannah

**Comment by DanC5** [comment]
@mrudangshah first off you need to watch the channel after it's creation, so your useEffect will need to be updated a bit...

```
const _channel = client.channel('livestream', env.ROOM_NAME);
await _channel.watch();
setChatClient(client);
setChannel(_channel)
```

Since this will solve the error you are referring to, I'm going to close the issue, but do let us know if other issues arise. Thanks.

**Comment by mrudangshah** [comment]
Hi @DanC5 , 
I have updated the things as you suggested, and it resolves the error. 

But while applying the `channel.hide()` for hiding full chat history when initialise the sdk, is not hiding the history messages. 
```
useEffect(() => {
  const hideChat = async () => {
    if(channel !== null) {
      await channel.hide();
    }
  }
  hideChat(); 
}, [channel])
```

**Comment by DanC5** [comment]
@mrudangshah the hide api will only ensure that the channel no longer shows up in query requests, it will not hide it from the DOM if it's already active. You'll likely need to include an additional state variable to toggle whether or not you render the chat app. Something like this should work...

```
const App = () => {
  const [chatClient, setChatClient] = useState(null);
  const [channel, setChannel] = useState(null);
  const [showChannel, setShowChannel] = useState(false);

  useEffect(() => {
    const initChat = async () => {
      const client = StreamChat.getInstance(env.API_KEY);

      const _channel = client.channel('livestream', env.ROOM_NAME);
      await _channel.watch();
      setChatClient(client);
      setChannel(_channel);
    };
    initChat();
  }, []);

  if (!showChannel) return null;

  return (
    <Chat client={chatClient}>
      <Channel channel={channel}>
        <Window>
          <VirtualizedMessageList />
        </Window>
      </Channel>
    </Chat>
  );
};

export default App;
```

**Comment by mrudangshah** [comment]
@DanC5 : Sorry I am really confused and writing you back. 
So my simple question is : How can I load the chat without displaying the previous chat history ? 

Eg: If people did chat on dated #05/19/2021 and a user now logged in on #05/20/2021; then the chat messages of #05/19/2021 should not be displayed to that user. 

With the solution that you suggested as above is not working in my this case. 
Hope you get the clue what I am trying.

**Comment by DanC5** [comment]
@mrudangshah if you'd like to display messages for just a single day in time, you can manually inject the messages you'd like to show into the `VirtualizedMessageList` component. By default the displayed `messages` are pulled from the channel state, but this can be overridden. This would allow you to slice or filter the array and only display certain messages. A simple code example would look like this...

```
const MessageListWrapper = () => {
  const { messages } = useChannelContext(); // if pre v6
  const { messages } = useChannelStateContext(); // if post v6

  const filteredMessages; // do some logic here to adjust the messages as you like

  return <VirtualizedMessageList messages={filteredMessages} />
};

const App = () => {
  const [chatClient, setChatClient] = useState(null);
  const [channel, setChannel] = useState(null);
  const [showChannel, setShowChannel] = useState(false);

  useEffect(() => {
    const initChat = async () => {
      const client = StreamChat.getInstance(env.API_KEY);

      const _channel = client.channel('livestream', env.ROOM_NAME);
      await _channel.watch();
      setChatClient(client);
      setChannel(_channel);
    };
    initChat();
  }, []);

  if (!showChannel) return null;

  return (
    <Chat client={chatClient}>
      <Channel channel={channel}>
        <Window>
          <MessageListWrapper />
        </Window>
      </Channel>
    </Chat>
  );
};

export default App;
```
