### ISSUE TITLE
overrideSubmitHandler not triggered when editing a message

### ISSUE THREAD

**Issue by gambitasto** [GetStream/stream-chat-react#886]
We currently use overrideSubmitHandler but now when we wanted to enabled editing, we notice that the overrideSubmitHandler is not used at all when a message is edited.

see [messageInput.js](https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageInput/hooks/messageInput.ts) (around line 638)

Would it be possible to get this fixed? Or recommendations on a workaround?

**Comment by ambaldwin** [comment]
Hi @gambitasto thanks for brining this to our attention. Yes, this needs a fix. I will update here when I have PR and/or release info. Thanks!

**Comment by ambaldwin** [comment]
Hi again @gambitasto after I looked into this, I realized I misspoke!
To override the submit when editing messages, you need to utilize the `doUpdateMessageRequest` prop on Channel. Within that handler should include your custom code, and then conclude with `client.updateMessage(updatedMessage);`

I believe this should work and so I will close this issue. Let us know if you have any other issues or questions, thanks!

**Comment by gambitasto** [comment]
Ok, thanks for the reply, I will try to use the doUpdateMessageRequest then for editing.

**Comment by dragon510629** [comment]
> 


Are you successful?

**Comment by dragon510629** [comment]
> Ok, thanks for the reply, I will try to use the doUpdateMessageRequest then for editing.

Are you successful?
