### ISSUE TITLE
MessageTeam: read receipts showing multiple times for the same user

### ISSUE THREAD

**Issue by kainosnoema** [GetStream/stream-chat-react#887]
In the latest version, we're noticing an issue with MessageTeam component read receipts showing up multiple times for the same user. It's as if past messages don't re-render when the user's read state updates.

Hard to say exactly when this was introduced, but I don't recall seeing it in any of the 4.x releases.

Example:

<img width="398" alt="Screen_Shot_2021-04-29_at_8_45_06_AM" src="https://user-images.githubusercontent.com/145951/116580645-6799f280-a8c8-11eb-9ec6-dc89f2df886e.png">

**Comment by DanC5** [comment]
@kainosnoema thanks for bringing this to our attention, there's a chance our message memoization is no longer catching read state updates. Will report back soon...

**Comment by DanC5** [comment]
@kainosnoema I just added another memoization case to our message UI component logic that looks for changes in the read state. I was able to recreate your bug without the added case and confirmed it no longer exists with the case, so I imagine this will fix the UI bug you're seeing. https://github.com/GetStream/stream-chat-react/pull/888

We're going to make a patch release tomorrow with a couple small items, so you'll be able to upgrade very soon. Closing the issue for now, but of course let us know if you need anything else, thanks!
