### ISSUE TITLE
How to use ChannelSearch Component

### ISSUE THREAD

**Issue by mmickler** [GetStream/stream-chat-react#89]
Hey, how can i use your ChannelSearch Component in maybe the ChannelHeader Component?

Will you implement a messageSearch Component in the future?

I am really new to react, but i want to use you components in the right way, maybe you can add a short description with the informations how and where to export and import components you build but don't use it now in other components

I want to write <ChannelSearch></ChannelSearch> in a render() function 

here i show you how i use it now for log messages in my consol.log:

```
  search(searchValue) {
    const filters = { members: { $in: ['userId'] } };
    const response = this.client.search(
      filters,
      searchValue,
      { limit: 20, offset: 0 },
    );
    response.then(data => {
      console.log(data);
    })
  }

```
i also change your typings: in index.d.ts
from:  _on(callbackOrString: string, callbackOrNothing?: any): { unsubsribe(): void };_
to:      **on(callbackOrString: any, callbackOrNothing?: any): { unsubsribe(): void };**
  
search(
            filterConditions: object,
from:   _query: object_,
to:       **query: string,**
           options: object,
   ): Promise<SearchAPIResponse>;

maybe this was an unseen behavior of .js i use .tsx to get typings in VS:Code

**Comment by jaapbakker88** [comment]
Hi @mmickler, we will implement a message search component in the future, i don't have an estimated time. Where are you making the changes to our library? Did you fork it?  Our components are exported from `src/components/index.js`.

Regarding the typescript typings, I'm not fully understanding the issues your having here? Are you running into build errors?

**Comment by mmickler** [comment]
Hey 

Nice to hear from you. I am still working on it, so i haven't fork it right now, what we done is query all messages in one channel, and than compare if a substring is in message.text or in message.translations[userlanguage] what is a customfield which we fill with translations out of microsofts translator text. It work really well after we switch of the loadmorepaginater for messages and query all messages. If we catch the limit of messages we do it again. We want to do the same for the channels, but it is more complicated. Without sending to much responses. So i use client.search() to get out the cid, and compare if the currentuserchannellist have this cid. But it is not like we want it right now, because i also want to search throw my custommessagefield translations as well, but it is really hard to understand how client.search() works, and how i can change it to a specific customfield. Maybe i will write somethink like the client.search() by my self. This is my first reactjs project, so it will take a lot more time for me as i thought. 

No i have fixed all build errors, i think that was a behavior because we use js files and tsx in the same projekt


--
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 30.12.19, 09:54 schrieb jaapbakker88 <notifications@github.com>:

  Hi @mmickler, we will implement a message search component in the future, i don't have an estimated time. Where are you making the changes to our library? Did you fork it? Our components are exported from src/components/index.js. 
  Regarding the typescript typings, I'm not fully understanding the issues your having here? Are you running into build errors?

**Comment by jaapbakker88** [comment]
I think the problem here is we're using the message.text field to search for messages and not custom fields on the message. So I think right now using the client.search will not work for your translated custom fields.

**Comment by jaapbakker88** [comment]
This will be added in a future release. We're currently working on the backend part of it.
