### ISSUE TITLE
Unable to Delete Channel

### ISSUE THREAD

**Issue by mobeendev** [GetStream/stream-chat-react#898]
Here is the code I am using to remove the channel but its not working:

  ```
const channel = serverClient.channel('messaging', { 
      members: ['u111', 'u1'], 
  }); 

  const result = await channel.delete("!members-q3LvqfghmcMDEkzmysjQpjO5dVlUBLxm3YQqhAKr7I8");
also tried like this:

const result = await channel.delete({id: "!members-q3LvqfghmcMDEkzmysjQpjO5dVlUBLxm3YQqhAKr7I8"});

  res.json(result); 
```
receiving this error

![image](https://user-images.githubusercontent.com/10846423/117125696-8e619880-ada2-11eb-80fd-2a4cfcc1802c.png)

**Comment by shodgetts** [comment]
Hello, according to the docs there is no need to pass the channel_id. It is simply` channel.delete(); `

https://getstream.io/chat/docs/javascript/channel_delete/

**Comment by mobeendev** [comment]
@shodgetts Yes when I was not passing the ID,it was asking for ID.
However now it is working without ID, I don't know what was the issue with the call await channel.delete().
Thanks for help.
