### ISSUE TITLE
client.disconnectUser() not a function

### ISSUE THREAD

**Issue by abbeyseto** [GetStream/stream-chat-react#917]
Hello,
This issue has been driving me crazy :)

I cannot manually disconnect user with `await client.disconnectUser()` function as described in the docs.

On further investigation, I found out that I could see and use `connectUser()` but the `disconnectUser()` function is not in my StreamChat Object as observed in the image below.

<img width="723" alt="Screen Shot 2021-05-12 at 10 08 50 PM" src="https://user-images.githubusercontent.com/14161363/118045592-0534fd80-b370-11eb-989b-8d2cfbc53040.png">

<img width="490" alt="Screen Shot 2021-05-12 at 9 51 28 PM" src="https://user-images.githubusercontent.com/14161363/118045738-37465f80-b370-11eb-8e5d-166e2e96b013.png">

```
useEffect(() => {
    const initChannel = async () => {
      const chatClient = chatClientAPI(props);
      const channel = await chatClient.channel("messaging", props.request.id, {
        image: "https://www.drupal.org/files/project-images/react.png",
        name: `Chat with ${recipient.firstname || "a user"}`,
        members: [props.user && props.user.username, recipient.username],
        color: "teal",
      });

      await channel.watch();
      setClient(chatClient);
      setChannel(channel);

      channel.on("notification.added_to_channel", (event) => {
        try {
          if (event.user.id != recipient) {
            addedToChannel();
            console.log(
              `${event.user.id} wants to chat with you, from ArtisanList`
            );
          }
        } catch (error) {
          console.log(error);
        }
      });

      channel.on("message.new", (event) => {
        try {
          if (event.user.id != recipient) {
            createNotification(event);
            console.log(`${event.user.id} just dropped a new message`);
          }
        } catch (error) {
          console.log(error);
        }
      });
      await chatClient.disconnectUser()
    };
    initChannel();
  }, []);
```

Below is the *chatClientAPI* function imported in line 3 in the above code snippet.

```
export const chatClientAPI = (props) => {
  let client;
  if (!client) {
    const initChat = async () => {
      client = StreamChat.getInstance("nz74tsspf62a", {
        timeout: 6000,
      });
      await client.connectUser(
        {
          id: props.user && props.user.username,
          name: props.user && props.user.firstname,
          image:
            (props.user && props.user.image.formats.thumbnail.url) ||
            "https://getstream.io/random_png/?id=green-star-1&name=green-star-1",
        },
        client.devToken(props.user && props.user.username)
      );
    };

    initChat();
  }
  return client;
};
```

**Comment by yetieaterxb1** [comment]
Hi @abbeyseto,
 
Thanks for reaching out. 

The `disconnect` method was deprecated and `disconnectUser` was added to stream-chat in version 3.5.0. You will need to upgrade to that version or later in order to use that method. Without upgrading you will need to use the deprecated `disconnect` method.

Best,
Grant

**Comment by abbeyseto** [comment]
> Hi @abbeyseto,
> 
> Thanks for reaching out.
> 
> The `disconnect` method was deprecated and `disconnectUser` was added to stream-chat in version 3.5.0. You will need to upgrade to that version or later in order to use that method. Without upgrading you will need to use the deprecated `disconnect` method.
> 
> Best,
> Grant

Thank you @yetieaterxb1 , Upgrading to version 3.5.0 resolved the issue.
