### ISSUE TITLE
Svg is hardcoded to blue

### ISSUE THREAD

**Issue by cabutler10** [GetStream/stream-chat-react#918]
I would like to change the color of the Send Button svg, however it looks like in the code for this component that it is hardcoded to fill=#006cff. Is there a way to override this color that I didn't see in the documentation or can this line simply be removed?

Code in question: Line 74 in https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageInput/icons.tsx;

![image](https://user-images.githubusercontent.com/4421077/118096096-372a7c00-b3d1-11eb-8fa2-66cb44bfbbd7.png)

**Comment by DanC5** [comment]
Hello @cabutler10, a simple way to make this work would be to grab the Stream class name in your own css and change the fill like so...

```
.str-chat__send-button svg path {
  fill: red;
}
```

Also, if you'd like more control over this component, you can pass your own custom send button into the `SendButton` prop on the `MessageInput` component, https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageInput/MessageInput.tsx#L118. Your component would then receive the same props and be rendered in the default component's place.

Thanks!
