### ISSUE TITLE
Add class/id (something) to <li> wrapping message

### ISSUE THREAD

**Issue by 0sserc** [GetStream/stream-chat-react#925]
Hi there

Unless I missed something, even when doing:

`<Channel channel={channel} Message={CustomMessageComponent}>`

There's no way to add a className to the <li> wrapping that custom message component, thus making the whole item customizable

**Comment by DanC5** [comment]
Hello @0sserc, I see what you're saying here, though you can always grab the existing `str-chat_li` class and adjust as you wish. This is what our users typically do. Is this not sufficient for your use case? Would it be helpful if you had access to a wrapper class in addition to the existing li class?

**Comment by phenry20** [comment]
This is important. I use bootstrap for all the styling on my application and it's quite annoying that I have to write custom css for styling I already have simply because there's no way to inject custom classes. The only way I've figured out how to do it is to inject the css class at runtime which is still annoying. 

It would be great if you could implement something like the "VirtualizedMessageList" which allows users to fully customize how the list works instead of having to navigate a bunch of custom layouts and classes.

**Comment by DanC5** [comment]
@phenry20 what would be most helpful to you here? Do you want to ability to append your own class at the point of the message list item (https://github.com/GetStream/stream-chat-react/blob/master/src/components/MessageList/hooks/useMessageListElements.tsx#L137)?

**Comment by phenry20** [comment]
Something like that looks like it works but it's not clear. Why not name it "className" like other components and other libraries use? 

Also there's just not a lot of custom class support in general. It seems as though you want us to implement styles using your custom classes but why not support both?

**Comment by DanC5** [comment]
Good feedback @phenry20, so to make sure I'm following what would serve you best, would either of the two below options be better/worse for you? Do you have in mind a third and more preferable option?

Option 1: Overwrite current class

```
const { customClass } = props;

<div className={customClass || 'str-chat__virtual-list'}
```

Option 2: Extend current class

```
const { customClass } = props;

<div className={`str-chat__virtual-list ${customClass}`}
```

**Comment by phenry20** [comment]
Either or works but option 1 would be preferred imo

**Comment by DanC5** [comment]
@phenry20 sounds good. There are a few high level classes in the app where I think this makes sense, so I'm likely going to add a prop to `Chat` that takes a mapping of overridable classes and pull these out of context at their respective locations. If all performs as expected, we'll release something end of this week.
