### ISSUE TITLE
A conflict between the role of owner and moderator

### ISSUE THREAD

**Issue by ahmeddahy** [GetStream/stream-chat-react#930]
Hello, 
when some user is an owner and a moderator too at some channel, the edit and delete of the messages are disabled and can't take these actions. This behavior is wrong so is there any solution to this problem.
"stream-chat": "^3.7.0",
"stream-chat-react": "^5.1.7"
Thanks

**Comment by DanC5** [comment]
@ahmeddahy the `useUserRole` hook determines actions at the message level. This `isModerator` boolean should return true when the connected user has moderation access, https://github.com/GetStream/stream-chat-react/blob/master/src/components/Message/hooks/useUserRole.ts#L34. Then the `Message` component sets edit/delete actions with the result, https://github.com/GetStream/stream-chat-react/blob/master/src/components/Message/Message.tsx#L114.

Can you verify the `isModerator` value on your end? I would suspect it's returning false if edit/delete isn't permitted.

**Comment by ahmeddahy** [comment]
@DanC5 
I use this method `Task AddModerators(IEnumerable<string> userIDs);` from stream-chat-net v0.4.3 NuGet package to add the owner of the channel as moderator but still have the ownership role (can't act as moderator or can't gain the moderator role). So what is the solution to make an owner acting as moderator.

**Comment by DanC5** [comment]
@ahmeddahy I don't have any experience with the `stream-chat-net` SDK, so you might need to transfer this issue to that repo. All the React library knows is that you'll be able to edit/delete messages as a moderator if this conditional returns true...

```
const isModerator =
    client?.user?.role === 'channel_moderator' ||
    channel?.state?.membership?.role === 'channel_moderator' ||
    channel?.state?.membership?.role === 'moderator';
```

That conditional feeds into this check, which provides the permissions to the message actions component, which renders the edit/delete options. Anything beyond these two conditionals would be outside the scope of the React component library.

```
const canEdit = isMyMessage || isModerator || isAdmin;
const canDelete = canEdit;
```
