### ISSUE TITLE
How to disable Replies

### ISSUE THREAD

**Issue by anonimitoraf** [GetStream/stream-chat-react#944]
It seems like I'm only able to disable Threads via the dashboard
![image](https://user-images.githubusercontent.com/15933322/119801519-1f024300-bf21-11eb-804b-24b5694a8d69.png)
 but not Replies.
 
 I've looked at the docs too and haven't had much luck.
 Anything I'm missing?

**Comment by DanC5** [comment]
Hello @anonimitoraf you can disable replies by taking advantage of our [`disableQuotedMessages`](https://getstream.github.io/stream-chat-react/#messagelist) prop on the MessageList component. Set it to true and you will see Reply removed from your message actions.

`<MessageList disableQuotedMessages />`

Let us know if you need further clarification, thanks!

**Comment by anonimitoraf** [comment]
Sorry @DanC5, also wanted to ask: Is it possible to disable message editing and pinning too?

Thanks

**Comment by DanC5** [comment]
Hey @anonimitoraf, while we don't have a boolean prop to override edit/pin, you can easily adjust the message actions in your app. Default actions in the library are `['edit', 'delete', 'flag', 'mute', 'pin', 'quote', 'react', 'reply']`. Pass your updated actions array to the `MessageList` component like so...

```
const updatedActions = ['delete', 'flag', 'mute', 'react', 'reply'];
<MessageList messageActions={updatedActions} />
```
