### ISSUE TITLE
All demo examples are deprecated, Unable to get help

### ISSUE THREAD

**Issue by SidRathi47** [GetStream/stream-chat-react#947]
Hi, I am really in a bad situation right now.
I have tried reading the docs, I need to create a team chat system. 
I tried to run your demo example. It worked but when I integrated it in my project I got this erro
```
./src/components/studentDashboard/chatContainer/components/PinnedMessageList/PinnedMessageList.js
Attempted import error: 'ChannelContext' is not exported from 'stream-chat-react'.
```
I am still not sure what could be the problem. But then I noticed the package versions.
Your example is at 
```
"stream-chat": "^2.12.0",
"stream-chat-react": "^3.1.2",
```
And my current project is at latest. 
```
 "stream-chat": "^3.10.0",
"stream-chat-react": "^6.0.2",
```
What can I do, Can anyone please just  help me? I only need some guidance on how to build custom components for team chat example.

**Comment by DanC5** [comment]
@SidRathi47 we released a major version of the library (v6) last week thats refactors our React Context usage in the library. For this reason, upgrading the demo apps to the latest version without switching out the references will not work. The update process is simple though, you just need to replace all old references of `ChannelContext` with their new values, for example `ChannelStateContext` or `ChannelActionContext`.

The [Context Overview section of our upgrade wiki](https://github.com/GetStream/stream-chat-react/wiki/Context-Overview-(v6.0.0)) explains this process in detail. So switch out each legacy context hook and you should be fine, thanks.
