### ISSUE TITLE
Enhancement Request: close / "&times;" button on modal that magnifies image

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-react#96]
It would be really nice if you had a close / "&times;" button on the top right of the magnified images modal, and if this button could receive focus. 

Right now the user can hit `escape` to dismiss the modal if they know to do that, but if the user does not know how to do that or opens an especially large image, they may be confused about how to get rid of the modal.

**Comment by vishalnarkhede** [comment]
Hey @codekiln , we do have close button on modal!
<img width="1382" alt="Screenshot 2019-12-30 at 16 53 59" src="https://user-images.githubusercontent.com/11586388/71589457-3cad5c00-2b25-11ea-9fee-7c1599615f82.png">

We will fix the focus issue soon!!
