### ISSUE TITLE
Changing Default Message 

### ISSUE THREAD

**Issue by mobeendev** [GetStream/stream-chat-react#962]
I want to change the default message i.e Nothing Yet to something else but I couldn't find any method on SDK or even on Backend SDKs

![image](https://user-images.githubusercontent.com/10846423/121206243-fb27f100-c880-11eb-8898-fba41b6f1f64.png)

**Comment by ambaldwin** [comment]
Hello! To support your requirements, please take a look at this link which outlines how to use Stream's instance of i18n and overriding certain keys. There's actually an example using the 'Nothing yet...' key:

https://github.com/GetStream/stream-chat-react/wiki/Internationalization-(i18n)

I'm going to close this issue, but please let us know if there are any other questions.

**Comment by mobeendev** [comment]
thanks for helping, it works.
