### ISSUE TITLE
1-0-1 CHAT | User Image in Header  

### ISSUE THREAD

**Issue by mobeendev** [GetStream/stream-chat-react#964]
For 1-0-1 chat I want to show the image/avatar of the other connected users in the header.
How I can do that?

**Comment by ambaldwin** [comment]
Hello!
To override the default ChannelHeader component, you can just replace with your custom header component.
Depending on the version of the SDK you're using, you'll be able to pull member data (including the images) from the channel via context.

 pre v6:
const { channel } = useChannelContext();
const members = channel.state.members;

v6:
const { members } = useChannelStateContext();

<Channel>
  <YourCustomChannelHeader />
</Channel>

Also, please note that the issue section of our GitHub is now reserved for bug reports and feature suggestions. For technical support for the library, please email our Customer Success and Engineer support team at support@getstream.io with your application ID and SDK version.

I'm closing this issue, but let us know if there are any problems implementing. Thanks!
