### ISSUE TITLE
Wishlist for 2.0

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-react#99]
Wishlist for Stream Chat React 2.0.
Summary updated January 24th:

## Codebase Improvements

* Upgrade Deps
* React to 16.12
* TypeScript
* Hooks
* Show Coverage percentage

## Features

* MML
* Message Search component
* Improved performance using one of the recyclerview style libraries for react & Additional benchmarking
* Unread count component

## Examples

- better customer support example (see Jeff's design)
- better team example (see Josh' design)
- better livestream example (see Nick's post)

## Docs

- Context usage when using hooks needs better docs

## Not included

* Styled components (too many people prefer CSS at this point)

**Comment by tbarbugli** [comment]
- improve test coverage (Jest)
- use Browserstack or similar (useful to avoid UI / UIX regressions)
- improve ease-of-use around unread messages

**Comment by jaapbakker88** [comment]
* Search Component

**Comment by tschellenbach** [comment]
* For livestream use case, this or an alternative would be nice: https://github.com/Flipkart/recyclerlistview

**Comment by lr-mjaouen** [comment]
typescript?

**Comment by tschellenbach** [comment]
For our feed library we used Flow. It was a bad experience since it made it hard for customers not using Flow to edit our components. That was the reason we didn't use typescript for this library. 

On the other hand it keeps on becoming more popular... So maybe we should reevaluate

**Comment by lr-mjaouen** [comment]
I'm not sure to understand more than popular typescript is becoming a standard
https://www.thoughtworks.com/radar/languages-and-frameworks/typescript

**Comment by fbartho** [comment]
### TypeScript

I certainly love TypeScript and know that I'm not alone in that :D -- I know people that have fallen off of Flow, and avoided all kinds of typed things too for a while, but have enjoyed TypeScript when they finally tried it.

Additionally, our web team is about to start using TypeScript (ancient tooling issues prevented us from adopting it on our website before now, but both of our React-Native mobile apps have TypeScript).

**TypeScript Support was a primary reason why we're working to integrate with Stream today. If the React-Native Stream libraries didn't have TypeScript support it would have fallen behind other competitors in our evaluation matrix.** 

### Performance

- @tschellenbach's idea of recyclerlistview is neat -- I'd also evaluate [react-window](https://react-window.now.sh/) [Repo](https://github.com/bvaughn/react-window) I've been watching that project for a year or two, and it's very impressive.

### Other

- StyledComponents I see both sides on. It's great if other people use it, but problematic to pull that in as a dependency if people don't use it. If you could somehow modularize the Styling and implement both ways so people could use either stream-chat-react-styled, or stream-chat-react-css then you get both wins. I don't know how easy that would be.

**Comment by DanC5** [comment]
- Thread preview enrichment with profile images of thread members (similar to Slack)

**Comment by lr-mjaouen** [comment]
- Provide build-in mock class files

**Comment by vishalnarkhede** [comment]
> Thread preview enrichment with profile images of thread members 
@DanC5 can you share some screenshot? I am not sure what you mean exactly

**Comment by DanC5** [comment]
> > Thread preview enrichment with profile images of thread members
> > @DanC5 can you share some screenshot? I am not sure what you mean exactly

<img width="270" alt="Screen Shot 2020-04-22 at 6 54 34 AM" src="https://user-images.githubusercontent.com/43552931/79984337-3e998300-8466-11ea-8399-cadecb9e35fb.png">

@vishalnarkhede so being able to display thread users' avatars in the MessageList like in Slack

**Comment by vishalnarkhede** [comment]
Yeah that needs some backend change. Not sure how easy is it to add information of users which are part of thread in a particular message. @tbarbugli ?
