### ISSUE TITLE
CSS rule for Avatar in .str-chat__li--top seems to affect visibility of str-chat__li--single, str-chat__li--bottom

### ISSUE THREAD

**Issue by myang5** [GetStream/stream-chat-react#993]
I am implementing a `CustomAvatar` component with a custom fallback UI to pass into the `Channel` component like so:
```
<Channel
  client={chatClient}
  ChannelHeader={ChannelHeader}
  onBack={() => setMenuOpen(true)}
  Avatar={CustomAvatar}
/>
```

The code for `CustomAvatar` is nearly identical to the [original source code for `Avatar`](https://github.com/GetStream/stream-chat-react/blob/master/src/components/Avatar/Avatar.tsx), including the same CSS classes. However, two strange things are happening:

- Although the UI displays as expected for the default `Avatar`, my `CustomAvatar` gets hidden completely from the `Channel` UI.
- I was able to track down that this seems to be a result rule from [Avatar.scss](https://github.com/GetStream/stream-chat-react/blob/master/src/styles/Avatar.scss) that sets `visibility: hidden` for any avatar components that are children of `str-chat__li--top` (I was able to determine that `str-chat__li--middle` mysteriously wasn't a problem by selectively replicating the CSS in `Avatar.scss`). For for some reason this rule also hides any `.str-chat__avatar` elements whose parent elements are `str-chat__li--single` and `str-chat__li--bottom`.

Here is a video of disabling `visibility: hidden` in the above-mentioned rule and how it seems to affect all `Avatar` components:
![Screen Recording 2021-06-21 at 4 11 22 PM](https://user-images.githubusercontent.com/19670297/122823061-e39f2e00-d2ac-11eb-8d0d-3e8b42a9ba1b.gif)

Is there some other CSS rule or piece of code that could be causing this?

**Comment by DanC5** [comment]
@myang5 I tried to reproduce this on my end but am having a hard time. The `li--bottom` element in your recording should be displaying the Avatar, but I see it isn't for some reason.

A couple questions, first can you send me the Avatar component you're using? I just created a custom one and used all the same CSS classes, but can't seem to hide it from the bottom list item like in your example. Also, what version of the library are you using?

**Comment by myang5** [comment]
@DanC5 Thanks for the response!

Here's the `CustomAvatar` code at the time of the bug:
```
import React, { useState, useEffect } from 'react';
import Avatar from 'boring-avatars';

/*
Custom avatar needed to use a custom UI for fallback state when user has no image
Code is mostly similar to original Avatar source code:
https://github.com/GetStream/stream-chat-react/blob/master/src/components/Avatar/Avatar.tsx
*/

const AvatarFallback = ({ name, size }) => {
  return (
    <Avatar
      name={name}
      size={size}
      variant="marble"
      colors={['#35846B', '#2980D6', '#BA3962', '#D5421E', '#228291']}
    />
  );
};

export const CustomAvatar = ({
  image,
  name,
  onClick = () => undefined,
  onMouseOver = () => undefined,
  shape = 'circle',
  size = 32,
}) => {
  const [error, setError] = useState(false);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    setError(false);
    setLoaded(false);
  }, [image]);

  const initials = name
    .split(' ')
    .map(word => word[0])
    .join('');

  return (
    <>
      <div
        className={`str-chat__avatar str-chat__avatar--${shape}`}
        onClick={onClick}
        onMouseOver={onMouseOver}
        style={{
          flexBasis: `${size}px`,
          fontSize: `${size / 2}px`,
          height: `${size}px`,
          lineHeight: `${size}px`,
          width: `${size}px`,
        }}
      >
        {image && !error ? (
          <img
            alt={initials}
            className={`str-chat__avatar-image${loaded ? ' str-chat__avatar-image--loaded' : ''}`}
            onError={() => setError(true)}
            onLoad={() => setLoaded(true)}
            src={image}
            style={{
              flexBasis: `${size}px`,
              height: `${size}px`,
              objectFit: 'cover',
              width: `${size}px`,
            }}
          />
        ) : (
          <AvatarFallback name={initials} size={size} />
        )}
      </div>
    </>
  );
};
```
Also the version is: 
```
stream-chat-react@^6.0.5:
  version "6.0.5"
  resolved "https://registry.yarnpkg.com/stream-chat-react/-/stream-chat-react-6.0.5.tgz#1fc184a17a29df5e8eb74576ccbca7f079e3e918"
```

**Comment by DanC5** [comment]
@myang5 I've located the issue and am now trying to fix it. If you see in the attached screenshots, the `boring-avatar` component doesn't immediately load on mount. Though if you scroll up the list and trigger load more messages event, the components load into view. This likely has something to do with the visibility hidden CSS issue you mentioned before. I'll keep looking into this and get back to you soon, thanks!

<img width="1359" alt="Screen Shot 2021-06-23 at 9 22 48 AM" src="https://user-images.githubusercontent.com/43552931/123124937-53c0c780-d405-11eb-87c7-b3efda36237d.png">
<img width="1282" alt="Screen Shot 2021-06-23 at 9 23 03 AM" src="https://user-images.githubusercontent.com/43552931/123124955-57544e80-d405-11eb-955b-f6acfc1f73a5.png">

**Comment by DanC5** [comment]
@myang5 I was able to get your custom component working properly by adding the following bit of CSS. I'm still a bit confused as to why this is only happening with the `boring-avatars` component, but hopefully you're all set now!

```
.str-chat__li {
  &--single,
  &--bottom {
    .str-chat__message {
      > .str-chat__avatar {
        visibility: visible;
      }
    }
  }
}
```

**Comment by myang5** [comment]
@DanC5 Interesting.. tt might be an issue with the `boring-avatars` library itself then so a workaround is inevitable. Thank you for digging into this!
